(()=>{'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const field=(label,control)=>'<label>'+esc(label)+control+'</label>';
 const input=(name,value,type='text')=>'<input name="'+esc(name)+'" type="'+type+'" value="'+esc(value)+'">';
 const select=(name,items,value)=>'<select name="'+esc(name)+'">'+items.map(x=>{const [id,label]=Array.isArray(x)?x:[x,x];return '<option value="'+esc(id)+'"'+(String(id)===String(value)?' selected':'')+'>'+esc(label)+'</option>';}).join('')+'</select>';
 const money=(n,currency='USD')=>n===null||n===undefined||n===''?'Need Rate':currency+' '+Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
 window.mountCommercialMatrix=async function(host,ctx){
  const {api,quoteData,can,modal,closeModal,toast,refresh,onBack,onProposal}=ctx,v=quoteData.version,q=quoteData.quote,base='quote-versions/'+v.id;
  const profit=can('quote.view_profit')&&can('profit.view'),cost=can('quote.view_cost'),frozen=['SENT','CONFIRMED','SUPERSEDED'].includes(v.version_status),editable=can('quote.edit')&&cost&&!frozen;
  const data=await api.request(base+'/price-matrix');let revision=data.costing_revision,busy=false;
  const request=(action,body={})=>api.request(base+'/price-matrix/'+action,{method:'POST',body:{...body,expected_revision:revision}});
  const run=async(fn,reload=true)=>{if(busy)return;busy=true;const controls=[...host.querySelectorAll('button:not(:disabled)')];controls.forEach(b=>b.disabled=true);try{const result=await fn();if(result?.costing_revision!==undefined)revision=result.costing_revision;if(reload)await refresh();return result;}catch(e){toast(e.message,true);return null;}finally{busy=false;controls.filter(x=>x.isConnected).forEach(b=>b.disabled=false);}};
  const find=s=>host.querySelector(s),policies=cost?(await api.request('commercial-policies')).items:[],options=cost?(await api.request(base+'/options')).items:[];
  const transportChoices=editable?(await api.request(base+'/price-matrix/transport-options')).items||[]:[];
  const offered=options.filter(x=>Number(x.is_offered)),config=data.config||{},cells=data.cells||[],locked=data.matrix?.status==='LOCKED',draft=data.matrix?.status==='DRAFT';
  const preferred=offered.find(o=>o.costing_mode==='PRIVATE'&&parseInt(o.hotel_level,10)===3&&Number(o.cruise_level)===4);
  const ruleLabels=[['FOLLOW_BASE_OFFSET','Keep the current population difference'],['PAYING_PAX','Follow paying pax'],['TOTAL_GUESTS','Follow total guests'],['FIXED','Fixed quantity']];
  host.innerHTML='<div class="page vs23"><div class="page-head"><div><h1>Pricing Matrix</h1><p>'+esc(q.quote_ref)+' · V'+esc(v.version_no)+' · '+esc(data.matrix?.status||'No matrix')+'</p></div><div class="actions"><button class="btn" data-back>Smart Costing</button><button class="btn" data-proposal>Visual Proposal</button></div></div><p class="notice">One itinerary and supplier cost sheet. Each pax scenario uses Smart Costing; sent prices remain frozen.</p>'+
   (editable&&!locked?'<section class="panel"><div class="panel-head"><h2>Matrix configuration</h2>'+(can('commercial.policy_manage')?'<button class="btn" data-policy>New policy version</button>':'')+'</div><form data-config class="panel-body"><div class="matrix-grid">'+field('Pricing method',select('method',['SAFE_PRICE','REPRESENTATIVE_PAX','EXACT_PAX'],config.method||'SAFE_PRICE'))+field('USD / VND FX',input('fx_rate',config.fx_rate||v.fx_rate,'number'))+field('FX source',select('fx_source',['QUOTE_SNAPSHOT','MANUAL'],data.fx?.source||'QUOTE_SNAPSHOT'))+['B2B_AGENT','B2C_DIRECT'].map(channel=>field(channel,select(channel,[['','Do not generate'],...policies.filter(p=>p.channel===channel).map(p=>[p.id,p.name+' · V'+p.version_no])],config.policies?.[channel]||''))).join('')+'</div><h3>Pax bands (inclusive)</h3><div class="matrix-scroll"><table><thead><tr><th>Minimum</th><th>Maximum</th><th>Representative</th><th></th></tr></thead><tbody data-bands></tbody></table></div><button type="button" class="btn" data-add-band>Add band</button><h3>Vehicle & supplier rate per group</h3><p>Review vehicle and supplier contract for each group. Missing rates block prices.</p><div class="matrix-scroll" data-group-vehicles></div><h3>Reviewed cost variants</h3>'+(preferred?'':'<p class="notice">Hotel 3★ + Cruise 4★ is not offered yet. Create and review this combination in Cost before generating the requested package.</p>')+'<div class="matrix-grid">'+offered.map(o=>'<label class="check"><input type="checkbox" name="variant" value="'+o.variant_id+'"'+((config.variant_ids?config.variant_ids.includes(Number(o.variant_id)):preferred?Number(o.variant_id)===Number(preferred.variant_id):o.costing_mode==='PRIVATE')?' checked':'')+'>'+esc(o.label)+' · '+esc(o.costing_mode)+' · Hotel '+esc(o.hotel_level)+' / Cruise '+esc(o.cruise_level||'N/A')+'</label>').join('')+'</div>'+(offered.length?'':'<p>Review and offer variants in Smart Costing first. Hotel and cruise tiers can be mixed there.</p>')+'<h3>Service populations</h3><div class="matrix-grid">'+['hotel_pax','cruise_pax','visa_pax','meal_pax','ticket_pax'].map(k=>field(k.replaceAll('_',' '),select(k+'_rule',ruleLabels,config.quantity_rules?.[k]?.mode||'FOLLOW_BASE_OFFSET'))+field('Fixed '+k.replaceAll('_',' '),input(k+'_fixed',config.quantity_rules?.[k]?.quantity??'','number'))).join('')+'</div><details><summary>Resource scenarios and stable overrides</summary><p>Vehicle/guide counts require reviewed supplier rates. Changing capacity never invents a rate.</p><div data-resources></div></details><button class="btn primary" type="submit">Generate Matrix</button></form></section>':'')+
   '<section class="panel"><div class="panel-head"><h2>Commercial comparison</h2><div class="actions">'+(editable&&!locked&&data.matrix?'<button class="btn" data-validate>Validate Matrix</button>':'')+(editable&&!locked&&data.matrix&&can('commercial.matrix_lock')?'<button class="btn primary" data-lock>Lock Matrix</button>':'')+(editable&&locked&&can('commercial.matrix_lock')?'<button class="btn" data-unlock>Unlock with reason</button>':'')+'</div></div><div class="panel-body"><div class="tabs">'+['PRIVATE','SIC','COMPARE'].map(t=>'<button data-mode="'+t+'">'+t+'</button>').join('')+'</div><div data-group-table></div><details class="vta-price-advanced"><summary>Option details, review & cost traces</summary><div class="matrix-scroll" data-matrix></div></details><div data-status role="status"></div></div></section>'+
   (frozen&&cost&&can('quote.confirm')&&v.version_status==='SENT'?'<section class="panel"><div class="panel-head"><h2>Exact pax acceptance</h2></div><form class="panel-body matrix-grid" data-exact>'+field('Offered commercial cell',select('cell_id',cells.filter(c=>Number(c.is_selected)).map(c=>[c.id,c.channel+' · '+c.result.label+' · '+c.band_key]),''))+field('Confirmed paying pax',input('paying_pax',v.paying_pax,'number'))+'<details><summary>Confirmed guest composition and service populations</summary><label class="check"><input name="use_confirmed_profile" type="checkbox">Use the confirmed values below</label><p>FOC stays as previously reviewed. Enter total, composition and service populations for the exact confirmed pax.</p><div class="matrix-grid">'+['adults','children','infants','total_guests','hotel_pax','cruise_pax','visa_pax','meal_pax','ticket_pax'].map(k=>field(k.replaceAll('_',' '),input('confirmed_'+k,v[k]??'','number'))).join('')+'</div></details><button class="btn" type="submit">Recheck Exact Pax</button><div data-recheck role="status"></div></form></section>':'')+'</div>';
  find('[data-back]').onclick=onBack;find('[data-proposal]').onclick=onProposal;if(data.validation&&!data.validation.valid)find('[data-status]').textContent='Review required: '+data.validation.errors.map(e=>e.code).join(', ');let mode='COMPARE';
  function drawGroupTable(){
   const sorted=[...new Set(cells.map(c=>c.band_key))].sort((a,b)=>Number(a.split('-')[0])-Number(b.split('-')[0]));
   const rows=[];
   for(const key of sorted){
    const matches=cells.filter(c=>c.band_key===key&&(mode==='COMPARE'||c.result.mode===mode));
    const vars=[...new Set(matches.map(c=>c.variant_id))];
    const vehicle=(config.vehicle_bands||[]).find(v=>v.min+'-'+v.max===key)?.vehicle||
      ({'2-2':'Sedan / 7-seater','3-4':'7-seater','5-9':'16-seater','10-14':'16 / 29-seater','15-20':'29-seater'}[key]||'Review vehicle');
    for(const id of vars){
     const example=matches.find(c=>Number(c.variant_id)===Number(id));
     const agent=matches.find(c=>Number(c.variant_id)===Number(id)&&c.channel==='B2B_AGENT');
     const retail=matches.find(c=>Number(c.variant_id)===Number(id)&&c.channel==='B2C_DIRECT');
     const price=c=>!c?'—':c.status==='SCENARIO_REVIEW_REQUIRED'?'Need Rate / Review':money(c.selling_per_pax,c.selling_currency);
     const priceEditor=c=>{
       const label=esc(price(c));
       if(!c||!editable||!draft||c.status==='SCENARIO_REVIEW_REQUIRED')return label;
       return '<details class="vta-inline-price"><summary>'+label+' · Edit</summary>'+
         '<label>Selling / Pax<input type="number" data-price-value="'+c.id+'" min="0.01" step="0.01" value="'+esc(c.selling_per_pax||'')+'"></label>'+
         '<label>Reason<input data-price-reason="'+c.id+'" placeholder="Approved discount or negotiated price"></label>'+
         '<button type="button" class="btn" data-price-save="'+c.id+'">Apply Price</button></details>';
     };
     const status=[agent,retail].filter(Boolean).map(c=>c.status).filter(v=>v!=='VALID');
     rows.push('<tr><th>'+esc(key.replace('-', '–'))+'</th><td>'+esc(vehicle)+'</td>'+
       '<td>'+esc(example.result.label)+'<small>Hotel '+esc(example.result.hotel_level)+' / Cruise '+esc(example.result.cruise_level||'—')+'</small></td>'+
       '<td>'+priceEditor(agent)+'</td><td>'+priceEditor(retail)+'</td><td>'+esc(status.join(' · ')||'Ready')+'</td></tr>');
    }
   }
   find('[data-group-table]').innerHTML='<div class="vta-price-heading"><h3>PRICE PER PERSON · PRIVATE TOUR</h3>'+
    '<p>SAFE_PRICE: every paying pax is evaluated within each band. Unresolved rates never become USD 0.</p></div>'+
    '<div class="matrix-scroll"><table class="vta-price-compact"><thead><tr><th>Paying Pax</th><th>Vehicle (planned)</th><th>Hotel / Cruise</th>'+
    '<th>B2B / Pax</th><th>B2C / Pax</th><th>Review</th></tr></thead><tbody>'+
    (rows.join('')||'<tr><td colspan="6">Generate the reviewed price matrix to show prices.</td></tr>')+'</tbody></table></div>';
   host.querySelectorAll('[data-price-save]').forEach(button=>button.onclick=()=>{
     const id=Number(button.dataset.priceSave);
     const price=host.querySelector('[data-price-value="'+id+'"]')?.value;
     const reason=host.querySelector('[data-price-reason="'+id+'"]')?.value.trim();
     if(!reason||!price||Number(price)<=0){toast('Enter a positive selling price and a reason',true);return;}
     run(()=>request('manual-price',{cell_id:id,selling_per_pax:price,reason}));
   });
  }
  function draw(){const shown=cells.filter(c=>mode==='COMPARE'||c.result.mode===mode);const bands=[...new Set(shown.map(c=>c.band_key))];find('[data-matrix]').innerHTML=cost?'<table><thead><tr><th>Pax</th><th>Options · Hotel / Cruise · Channel</th></tr></thead><tbody>'+bands.map(b=>'<tr><th>'+esc(b)+'</th><td><div class="matrix-grid">'+shown.filter(c=>c.band_key===b).map(c=>{const s=c.result.scenarios[0],p=s?.pricing;return '<article class="matrix-card '+(c.status==='SCENARIO_REVIEW_REQUIRED'||(c.status==='MARGIN_BELOW_POLICY'&&!c.override_approved)?'invalid':'')+'"><strong>'+esc(c.result.label)+' · '+esc(c.channel)+'</strong><p>'+esc(c.result.mode)+' · Hotel '+esc(c.result.hotel_level)+' / Cruise '+esc(c.result.cruise_level||'N/A')+'</p><p>Selling/pax: '+esc(money(c.selling_per_pax,c.selling_currency))+'</p><p>'+esc(c.status)+(c.override_approved?' · Override approved':'')+'</p>'+(p?'<p>Cost/pax: '+esc(money(p.cost_per_paying_pax_vnd,'VND'))+(profit?' · Profit: '+esc(money(p.profit_vnd,'VND')):'')+'</p>'+(profit?'<p>Margin '+esc(p.margin_pct)+'% · Markup '+esc(p.markup_pct)+'%</p>':''):'')+(editable&&draft?'<label class="check"><input type="checkbox" data-select="'+c.id+'"'+(Number(c.is_selected)?' checked':'')+'>Select for proposal</label><label class="check"><input type="checkbox" data-recommend="'+c.id+'"'+(Number(c.is_recommended)?' checked':'')+'>Recommended</label>':'')+(can('commercial.margin_override')&&!frozen&&c.status==='MARGIN_BELOW_POLICY'&&!c.override_approved?'<button class="btn" data-override="'+c.id+'">Request / approve override</button>':'')+'<button class="btn" data-trace="'+c.id+'">Scenarios and trace</button></article>';}).join('')+'</div></td></tr>').join('')+'</tbody></table>':(data.selling||[]).map(m=>'<h3>'+esc(m.channel)+'</h3>'+m.cells.map(c=>'<p>'+esc(c.label)+' · '+c.pax_min+'–'+c.pax_max+' pax · '+esc(money(c.selling_per_pax,c.currency))+'</p>').join('')).join('');
   for(const attr of ['select','recommend'])host.querySelectorAll('[data-'+attr+']').forEach(el=>el.onchange=()=>{const c=cells.find(c=>Number(c.id)===Number(el.dataset[attr]));run(()=>request('select',{cell_id:Number(c.id),is_selected:attr==='select'?el.checked:!!Number(c.is_selected),is_recommended:attr==='recommend'?el.checked:!!Number(c.is_recommended)}));});
   host.querySelectorAll('[data-trace]').forEach(el=>el.onclick=()=>{const c=cells.find(c=>String(c.id)===el.dataset.trace);modal('Calculation scenarios','<div class="vs23"><p>FX '+esc(data.fx?.value)+' · '+esc(data.fx?.source)+'</p><pre class="trace">'+esc(JSON.stringify(c.result,null,2))+'</pre></div>');});
   host.querySelectorAll('[data-override]').forEach(el=>el.onclick=()=>reasonDialog('Commercial margin override',reason=>{const c=cells.find(c=>String(c.id)===el.dataset.override);return request('override',{cell_id:Number(c.id),context_hash:c.context_hash,reason});}));
   drawGroupTable();
  }draw();host.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;draw();});
  function reasonDialog(title,fn){const m=modal(title,field('Reason','<textarea name="reason" required></textarea>'),'<button class="btn primary" data-reason-save>Confirm</button>');m.querySelector('[data-reason-save]').onclick=()=>{const reason=m.querySelector('[name=reason]').value;if(!reason.trim())return toast('A reason is required',true);closeModal();run(()=>fn(reason));};}
  if(find('[data-validate]'))find('[data-validate]').onclick=()=>run(()=>request('validate'));
  if(find('[data-lock]'))find('[data-lock]').onclick=()=>run(()=>request('lock'));
  if(find('[data-unlock]'))find('[data-unlock]').onclick=()=>reasonDialog('Unlock draft matrix',reason=>request('unlock',{reason}));
  const form=find('[data-config]');if(form){let bands=(config.bands||[{min:2,max:2},{min:3,max:4},{min:5,max:9},{min:10,max:14},{min:15,max:20}]).map(x=>({...x}));
   const standard={'2-2':'Sedan / 7-seater','3-4':'7-seater','5-9':'16-seater','10-14':'16 / 29-seater','15-20':'29-seater'};
   const byVehicle=Object.fromEntries((config.vehicle_bands||[]).map(b=>[b.min+'-'+b.max,{...b}]));
   const rates=JSON.parse(JSON.stringify(config.transport_rate_versions||{}));
   const transferRows=offered.flatMap(v=>(v.lines||[]).filter(l=>l.line_kind==='SERVICE'&&l.formula_code==='TRANSFER_PACKAGE').map(l=>({...l,variant_label:v.label})));
   const rateOptions=[['','Need Rate / Select supplier source'],...transportChoices.map(t=>[String(t.rate_version_id),
      t.product_name+' · '+t.supplier_name+' · '+t.capacity+' seats · '+t.amount+' '+t.currency])];
   function drawVehicles(){
     const table=find('[data-group-vehicles]');if(!table)return;
     table.innerHTML='<table class="vta-vehicles"><thead><tr><th>Paying Pax</th><th>Vehicle</th><th>Supplier check / luggage</th><th>Verified Transfer price sources</th></tr></thead><tbody>'+
       bands.map(b=>{const key=b.min+'-'+b.max,v=byVehicle[key]||{vehicle:standard[key]||'Review vehicle',reason:''};
        return '<tr data-vehicle-band="'+esc(key)+'"><th>'+esc(key)+'</th><td>'+
          input('vehicle',v.vehicle)+'</td><td>'+input('vehicle_reason',v.reason||'')+'</td><td>'+
          (transferRows.length?'<details><summary>Rates for '+transferRows.length+' transfer line(s)</summary>'+
            transferRows.map(l=>'<label>'+esc(l.variant_label+' · '+(l.service_name||l.formula_code))+
              select('transport_'+l.id,rateOptions,rates[String(l.id)]?.[key]||'')+'</label>').join('')+
          '</details>':'No transfer lines in reviewed variants')+'</td></tr>';}).join('')+'</tbody></table>';
     table.querySelectorAll('input,select').forEach(el=>el.onchange=()=>{
       const row=el.closest('[data-vehicle-band]'),key=row.dataset.vehicleBand;
       byVehicle[key]={min:Number(key.split('-')[0]),max:Number(key.split('-')[1]),
         vehicle:row.querySelector('[name=vehicle]').value,reason:row.querySelector('[name=vehicle_reason]').value};
       for(const l of transferRows)rates[String(l.id)]={...(rates[String(l.id)]||{}),[key]:row.querySelector('[name=transport_'+l.id+']')?.value||''};
     });
   }
   function drawBands(){find('[data-bands]').innerHTML=bands.map((b,i)=>'<tr data-band="'+i+'"><td>'+input('min',b.min,'number')+'</td><td>'+input('max',b.max,'number')+'</td><td>'+input('representative',b.representative??b.min,'number')+'</td><td><button type="button" class="btn" data-remove="'+i+'">Remove</button></td></tr>').join('');find('[data-bands]').querySelectorAll('input').forEach(el=>el.onchange=()=>bands[Number(el.closest('tr').dataset.band)][el.name]=Number(el.value));find('[data-bands]').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{bands.splice(Number(b.dataset.remove),1);drawBands();});drawVehicles();}drawBands();find('[data-add-band]').onclick=()=>{bands.push({min:(bands.at(-1)?.max||0)+1,max:(bands.at(-1)?.max||0)+1});drawBands();};
   const resources=offered.flatMap(o=>(o.lines||[]).filter(l=>l.quantity_override!==null||['TRANSFER_PACKAGE','GUIDE_DAY'].includes(l.formula_code)).map(l=>({...l,variant_label:o.label})));find('[data-resources]').innerHTML=resources.map(l=>'<div data-resource="'+l.id+'"><p>'+esc(l.variant_label)+' · '+esc(l.service_name||l.formula_code)+' · Current quantity '+esc(l.quantity_override??l.custom_quantity)+'</p>'+field('Review of stable manual override',input('review',config.override_reviews?.[l.id]||''))+(l.quantity_source==='CUSTOM_QTY'&&['TRANSFER_PACKAGE','GUIDE_DAY'].includes(l.formula_code)?'<div class="matrix-grid">'+field('Exact scenario pax',input('pax','','number'))+field('Reviewed vehicle/guide count',input('count','','number'))+field('Reason',input('reason',''))+'</div>':'')+'</div>').join('');
   form.onsubmit=e=>{e.preventDefault();const f=new FormData(form);
     const vehicle_bands=bands.map(b=>{const key=b.min+'-'+b.max,v=byVehicle[key]||{vehicle:standard[key]||'Review vehicle',reason:''};return {min:b.min,max:b.max,vehicle:v.vehicle,reason:v.reason};});
     const transport_rate_versions=Object.fromEntries(Object.entries(rates).map(([id,byBand])=>[id,Object.fromEntries(
       Object.entries(byBand).filter(([key,value])=>bands.some(b=>b.min+'-'+b.max===key)&&value!=='').map(([k,v])=>[k,Number(v)]))]));
     const body={method:f.get('method'),bands,vehicle_bands,transport_rate_versions,variant_ids:f.getAll('variant').map(Number),policies:{},fx_rate:f.get('fx_rate'),fx_source:f.get('fx_source'),quantity_rules:{},override_reviews:{},resource_counts:config.resource_counts||{}};for(const channel of ['B2B_AGENT','B2C_DIRECT'])if(f.get(channel))body.policies[channel]=Number(f.get(channel));for(const k of ['hotel_pax','cruise_pax','visa_pax','meal_pax','ticket_pax'])body.quantity_rules[k]={mode:f.get(k+'_rule'),...(f.get(k+'_rule')==='FIXED'?{quantity:f.get(k+'_fixed')===''?null:Number(f.get(k+'_fixed'))}:{})};host.querySelectorAll('[data-resource]').forEach(el=>{const id=el.dataset.resource,review=el.querySelector('[name=review]').value;if(review)body.override_reviews[id]=review;const pax=el.querySelector('[name=pax]')?.value;if(pax)body.resource_counts[id]={counts:{...(body.resource_counts[id]?.counts||{}),[pax]:Number(el.querySelector('[name=count]').value)},reason:el.querySelector('[name=reason]').value};});run(()=>request('generate',body));};
  }
  if(find('[data-policy]'))find('[data-policy]').onclick=()=>{const fields={policy_key:'',name:'',pricing_value:'20',minimum_margin_pct:'10',warning_margin_pct:'15',commission_pct:'0',deposit_pct:'30',rounding_step:'1',validity_days:'14',payment_terms:'',cancellation_policy:''};const m=modal('New commercial policy version','<form class="vs23 matrix-grid">'+field('Channel',select('channel',['B2B_AGENT','B2C_DIRECT'],'B2B_AGENT'))+field('Policy',select('policy_mode',['B2B_MARKUP','B2B_MARGIN','B2B_NET_RATE','B2C_MARKUP','B2C_MARGIN','B2C_RETAIL_PRICE'],'B2B_MARKUP'))+field('Selling currency',select('selling_currency',['USD','VND'],'USD'))+Object.entries(fields).map(([k,value])=>field(k.replaceAll('_',' '),['payment_terms','cancellation_policy'].includes(k)?'<textarea name="'+k+'"></textarea>':input(k,value,['policy_key','name'].includes(k)?'text':'number'))).join('')+'</form>','<button class="btn primary" data-save-policy>Save new version</button>');m.querySelector('[data-save-policy]').onclick=()=>{const body=Object.fromEntries(new FormData(m.querySelector('form')));body.validity_days=Number(body.validity_days);closeModal();run(()=>api.request('commercial-policies',{method:'POST',body}));};};
  if(find('[data-exact]'))find('[data-exact]').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),body={cell_id:Number(f.get('cell_id')),paying_pax:Number(f.get('paying_pax'))};if(f.has('use_confirmed_profile')){body.guest_profile={paying_pax:body.paying_pax,foc:Number(v.foc)};for(const k of ['adults','children','infants','total_guests','hotel_pax','cruise_pax','visa_pax','meal_pax','ticket_pax'])body.guest_profile[k]=f.get('confirmed_'+k)===''?null:Number(f.get('confirmed_'+k));}run(async()=>{const out=await request('recheck',body),r=out.recheck;const target=find('[data-recheck]');target.innerHTML='<p>'+esc(r.status)+' · '+esc(money(r.pricing.total_selling,r.pricing.selling_currency))+' · Margin '+esc(r.pricing.margin_pct)+'%</p>'+(['VALID','VALID_WITH_OVERRIDE'].includes(r.status)?'<button type="button" class="btn primary" data-confirm>Accept this exact option</button>':can('commercial.margin_override')?'<button type="button" class="btn" data-exact-override>Approve exact margin override</button>':'');if(target.querySelector('[data-exact-override]'))target.querySelector('[data-exact-override]').onclick=()=>reasonDialog('Exact margin override',reason=>request('override',{...body,reason,context_hash:r.context_hash}));if(target.querySelector('[data-confirm]'))target.querySelector('[data-confirm]').onclick=()=>run(async()=>{const opt=await api.request(base+'/options');const c=cells.find(c=>Number(c.id)===body.cell_id);await api.request('quotes/'+q.id+'/confirm',{method:'POST',body:{...body,option_id:c.result.option_id,variant_id:Number(c.variant_id),sent_content_hash:opt.sent_content_hash,expected_revision:revision}});});},false);};
 };
})();
