(function(){
 'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=v=>v===null||v===undefined?'—':Number(v).toLocaleString('en-US',{maximumFractionDigits:2});
 const sources=['TOTAL_GUESTS','PAYING_PAX','HOTEL_PAX','CRUISE_PAX','VISA_PAX','MEAL_PAX','TICKET_PAX','CUSTOM_QTY'];
 const select=(name,items,value)=>'<select name="'+name+'">'+items.map(x=>{const [id,label]=Array.isArray(x)?x:[x,x];return '<option value="'+esc(id)+'" '+(String(id)===String(value)?'selected':'')+'>'+esc(label)+'</option>';}).join('')+'</select>';
 const field=(label,name,value,type='text')=>'<label>'+esc(label)+'<input name="'+name+'" type="'+type+'" value="'+esc(value)+'"></label>';
 window.mountCostSheet=async function(host,{api,quoteData,can,navigate,modal,closeModal,toast,refresh,onProposal,ctx,data}){
  const v=quoteData.version,q=quoteData.quote,base='quote-versions/'+v.id,locked=['SENT','CONFIRMED','SUPERSEDED'].includes(v.version_status),cost=can('quote.view_cost'),profit=can('quote.view_profit'),edit=can('quote.edit')&&!locked;
  let revision=ctx.costing_revision,busy=false,mode=host.dataset.sheetMode||data.items.find(x=>Number(x.is_offered))?.costing_mode||['PRIVATE','SIC','HYBRID'].find(m=>[3,4,5].every(star=>data.items.some(x=>x.costing_mode===m&&parseInt(x.hotel_level)===star)))||data.items[0]?.costing_mode||'PRIVATE';
  let selectedIds=null;try{const pick=JSON.parse(host.dataset.vtaCostVariants||'null');if(Array.isArray(pick)&&pick.length===3)selectedIds=pick;}catch(e){}
  const selectedPackages=selectedIds?.map(id=>data.items.find(p=>Number(p.variant_id)===Number(id)&&p.costing_mode===mode));
  const packages=selectedPackages?.every(Boolean)?selectedPackages:[3,4,5].map(star=>data.items.find(x=>x.costing_mode===mode&&parseInt(x.hotel_level)===star&&x.variant_key===mode.toLowerCase()+'-'+star+'-'+star)||data.items.find(x=>x.costing_mode===mode&&parseInt(x.hotel_level)===star));
  const ids=packages.filter(Boolean).map(x=>Number(x.variant_id)),all=ids.length===3;
  let proposal=null;const priceView=host.dataset.sheetStep==='price';
  const request=async(path,b,method='POST')=>{const r=await api.request(path,{method,body:{...b,expected_revision:revision}});if(r.costing_revision!==undefined)revision=r.costing_revision;return r;};
  const sheet=b=>request(base+'/smart-costing/sheet',{variant_ids:ids,...b});
  const status=t=>{const el=host.querySelector('[data-sheet-status]');if(el)el.textContent=t;};
  const run=async fn=>{if(busy)return;busy=true;status('Saving…');const controls=[...host.querySelectorAll('input:not(:disabled),select:not(:disabled),button:not(:disabled)')];controls.forEach(x=>x.disabled=true);try{await fn();status('Saved');await refresh();}catch(e){status('Save failed · '+e.message);toast(e.message,true);}finally{busy=false;controls.filter(x=>x.isConnected).forEach(x=>x.disabled=false);}};
  const line=(p,r)=>p?.lines.find(l=>Number(l.requirement_id)===Number(r.id)&&l.line_kind==='SERVICE');
  const rows=ctx.requirements.filter(r=>r.requirement_state!=='NOT_APPLICABLE'&&packages.some(p=>line(p,r)?.active));
  const warnings=ls=>ls.some(l=>l?.active&&l.rate_status==='RATE_CONFLICT')?'⚠ Rate conflict':ls.some(l=>l?.active&&l.coverage_state==='UNRESOLVED')?'⚠ Rate not found':ls.some(l=>l?.active&&Number(l.review_required))?'⚠ Review required':'';
  const qtyValue=(r,l)=>l?.quantity_override??l?.custom_quantity??l?.resolved_quantity??ctx.profile[r.default_quantity_source.toLowerCase()]??ctx.guests[r.default_quantity_source.toLowerCase()]??'';
  const modes=['PRIVATE','SIC','HYBRID'];
  host.innerHTML='<div class="page cost-sheet"><div class="page-head"><div><h1>'+esc(v.tour_name||q.quote_ref)+'</h1><p>'+esc(q.quote_ref)+' · V'+v.version_no+' · '+esc(v.version_status)+'</p></div><button class="btn" data-sales>Sales</button></div><nav class="quote-steps"><button data-info>Info</button><button data-itinerary>Itinerary</button><button data-cost class="'+(!priceView?'active':'')+'">Cost</button><button data-price class="'+(priceView?'active':'')+'">Price</button><button data-proposal>Proposal / Send</button></nav><div role="status" class="sheet-status" data-sheet-status>'+ (locked?'Read-only · Create a revision to edit':'Saved')+'</div><form data-guests class="sheet-guests"><strong>Guests</strong>'+['adults','children','infants','foc','paying_pax','total_guests'].map(k=>'<label>'+esc(k==='paying_pax'?'Paying':k==='total_guests'?'Total':k==='foc'?'FOC':k[0].toUpperCase()+k.slice(1))+'<input name="'+k+'" type="number" min="0" value="'+esc(ctx.guests[k])+'" '+(!edit||k==='total_guests'?'disabled':'')+'></label>').join('')+'</form>'+ (cost?'<section class="panel"><div class="panel-head"><h2>'+ (priceView?'Price · three packages':'Cost Sheet')+'</h2><div class="actions">'+select('mode',modes,mode)+(edit&&!priceView?'<button class="btn primary" data-add>+ Add Service</button><button class="btn" data-paste>Import / Paste</button>':'')+'<button class="btn" data-advanced>Advanced</button></div></div>'+(!all?'<div class="panel-body"><p>Three variants over this itinerary have not been prepared for '+esc(mode)+'. Existing variants are retained.</p>'+(edit?'<button class="btn primary" data-init>Prepare 3★ / 4★ / 5★</button>':'')+'</div>':'')+(!priceView&&all?'<div class="sheet-scroll"><table class="sheet-table"><thead><tr><th>Service</th><th>Pax / Resources</th><th>Qty</th>'+[3,4,5].map(s=>'<th>'+s+'★ Unit · VND</th><th>'+s+'★ Total · VND</th>').join('')+'<th></th></tr></thead><tbody>'+rows.map(r=>rowHTML(r)).join('')+'</tbody><tfoot><tr><th colspan="3">Total cost · VND</th>'+packages.map(p=>'<td></td><td>'+money(p.pricing?.cost_total_vnd)+'</td>').join('')+'<td></td></tr></tfoot></table></div>':'')+(all?'<div class="sheet-summaries">'+packages.map((p,i)=>summary(p,i+3)).join('')+'</div>':'')+'<div class="panel-body actions">'+(all&&edit?'<button class="btn" data-offer>Offer these three packages</button>':'')+'<button class="btn" data-check>Check quote</button><button class="btn primary" data-next>'+ (priceView?'Continue to Proposal':'Continue to Price')+'</button></div><div class="panel-body" data-validation></div></section>':'<p>Financial access is required to open supplier costs. Itinerary and proposal remain available.</p>')+'</div>';
  function rowHTML(r){const ls=packages.map(p=>line(p,r)),first=ls.find(l=>l?.active),shared=host.dataset['separate'+r.id]!=='1'&&ls.filter(l=>l?.active).every(l=>l.unit_rate_vnd===first?.unit_rate_vnd),units=['GUIDE','HOTEL','MEAL','OTHER'].includes(r.category);
   return '<tr data-row="'+r.id+'"><td><input data-name aria-label="Service" value="'+esc(r.service_name)+'" '+(!edit?'disabled':'')+'><small>'+esc(r.service_date||'Review service date')+' · '+esc(r.category)+'</small><label class="sheet-share"><input data-shared type="checkbox" '+(shared?'checked':'')+' '+(!edit?'disabled':'')+'> Same for all options</label>'+(warnings(ls)?'<button class="sheet-warning" data-details="'+r.id+'">'+warnings(ls)+'</button>':'')+'</td><td><input type="number" data-pax min="0" aria-label="Pax or resource count" value="'+esc(qtyValue(r,first))+'" '+(!edit?'disabled':'')+'><small>'+esc(['TRANSPORT','GUIDE'].includes(r.category)?r.category==='TRANSPORT'?'Vehicles':'Guides':r.default_quantity_source.replaceAll('_',' '))+'</small></td><td><input type="number" data-qty min="1" aria-label="Service units" value="'+esc(first?.units_override??r.service_units??1)+'" '+(!edit||!units?'disabled':'')+'><small>'+esc(r.category==='HOTEL'?'Nights':r.category==='GUIDE'?'Guide days':r.category==='MEAL'?'Meals':'')+'</small></td>'+ls.map((l,i)=>'<td>'+(l?.active&&l.coverage_state!=='INCLUDED'?'<input type="number" min="0" step="0.01" data-unit="'+ids[i]+'" aria-label="'+(i+3)+' star unit VND" value="'+esc(l.unit_rate_vnd??'')+'" '+(!edit||shared&&i>0?'disabled':'')+'>':esc(l?.coverage_state==='INCLUDED'?'Included':'—'))+'</td><td class="sheet-total">'+(l?.active?money(l.total_vnd):'—')+'</td>').join('')+'<td><button class="sheet-detail" data-details="'+r.id+'" aria-label="Service details">⋯</button>'+(edit?'<button class="sheet-delete" data-remove="'+r.id+'" aria-label="Delete service">×</button>':'')+'</td></tr>';
  }
  function summary(p,star){const x=p.pricing||{};return '<article class="sheet-summary" data-summary="'+star+'"><h3>'+star+'★ PACKAGE</h3><p>Hotel '+esc(p.hotel_level)+' · Cruise '+esc(p.cruise_level??'N/A')+'★</p><dl><dt>Total Cost · VND</dt><dd>'+money(x.cost_total_vnd)+'</dd>'+ (profit?'<dt>Profit · VND</dt><dd>'+money(x.profit_vnd)+'</dd><dt>Margin / Markup</dt><dd>'+money(x.margin_pct)+'% / '+money(x.markup_pct)+'%</dd>':'')+'<dt>Selling Price</dt><dd>'+esc(p.selling_currency)+' '+money(x.total_selling)+'</dd><dt>Paying Pax</dt><dd>'+ctx.guests.paying_pax+'</dd></dl><strong>Price / Paying Pax<br>'+esc(p.selling_currency)+' '+money(x.selling_per_pax)+'</strong>'+ (profit&&edit?'<label>Commercial target'+select('pricing_mode'+p.variant_id,[['MARKUP','Markup %'],['TARGET_MARGIN','Target margin %'],['MANUAL','Manual price / paying pax']],p.pricing_mode)+'<input type="number" min="0" step="0.01" data-pricing="'+p.variant_id+'" value="'+esc(p.pricing_value)+'"></label>':'')+(edit?'<label>Cruise category'+select('cruise_level'+p.variant_id,[['','Not applicable'],['3','3★'],['4','4★'],['5','5★']],p.cruise_level??'')+'</label>':'')+'<div data-stay="'+p.variant_id+'"></div></article>';}
  host.querySelector('[data-sales]').onclick=()=>navigate('sales-list',{salesTab:'quotes'});
  for(const s of ['cost','price'])host.querySelector('[data-'+s+']').onclick=()=>{host.dataset.sheetStep=s;refresh();};
  host.querySelectorAll('[data-itinerary],[data-proposal]').forEach(b=>b.onclick=()=>onProposal?.());
  host.querySelector('[data-info]').onclick=()=>{const m=modal('Quote Info','<form>'+field('Tour title','tour_name',v.tour_name)+field('Start date','start_date',v.start_date,'date')+field('End date','end_date',v.end_date,'date')+(cost?field('FX · VND per USD','fx_rate',v.fx_rate,'number'):'')+'</form>',edit?'<button class="btn primary" data-save-info>Save</button>':'');if(!edit)m.querySelectorAll('input').forEach(x=>x.disabled=true);else m.querySelector('[data-save-info]').onclick=()=>{const body=Object.fromEntries(new FormData(m.querySelector('form')));closeModal();run(()=>request(base+'/smart-costing/context',body,'PUT'));};};
  const gf=host.querySelector('[data-guests]');gf.onsubmit=e=>e.preventDefault();
  const nonPaying=Math.max(0,Number(ctx.guests.total_guests)-Number(ctx.guests.foc)-Number(ctx.guests.paying_pax));
  gf.querySelectorAll('input:not(:disabled)').forEach(x=>{x.oninput=()=>{status('Unsaved changes');if(x.name!=='paying_pax'){const total=['adults','children','infants','foc'].reduce((sum,k)=>sum+Number(gf.elements[k].value),0);gf.elements.total_guests.value=total;gf.elements.paying_pax.value=Math.max(1,total-Number(gf.elements.foc.value)-nonPaying);}};x.onchange=()=>{const b=Object.fromEntries([...gf.querySelectorAll('input')].map(el=>[el.name,Number(el.value)]));run(()=>request(base+'/smart-costing/context',b,'PUT'));};});
  if(!cost)return;
  host.querySelector('[name=mode]').onchange=e=>{host.dataset.sheetMode=e.target.value;refresh();};
  host.querySelector('[data-advanced]').onclick=()=>{host.dataset.vs21Advanced='1';refresh();};
  host.querySelector('[data-init]')?.addEventListener('click',()=>run(()=>sheet({action:'init',mode})));
  host.querySelector('[data-next]').onclick=()=>{if(priceView)onProposal?.();else{host.dataset.sheetStep='price';refresh();}};
  host.querySelector('[data-offer]')?.addEventListener('click',()=>run(()=>sheet({action:'variant',changes:{is_offered:true}})));
  host.querySelector('[data-check]').onclick=async()=>{try{const r=await api.request(base+'/smart-costing/validation');host.querySelector('[data-validation]').innerHTML=r.valid?'Quote checks passed.':[...r.errors,...r.warnings].map(e=>'<p>'+esc(e.code)+(e.line_id?' · Line '+e.line_id:'')+'</p>').join('');}catch(e){toast(e.message,true);}};
  function evidence(req,ls,done){const existing=ls.find(l=>l?.supplier_id),contract=existing?.manual_contract_json?JSON.parse(existing.manual_contract_json):{};const m=modal('Manual supplier cost','<p>VND per '+esc(req.category==='TRANSPORT'?'vehicle for full tour':req.category==='HOTEL'?'pax per night':req.category==='GUIDE'?'guide per day':'service basis')+'. Supplier evidence is required. Rates remain unchanged.</p><form><label>Supplier'+select('supplier_id',[['','Select supplier'],...(data.supplier_choices||[]).map(s=>[s.id,s.name])],existing?.supplier_id||'')+'</label>'+field('Supplier evidence / reason','manual_reason',existing?.manual_reason||'')+'<label>Tax basis'+select('tax_basis',['NET','TAX_INCLUDED'],contract.tax_basis||'NET')+'</label>'+ (req.category==='TRANSPORT'?field('Seats per vehicle','capacity',contract.capacity||'','number'):'')+'</form>','<button class="btn primary" data-manual-save>Save cost</button>');m.querySelector('[data-manual-save]').onclick=()=>{const f=m.querySelector('form'),b=Object.fromEntries(new FormData(f));if(!b.supplier_id||!b.manual_reason.trim())return toast('Select a supplier and provide its evidence.',true);closeModal();done({supplier_id:Number(b.supplier_id),original_currency:'VND',manual_reason:b.manual_reason,manual_contract:{evidence:b.manual_reason,tax_basis:b.tax_basis,capacity:b.capacity?Number(b.capacity):null,package_scope:{itinerary_scope:{start_date:v.start_date,end_date:v.end_date,legs:ctx.schedule.map(d=>({day_key:d.day_key,date:d.date,route:d.route||'',transport_mode:d.transport_mode||''}))}}}});};}
  host.querySelectorAll('[data-row]').forEach(row=>{const req=ctx.requirements.find(r=>String(r.id)===row.dataset.row),ls=packages.map(p=>line(p,req));
   row.querySelector('[data-shared]').onchange=e=>{host.dataset['separate'+req.id]=e.target.checked?'0':'1';row.querySelectorAll('[data-unit]').forEach((x,i)=>x.disabled=!edit||e.target.checked&&i>0);if(e.target.checked)row.querySelectorAll('[data-unit]').forEach((x,i)=>{if(i)x.value=row.querySelector('[data-unit]')?.value||'';});if(e.target.checked&&row.querySelector('[data-unit]')?.value!=='')row.querySelector('[data-unit]')?.dispatchEvent(new Event('change'));else status('Unsaved changes · enter a unit price.');};
   const save=(b)=>run(()=>sheet(b));
   row.querySelector('[data-name]').onchange=e=>save({requirement:{id:Number(req.id),service_name:e.target.value},line:{}});
   row.querySelector('[data-qty]').onchange=e=>save({requirement:{id:Number(req.id),service_units:Number(e.target.value)},line:{}});
   row.querySelector('[data-pax]').onchange=e=>{const custom=req.default_quantity_source==='CUSTOM_QTY';const m=modal(custom?'Resource count':'Quantity override','<p>'+ (custom?'Explicit vehicle / guide / custom count.':'This overrides the guest source for this service. It stays fixed when guests change; review remains required.')+'</p>'+field('Reason','reason','')+'<button class="btn" data-follow>Follow source</button>','<button class="btn primary" data-qty-save>Apply</button>');m.querySelector('[data-follow]').disabled=custom;m.querySelector('[data-follow]').onclick=()=>{closeModal();save({requirement_id:Number(req.id),line:{quantity_override:null}});};m.querySelector('[data-qty-save]').onclick=()=>{const reason=m.querySelector('[name=reason]').value;if(!reason.trim())return toast('Enter a reason.',true);closeModal();save({requirement_id:Number(req.id),line:custom?{custom_quantity:Number(e.target.value)}:{quantity_override:Number(e.target.value),override_reason:reason}});};};
   row.querySelectorAll('[data-unit]').forEach(x=>{x.oninput=()=>status('Unsaved changes');x.onchange=()=>{const shared=row.querySelector('[data-shared]').checked;const b={requirement_id:Number(req.id),shared};evidence(req,ls,manual=>{if(shared)b.line={...manual,unit_amount_original:x.value};else b.lines={[x.dataset.unit]:{...manual,unit_amount_original:x.value}};if(!shared)b.variant_ids=[Number(x.dataset.unit)];save(b);});};});
  });
  host.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{const m=modal('Remove service from draft','<p>The requirement is retained as Not Applicable with your reason. This removes its cost from all variants of this draft.</p>'+field('Reason','reason',''),' <button class="btn danger" data-confirm-remove>Remove</button>');m.querySelector('[data-confirm-remove]').onclick=()=>{const reason=m.querySelector('[name=reason]').value;if(!reason.trim())return toast('Enter a reason.',true);closeModal();run(()=>sheet({action:'remove',requirement_id:Number(x.dataset.remove),reason}));};});
  host.querySelectorAll('[data-details]').forEach(x=>x.onclick=()=>{const r=ctx.requirements.find(r=>String(r.id)===x.dataset.details),ls=packages.map(p=>line(p,r)),m=modal(r.service_name,'<p>'+esc(r.category)+' · '+esc(r.default_quantity_source)+' · '+esc(r.requirement_state)+'</p>'+ls.map((l,i)=>'<h3>'+(i+3)+'★</h3><p>'+esc(l?.trace?.sentence||'Rate not found')+'</p><p>'+esc(l?.override_reason||l?.manual_reason||'')+'</p>').join('')+(edit?'<form>'+field('Destination','destination',r.scope?.destination||'')+field('Service date','service_date',r.service_date,'date')+'<label>Quantity source'+select('default_quantity_source',sources,r.default_quantity_source)+'</label><label>Requirement'+select('requirement_state',['REQUIRED','NEEDS_REVIEW','NOT_APPLICABLE'],r.requirement_state)+'</label>'+field('Review reason','reason','')+'</form>':''),edit?'<button class="btn" data-save-details>Save details</button><button class="btn primary" data-review>Review supplier evidence & quantities</button>':'');if(edit){m.querySelector('[data-save-details]').onclick=()=>{const b=Object.fromEntries(new FormData(m.querySelector('form')));closeModal();run(()=>sheet({requirement:{id:Number(r.id),service_date:b.service_date,default_quantity_source:b.default_quantity_source,requirement_state:b.requirement_state,scope:{...r.scope,destination:b.destination},metadata:{...r.metadata,reason:b.reason}},line:{quantity_source:b.default_quantity_source}}));};m.querySelector('[data-review]').onclick=()=>{const reason=m.querySelector('[name=reason]').value;if(!reason.trim())return toast('Enter your review reason.',true);closeModal();run(()=>sheet({action:'review',requirement_id:Number(r.id),variant_ids:packages.filter(p=>line(p,r)?.active).map(p=>Number(p.variant_id)),review_reason:reason}));};}});
  function addService(prefill={}){const m=modal('Add Service','<form>'+field('Service','service_name',prefill.service_name||'')+'<label>Category'+select('category',['TRANSPORT','GUIDE','HOTEL','CRUISE','VISA','MEAL','ATTRACTION','TOUR','OTHER'],prefill.category||'OTHER')+'</label>'+field('Service date','service_date',v.start_date,'date')+field('Destination','destination','')+field('Quantity / nights / guide days / meals','service_units',prefill.qty||1,'number')+'</form><p>Guest population, resources and supplier evidence can be reviewed in the new row. No supplier price is generated from text.</p>','<button class="btn primary" data-add-save>Add service</button>');m.querySelector('[data-add-save]').onclick=()=>{const b=Object.fromEntries(new FormData(m.querySelector('form'))),source={TRANSPORT:'CUSTOM_QTY',GUIDE:'CUSTOM_QTY',HOTEL:'HOTEL_PAX',CRUISE:'CRUISE_PAX',VISA:'VISA_PAX',MEAL:'MEAL_PAX',ATTRACTION:'TICKET_PAX',TOUR:'TOTAL_GUESTS',OTHER:'CUSTOM_QTY'}[b.category];closeModal();run(()=>sheet({requirement:{category:b.category,service_name:b.service_name,service_date:b.service_date,service_units:Number(b.service_units),default_quantity_source:source,service_mode:mode==='HYBRID'?'BOTH':mode,requirement_state:'REQUIRED',scope:{destination:b.destination}},line:source==='CUSTOM_QTY'?{custom_quantity:prefill.pax??1}:{}}));};}
  host.querySelector('[data-add]')?.addEventListener('click',()=>{if(!all)return toast('Prepare the three packages first.',true);addService();});
  host.querySelectorAll('[data-pricing]').forEach(x=>x.onchange=()=>{const id=Number(x.dataset.pricing),mode=host.querySelector('[name=pricing_mode'+id+']').value;run(()=>sheet({action:'variant',variant_ids:[id],changes:{pricing_mode:mode,pricing_value:x.value}}));});
  host.querySelectorAll('select[name^=cruise_level]').forEach(x=>x.onchange=()=>run(()=>sheet({action:'variant',variant_ids:[Number(x.name.replace('cruise_level',''))],changes:{cruise_level:x.value===''?null:Number(x.value)}})));
  host.querySelectorAll('select[name^=pricing_mode]').forEach(x=>x.onchange=()=>status('Unsaved changes · enter the commercial target to apply.'));
  host.querySelector('[data-paste]')?.addEventListener('click',()=>{const m=modal('Paste Cost Rows','<p>Tab-separated: Service, Pax/resources, Qty, Unit VND; or Service, Pax/resources, Qty, 3★ Unit, 4★ Unit, 5★ Unit. Headers are optional. Preview first; pasted supplier prices require evidence. Category defaults to Other and must be reviewed.</p><textarea data-sheet-paste rows="8"></textarea><button class="btn" data-paste-preview>Preview</button><div data-paste-result></div>','');m.querySelector('[data-paste-preview]').onclick=()=>{try{const parsed=m.querySelector('textarea').value.trim().split(/\r?\n/).filter(Boolean).map(s=>s.split('\t'));if(parsed[0]?.[0].toLowerCase()==='service')parsed.shift();if(!parsed.length||parsed.length>50)throw Error('Paste one to 50 rows.');parsed.forEach(r=>{if(![4,6].includes(r.length)||!r[0].trim()||r.slice(1).some(s=>!/^\d+(?:\.\d{1,2})?$/.test(s.trim())))throw Error('Review columns; use plain non-negative numbers without separators.');if(!Number.isInteger(Number(r[1]))||!Number.isInteger(Number(r[2]))||Number(r[2])<1)throw Error('Pax and quantity must be whole numbers.');});m.querySelector('[data-paste-result]').innerHTML=parsed.map((r,i)=>'<p>'+esc(r.join(' · '))+' · '+(r.length===4?'Same for all':'Separate options')+' <button class="btn" data-import-row="'+i+'">Review & add</button></p>').join('');m.querySelectorAll('[data-import-row]').forEach(x=>x.onclick=()=>{const r=parsed[Number(x.dataset.importRow)],req={category:'OTHER',service_name:r[0],service_date:v.start_date,service_units:Number(r[2]),default_quantity_source:'CUSTOM_QTY',service_mode:mode==='HYBRID'?'BOTH':mode,requirement_state:'REQUIRED',scope:{}},ls=[];evidence(req,ls,manual=>{const b={requirement:req,shared:r.length===4};if(b.shared)b.line={...manual,custom_quantity:Number(r[1]),unit_amount_original:r[3]};else b.lines=Object.fromEntries(ids.map((id,i)=>[id,{...manual,custom_quantity:Number(r[1]),unit_amount_original:r[i+3]}]));closeModal();run(()=>sheet(b));});});}catch(e){m.querySelector('[data-paste-result]').textContent=e.message;}};});
  if(all){try{proposal=await api.request(base+'/proposal');}catch(e){status('Accommodation unavailable · '+e.message);}if(proposal)for(const p of packages){const box=host.querySelector('[data-stay="'+p.variant_id+'"]'),star=parseInt(p.hotel_level),key={3:'three_star',4:'four_star',5:'five_star'}[star];box.innerHTML='<div class="sheet-stay">'+(proposal.settings.accommodation||[]).map((r,i)=>'<label>'+esc(r.type+' · '+r.destination)+'<input data-accommodation="'+i+'" value="'+esc(r[key])+'" '+(!edit||!can('proposal.edit')?'disabled':'')+'></label>').join('')+(edit&&can('proposal.edit')?'<button class="btn" data-stay-add>Add Hotel / Cruise</button>':'')+'</div>';box.querySelectorAll('[data-accommodation]').forEach(x=>x.onchange=()=>run(async()=>{const settings=structuredClone(proposal.settings);settings.accommodation[Number(x.dataset.accommodation)][key]=x.value;await request(base+'/proposal',{settings,days:proposal.days,links:proposal.links},'PUT');}));box.querySelector('[data-stay-add]')?.addEventListener('click',()=>{const m=modal('Accommodation selection','<p>Public selection label; supplier rate remains independently reviewed.</p><form><label>Type'+select('type',['HOTEL','CRUISE'],'HOTEL')+'</label>'+field('Destination','destination','')+field('Property / room / cabin','property','')+field('Nights','nights',1,'number')+'</form>','<button class="btn primary" data-stay-save>Add selection</button>');m.querySelector('[data-stay-save]').onclick=()=>{const b=Object.fromEntries(new FormData(m.querySelector('form'))),settings=structuredClone(proposal.settings);let r=settings.accommodation.find(r=>r.type===b.type&&r.destination===b.destination);if(!r){r={type:b.type,destination:b.destination,nights:Number(b.nights),three_star:'',four_star:'',five_star:''};settings.accommodation.push(r);}r[key]=b.property;closeModal();run(()=>request(base+'/proposal',{settings,days:proposal.days,links:proposal.links},'PUT'));};});}}
 };
})();
