(()=>{'use strict';
const types={hero:'Ảnh bìa & tiêu đề',text:'Đoạn giới thiệu',highlights:'Điểm nổi bật',itinerary:'Lịch trình',image:'Ảnh',faq:'Câu hỏi thường gặp',cta:'Nút liên hệ'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const copy=x=>JSON.parse(JSON.stringify(x));
function key(){return 'lp-'+crypto.randomUUID();}
function url(s){if(!s)return '';if(typeof s!=='string'||s.length>1000||/[\s\\\u0000-\u001f]/.test(s))throw Error('Link phải là HTTPS hợp lệ.');try{const u=new URL(s);if(u.protocol!=='https:'||u.username||u.password)throw Error();return s;}catch{throw Error('Link phải là HTTPS hợp lệ, không chứa tài khoản/mật khẩu.');}}
function block(type){if(!Object.hasOwn(types,type))throw Error('Loại khối không hợp lệ.');return {id:key(),type,title:{hero:'Your Vietnam journey, thoughtfully planned',text:'Travel your way',highlights:'Why travel with us',itinerary:'Your suggested itinerary',image:'A glimpse of Vietnam',faq:'Before you travel',cta:'Let’s plan your Vietnam trip'}[type],body:{hero:'Private Vietnam tours for Indian families and groups. Share your dates and interests for a tailored proposal.',text:'Replace this text with your verified tour details.',highlights:'Flexible travel dates\nPrivate itinerary planning\nMeal preferences discussed before booking',itinerary:'Day 1 · Arrival and check-in\nDay 2 · Explore with your local guide\nDay 3 · Tailor the day to your interests',image:'Add a real photo that you own or have permission to use.',faq:'Can I customise the itinerary? | Please share your interests and preferred travel dates.\nAre prices confirmed? | Prices and services are subject to written confirmation.',cta:'Tell us your travel dates, group size and preferred destinations.'}[type],image:'',alt:'',rights:'',button:['hero','cta'].includes(type)?'Request a tailored itinerary':'',url:''};}
function template(name='vietnam'){const blocks=name==='blank'?[]:name==='short'?['hero','highlights','cta']:['hero','text','highlights','itinerary','faq','cta'];return {schema:1,title:name==='blank'?'Landing page mới':'Vietnam Private Tours',description:'Plan a private Vietnam trip with Vietnam Travel Advisor.',brand:'Vietnam Travel Advisor',accent:'#087f8c',language:'en',blocks:blocks.map(block)};}
function normalize(x){if(!x||x.schema!==1||!Array.isArray(x.blocks)||x.blocks.length>40)throw Error('File landing page không hợp lệ (tối đa 40 khối).');const str=(o,k,max,required=false)=>{if(typeof o[k]!=='string'||o[k].length>max||(required&&!o[k].trim()))throw Error('Kiểm tra trường '+k+' (tối đa '+max+' ký tự).');return o[k].trim();};
 const p={schema:1,title:str(x,'title',120,true),description:str(x,'description',300),brand:str(x,'brand',100,true),accent:str(x,'accent',7),language:str(x,'language',2),blocks:[]};if(!/^#[0-9a-f]{6}$/i.test(p.accent)||!['en','vi'].includes(p.language))throw Error('Màu hoặc ngôn ngữ không hợp lệ.');const ids=new Set();
 for(const b of x.blocks){if(!b||!Object.hasOwn(types,b.type)||typeof b.id!=='string'||!/^lp-[a-zA-Z0-9-]{8,70}$/.test(b.id)||ids.has(b.id))throw Error('Khối bị trùng hoặc không hợp lệ.');ids.add(b.id);const n={id:b.id,type:b.type,title:str(b,'title',200),body:str(b,'body',5000),image:url(b.image),alt:str(b,'alt',200),rights:str(b,'rights',500),button:str(b,'button',80),url:url(b.url)};if(n.image&&(!n.alt||!n.rights))throw Error('Ảnh cần mô tả và ghi chú quyền sử dụng.');p.blocks.push(n);}return p;
}
const css=`*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#172c3d;background:#fff;line-height:1.65}header,footer{padding:22px max(6vw,20px);background:#102e3d;color:#fff}header{font-weight:700;letter-spacing:.04em}main{max-width:1100px;margin:auto}section{padding:56px 7%;overflow-wrap:anywhere}section:nth-child(even){background:#f2f7f6}h1,h2{line-height:1.18;letter-spacing:-.035em;margin:0 0 22px}h1{font-size:clamp(32px,5vw,60px)}h2{font-size:clamp(25px,3vw,38px)}p{white-space:pre-line}img{display:block;width:100%;max-height:550px;object-fit:cover;border-radius:18px;margin:22px 0}.hero{padding-top:76px;padding-bottom:76px}.eyebrow{font-size:12px;text-transform:uppercase;font-weight:bold;letter-spacing:.16em}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(220px,100%),1fr));gap:16px;list-style:none;padding:0}.cards li{background:#fff;border:1px solid #dce7e5;border-radius:14px;padding:24px}ol li{padding:12px 0}details{border-bottom:1px solid #dce7e5;padding:18px 0}summary{cursor:pointer;font-weight:bold}a.cta{display:inline-block;padding:14px 26px;border-radius:9px;background:var(--accent);color:#fff;font-weight:bold;text-decoration:none;margin-top:12px}.disabled-cta{display:inline-block;padding:14px 26px;border:1px dashed #728792;color:#526b79;border-radius:9px}.cta-section{text-align:center}.placeholder{padding:45px;border:1px dashed #8da8ae;border-radius:14px;color:#526b79;text-align:center}footer{font-size:13px} @media(max-width:600px){section{padding:36px 22px}.hero{padding:45px 22px}}`;
function renderBlock(b){const title=b.title?`<${b.type==='hero'?'h1':'h2'}>${esc(b.title)}</${b.type==='hero'?'h1':'h2'}>`:'',photo=b.image?`<img src="${esc(b.image)}" alt="${esc(b.alt)}" loading="lazy" referrerpolicy="no-referrer">`:'',paragraph=b.body?`<p>${esc(b.body)}</p>`:'',cta=b.button?(b.url?`<a class="cta" href="${esc(b.url)}" rel="noopener noreferrer">${esc(b.button)}</a>`:`<span class="disabled-cta">${esc(b.button)} · ${'Chưa có link'}</span>`):'';
 let content=paragraph;if(b.type==='highlights')content='<ul class="cards">'+b.body.split('\n').filter(Boolean).map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul>';if(b.type==='itinerary')content='<ol>'+b.body.split('\n').filter(Boolean).map(s=>'<li>'+esc(s)+'</li>').join('')+'</ol>';if(b.type==='faq')content=b.body.split('\n').filter(Boolean).map(s=>{const i=s.indexOf('|');return `<details><summary>${esc(i<0?s:s.slice(0,i))}</summary><p>${esc(i<0?'':s.slice(i+1))}</p></details>`;}).join('');
 return `<section class="${b.type==='hero'?'hero':b.type==='cta'?'cta-section':''}">${b.type==='hero'?'<p class="eyebrow">Discover Vietnam</p>':''}${title}${photo|| (b.type==='image'?'<div class="placeholder">Thêm ảnh thật của tour</div>':'')}${content}${['hero','cta'].includes(b.type)?cta:''}</section>`;
}
function html(page){const p=normalize(page);return `<!doctype html><html lang="${p.language}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(p.description)}"><meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src https:; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>${esc(p.title)}</title><style>${css}</style></head><body style="--accent:${p.accent}"><header>${esc(p.brand)}</header><main>${p.blocks.map(renderBlock).join('')}</main><footer>${esc(p.brand)}</footer></body></html>`;}
window.VTALandingModel={types,key,copy,esc,url,block,template,normalize,html,css,renderBlock};
})();
