(()=>{'use strict';
const M=window.VTAMarketingModel;
let owner='',sequence=0,ui={tab:'overview',q:'',channel:'',topic:'',status:'',day:'',month:M.today().slice(0,7)};
window.VTAMarketing=async function(options){
 const {esc,modal,closeModal,toast,navigate,can}=options,preview=!!window.VTA_PREVIEW,api=preview?window.VTAMarketingDemo:options.api;
 const vi=window.VTA_I18N?.language==='vi',t=(en,vn)=>vi?vn:en,root=document.querySelector('#workspace'),renderId=++sequence;
 const userKey=preview?'demo':String(options.api.user?.company_id)+':'+String(options.api.user?.id);
 if(owner!==userKey){owner=userKey;ui={tab:'overview',q:'',channel:'',topic:'',status:'',day:'',month:M.today().slice(0,7)};}
 const data=await api.request('marketing/studio');if(renderId!==sequence||!root.isConnected||root.dataset.view!=='marketing')return;
 const manage=can('campaign.manage'),approve=can('marketing.approve'),leadManage=can('lead.manage');
 const tabs=[['overview',t('Overview','Tổng quan')],['content',t('Content & review','Nội dung & duyệt')],['calendar',t('Calendar','Lịch nội dung')],['publishing',t('Publishing','Đăng bài')],['connections',t('Connections','Kết nối Meta')],['library',t('Content library','Kho nội dung')],['webhooks',t('Webhooks','Webhook')],['campaigns',t('Campaigns','Chiến dịch')],['inbox',t('Conversations','Trao đổi & lead')],['insights',t('Reports','Báo cáo')],['channels',t('Channels','Kênh')]];
 if(options.initialTab&&tabs.some(x=>x[0]===options.initialTab))ui.tab=options.initialTab;
 const statusName=s=>({DRAFT:t('Draft','Bản nháp'),PENDING:t('Review','Chờ duyệt'),APPROVED:t('Approved · held','Đã duyệt · chờ phát hành'),REJECTED:t('Rejected','Từ chối'),NEW:t('New','Mới'),FOLLOW_UP:t('Follow-up','Theo dõi'),CLOSED:t('Closed','Đã đóng')}[s]||s);
 const badge=s=>`<span class="mk-badge ${esc(s.toLowerCase())}">${esc(statusName(s))}</span>`;
 const dateText=x=>M.localStamp(x).replace('T',' ')||t('No planned time','Chưa có lịch');
 const empty=text=>`<div class="mk-empty">${text}</div>`;
 const button=(act,label,id='',primary=false)=>`<button class="btn ${primary?'primary':''}" data-mk="${act}" data-id="${esc(id)}">${label}</button>`;
 const asset=x=>M.url(x.asset_url)?`<a class="mk-asset" href="${esc(M.url(x.asset_url))}" target="_blank" rel="noopener noreferrer">${t('Open media / design link ↗','Mở link media / thiết kế ↗')}</a>`:'';
 const selected=(a,b)=>String(a)===String(b)?' selected':'';
 const select=(label,name,values,value='',required=false)=>`<label>${label}<select name="${name}" ${required?'required':''}>${values.map(v=>{const a=Array.isArray(v)?v:[v,v];return `<option value="${esc(a[0])}"${selected(a[0],value)}>${esc(a[1])}</option>`;}).join('')}</select></label>`;
 const input=(label,name,value='',type='text',required=false)=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value??'')}" ${required?'required':''} ${type==='number'?(name==='budget'?'min="0" step="0.01"':'min="0" step="1"'):'maxlength="190"'}></label>`;
 const area=(label,name,value='',required=true)=>`<label class="mk-span">${label}<textarea name="${name}" rows="5" maxlength="12000" ${required?'required':''}>${esc(value??'')}</textarea></label>`;
 const campaignOptions=data.campaigns.filter(c=>c.status!=='ARCHIVED').map(c=>[c.id,c.name]);
 const metadata=x=>select(t('Topic','Chủ đề'),'topic',M.topics,x.topic||'General')+input(t('Tags, separated by commas','Thẻ, cách nhau bằng dấu phẩy'),'tags',x.tags)+`<label class="mk-span">${t('Optional HTTPS media / Canva / Drive link','Link HTTPS media / Canva / Drive (tùy chọn)')}<input name="asset_url" type="url" maxlength="1000" value="${esc(x.asset_url||'')}"></label>`+`<label class="mk-span">${t('Asset ownership / permission note','Ghi chú quyền sử dụng media')}<input name="rights_note" maxlength="500" value="${esc(x.rights_note||'')}" placeholder="${t('VTA-owned footage or licensed source…','Tư liệu VTA sở hữu hoặc nguồn được cấp quyền…')}"></label>`;
 function matches(x){const s=(ui.q||'').trim().toLowerCase();return (!s||[x.body,x.title,x.campaign_name,x.tags,x.contact_name,x.message].some(v=>String(v||'').toLowerCase().includes(s)))&&(!ui.channel||x.channel===ui.channel)&&(!ui.topic||x.topic===ui.topic)&&(!ui.status||x.status===ui.status)&&(!ui.day||M.localStamp(x.planned_at).slice(0,10)===ui.day);}
 function counts(){return Object.fromEntries((data.counts||[]).map(x=>[x.status,Number(x.total)]));}
 function filters(content=true){return `<div class="mk-filters"><label>${t('Search','Tìm kiếm')}<input id="mkSearch" value="${esc(ui.q)}" placeholder="${t('Content, campaign, tags…','Nội dung, chiến dịch, thẻ…')}"></label>${content?select(t('Channel','Kênh'),'filterChannel',[['',t('All channels','Tất cả kênh')],...M.channels],ui.channel):''}${select(t('Topic','Chủ đề'),'filterTopic',[['',t('All topics','Tất cả chủ đề')],...M.topics],ui.topic)}${content?select(t('Status','Trạng thái'),'filterStatus',[['',t('All statuses','Tất cả trạng thái')],...['DRAFT','PENDING','APPROVED','REJECTED'].map(s=>[s,statusName(s)])],ui.status):''}${button('clear',t('Clear filters','Xóa bộ lọc'))}</div>${ui.day?`<p class="mk-note">${t('Date','Ngày')}: ${esc(ui.day)} · UTC+7</p>`:''}`;}
 function card(x){return `<article class="mk-content"><div class="mk-card-top"><span class="mk-channel">${esc(x.channel)}</span>${badge(x.status)}</div><h3>${esc(x.campaign_name||'')}</h3><div class="mk-meta">${esc(x.topic||'General')} · ${esc(x.content_format||'POST')} · #${x.id}</div><p class="mk-body">${esc(x.body)}</p>${asset(x)}<div class="mk-meta">${esc(dateText(x.planned_at))}${x.planned_at?' · UTC+7':''}${x.parent_content_id?` · ${t('Revision of','Bản sửa của')} #${x.parent_content_id}`:''}</div>${x.tags?`<div class="mk-tags">${esc(x.tags)}</div>`:''}${x.creator_name?`<div class="mk-meta">${t('Author','Người soạn')}: ${esc(x.creator_name)}${x.reviewer_name?' · '+t('Reviewer','Người duyệt')+': '+esc(x.reviewer_name):''}</div>`:''}<div class="mk-actions">${button('copy',t('Copy','Sao chép'),x.id)}${manage?button('revise',t('New revision','Bản sửa mới'),x.id)+button('save-template',t('Save template','Lưu vào kho'),x.id):''}${manage&&x.status==='DRAFT'?button('submit',t('Submit','Trình duyệt'),x.id,true):''}${approve&&x.status==='PENDING'?button('approve',t('Approve','Duyệt'),x.id,true)+button('reject',t('Reject','Từ chối'),x.id):''}</div></article>`;}
 function overview(){const c=counts();return `<div class="mk-kpis">${[['DRAFT',t('Drafts','Bản nháp')],['PENDING',t('Awaiting review','Chờ anh duyệt')],['APPROVED',t('Approved · on hold','Đã duyệt · đang chờ')],['REJECTED',t('Needs revision','Cần chỉnh sửa')]].map(([s,label])=>`<button class="mk-kpi" data-mk="queue" data-id="${s}"><span>${label}</span><strong>${c[s]||0}</strong><small>${t('Open content →','Mở nội dung →')}</small></button>`).join('')}</div><div class="mk-grid"><section class="mk-panel"><div class="mk-section-head"><h2>${t('Your content operation','Vận hành nội dung')}</h2></div><div class="mk-flow">${[t('Library','Kho ý tưởng'),t('Channel drafts','Nháp từng kênh'),t('Review','Phê duyệt'),t('Publishing job','Lịch đăng riêng')].map((v,i)=>`<div><span>${i+1}</span><strong>${v}</strong></div>`).join('')}</div><p class="mk-note">${t('Create and review channel drafts. To publish, create a separate job in Publishing; delivery needs a second approval and an authorized worker.','Soạn và duyệt bản nháp từng kênh. Muốn đăng, tạo lịch riêng tại Đăng bài; cần người thứ hai duyệt và bộ xử lý được cấp quyền.')}</p><div class="mk-actions">${manage?button('compose',t('Create multichannel drafts','Soạn bài đa kênh'),'',true)+button('repeat',t('Plan recurring content','Lập kế hoạch lặp lại')):''}${can('ai.chat')?button('ai',t('Open AI Chat','Mở AI Chat')):''}</div></section><section class="mk-panel"><h2>${t('Upcoming planned content','Nội dung dự kiến sắp tới')}</h2>${data.items.filter(x=>x.planned_at&&M.localStamp(x.planned_at).slice(0,10)>=M.today()).sort((a,b)=>String(a.planned_at).localeCompare(String(b.planned_at))).slice(0,5).map(x=>`<div class="mk-row"><div><strong>${esc(x.channel)}</strong><small>${esc(dateText(x.planned_at))} · UTC+7</small><span>${esc(x.campaign_name)}</span></div>${badge(x.status)}</div>`).join('')||empty(t('No planned dates yet.','Chưa có lịch dự kiến.'))}</section></div><section class="mk-panel"><h2>${t('Content channels','Các kênh nội dung')}</h2><div class="mk-channel-list">${M.channels.map(c=>`<span>${esc(c)}</span>`).join('')}</div><p class="mk-note">${t('Copy, scheduling and approvals are available. Account sync and publishing require verified provider connections.','Có thể soạn bài, lập lịch dự kiến và duyệt. Đồng bộ tài khoản và đăng thật cần kết nối nhà cung cấp được xác thực.')}</p>${button('tab',t('View channel status','Xem trạng thái kênh'),'channels')}</section>`;}
 function calendar(){const [year,month]=ui.month.split('-').map(Number),days=new Date(Date.UTC(year,month,0)).getUTCDate(),pad=(new Date(Date.UTC(year,month-1,1)).getUTCDay()+6)%7;let cells='';for(let i=0;i<pad;i++)cells+='<div class="mk-day blank"></div>';for(let d=1;d<=days;d++){const day=ui.month+'-'+String(d).padStart(2,'0'),rows=data.items.filter(x=>M.localStamp(x.planned_at).slice(0,10)===day);cells+=`<button class="mk-day ${day===M.today()?'today':''}" data-mk="day" data-id="${day}"><strong>${d}</strong>${rows.slice(0,3).map(x=>`<span class="mk-calendar-item ${x.status.toLowerCase()}">${esc(x.channel)} · ${esc(M.localStamp(x.planned_at).slice(11))}</span>`).join('')}${rows.length>3?`<small>+${rows.length-3}</small>`:''}</button>`;}return `<section class="mk-panel"><div class="mk-section-head"><div><h2>${t('Editorial calendar','Lịch nội dung dự kiến')} · ${esc(ui.month)}</h2><p class="mk-note">${t('All dates use Vietnam time (UTC+7). Planned dates do not trigger posting.','Tất cả thời gian theo Việt Nam (UTC+7). Lịch dự kiến không tự kích hoạt đăng bài.')}</p></div><div class="mk-actions">${button('month','←',-1)}${button('month',t('Today','Hôm nay'),0)}${button('month','→',1)}</div></div><div class="mk-calendar-scroll"><div class="mk-calendar">${(vi?['T2','T3','T4','T5','T6','T7','CN']:['Mon','Tue','Wed','Thu','Fri','Sat','Sun']).map(d=>`<div class="mk-weekday">${d}</div>`).join('')}${cells}</div></div><p class="mk-note">${t('Click a day to view its drafts. Calendar uses the newest 500 content records loaded from the server.','Bấm một ngày để xem nội dung. Lịch dùng tối đa 500 bản nội dung mới nhất tải từ máy chủ.')}</p></section>`;}
 function library(){return `${filters(false)}<div class="mk-actions">${manage?button('new-template',t('Add template','Thêm mẫu nội dung'),'',true):''}</div><div class="mk-cards">${data.library.filter(matches).map(x=>`<article class="mk-content"><span class="mk-eyebrow">${esc(x.topic)}</span><h3>${esc(x.title)}</h3><p class="mk-body">${esc(x.body)}</p>${asset(x)}<p class="mk-meta">${esc(x.tags||'')}</p>${x.rights_note?`<p class="mk-note">${esc(x.rights_note)}</p>`:''}<div class="mk-actions">${manage?button('use-template',t('Use for channels','Dùng cho các kênh'),x.id,true)+button('repeat-template',t('Plan repeat','Lên kế hoạch lặp'),x.id):''}</div></article>`).join('')||empty(t('No templates match. Add your own reusable copy or media link.','Chưa có mẫu phù hợp. Thêm nội dung tái sử dụng hoặc link media.'))}</div>`;}
 function campaigns(){return `<div class="mk-cards">${data.campaigns.map(c=>`<article class="mk-content"><span class="mk-eyebrow">${esc(c.market||'')} · #${c.id}</span><h3>${esc(c.name)}</h3><p>${esc(c.offer||'')}</p><p class="mk-note">${esc(c.audience||'')}</p><p><strong>${Number(c.budget||0).toLocaleString()} ${esc(c.currency||'')}</strong> · ${t('planned budget, not actual spend','ngân sách dự kiến, chưa phải chi tiêu')}</p><div class="mk-small-stats"><span>${Number(c.request_count||0)} ${t('requests','yêu cầu')}</span><span>${Number(c.qualified_count||0)} ${t('qualified','đã qualify')}</span><span>${Number(c.converted_count||0)} ${t('inquiries','inquiry')}</span></div>${manage&&c.status!=='ARCHIVED'?button('campaign-compose',t('Compose for this campaign','Soạn cho chiến dịch'),c.id,true):''}</article>`).join('')||empty(t('Create a campaign to begin.','Tạo chiến dịch để bắt đầu.'))}</div>`;}
 function inbox(){return '<div id="mkLiveWebsiteInbox"></div>'+`<section class="mk-panel"><div class="mk-section-head"><div><h2>${t('Conversation notes & handoff','Ghi nhận trao đổi & chuyển lead')}</h2><p class="mk-note">${t('Internal conversation notes. Replies below remain drafts; connected conversations are handled in Unified Inbox above.','Ghi nhận trao đổi nội bộ. Câu trả lời bên dưới là bản nháp; hội thoại từ kênh đã kết nối được xử lý tại Hộp thư chung phía trên.')}</p></div>${leadManage?button('new-note',t('Add conversation','Thêm trao đổi'),'',true):''}</div></section><div class="mk-cards">${data.inbox.map(x=>`<article class="mk-content"><div class="mk-card-top"><span class="mk-channel">${esc(x.channel)} · ${t('MANUAL','NHẬP TAY')}</span>${badge(x.status)}</div><h3>${esc(x.contact_name)}</h3><p class="mk-meta">${esc(x.campaign_name)} · ${esc(x.owner_name)}</p><p class="mk-body">${esc(x.message)}</p>${x.reply_draft?`<div class="mk-reply"><strong>${t('Reply draft · not sent','Nháp trả lời · chưa gửi')}</strong><p>${esc(x.reply_draft)}</p></div>`:''}<p class="mk-note">${esc(x.email||x.phone||t('Contact details needed before lead handoff','Cần thông tin liên hệ trước khi chuyển lead'))}</p>${x.lead_request_id?`<p class="mk-note">${t('Lead Hub request','Yêu cầu Lead Hub')} #${x.lead_request_id}${preview?' · DEMO':''}</p>`:''}<div class="mk-actions">${leadManage?button('edit-note',t('Reply / assign','Soạn trả lời / phân công'),x.id)+(!x.lead_request_id?button('handoff',t('Create lead request','Chuyển yêu cầu sang Lead Hub'),x.id,true):''):''}${x.reply_draft?button('copy-reply',t('Copy reply','Sao chép nháp'),x.id):''}</div></article>`).join('')||empty(t('No conversation notes yet.','Chưa có trao đổi.'))}</div>`;}
 function insights(){return `<section class="mk-panel"><h2>${t('Campaign to lead reporting','Báo cáo chiến dịch → lead')}</h2><p class="mk-note">${preview?t('All values below are demo fixtures.','Các số dưới đây là dữ liệu minh họa.'):t('Counts come from VTA Lead Hub, grouped by campaign. They are not advertising platform conversions.','Số liệu từ Lead Hub của VTA, nhóm theo mã chiến dịch. Đây không phải conversion do nền tảng quảng cáo báo cáo.')}</p><div class="table-wrap"><table class="table"><thead><tr><th>${t('Campaign','Chiến dịch')}</th><th>${t('Requests','Yêu cầu')}</th><th>${t('Qualified','Đã qualify')}</th><th>${t('Converted to inquiry','Đã chuyển inquiry')}</th></tr></thead><tbody>${data.campaigns.map(c=>`<tr><td>${esc(c.name)}</td><td>${Number(c.request_count||0)}</td><td>${Number(c.qualified_count||0)}</td><td>${Number(c.converted_count||0)}</td></tr>`).join('')}</tbody></table></div><p class="mk-note">${t('Qualified and converted are cumulative milestones, not separate totals to add together.','Qualify và chuyển inquiry là các mốc lũy kế, không cộng thành tổng khách.')}</p></section><section class="mk-panel"><h2>${t('Social performance','Hiệu quả mạng xã hội')}</h2>${empty(t('Reach, impressions, ad spend, CPL and ROAS: no verified platform data connected.','Reach, impressions, chi tiêu, CPL và ROAS: chưa có dữ liệu nền tảng được kết nối.'))}</section>`;}
 function channelsView(){return `<div class="mk-cards">${M.channels.map(c=>{const meta=['Facebook','Instagram'].includes(c);return `<article class="mk-content"><span class="mk-eyebrow">${c==='Google Ads'?t('PAID CAMPAIGN COPY','NỘI DUNG QUẢNG CÁO'):t('CONTENT CHANNEL','KÊNH NỘI DUNG')}</span><h3>${esc(c)}</h3><span class="mk-badge">${meta?t('Check Meta connection status','Xem trạng thái kết nối Meta'):t('Draft planning only','Chỉ soạn và lập kế hoạch')}</span><p class="mk-note">${meta?t('Draft here, check accounts in Connections, and create approved delivery jobs in Publishing.','Soạn tại đây, xem tài khoản ở Kết nối và tạo lịch phát hành có phê duyệt ở Đăng bài.'):t('Create channel-specific copy and export a plan. Live delivery is not available here for this channel.','Soạn nội dung riêng cho kênh và xuất kế hoạch. Chưa hỗ trợ phát hành trực tiếp cho kênh này.')}</p>${meta?button('tab',t('View Meta connections','Xem kết nối Meta'),'connections'):button('connection',t('Connection requirements','Điều kiện kết nối'),c)}</article>`;}).join('')}</div>`;}
 function mountModule(selector,handler,settings){const host=root.querySelector(selector);if(!host)return;try{if(typeof handler!=='function')throw Error('Module unavailable');handler(host,settings);}catch(e){host.innerHTML='<section class="mk-panel"><h2>'+t('Interface unavailable','Chưa tải được giao diện')+'</h2><p class="mk-note" role="status">'+t('Some interface files could not be loaded. Try again or reload the page.','Một số file giao diện chưa tải được. Thử lại hoặc tải lại trang.')+'</p>'+button('retry-module',t('Try again','Thử lại'))+'</section>';}}

 function webhookView(){return '<section class="mk-panel" id="mkWebhookCenter"><h2>'+t('Webhook Center','Trung tâm Webhook')+'</h2><p class="mk-note">'+t('Loading inbound website events…','Đang tải sự kiện từ website…')+'</p></section>';}
 async function loadWebhooks(){
  const host=root.querySelector('#mkWebhookCenter');if(!host)return;
  if(preview){host.innerHTML='<h2>'+t('Webhook Center','Trung tâm Webhook')+'</h2><p class="mk-note">'+t('Demo mode: no real webhook connections.','Chế độ demo: chưa kết nối webhook thật.')+'</p>';return;}
  host.innerHTML='<h2>'+t('Webhook Center','Trung tâm Webhook')+'</h2><p class="mk-note" role="status">'+t('Loading inbound website events…','Đang tải sự kiện từ website…')+'</p>';
  try {
   const r=await api.request('marketing/webhooks');
   if(!host.isConnected||ui.tab!=='webhooks')return;
   const sources=(r.sources||[]).map(x=>'<div class="mk-row"><div><strong>'+esc(x.source_code)+'</strong><small>Website lead · '+(x.ready?t('Ready for signed events','Đã cấu hình ký xác thực'):t('Configuration required','Cần cấu hình'))+'</small></div></div>').join('')||empty(t('No website sources configured for this company.','Chưa cấu hình website webhook cho công ty này.'));
   const events=(r.events||[]).map(x=>'<tr><td>'+esc(x.created_at||'')+'</td><td>'+esc(x.source_code||'')+'</td><td>'+esc(x.event_type||'')+'</td><td>'+esc(x.status||'')+'</td><td>'+(x.lead_request_id?'Lead #'+Number(x.lead_request_id):x.conversation_id?'Chat #'+Number(x.conversation_id):'—')+'</td></tr>').join('');
   host.innerHTML='<h2>'+t('Webhook Center','Trung tâm Webhook')+'</h2><p class="mk-note">'+t('Verified inbound events from VTA websites. Meta account status is available in Connections; publishing jobs are managed separately.','Sự kiện đầu vào đã xác thực từ website VTA. Xem tài khoản Meta tại Kết nối; quản lý lịch đăng ở mục riêng.')+'</p><div class="mk-small-stats"><span>'+t('Accepted events','Sự kiện đã nhận')+': <strong>'+Number(r.total_events||0)+'</strong></span><span>'+t('Website sources','Nguồn website')+': <strong>'+(r.sources||[]).length+'</strong></span></div><h3>'+t('Configured sources','Nguồn đã cấu hình')+'</h3>'+sources+'<h3>'+t('Recent accepted events','Sự kiện đã nhận gần đây')+'</h3>'+(events?'<div class="table-wrap"><table class="table"><thead><tr><th>'+t('Received','Thời gian')+'</th><th>'+t('Source','Nguồn')+'</th><th>'+t('Event','Sự kiện')+'</th><th>'+t('Status','Trạng thái')+'</th><th>Lead</th></tr></thead><tbody>'+events+'</tbody></table></div>':empty(t('No verified inbound events yet.','Chưa có sự kiện đã xác thực.')));
  }catch(e){if(host.isConnected&&ui.tab==='webhooks')host.innerHTML='<h2>'+t('Webhook Center','Trung tâm Webhook')+'</h2><p class="mk-note" role="status">'+t('Unable to load website events. Try again or contact your administrator.','Không tải được sự kiện website. Thử lại hoặc liên hệ quản trị viên.')+'</p>'+button('refresh-webhooks',t('Try again','Thử lại'));}
 }
 function draw(){root.innerHTML=`<div class="mk-studio" data-no-translate><header class="mk-hero"><div><span class="mk-eyebrow">VIETNAM TRAVEL ADVISOR</span><h1>${t('Marketing Command Center','Trung tâm Marketing')}</h1><p>${t('Plan content. Review together. Turn interest into travel inquiries.','Lập kế hoạch nội dung. Phê duyệt cùng đội ngũ. Chuyển quan tâm thành yêu cầu tour.')}</p></div><div class="mk-actions">${button('leads','Lead Hub ↗')}${manage?button('new-campaign',t('+ Campaign','+ Chiến dịch'))+button('compose',t('+ Create content','+ Soạn nội dung'),'',true):''}</div></header><div class="mk-notice"><strong>${preview?'DEMO · RC6.2':t('Approval-first workspace','Không gian làm việc có phê duyệt')}</strong><span>${preview?t('Sample data stays in this tab and resets on reload. No AI, live messages or publishing calls are made in preview.','Dữ liệu mẫu chỉ trong tab, tải lại sẽ đặt lại. Không gọi AI, tin nhắn trực tiếp hoặc đăng bài.'):t('Manage content, publishing jobs and conversations. Check Meta Connections for account status; delivery requires separate authorization.','Quản lý nội dung, lịch đăng và hội thoại. Xem trạng thái tài khoản tại Kết nối Meta; đăng bài và gửi tin cần điều kiện cấp quyền riêng.')}</span>${preview?button('reset',t('Reset demo','Đặt lại demo')):''}</div><nav class="mk-tabs" aria-label="${t('Marketing workspace','Không gian Marketing')}">${tabs.map(([id,label])=>`<button data-mk="tab" data-id="${id}" class="${ui.tab===id?'active':''}" aria-current="${ui.tab===id?'page':'false'}">${label}</button>`).join('')}</nav><div id="mkBody">${ui.tab==='publishing'?'<div id="mkSocialPublishing"></div>':ui.tab==='connections'?'<div id="mkMetaConnections"></div>':ui.tab==='webhooks'?webhookView():ui.tab==='overview'?overview():ui.tab==='calendar'?calendar():ui.tab==='library'?library():ui.tab==='campaigns'?campaigns():ui.tab==='inbox'?inbox():ui.tab==='insights'?insights():ui.tab==='channels'?channelsView():`${filters()}<div class="mk-section-head"><p class="mk-note">${t('Newest 500 content records. Dates are editorial plans, not scheduled delivery.','Tối đa 500 bản nội dung mới nhất. Ngày giờ là kế hoạch, chưa phải lệnh đăng.')} ${data.items.filter(matches).length} ${t('shown','mục đang hiển thị')}.</p>${button('export',t('Export visible plan (JSON)','Xuất kế hoạch đang xem (JSON)'))}</div><div class="mk-cards">${data.items.filter(matches).map(card).join('')||empty(t('No content matches these filters.','Chưa có nội dung phù hợp bộ lọc.'))}</div>`}</div></div>`;if(ui.tab==='webhooks')loadWebhooks();
 if(ui.tab==='connections')mountModule('#mkMetaConnections',window.VTAMetaConnectionCenter,{api,esc,toast,t,preview});
 if(ui.tab==='publishing')mountModule('#mkSocialPublishing',window.VTASocialPublisher,{api,esc,toast,t,can,preview,contents:data.items,user:options.api.user});
 if(ui.tab==='inbox')mountModule('#mkLiveWebsiteInbox',window.VTAWebsiteInbox,{api,esc,toast,can,t,preview});}
 async function mutate(route,body,buttonEl,after){if(buttonEl?.disabled)return; if(buttonEl)buttonEl.disabled=true;const dialog=buttonEl?.closest('.modal-backdrop');try{const r=await api.request(route,{method:'POST',body});if(dialog?.isConnected)closeModal();if(after)after(r);if(root.isConnected&&root.dataset.view==='marketing')await navigate('marketing');return r;}catch(e){toast(e.message,true);if(buttonEl)buttonEl.disabled=false;}}
 function bindForm(m,route,transform=x=>x,after){const form=m.querySelector('form');form.onsubmit=e=>{e.preventDefault();let b;try{b=transform(Object.fromEntries(new FormData(form)));}catch(err){toast(err.message,true);return;}return mutate(route,b,form.querySelector('button[type=submit]'),after);};}
 function newCampaign(){const m=modal(t('Campaign brief','Brief chiến dịch'),`<form class="mk-form" data-no-translate><div class="mk-grid2">${input(t('Campaign name','Tên chiến dịch'),'name','', 'text',true)}${input(t('Market','Thị trường'),'market','India','text',true)}${area(t('Verified tour / offer','Tour / sản phẩm đã xác nhận'),'offer')}${area(t('Audience','Khách mục tiêu'),'audience','Indian families and private groups')}${input(t('Planned budget','Ngân sách dự kiến'),'budget',0,'number',true)}${select(t('Currency','Tiền tệ'),'currency',['USD','INR','VND'],'USD')}</div><button type="submit" class="btn primary">${t('Save campaign','Lưu chiến dịch')}</button></form>`,'',true);bindForm(m,'marketing/campaigns',x=>x,()=>{ui.tab='campaigns';});}
 function templateForm(x={}){const m=modal(t('Reusable content template','Mẫu nội dung tái sử dụng'),`<form class="mk-form" data-no-translate><div class="mk-grid2">${input(t('Template name','Tên mẫu'),'title',x.title||'', 'text',true)}${metadata(x)}${area(t('Template copy / script','Nội dung / kịch bản mẫu'),'body',x.body||'')}</div><p class="mk-note">${t('Links are stored as references; files are not uploaded or copied. Use content you own or have permission to reuse.','Lưu link tham chiếu; chưa upload hoặc sao chép file media. Dùng nội dung anh sở hữu hoặc có quyền tái sử dụng.')}</p><button type="submit" class="btn primary">${t('Save template','Lưu mẫu')}</button></form>`,'',true);bindForm(m,'marketing/library',x=>{if(x.asset_url&&(!M.url(x.asset_url)||!x.rights_note.trim()))throw Error(t('Provide an HTTPS link and rights note.','Cần link HTTPS và ghi chú quyền sử dụng.'));return x;},()=>{ui.tab='library';});}
 function compose(x={},recurring=false){if(!campaignOptions.length){toast(t('Create an active campaign first.','Cần tạo chiến dịch đang hoạt động trước.'),true);return;}const campaignId=x.campaign_id||campaignOptions[0][0],c=data.campaigns.find(c=>Number(c.id)===Number(campaignId));
  const m=modal(recurring?t('Recurring draft plan','Kế hoạch nháp lặp lại'):t('Multichannel composer','Soạn nội dung đa kênh'),`<form class="mk-form" data-no-translate><div class="mk-grid2">${select(t('Campaign','Chiến dịch'),'campaign_id',campaignOptions,campaignId,true)}${select(t('Format','Định dạng'),'content_format',M.formats,x.content_format||'POST')}${metadata(x)}${area(t('Base copy — edit each channel next','Nội dung gốc — sửa riêng từng kênh ở bước sau'),'body',x.body||`${c.offer||c.name}\n\nTell Vietnam Travel Advisor your dates, duration and group size.\nAll services and prices are subject to final confirmation.`)}<fieldset class="mk-span"><legend>${t('Channels','Các kênh')}</legend><div class="mk-checkboxes">${M.channels.map(ch=>`<label><input type="checkbox" name="channels" value="${ch}" ${(x.channel?[x.channel]:['Facebook','Instagram']).includes(ch)?'checked':''}>${ch}</label>`).join('')}</div></fieldset>${input(t('First planned time · Vietnam UTC+7','Thời gian dự kiến · Việt Nam UTC+7'),'start',ui.day?ui.day+'T10:00':'','datetime-local',recurring)}${input(t('Number of occurrences (1–8)','Số lần (1–8)'),'repeat',recurring?4:1,'number',true)}${input(t('Days between occurrences','Số ngày cách nhau'),'interval',7,'number',true)}</div><p class="mk-note">${t('Maximum 30 drafts per batch. Recurrence generates a finite set of drafts now; no automatic recycling or posting.','Tối đa 30 bản nháp/lần. Lặp lại tạo một số bản nháp xác định ngay bây giờ; không tự tái đăng hoặc phát hành.')}</p><button type="submit" class="btn primary">${t('Review channel drafts →','Kiểm tra từng bản →')}</button></form>`,'',true);
  m.querySelector('form').onsubmit=e=>{e.preventDefault();try{const b=Object.fromEntries(new FormData(e.target));b.channels=new FormData(e.target).getAll('channels');b.parent_content_id=x.id&&x.campaign_id&&Number(b.campaign_id)===Number(x.campaign_id)?Number(x.id):null;review(M.plan(b));}catch(err){toast(err.message,true);}};
 }
 function review(entries){let requestKey=M.key(),lastHash='';const m=modal(t('Review before saving','Kiểm tra trước khi lưu'),`<form class="mk-form" data-no-translate><p>${entries.length} ${t('drafts. Edit copy for each channel. All will start as DRAFT.','bản nháp. Sửa nội dung từng kênh. Tất cả bắt đầu ở trạng thái DRAFT.')}</p>${entries.map((r,i)=>`<label class="mk-variant"><strong>${esc(r.channel)}</strong><small>${esc(dateText(r.planned_at))}${r.planned_at?' · UTC+7':''}</small><textarea data-variant="${i}" rows="4" required maxlength="12000">${esc(r.body)}</textarea></label>`).join('')}<button type="submit" class="btn primary">${t('Save all drafts','Lưu tất cả bản nháp')}</button></form>`,'',true);
  m.querySelector('form').onsubmit=e=>{e.preventDefault();const rows=entries.map((r,i)=>({...r,body:m.querySelector(`[data-variant="${i}"]`).value})),hash=JSON.stringify(rows);if(lastHash&&lastHash!==hash)requestKey=M.key();lastHash=hash;return mutate('marketing/batch',{entries:rows,request_key:requestKey},e.target.querySelector('button[type=submit]'),()=>{ui.tab='content';ui.status='DRAFT';ui.q='';ui.day='';ui.channel='';ui.topic='';});};
 }
 function noteForm(x){const edit=!!x,record=x||{},ownerId=record.owner_user_id||(preview?1:options.api.user?.id);if(!edit&&!campaignOptions.length){toast(t('Create a campaign first.','Cần tạo chiến dịch trước.'),true);return;}
  const m=modal(edit?t('Reply draft and assignment','Nháp trả lời & phân công'):t('Add a manual conversation note','Ghi nhận trao đổi thủ công'),`<form class="mk-form" data-no-translate><div class="mk-grid2">${!edit?select(t('Campaign','Chiến dịch'),'campaign_id',campaignOptions,'',true)+select(t('Channel','Kênh'),'channel',M.channels,'Facebook')+input(t('Contact name','Tên khách'),'contact_name','','text',true)+area(t('Original message / comment','Tin nhắn / bình luận gốc'),'message'):''}${input('Email','email',record.email||'','email')}${input(t('Phone / WhatsApp','Điện thoại / WhatsApp'),'phone',record.phone||'')}${select(t('Assigned staff','Nhân viên phụ trách'),'owner_user_id',data.users.map(u=>[u.id,u.full_name]),ownerId,true)}${edit?select(t('Status','Trạng thái'),'status',['NEW','FOLLOW_UP','CLOSED'].map(s=>[s,statusName(s)]),record.status)+area(t('Reply draft — never sent automatically','Nháp trả lời — không tự gửi'),'reply_draft',record.reply_draft||'',false):''}</div><p class="mk-note">${t('This form saves an internal note only. It does not send a message.','Biểu mẫu này chỉ lưu ghi chú nội bộ, không gửi tin cho khách.')}</p><button class="btn primary" type="submit">${t('Save internal note','Lưu nội bộ')}</button></form>`,'',true);
  bindForm(m,edit?'marketing/inbox-update':'marketing/inbox',b=>({...b,...(edit?{id:record.id,version_no:record.version_no}:{}),owner_user_id:Number(b.owner_user_id),...(!edit?{campaign_id:Number(b.campaign_id)}:{})}),()=>{ui.tab='inbox';});
 }
 function handoff(x){if(!x.email&&!x.phone){toast(t('Add email or phone in Reply / assign first.','Bổ sung email hoặc điện thoại trong Soạn trả lời / phân công trước.'),true);return;}
  const m=modal(t('Create a Lead Hub request','Tạo yêu cầu trong Lead Hub'),`<form class="mk-form" data-no-translate><p>${esc(x.contact_name)} · ${esc(x.campaign_name)}</p><div class="mk-grid2">${input(t('Travel date (optional)','Ngày đi (nếu biết)'),'travel_date','','date')}${input(t('Total guests','Tổng số khách'),'total_guests','','number',true)}${input(t('Paying guests','Khách trả tiền'),'paying_pax','','number',true)}${input('FOC','foc',0,'number',true)}${input(t('Destination','Điểm đến'),'destination')}${input(t('Hotel category','Hạng khách sạn'),'hotel_level')}</div><p class="mk-note">${t('Enter confirmed guest counts. Creates a NEW request for qualification in Lead Hub; it does not create a quote or send a reply.','Nhập số khách đã xác nhận. Tạo yêu cầu NEW để qualify trong Lead Hub; chưa tạo báo giá hoặc gửi khách.')}${preview?' '+t('Demo handoff is simulated; it does not populate the separate Lead Hub preview.','Chuyển lead trong demo là mô phỏng, không ghi sang màn hình Lead Hub preview riêng.'):''}</p><button type="submit" class="btn primary">${t('Create request','Tạo yêu cầu')}</button></form>`,'',true);
  bindForm(m,'marketing/inbox-lead',b=>{const total=Number(b.total_guests),pay=Number(b.paying_pax),foc=Number(b.foc);if(total<1||pay<1||pay+foc>total)throw Error(t('Check guest counts.','Kiểm tra số khách.'));return {...b,id:x.id,total_guests:total,paying_pax:pay,foc};},r=>toast(t('Lead request created #','Đã tạo yêu cầu #')+r.request_id));
 }
 root.onclick=async e=>{if(root.dataset.view!=='marketing')return;const b=e.target.closest('[data-mk]');if(!b)return;const action=b.dataset.mk,id=b.dataset.id,item=data.items.find(x=>Number(x.id)===Number(id)),template=data.library.find(x=>Number(x.id)===Number(id)),note=data.inbox.find(x=>Number(x.id)===Number(id));
  if(action==='tab'&&tabs.some(x=>x[0]===id)){ui.tab=id;ui.q='';ui.topic='';ui.status='';ui.channel='';ui.day='';draw();}
  if(action==='queue'){ui.tab='content';ui.status=id;ui.q='';ui.day='';ui.topic='';ui.channel='';draw();}
  if(action==='retry-module')draw();
  if(action==='refresh-webhooks')loadWebhooks();
  if(action==='clear'){ui.q='';ui.channel='';ui.topic='';ui.status='';ui.day='';draw();}
  if(action==='day'){ui.tab='content';ui.day=id;ui.q='';ui.channel='';ui.topic='';ui.status='';draw();}
  if(action==='month'){if(Number(id)===0)ui.month=M.today().slice(0,7);else{const [y,m]=ui.month.split('-').map(Number);ui.month=new Date(Date.UTC(y,m-1+Number(id),1)).toISOString().slice(0,7);}draw();}
  if(action==='reset'&&preview){window.VTAMarketingDemo.reset();await navigate('marketing');}
  if(action==='leads')navigate('leads');if(action==='ai')navigate('ai');
  if(action==='new-campaign'&&manage)newCampaign();if(action==='new-template'&&manage)templateForm();
  if(['compose','repeat','campaign-compose','revise','use-template','repeat-template'].includes(action)&&manage)compose(action==='revise'?item:action.includes('template')?template:action==='campaign-compose'?{campaign_id:Number(id)}:{},action==='repeat'||action==='repeat-template');
  if(action==='save-template'&&manage)templateForm({...item,title:item.campaign_name+' · '+item.channel});
  if(action==='submit'&&manage)await mutate('marketing/submit',{id:Number(id)},b);
  if((action==='approve'||action==='reject')&&approve)await mutate('marketing/decision',{id:Number(id),decision:action==='approve'?'APPROVED':'REJECTED'},b);
  if(action==='new-note'&&leadManage)noteForm();if(action==='edit-note'&&leadManage)noteForm(note);if(action==='handoff'&&leadManage)handoff(note);
  if(action==='copy'||action==='copy-reply'){try{await navigator.clipboard.writeText(action==='copy'?item.body:note.reply_draft);toast(t('Copied','Đã sao chép'));}catch{toast(t('Select and copy the text manually.','Anh có thể bôi đen và sao chép văn bản.'),true);}}
  if(action==='export'){const blob=new Blob([JSON.stringify({timezone:'Asia/Ho_Chi_Minh',preview,delivery_enabled:false,items:data.items.filter(matches)},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='VTA_Content_Plan_'+M.today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  if(action==='connection')modal(t('Connect ','Kết nối ')+id,`<div class="mk-form" data-no-translate><p>${t('This channel currently supports draft planning in VTA. Live delivery requires a separately implemented and authorized connection.','Kênh này hiện hỗ trợ soạn và lập kế hoạch trong VTA. Phát hành trực tiếp cần kết nối được triển khai và cấp quyền riêng.')}</p><ol><li>${t('Connect directly to the official platform API after the required app review.','Chỉ kết nối trực tiếp API chính thức sau khi được duyệt quyền ứng dụng.')}</li><li>${t('Configure OAuth and credentials privately on the server; never paste tokens into post content.','Cấu hình OAuth và khóa riêng trên máy chủ; không dán token vào nội dung bài.')}</li><li>${t('Implement and test media upload, token renewal, webhooks and delivery receipts for that provider.','Triển khai và thử upload media, gia hạn token, webhook và kết quả gửi của nhà cung cấp.')}</li><li>${t('Enable delivery for this channel only after integration testing and release approval.','Chỉ bật phát hành cho kênh này sau khi kiểm thử kết nối và duyệt phát hành.')}</li></ol></div>`);
 };
 root.onchange=e=>{const k={filterChannel:'channel',filterTopic:'topic',filterStatus:'status'}[e.target.name];if(k){ui[k]=e.target.value;draw();}};
 root.oninput=e=>{if(e.target.id==='mkSearch'){const at=e.target.selectionStart;ui.q=e.target.value;draw();const input=root.querySelector('#mkSearch');input.focus();input.setSelectionRange(at,at);}};
 draw();
};
})();
