(()=>{'use strict';
const M=window.VTAMarketingModel;
let owner='',sequence=0,ui={tab:'overview',q:'',channel:'',topic:'',status:'',day:'',month:M.today().slice(0,7)};
window.VTAMarketing=async function(options){
 const {esc,modal,closeModal,toast,navigate,can}=options,preview=!!window.VTA_PREVIEW,api=preview?window.VTAMarketingDemo:options.api;
 const vi=window.VTA_I18N?.language==='vi',t=(en,vn)=>vi?vn:en,root=document.querySelector('#workspace'),renderId=++sequence;
 const userKey=preview?'demo':String(options.api.user?.company_id)+':'+String(options.api.user?.id);
 if(owner!==userKey){owner=userKey;ui={tab:'overview',q:'',channel:'',topic:'',status:'',day:'',month:M.today().slice(0,7)};}
 const data=await api.request('marketing/studio');if(renderId!==sequence||!root.isConnected||root.dataset.view!=='marketing')return;
 const manage=can('campaign.manage'),approve=can('marketing.approve'),leadManage=can('lead.manage');
 const tabs=[['overview',t('Overview','Tổng quan')],['content',t('Content & review','Nội dung & duyệt')],['calendar',t('Calendar','Lịch nội dung')],['library',t('Content library','Kho nội dung')],['landing','Landing Pages'],['campaigns',t('Campaigns','Chiến dịch')],['inbox',t('Conversations','Trao đổi & lead')],['insights',t('Reports','Báo cáo')],['channels',t('Channels','Kênh')]];
 if(options.initialTab&&tabs.some(x=>x[0]===options.initialTab))ui.tab=options.initialTab;
 const statusName=s=>({DRAFT:t('Draft','Bản nháp'),PENDING:t('Review','Chờ duyệt'),APPROVED:t('Approved · held','Đã duyệt · chờ phát hành'),REJECTED:t('Rejected','Từ chối'),NEW:t('New','Mới'),FOLLOW_UP:t('Follow-up','Theo dõi'),CLOSED:t('Closed','Đã đóng')}[s]||s);
 const badge=s=>`<span class="mk-badge ${esc(s.toLowerCase())}">${esc(statusName(s))}</span>`;
 const dateText=x=>M.localStamp(x).replace('T',' ')||t('No planned time','Chưa có lịch');
 const empty=text=>`<div class="mk-empty">${text}</div>`;
 const button=(act,label,id='',primary=false)=>`<button class="btn ${primary?'primary':''}" data-mk="${act}" data-id="${esc(id)}">${label}</button>`;
 const asset=x=>M.url(x.asset_url)?`<a class="mk-asset" href="${esc(M.url(x.asset_url))}" target="_blank" rel="noopener noreferrer">${t('Open media / design link ↗','Mở link media / thiết kế ↗')}</a>`:'';
 const selected=(a,b)=>String(a)===String(b)?' selected':'';
 const select=(label,name,values,value='',required=false)=>`<label>${label}<select name="${name}" ${required?'required':''}>${values.map(v=>{const a=Array.isArray(v)?v:[v,v];return `<option value="${esc(a[0])}"${selected(a[0],value)}>${esc(a[1])}</option>`;}).join('')}</select></label>`;
 const input=(label,name,value='',type='text',required=false)=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value??'')}" ${required?'required':''} ${type==='number'?(name==='budget'?'min="0" step="0.01"':'min="0" step="1"'):'maxlength="190"'}></label>`;
 const area=(label,name,value='',required=true)=>`<label class="mk-span">${label}<textarea name="${name}" rows="5" maxlength="12000" ${required?'required':''}>${esc(value??'')}</textarea></label>`;
 const campaignOptions=data.campaigns.filter(c=>c.status!=='ARCHIVED').map(c=>[c.id,c.name]);
 const metadata=x=>select(t('Topic','Chủ đề'),'topic',M.topics,x.topic||'General')+input(t('Tags, separated by commas','Thẻ, cách nhau bằng dấu phẩy'),'tags',x.tags)+`<label class="mk-span">${t('Optional HTTPS media / Canva / Drive link','Link HTTPS media / Canva / Drive (tùy chọn)')}<input name="asset_url" type="url" maxlength="1000" value="${esc(x.asset_url||'')}"></label>`+`<label class="mk-span">${t('Asset ownership / permission note','Ghi chú quyền sử dụng media')}<input name="rights_note" maxlength="500" value="${esc(x.rights_note||'')}" placeholder="${t('VTA-owned footage or licensed source…','Tư liệu VTA sở hữu hoặc nguồn được cấp quyền…')}"></label>`;
 function matches(x){const s=(ui.q||'').trim().toLowerCase();return (!s||[x.body,x.title,x.campaign_name,x.tags,x.contact_name,x.message].some(v=>String(v||'').toLowerCase().includes(s)))&&(!ui.channel||x.channel===ui.channel)&&(!ui.topic||x.topic===ui.topic)&&(!ui.status||x.status===ui.status)&&(!ui.day||M.localStamp(x.planned_at).slice(0,10)===ui.day);}
 function counts(){return Object.fromEntries((data.counts||[]).map(x=>[x.status,Number(x.total)]));}
 function filters(content=true){return `<div class="mk-filters"><label>${t('Search','Tìm kiếm')}<input id="mkSearch" value="${esc(ui.q)}" placeholder="${t('Content, campaign, tags…','Nội dung, chiến dịch, thẻ…')}"></label>${content?select(t('Channel','Kênh'),'filterChannel',[['',t('All channels','Tất cả kênh')],...M.channels],ui.channel):''}${select(t('Topic','Chủ đề'),'filterTopic',[['',t('All topics','Tất cả chủ đề')],...M.topics],ui.topic)}${content?select(t('Status','Trạng thái'),'filterStatus',[['',t('All statuses','Tất cả trạng thái')],...['DRAFT','PENDING','APPROVED','REJECTED'].map(s=>[s,statusName(s)])],ui.status):''}${button('clear',t('Clear filters','Xóa bộ lọc'))}</div>${ui.day?`<p class="mk-note">${t('Date','Ngày')}: ${esc(ui.day)} · UTC+7</p>`:''}`;}
 function card(x){return `<article class="mk-content"><div class="mk-card-top"><span class="mk-channel">${esc(x.channel)}</span>${badge(x.status)}</div><h3>${esc(x.campaign_name||'')}</h3><div class="mk-meta">${esc(x.topic||'General')} · ${esc(x.content_format||'POST')} · #${x.id}</div><p class="mk-body">${esc(x.body)}</p>${asset(x)}<div class="mk-meta">${esc(dateText(x.planned_at))}${x.planned_at?' · UTC+7':''}${x.parent_content_id?` · ${t('Revision of','Bản sửa của')} #${x.parent_content_id}`:''}</div>${x.tags?`<div class="mk-tags">${esc(x.tags)}</div>`:''}${x.creator_name?`<div class="mk-meta">${t('Author','Người soạn')}: ${esc(x.creator_name)}${x.reviewer_name?' · '+t('Reviewer','Người duyệt')+': '+esc(x.reviewer_name):''}</div>`:''}<div class="mk-actions">${button('copy',t('Copy','Sao chép'),x.id)}${manage?button('revise',t('New revision','Bản sửa mới'),x.id)+button('save-template',t('Save template','Lưu vào kho'),x.id):''}${manage&&x.status==='DRAFT'?button('submit',t('Submit','Trình duyệt'),x.id,true):''}${approve&&x.status==='PENDING'?button('approve',t('Approve','Duyệt'),x.id,true)+button('reject',t('Reject','Từ chối'),x.id):''}</div></article>`;}
 function overview(){const c=counts();return `<div class="mk-kpis">${[['DRAFT',t('Drafts','Bản nháp')],['PENDING',t('Awaiting review','Chờ anh duyệt')],['APPROVED',t('Approved · on hold','Đã duyệt · đang chờ')],['REJECTED',t('Needs revision','Cần chỉnh sửa')]].map(([s,label])=>`<button class="mk-kpi" data-mk="queue" data-id="${s}"><span>${label}</span><strong>${c[s]||0}</strong><small>${t('Open content →','Mở nội dung →')}</small></button>`).join('')}</div><div class="mk-grid"><section class="mk-panel"><div class="mk-section-head"><h2>${t('Your content operation','Vận hành nội dung')}</h2></div><div class="mk-flow">${[t('Library','Kho ý tưởng'),t('Channel drafts','Nháp từng kênh'),t('Review','Phê duyệt'),t('Hold for release','Chờ phát hành')].map((v,i)=>`<div><span>${i+1}</span><strong>${v}</strong></div>`).join('')}</div><p class="mk-note">${t('Create variants from one brief, plan dates, and review every draft. Approval never starts publishing in this release.','Tạo các bản cho từng kênh từ một brief, lập lịch và kiểm tra từng bản. Bản này không tự phát hành sau khi duyệt.')}</p><div class="mk-actions">${manage?button('compose',t('Create multichannel drafts','Soạn bài đa kênh'),'',true)+button('repeat',t('Plan recurring content','Lập kế hoạch lặp lại')):''}${can('ai.chat')?button('ai',t('Open AI Chat','Mở AI Chat')):''}</div></section><section class="mk-panel"><h2>${t('Upcoming planned content','Nội dung dự kiến sắp tới')}</h2>${data.items.filter(x=>x.planned_at&&M.localStamp(x.planned_at).slice(0,10)>=M.today()).sort((a,b)=>String(a.planned_at).localeCompare(String(b.planned_at))).slice(0,5).map(x=>`<div class="mk-row"><div><strong>${esc(x.channel)}</strong><small>${esc(dateText(x.planned_at))} · UTC+7</small><span>${esc(x.campaign_name)}</span></div>${badge(x.status)}</div>`).join('')||empty(t('No planned dates yet.','Chưa có lịch dự kiến.'))}</section></div><section class="mk-panel"><h2>${t('Channels waiting for server setup','Các kênh chờ cấu hình trên máy chủ')}</h2><div class="mk-channel-list">${M.channels.map(c=>`<span>${esc(c)}</span>`).join('')}</div><p class="mk-note">${t('Copy, scheduling and approvals are available. Account sync and publishing require verified provider connections.','Có thể soạn bài, lập lịch dự kiến và duyệt. Đồng bộ tài khoản và đăng thật cần kết nối nhà cung cấp được xác thực.')}</p>${button('tab',t('View channel status','Xem trạng thái kênh'),'channels')}</section>`;}
 function calendar(){const [year,month]=ui.month.split('-').map(Number),days=new Date(Date.UTC(year,month,0)).getUTCDate(),pad=(new Date(Date.UTC(year,month-1,1)).getUTCDay()+6)%7;let cells='';for(let i=0;i<pad;i++)cells+='<div class="mk-day blank"></div>';for(let d=1;d<=days;d++){const day=ui.month+'-'+String(d).padStart(2,'0'),rows=data.items.filter(x=>M.localStamp(x.planned_at).slice(0,10)===day);cells+=`<button class="mk-day ${day===M.today()?'today':''}" data-mk="day" data-id="${day}"><strong>${d}</strong>${rows.slice(0,3).map(x=>`<span class="mk-calendar-item ${x.status.toLowerCase()}">${esc(x.channel)} · ${esc(M.localStamp(x.planned_at).slice(11))}</span>`).join('')}${rows.length>3?`<small>+${rows.length-3}</small>`:''}</button>`;}return `<section class="mk-panel"><div class="mk-section-head"><div><h2>${t('Editorial calendar','Lịch nội dung dự kiến')} · ${esc(ui.month)}</h2><p class="mk-note">${t('All dates use Vietnam time (UTC+7). Planned dates do not trigger posting.','Tất cả thời gian theo Việt Nam (UTC+7). Lịch dự kiến không tự kích hoạt đăng bài.')}</p></div><div class="mk-actions">${button('month','←',-1)}${button('month',t('Today','Hôm nay'),0)}${button('month','→',1)}</div></div><div class="mk-calendar-scroll"><div class="mk-calendar">${(vi?['T2','T3','T4','T5','T6','T7','CN']:['Mon','Tue','Wed','Thu','Fri','Sat','Sun']).map(d=>`<div class="mk-weekday">${d}</div>`).join('')}${cells}</div></div><p class="mk-note">${t('Click a day to view its drafts. Calendar uses the newest 500 content records loaded from the server.','Bấm một ngày để xem nội dung. Lịch dùng tối đa 500 bản nội dung mới nhất tải từ máy chủ.')}</p></section>`;}
 function library(){return `${filters(false)}<div class="mk-actions">${manage?button('new-template',t('Add template','Thêm mẫu nội dung'),'',true):''}</div><div class="mk-cards">${data.library.filter(matches).map(x=>`<article class="mk-content"><span class="mk-eyebrow">${esc(x.topic)}</span><h3>${esc(x.title)}</h3><p class="mk-body">${esc(x.body)}</p>${asset(x)}<p class="mk-meta">${esc(x.tags||'')}</p>${x.rights_note?`<p class="mk-note">${esc(x.rights_note)}</p>`:''}<div class="mk-actions">${manage?button('use-template',t('Use for channels','Dùng cho các kênh'),x.id,true)+button('repeat-template',t('Plan repeat','Lên kế hoạch lặp'),x.id):''}</div></article>`).join('')||empty(t('No templates match. Add your own reusable copy or media link.','Chưa có mẫu phù hợp. Thêm nội dung tái sử dụng hoặc link media.'))}</div>`;}
 function campaigns(){return `<div class="mk-cards">${data.campaigns.map(c=>`<article class="mk-content"><span class="mk-eyebrow">${esc(c.market||'')} · #${c.id}</span><h3>${esc(c.name)}</h3><p>${esc(c.offer||'')}</p><p class="mk-note">${esc(c.audience||'')}</p><p><strong>${Number(c.budget||0).toLocaleString()} ${esc(c.currency||'')}</strong> · ${t('planned budget, not actual spend','ngân sách dự kiến, chưa phải chi tiêu')}</p><div class="mk-small-stats"><span>${Number(c.request_count||0)} ${t('requests','yêu cầu')}</span><span>${Number(c.qualified_count||0)} ${t('qualified','đã qualify')}</span><span>${Number(c.converted_count||0)} ${t('inquiries','inquiry')}</span></div>${manage&&c.status!=='ARCHIVED'?button('campaign-compose',t('Compose for this campaign','Soạn cho chiến dịch'),c.id,true):''}</article>`).join('')||empty(t('Create a campaign to begin.','Tạo chiến dịch để bắt đầu.'))}</div>`;}
 function inbox(){return `<section class="mk-panel"><div class="mk-section-head"><div><h2>${t('Conversation notes & handoff','Ghi nhận trao đổi & chuyển lead')}</h2><p class="mk-note">${t('Manual entry. Social inbox/comment sync is not connected. Replies stay as drafts.','Nhập thủ công. Chưa đồng bộ inbox/comment mạng xã hội. Câu trả lời luôn là bản nháp.')}</p></div>${leadManage?button('new-note',t('Add conversation','Thêm trao đổi'),'',true):''}</div></section><div class="mk-cards">${data.inbox.map(x=>`<article class="mk-content"><div class="mk-card-top"><span class="mk-channel">${esc(x.channel)} · ${t('MANUAL','NHẬP TAY')}</span>${badge(x.status)}</div><h3>${esc(x.contact_name)}</h3><p class="mk-meta">${esc(x.campaign_name)} · ${esc(x.owner_name)}</p><p class="mk-body">${esc(x.message)}</p>${x.reply_draft?`<div class="mk-reply"><strong>${t('Reply draft · not sent','Nháp trả lời · chưa gửi')}</strong><p>${esc(x.reply_draft)}</p></div>`:''}<p class="mk-note">${esc(x.email||x.phone||t('Contact details needed before lead handoff','Cần thông tin liên hệ trước khi chuyển lead'))}</p>${x.lead_request_id?`<p class="mk-note">${t('Lead Hub request','Yêu cầu Lead Hub')} #${x.lead_request_id}${preview?' · DEMO':''}</p>`:''}<div class="mk-actions">${leadManage?button('edit-note',t('Reply / assign','Soạn trả lời / phân công'),x.id)+(!x.lead_request_id?button('handoff',t('Create lead request','Chuyển yêu cầu sang Lead Hub'),x.id,true):''):''}${x.reply_draft?button('copy-reply',t('Copy reply','Sao chép nháp'),x.id):''}</div></article>`).join('')||empty(t('No conversation notes yet.','Chưa có trao đổi.'))}</div>`;}
 function insights(){return `<section class="mk-panel"><h2>${t('Campaign to lead reporting','Báo cáo chiến dịch → lead')}</h2><p class="mk-note">${preview?t('All values below are demo fixtures.','Các số dưới đây là dữ liệu minh họa.'):t('Counts come from VTA Lead Hub, grouped by campaign. They are not advertising platform conversions.','Số liệu từ Lead Hub của VTA, nhóm theo mã chiến dịch. Đây không phải conversion do nền tảng quảng cáo báo cáo.')}</p><div class="table-wrap"><table class="table"><thead><tr><th>${t('Campaign','Chiến dịch')}</th><th>${t('Requests','Yêu cầu')}</th><th>${t('Qualified','Đã qualify')}</th><th>${t('Converted to inquiry','Đã chuyển inquiry')}</th></tr></thead><tbody>${data.campaigns.map(c=>`<tr><td>${esc(c.name)}</td><td>${Number(c.request_count||0)}</td><td>${Number(c.qualified_count||0)}</td><td>${Number(c.converted_count||0)}</td></tr>`).join('')}</tbody></table></div><p class="mk-note">${t('Qualified and converted are cumulative milestones, not separate totals to add together.','Qualify và chuyển inquiry là các mốc lũy kế, không cộng thành tổng khách.')}</p></section><section class="mk-panel"><h2>${t('Social performance','Hiệu quả mạng xã hội')}</h2>${empty(t('Reach, impressions, ad spend, CPL and ROAS: no verified platform data connected.','Reach, impressions, chi tiêu, CPL và ROAS: chưa có dữ liệu nền tảng được kết nối.'))}</section>`;}
 function channelsView(){return `<div class="mk-cards">${M.channels.map(c=>`<article class="mk-content"><span class="mk-eyebrow">${c==='Google Ads'?t('PAID CAMPAIGN COPY','NỘI DUNG QUẢNG CÁO'):t('CONTENT CHANNEL','KÊNH NỘI DUNG')}</span><h3>${esc(c)}</h3><span class="mk-badge pending">${t('Server connection not configured','Chưa cấu hình kết nối máy chủ')}</span><p class="mk-note">${t('Draft and plan here. OAuth, media delivery and verified provider responses are required before real publishing.','Có thể soạn và lập lịch tại đây. Đăng thật cần OAuth, xử lý media và kết quả xác nhận từ nhà cung cấp.')}</p>${button('connection',t('Connection requirements','Điều kiện kết nối'),c)}</article>`).join('')}</div>`;}
 function draw(){root.innerHTML=`<div class="mk-studio" data-no-translate><header class="mk-hero"><div><span class="mk-eyebrow">VIETNAM TRAVEL ADVISOR</span><h1>${t('Marketing Command Center','Trung tâm Marketing')}</h1><p>${t('Plan content. Review together. Turn interest into travel inquiries.','Lập kế hoạch nội dung. Phê duyệt cùng đội ngũ. Chuyển quan tâm thành yêu cầu tour.')}</p></div><div class="mk-actions">${button('leads','Lead Hub ↗')}${manage?button('new-campaign',t('+ Campaign','+ Chiến dịch'))+button('compose',t('+ Create content','+ Soạn nội dung'),'',true)+(window.VTAPlusAssist?button('plus-marketing',t('ChatGPT Plus · Content','ChatGPT Plus · Content')):''):''}</div></header><div class="mk-notice"><strong>${preview?'DEMO · RC6.2':t('Approval-first workspace','Không gian làm việc có phê duyệt')}</strong><span>${preview?t('Sample data stays in this tab and resets on reload. Landing images load from links you add. No AI or publishing calls.','Dữ liệu mẫu chỉ trong tab, tải lại sẽ đặt lại. Ảnh landing page dùng link anh thêm. Không gọi AI hoặc đăng bài.'):t('Planning and approval are active. Publishing and social inbox sync are not connected.','Có lập kế hoạch và duyệt. Chưa kết nối đăng bài và đồng bộ inbox mạng xã hội.')}</span>${preview?button('reset',t('Reset demo','Đặt lại demo')):''}</div><nav class="mk-tabs" aria-label="Marketing workspace">${tabs.map(([id,label])=>`<button data-mk="tab" data-id="${id}" class="${ui.tab===id?'active':''}" aria-current="${ui.tab===id?'page':'false'}">${label}</button>`).join('')}</nav><div id="mkBody">${ui.tab==='landing'?'<div id="mkLanding"></div>':ui.tab==='overview'?overview():ui.tab==='calendar'?calendar():ui.tab==='library'?library():ui.tab==='campaigns'?campaigns():ui.tab==='inbox'?inbox():ui.tab==='insights'?insights():ui.tab==='channels'?channelsView():`${filters()}<div class="mk-section-head"><p class="mk-note">${t('Newest 500 content records. Dates are editorial plans, not scheduled delivery.','Tối đa 500 bản nội dung mới nhất. Ngày giờ là kế hoạch, chưa phải lệnh đăng.')} ${data.items.filter(matches).length} ${t('shown','mục đang hiển thị')}.</p>${button('export',t('Export visible plan (JSON)','Xuất kế hoạch đang xem (JSON)'))}</div><div class="mk-cards">${data.items.filter(matches).map(card).join('')||empty(t('No content matches these filters.','Chưa có nội dung phù hợp bộ lọc.'))}</div>`}</div></div>`;if(ui.tab==='landing')window.VTALandingBuilder(root.querySelector('#mkLanding'),{...options,campaigns:data.campaigns,mediaLibrary:data.library}).catch(e=>toast(e.message,true));}
 async function mutate(route,body,buttonEl,after){if(buttonEl?.disabled)return; if(buttonEl)buttonEl.disabled=true;const dialog=buttonEl?.closest('.modal-backdrop');try{const r=await api.request(route,{method:'POST',body});if(dialog?.isConnected)closeModal();if(after)after(r);if(root.isConnected&&root.dataset.view==='marketing')await navigate('marketing');return r;}catch(e){toast(e.message,true);if(buttonEl)buttonEl.disabled=false;}}
 function bindForm(m,route,transform=x=>x,after){const form=m.querySelector('form');form.onsubmit=e=>{e.preventDefault();let b;try{b=transform(Object.fromEntries(new FormData(form)));}catch(err){toast(err.message,true);return;}return mutate(route,b,form.querySelector('button[type=submit]'),after);};}
 function newCampaign(){const m=modal(t('Campaign brief','Brief chiến dịch'),`<form class="mk-form" data-no-translate><div class="mk-grid2">${input(t('Campaign name','Tên chiến dịch'),'name','', 'text',true)}${input(t('Market','Thị trường'),'market','India','text',true)}${area(t('Verified tour / offer','Tour / sản phẩm đã xác nhận'),'offer')}${area(t('Audience','Khách mục tiêu'),'audience','Indian families and private groups')}${input(t('Planned budget','Ngân sách dự kiến'),'budget',0,'number',true)}${select(t('Currency','Tiền tệ'),'currency',['USD','INR','VND'],'USD')}</div><button type="submit" class="btn primary">${t('Save campaign','Lưu chiến dịch')}</button></form>`,'',true);bindForm(m,'marketing/campaigns',x=>x,()=>{ui.tab='campaigns';});}
 function templateForm(x={}){const m=modal(t('Reusable content template','Mẫu nội dung tái sử dụng'),`<form class="mk-form" data-no-translate><div class="mk-grid2">${input(t('Template name','Tên mẫu'),'title',x.title||'', 'text',true)}${metadata(x)}${area(t('Template copy / script','Nội dung / kịch bản mẫu'),'body',x.body||'')}</div><p class="mk-note">${t('Links are stored as references; files are not uploaded or copied. Use content you own or have permission to reuse.','Lưu link tham chiếu; chưa upload hoặc sao chép file media. Dùng nội dung anh sở hữu hoặc có quyền tái sử dụng.')}</p><button type="submit" class="btn primary">${t('Save template','Lưu mẫu')}</button></form>`,'',true);bindForm(m,'marketing/library',x=>{if(x.asset_url&&(!M.url(x.asset_url)||!x.rights_note.trim()))throw Error(t('Provide an HTTPS link and rights note.','Cần link HTTPS và ghi chú quyền sử dụng.'));return x;},()=>{ui.tab='library';});}
 function compose(x={},recurring=false){if(!campaignOptions.length){toast(t('Create an active campaign first.','Cần tạo chiến dịch đang hoạt động trước.'),true);return;}const campaignId=x.campaign_id||campaignOptions[0][0],c=data.campaigns.find(c=>Number(c.id)===Number(campaignId));
  const m=modal(recurring?t('Recurring draft plan','Kế hoạch nháp lặp lại'):t('Multichannel composer','Soạn nội dung đa kênh'),`<form class="mk-form" data-no-translate><div class="mk-grid2">${select(t('Campaign','Chiến dịch'),'campaign_id',campaignOptions,campaignId,true)}${select(t('Format','Định dạng'),'content_format',M.formats,x.content_format||'POST')}${metadata(x)}${area(t('Base copy — edit each channel next','Nội dung gốc — sửa riêng từng kênh ở bước sau'),'body',x.body||`${c.offer||c.name}\n\nTell Vietnam Travel Advisor your dates, duration and group size.\nAll services and prices are subject to final confirmation.`)}<fieldset class="mk-span"><legend>${t('Channels','Các kênh')}</legend><div class="mk-checkboxes">${M.channels.map(ch=>`<label><input type="checkbox" name="channels" value="${ch}" ${(x.channel?[x.channel]:['Facebook','Instagram']).includes(ch)?'checked':''}>${ch}</label>`).join('')}</div></fieldset>${input(t('First planned time · Vietnam UTC+7','Thời gian dự kiến · Việt Nam UTC+7'),'start',ui.day?ui.day+'T10:00':'','datetime-local',recurring)}${input(t('Number of occurrences (1–8)','Số lần (1–8)'),'repeat',recurring?4:1,'number',true)}${input(t('Days between occurrences','Số ngày cách nhau'),'interval',7,'number',true)}</div><p class="mk-note">${t('Maximum 30 drafts per batch. Recurrence generates a finite set of drafts now; no automatic recycling or posting.','Tối đa 30 bản nháp/lần. Lặp lại tạo một số bản nháp xác định ngay bây giờ; không tự tái đăng hoặc phát hành.')}</p>${window.VTAPlusAssist?'<button type="button" class="btn" data-plus-compose>Soạn bằng ChatGPT Plus</button>':''}<button type="submit" class="btn primary">${t('Review channel drafts →','Kiểm tra từng bản →')}</button></form>`,'',true);
  const plusButton=m.querySelector('[data-plus-compose]');
  if(plusButton)plusButton.onclick=()=>{
    if(!window.VTAPlusAssist)return toast('ChatGPT Plus companion chưa sẵn sàng.',true);
    window.VTAPlusAssist.open({mode:'marketing-base',onApply:answer=>{
      if(!m.isConnected)throw Error('Đã đóng cửa sổ soạn nội dung Marketing.');
      const field=m.querySelector('textarea[name="body"]');
      if(!field)throw Error('Không tìm thấy ô nội dung gốc.');
      if(answer.length>12000)throw Error('Nội dung quá dài (tối đa 12.000 ký tự).');
      field.value=answer;
      field.dispatchEvent(new Event('input',{bubbles:true}));
      toast('Đã chèn nội dung AI vào bản nháp. Hãy kiểm tra và chọn kênh trước khi lưu.');
    }});
  };
  m.querySelector('form').onsubmit=e=>{e.preventDefault();try{const b=Object.fromEntries(new FormData(e.target));b.channels=new FormData(e.target).getAll('channels');b.parent_content_id=x.id&&x.campaign_id&&Number(b.campaign_id)===Number(x.campaign_id)?Number(x.id):null;review(M.plan(b));}catch(err){toast(err.message,true);}};
 }
 function review(entries){let requestKey=M.key(),lastHash='';const m=modal(t('Review before saving','Kiểm tra trước khi lưu'),`<form class="mk-form" data-no-translate><p>${entries.length} ${t('drafts. Edit copy for each channel. All will start as DRAFT.','bản nháp. Sửa nội dung từng kênh. Tất cả bắt đầu ở trạng thái DRAFT.')}</p>${entries.map((r,i)=>`<label class="mk-variant"><strong>${esc(r.channel)}</strong><small>${esc(dateText(r.planned_at))}${r.planned_at?' · UTC+7':''}</small><textarea data-variant="${i}" rows="4" required maxlength="12000">${esc(r.body)}</textarea></label>`).join('')}<button type="submit" class="btn primary">${t('Save all drafts','Lưu tất cả bản nháp')}</button></form>`,'',true);
  m.querySelector('form').onsubmit=e=>{e.preventDefault();const rows=entries.map((r,i)=>({...r,body:m.querySelector(`[data-variant="${i}"]`).value})),hash=JSON.stringify(rows);if(lastHash&&lastHash!==hash)requestKey=M.key();lastHash=hash;return mutate('marketing/batch',{entries:rows,request_key:requestKey},e.target.querySelector('button[type=submit]'),()=>{ui.tab='content';ui.status='DRAFT';ui.q='';ui.day='';ui.channel='';ui.topic='';});};
 }
 function noteForm(x){const edit=!!x,record=x||{},ownerId=record.owner_user_id||(preview?1:options.api.user?.id);if(!edit&&!campaignOptions.length){toast(t('Create a campaign first.','Cần tạo chiến dịch trước.'),true);return;}
  const m=modal(edit?t('Reply draft and assignment','Nháp trả lời & phân công'):t('Add a manual conversation note','Ghi nhận trao đổi thủ công'),`<form class="mk-form" data-no-translate><div class="mk-grid2">${!edit?select(t('Campaign','Chiến dịch'),'campaign_id',campaignOptions,'',true)+select(t('Channel','Kênh'),'channel',M.channels,'Facebook')+input(t('Contact name','Tên khách'),'contact_name','','text',true)+area(t('Original message / comment','Tin nhắn / bình luận gốc'),'message'):''}${input('Email','email',record.email||'','email')}${input(t('Phone / WhatsApp','Điện thoại / WhatsApp'),'phone',record.phone||'')}${select(t('Assigned staff','Nhân viên phụ trách'),'owner_user_id',data.users.map(u=>[u.id,u.full_name]),ownerId,true)}${edit?select(t('Status','Trạng thái'),'status',['NEW','FOLLOW_UP','CLOSED'].map(s=>[s,statusName(s)]),record.status)+area(t('Reply draft — never sent automatically','Nháp trả lời — không tự gửi'),'reply_draft',record.reply_draft||'',false):''}</div><p class="mk-note">${t('This saves an internal note only. Customer messaging is not connected.','Chỉ lưu ghi chú nội bộ. Chưa kết nối gửi tin cho khách.')}</p><button class="btn primary" type="submit">${t('Save internal note','Lưu nội bộ')}</button></form>`,'',true);
  bindForm(m,edit?'marketing/inbox-update':'marketing/inbox',b=>({...b,...(edit?{id:record.id,version_no:record.version_no}:{}),owner_user_id:Number(b.owner_user_id),...(!edit?{campaign_id:Number(b.campaign_id)}:{})}),()=>{ui.tab='inbox';});
 }
 function handoff(x){if(!x.email&&!x.phone){toast(t('Add email or phone in Reply / assign first.','Bổ sung email hoặc điện thoại trong Soạn trả lời / phân công trước.'),true);return;}
  const m=modal(t('Create a Lead Hub request','Tạo yêu cầu trong Lead Hub'),`<form class="mk-form" data-no-translate><p>${esc(x.contact_name)} · ${esc(x.campaign_name)}</p><div class="mk-grid2">${input(t('Travel date (optional)','Ngày đi (nếu biết)'),'travel_date','','date')}${input(t('Total guests','Tổng số khách'),'total_guests','','number',true)}${input(t('Paying guests','Khách trả tiền'),'paying_pax','','number',true)}${input('FOC','foc',0,'number',true)}${input(t('Destination','Điểm đến'),'destination')}${input(t('Hotel category','Hạng khách sạn'),'hotel_level')}</div><p class="mk-note">${t('Enter confirmed guest counts. Creates a NEW request for qualification in Lead Hub; it does not create a quote or send a reply.','Nhập số khách đã xác nhận. Tạo yêu cầu NEW để qualify trong Lead Hub; chưa tạo báo giá hoặc gửi khách.')}${preview?' '+t('Demo handoff is simulated; it does not populate the separate Lead Hub preview.','Chuyển lead trong demo là mô phỏng, không ghi sang màn hình Lead Hub preview riêng.'):''}</p><button type="submit" class="btn primary">${t('Create request','Tạo yêu cầu')}</button></form>`,'',true);
  bindForm(m,'marketing/inbox-lead',b=>{const total=Number(b.total_guests),pay=Number(b.paying_pax),foc=Number(b.foc);if(total<1||pay<1||pay+foc>total)throw Error(t('Check guest counts.','Kiểm tra số khách.'));return {...b,id:x.id,total_guests:total,paying_pax:pay,foc};},r=>toast(t('Lead request created #','Đã tạo yêu cầu #')+r.request_id));
 }
 root.onclick=async e=>{if(root.dataset.view!=='marketing')return;const b=e.target.closest('[data-mk]');if(!b)return;const action=b.dataset.mk,id=b.dataset.id,item=data.items.find(x=>Number(x.id)===Number(id)),template=data.library.find(x=>Number(x.id)===Number(id)),note=data.inbox.find(x=>Number(x.id)===Number(id));
  if(action==='tab'){ui.tab=id;ui.q='';ui.topic='';ui.status='';ui.channel='';ui.day='';draw();}
  if(action==='queue'){ui.tab='content';ui.status=id;ui.q='';ui.day='';ui.topic='';ui.channel='';draw();}
  if(action==='clear'){ui.q='';ui.channel='';ui.topic='';ui.status='';ui.day='';draw();}
  if(action==='day'){ui.tab='content';ui.day=id;ui.q='';ui.channel='';ui.topic='';ui.status='';draw();}
  if(action==='month'){if(Number(id)===0)ui.month=M.today().slice(0,7);else{const [y,m]=ui.month.split('-').map(Number);ui.month=new Date(Date.UTC(y,m-1+Number(id),1)).toISOString().slice(0,7);}draw();}
  if(action==='reset'&&preview){window.VTAMarketingDemo.reset();await navigate('marketing');}
  if(action==='leads')navigate('leads');if(action==='ai')navigate('ai');if(action==='plus-marketing'&&manage&&window.VTAPlusAssist)window.VTAPlusAssist.open({mode:'marketing'});
  if(action==='new-campaign'&&manage)newCampaign();if(action==='new-template'&&manage)templateForm();
  if(['compose','repeat','campaign-compose','revise','use-template','repeat-template'].includes(action)&&manage)compose(action==='revise'?item:action.includes('template')?template:action==='campaign-compose'?{campaign_id:Number(id)}:{},action==='repeat'||action==='repeat-template');
  if(action==='save-template'&&manage)templateForm({...item,title:item.campaign_name+' · '+item.channel});
  if(action==='submit'&&manage)await mutate('marketing/submit',{id:Number(id)},b);
  if((action==='approve'||action==='reject')&&approve)await mutate('marketing/decision',{id:Number(id),decision:action==='approve'?'APPROVED':'REJECTED'},b);
  if(action==='new-note'&&leadManage)noteForm();if(action==='edit-note'&&leadManage)noteForm(note);if(action==='handoff'&&leadManage)handoff(note);
  if(action==='copy'||action==='copy-reply'){try{await navigator.clipboard.writeText(action==='copy'?item.body:note.reply_draft);toast(t('Copied','Đã sao chép'));}catch{toast(t('Select and copy the text manually.','Anh có thể bôi đen và sao chép văn bản.'),true);}}
  if(action==='export'){const blob=new Blob([JSON.stringify({timezone:'Asia/Ho_Chi_Minh',preview,delivery_enabled:false,items:data.items.filter(matches)},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='VTA_Content_Plan_'+M.today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  if(action==='connection')modal(t('Connect ','Kết nối ')+id,`<div class="mk-form" data-no-translate><p>${t('This server has no verified publishing connection for this channel.','Máy chủ này chưa có kết nối phát hành được xác thực cho kênh này.')}</p><ol><li>${t('Choose an authorized provider: Composio, SO9 API, Make/n8n or the platform API.','Chọn nhà cung cấp được cấp quyền: Composio, SO9 API, Make/n8n hoặc API nền tảng.')}</li><li>${t('Configure OAuth and credentials privately on the server; never paste tokens into post content.','Cấu hình OAuth và khóa riêng trên máy chủ; không dán token vào nội dung bài.')}</li><li>${t('Implement and test media upload, token renewal, webhooks and delivery receipts for that provider.','Triển khai và thử upload media, gia hạn token, webhook và kết quả gửi của nhà cung cấp.')}</li><li>${t('Enable delivery only after a reviewed release action. No transport is enabled in this build.','Chỉ bật phát hành qua thao tác đã được duyệt. Bản này chưa bật bộ xử lý gửi.')}</li></ol></div>`);
 };
 root.onchange=e=>{const k={filterChannel:'channel',filterTopic:'topic',filterStatus:'status'}[e.target.name];if(k){ui[k]=e.target.value;draw();}};
 root.oninput=e=>{if(e.target.id==='mkSearch'){const at=e.target.selectionStart;ui.q=e.target.value;draw();const input=root.querySelector('#mkSearch');input.focus();input.setSelectionRange(at,at);}};
 draw();
};
})();
