(function(){
 'use strict';
 const list=x=>Array.isArray(x)?x:[];
 const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const tiles=[
  ['intake','Operations Intake','Nhận bàn giao từ Sales, trả về để làm rõ và chuẩn bị đặt dịch vụ','IN','green','operations.view'],
  ['today','Today Operations','Hôm nay: dịch vụ, phân công và việc cần xử lý','TOD','blue','operations.view'],
  ['bookings','Booking Operations','Theo dõi booking và mức sẵn sàng khởi hành','BKG','green','booking.view'],
  ['arrivals','Arrivals / Departures','Chuyến bay, giờ đến và giờ đi theo booking','FLY','blue','booking.view'],
  ['schedule','Tour Schedule','Lịch dịch vụ và hành trình của từng tour','ITN','purple','booking.view'],
  ['guides','Guide Center','Hướng dẫn viên, liên hệ và phân công','GD','blue','operations.view'],
  ['transport','Driver & Vehicle','Tài xế, xe và lịch phục vụ','CAR','blue','operations.view'],
  ['hotel','Hotel','Lưu trú, xác nhận và thông tin dịch vụ','HTL','purple','booking.view'],
  ['activities','Cruise & Activities','Du thuyền, tham quan và các hoạt động','SEA','green','booking.view'],
  ['confirmations','Supplier Confirmations','Đơn dịch vụ và trạng thái nhà cung cấp','SUP','green','operations.view'],
  ['vouchers','Voucher Center','Mở bộ chứng từ dịch vụ theo booking','V','olive','booking.view'],
  ['passengers','Passenger / Rooming List','Danh sách khách và bộ hồ sơ xếp phòng','PAX','purple','booking.view'],
  ['tasks','Tasks','Công việc, hạn xử lý và người phụ trách','✓','blue','task.view'],
  ['incidents','Incidents','Sự cố đang mở, mức độ và hướng xử lý','!','amber','operations.view'],
  ['payments','Supplier Payments','Công nợ nhà cung cấp và ghi nhận thanh toán','AP','green','supplier_ap.view'],
  ['reports','Operations Reports','Tổng hợp dịch vụ và readiness theo ngày','RPT','purple','report.view']
 ];
 window.VTAOperationsCenter=async function(options){
  const {api,esc,can,navigate,modal,closeModal,toast,openTravelDocuments,openServiceDetails}=options;
  const root=document.querySelector('#workspace');if(!root)return;
  const vi=window.VTA_I18N?.language==='vi',t=(en,vn)=>vi?vn:en;
  let date=today(),view='home',bookingId='',query='',ticket=0,payables=[];
  const alive=n=>n===ticket&&root.dataset.view==='operations';
  const request=route=>api.request(route);
  const safe=x=>esc(x??'');
  const items=response=>{if(!Array.isArray(response?.items))throw Error(t('The data response is incomplete. Please try again.','Dữ liệu trả về chưa đầy đủ. Vui lòng thử lại.'));return response.items;};
  const title=id=>tiles.find(x=>x[0]===id)?.[1]||'Operations Control Center';
  const status=s=>'<span class="ops-status">'+safe(s||'Pending')+'</span>';
  const empty=message=>'<div class="ops-empty">'+safe(message||t('No records found.','Chưa có dữ liệu.'))+'</div>';
  const note=message=>'<p class="ops-note">'+safe(message)+'</p>';
  const openBooking=(id,tab='overview')=>navigate('booking',{bookingId:Number(id),bookingTab:tab});
  function header(){return '<header class="ops-heading"><div><h1>'+safe(title(view))+'</h1><p>'+safe(view==='home'?t('Vietnam Travel Advisor · One place to run every tour','Vietnam Travel Advisor · Điều phối tour từ một trung tâm'):t('Operations Control Center · '+date,'Trung tâm Điều hành · '+date))+'</p></div><div class="ops-head-actions">'+(view!=='home'?'<button class="btn" data-op-home>← '+t('Control Center','Trung tâm')+'</button>':'')+'<button class="btn" data-op-refresh>'+t('Refresh','Làm mới')+'</button></div></header>'+
   '<div class="ops-context"><form data-op-date-form><label>'+t('Operations date','Ngày điều hành')+'<input type="date" name="date" value="'+safe(date)+'" required></label><button class="btn" type="submit">'+t('Load day','Xem ngày')+'</button></form><span class="ops-mode">'+(window.VTA_PREVIEW?t('PREVIEW · Sample data, changes stay in memory','XEM THỬ · Dữ liệu mẫu, thay đổi chỉ trong phiên'):t('LIVE WORKSPACE · UTC+7','DỮ LIỆU HỆ THỐNG · UTC+7'))+'</span></div>';}
  function shell(content){root.innerHTML='<div class="page ops-center" data-no-translate>'+header()+'<div data-op-content>'+content+'</div></div>';bindCommon();}
  function bindCommon(){
   root.querySelector('[data-op-home]')?.addEventListener('click',()=>go('home'));
   root.querySelector('[data-op-control]')?.addEventListener('click',()=>navigate('control'));root.querySelector('[data-op-finance]')?.addEventListener('click',()=>navigate('finance'));root.querySelector('[data-op-refresh]').onclick=()=>go(view);
   root.querySelector('[data-op-date-form]').onsubmit=e=>{e.preventDefault();date=e.target.elements.date.value;go(view);};
   root.querySelectorAll('[data-op-open-booking]').forEach(b=>{b.disabled=!can('booking.view');if(!b.disabled)b.onclick=()=>openBooking(b.dataset.opOpenBooking,b.dataset.opTab||'overview');});
   root.querySelector('[data-op-retry]')?.addEventListener('click',()=>go(view));
  }
  const metric=(value,label)=>'<div class="ops-metric"><strong>'+safe(value)+'</strong><span>'+safe(label)+'</span></div>';
  function cardGrid(){return (['supplier.view','document.view','rate.view','finance.view','quote.approve','finance.close'].some(can)?'<div class="ops-head-actions ops-vault-actions">'+(can('supplier.view')?'<button class="btn" data-op-vault>'+t('Suppliers & rates','Nhà cung cấp & bảng giá')+'</button>':'')+(can('finance.view')?'<button class="btn" data-op-finance>'+t('Customer invoices & finance','Hóa đơn khách & tài chính')+'</button>':'')+(['quote.approve','finance.close'].some(can)?'<button class="btn" data-op-control>'+t('Approvals','Phê duyệt')+'</button>':'')+'</div>':'')+'<label class="ops-search">'+t('Find an operations tool','Tìm công cụ điều hành')+'<input data-op-search type="search" placeholder="'+t('Search cards…','Tìm thẻ chức năng…')+'" value="'+safe(query)+'"></label><div class="ops-grid">'+tiles.map(([id,name,desc,icon,tone,permission])=>{
   const allowed=can(permission)&&(id!=='reports'||can('operations.view'));
   return '<button type="button" class="ops-tile tone-'+tone+'" data-op-tile="'+id+'" '+(!allowed?'disabled':'')+'><span class="ops-tile-icon" aria-hidden="true">'+icon+'</span><strong>'+name+'</strong><span class="ops-tile-description">'+safe(vi?desc:({today:'Daily services, assignments and urgent work',bookings:'Bookings, service status and departure readiness',arrivals:'Booking flights and arrival / departure times',schedule:'Service plans and the tour timeline',guides:'Guide contacts, availability and assignments',transport:'Drivers, vehicles and service assignments',hotel:'Stays, confirmations and service details',activities:'Cruises, sightseeing and activities',confirmations:'Supplier orders and confirmation status',vouchers:'Open service documents for a booking',passengers:'Guest lists and rooming documents',tasks:'Deadlines, owners and open work',incidents:'Open issues, severity and resolution',payments:'Supplier balances and payment records',reports:'Daily service and readiness summary'}[id]))+'</span>'+(!allowed?'<span class="ops-access">'+t('Access required','Cần quyền truy cập')+'</span>':'')+'</button>';
  }).join('')+'</div><p data-op-no-match hidden>'+t('No matching tools.','Không tìm thấy công cụ phù hợp.')+'</p>';}
  function bindCards(){
   root.querySelectorAll('[data-op-tile]').forEach(b=>b.onclick=()=>{if(!b.disabled)go(b.dataset.opTile);});
   root.querySelector('[data-op-vault]')?.addEventListener('click',()=>navigate('suppliers',{productTab:'overview'}));const input=root.querySelector('[data-op-search]');
   if(input){input.oninput=()=>{query=input.value;let count=0;root.querySelectorAll('[data-op-tile]').forEach(b=>{b.hidden=!b.textContent.toLowerCase().includes(query.toLowerCase().trim());if(!b.hidden)count++;});root.querySelector('[data-op-no-match]').hidden=count>0;};input.oninput();}
  }
  function failure(error){return '<div class="ops-alert" role="alert"><strong>'+t('Could not load this data','Chưa tải được dữ liệu')+'</strong><p>'+safe(error.message||error)+'</p><button class="btn" data-op-retry>'+t('Try again','Thử lại')+'</button></div>';}
  async function operations(){const d=await request('v3/operations?date='+encodeURIComponent(date));if(!Array.isArray(d?.movement)||!Array.isArray(d?.readiness)||!Array.isArray(d?.issues))throw Error(t('Operations data is incomplete. Please reload or check the API.','Dữ liệu điều hành chưa đầy đủ. Vui lòng tải lại hoặc kiểm tra API.'));return d;}
  function movementRows(rows){return list(rows).map(s=>'<article class="ops-row"><div><strong>'+safe(s.service_name)+'</strong><p>'+safe(s.booking_ref)+' · '+safe(s.service_date||date)+' · '+safe(s.start_time||t('Time pending','Chưa có giờ'))+' → '+safe(s.end_time||'—')+'</p><p>'+safe(s.pickup_location||'')+(s.dropoff_location?' → '+safe(s.dropoff_location):'')+'</p>'+status(s.booking_status)+'</div><div class="ops-row-actions"><button class="btn" data-op-open-booking="'+Number(s.booking_id)+'" data-op-tab="services">'+t('Booking','Booking')+'</button>'+(can('service.manage')?'<button class="btn" data-op-assign="'+Number(s.id)+'">'+t('Assign resource','Phân công')+'</button>':'')+((can('service.manage')&&can('operations.view'))?'<button class="btn" data-op-service-details="'+Number(s.id)+'">'+t('Service details','Thông tin dịch vụ')+'</button>':'')+'</div></article>').join('')||empty(t('No services on this date.','Chưa có dịch vụ trong ngày đã chọn.'));}
  function readinessRows(rows){return list(rows).map(b=>'<article class="ops-row"><div><strong>'+safe(b.booking_ref)+'</strong><p>'+safe(b.readiness_pct??0)+'% '+t('ready','sẵn sàng')+'</p><div class="ops-checks">'+Object.entries(b.checks||{}).map(([k,v])=>'<span class="'+(v?'ready':'pending')+'">'+(v?'✓ ':'○ ')+safe(k.replaceAll('_',' '))+'</span>').join('')+'</div></div><button class="btn" data-op-open-booking="'+Number(b.booking_id||b.id)+'">'+t('Open booking','Mở booking')+'</button></article>').join('')||empty(t('No readiness records for services on this date.','Chưa có dữ liệu readiness cho dịch vụ trong ngày.'));}
  function issuesRows(rows){return list(rows).map(i=>'<article class="ops-row"><div><strong>'+safe(i.title)+'</strong><p>'+safe(i.booking_ref)+' · '+safe(i.severity)+' · '+safe(i.status||'OPEN')+'</p></div><div class="ops-row-actions"><button class="btn" data-op-open-booking="'+Number(i.booking_id)+'">'+t('Booking','Booking')+'</button>'+(can('service.manage')?'<button class="btn" data-op-resolve="'+Number(i.id)+'">'+t('Resolve','Giải quyết')+'</button>':'')+'</div></article>').join('')||empty(t('No open incidents.','Không có sự cố đang mở.'));}
  const section=(name,body)=>'<section class="ops-panel"><h2>'+safe(name)+'</h2>'+body+'</section>';
  function formDialog(name,fields,route,transform=x=>x){const m=modal(name,'<form data-op-form>'+fields+'<button class="btn primary" type="submit">'+t('Save','Lưu')+'</button><p data-op-form-error role="alert"></p></form>');const form=m.querySelector('[data-op-form]');form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;try{const data=Object.fromEntries(new FormData(form));await api.request(route,{method:'POST',body:transform(data)});m.remove();await go(view);}catch(error){form.querySelector('[data-op-form-error]').textContent=error.message;button.disabled=false;}};}
  const field=(label,name,type='text',value='',extra='')=>'<label>'+safe(label)+'<input name="'+name+'" type="'+type+'" value="'+safe(value)+'" '+extra+'></label>';
  function bindOperational(resources=[]){
   root.querySelectorAll('[data-op-service-details]').forEach(b=>b.onclick=()=>openServiceDetails?.(Number(b.dataset.opServiceDetails)));
   root.querySelectorAll('[data-op-assign]').forEach(b=>b.onclick=()=>{const active=list(resources).filter(r=>r.status==='ACTIVE');if(!active.length)return toast(t('Add an active resource first.','Cần thêm tài nguyên hoạt động trước.'),true);formDialog(t('Assign resource','Phân công tài nguyên'),'<label>'+t('Resource','Tài nguyên')+'<select name="resource_id">'+active.map(r=>'<option value="'+Number(r.id)+'">'+safe(r.kind+' · '+r.name)+'</option>').join('')+'</select></label>'+field(t('From','Từ'),'starts_at','datetime-local',date+'T08:00','required')+field(t('Until','Đến'),'ends_at','datetime-local',date+'T18:00','required'),'services/'+Number(b.dataset.opAssign)+'/assign',x=>({...x,resource_id:Number(x.resource_id),starts_at:x.starts_at.replace('T',' ')+':00',ends_at:x.ends_at.replace('T',' ')+':00'}));});
   root.querySelectorAll('[data-op-resolve]').forEach(b=>b.onclick=()=>formDialog(t('Resolve incident','Giải quyết sự cố'),'<label>'+t('Root cause','Nguyên nhân')+'<textarea name="root_cause" required></textarea></label><label>'+t('Resolution','Cách xử lý')+'<textarea name="resolution" required></textarea></label><label>'+t('Lessons learned','Kinh nghiệm')+'<textarea name="lessons_learned" required></textarea></label>'+field(t('Financial impact','Ảnh hưởng tài chính'),'financial_impact','number','0','min="0" step="0.01"')+'<label>Currency<select name="currency"><option>VND</option><option>USD</option></select></label>','issues/'+Number(b.dataset.opResolve)+'/resolve'));
   root.querySelector('[data-op-add-resource]')?.addEventListener('click',()=>formDialog(t('Add resource','Thêm tài nguyên'),'<label>'+t('Type','Loại')+'<select name="kind">'+(view==='guides'?'<option>GUIDE</option>':'<option>DRIVER</option><option>VEHICLE</option>')+'</select></label>'+field(t('Name / vehicle reference','Tên / mã xe'),'name','text','','required maxlength="190"')+field(t('Phone','Điện thoại'),'phone','tel','','maxlength="64"')+field(t('Vehicle seat capacity','Số chỗ (đối với xe)'),'capacity','number','','min="1" max="1000"'),'v3/resources'));
  }
  async function selectedBooking(n){const response=await request('bookings');if(!alive(n))return null;const bookings=items(response);if(!bookings.some(b=>String(b.id)===bookingId))bookingId=String(bookings[0]?.id||'');const detail=bookingId?await request('bookings/'+bookingId):null;if(detail&&(!detail.booking||!Array.isArray(detail.services)||!Array.isArray(detail.guests)||!Array.isArray(detail.flights)))throw Error(t('Booking data is incomplete. Please try again.','Dữ liệu booking chưa đầy đủ. Vui lòng thử lại.'));return {bookings,detail};}
  function bookingPicker(bookings){return '<label class="ops-booking-picker">'+t('Booking','Booking')+'<select data-op-booking-select>'+list(bookings).map(b=>'<option value="'+Number(b.id)+'" '+(String(b.id)===bookingId?'selected':'')+'>'+safe(b.booking_ref+' · '+(b.lead_guest_name||b.title||''))+'</option>').join('')+'</select></label>'+note(t('This section shows the selected booking across its full travel dates.','Mục này hiển thị booking đã chọn trong toàn bộ thời gian tour.'));}
  function bindPicker(){const select=root.querySelector('[data-op-booking-select]');if(select)select.onchange=()=>{bookingId=select.value;go(view);};}
  function paymentDialog(payable){
   const m=modal(t('Record supplier payment','Ghi nhận thanh toán nhà cung cấp'),'<form data-op-payment-form>'+note(payable.supplier_name+' · '+payable.payable_ref)+note(t('Balance: ','Còn phải trả: ')+payable.balance+' '+payable.currency)+field(t('Amount','Số tiền'),'amount','number','','required min="0.01" step="0.01" max="'+safe(payable.balance)+'"')+field(t('Payment date','Ngày thanh toán'),'payment_date','date',date,'required')+field(t('Bank transaction / payment reference','Mã giao dịch / tham chiếu thanh toán'),'transaction_reference','text','','required maxlength="190"')+'<button class="btn primary" type="submit">'+t('Record payment','Ghi nhận thanh toán')+'</button><p role="alert"></p></form>');
   const form=m.querySelector('form');let signature='',key='';
   form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;
    try{const fields=Object.fromEntries(new FormData(form)),payload={amount:fields.amount,payment_date:fields.payment_date,transaction_reference:fields.transaction_reference,currency:payable.currency};
     const next=JSON.stringify(payload);if(next!==signature){signature=next;key='ops-'+(crypto.randomUUID?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint32Array(4))).map(x=>x.toString(16)).join('-'));}
     await api.request('payables/'+Number(payable.id)+'/payments',{method:'POST',body:{...payload,idempotency_key:key}});m.remove();await go(view);
    }catch(error){form.querySelector('[role=alert]').textContent=error.message;button.disabled=false;}
   };
  }
  function bookingCards(bookings,tab='overview'){return list(bookings).map(b=>'<article class="ops-booking-card"><strong>'+safe(b.booking_ref)+'</strong><h3>'+safe(b.lead_guest_name||b.title)+'</h3><p>'+safe(b.start_date)+' → '+safe(b.end_date)+' · '+safe(b.total_guests)+' '+t('guests','khách')+'</p>'+status(b.operations_status)+'<p>'+safe(b.readiness_pct??0)+'% '+t('readiness','sẵn sàng')+'</p><button class="btn" data-op-open-booking="'+Number(b.id)+'" data-op-tab="'+tab+'">'+t('Open booking','Mở booking')+' →</button></article>').join('')||empty();}
  async function go(id){
   if(root.dataset.view!=='operations')return;
   const tile=tiles.find(x=>x[0]===id);if(id!=='home'&&(!tile||!can(tile[5])||(id==='reports'&&!can('operations.view'))))return;
   view=id;const n=++ticket;shell(id==='home'?cardGrid():'<div class="ops-empty" role="status">'+t('Loading…','Đang tải…')+'</div>');if(id==='home')bindCards();
   try{
    if(id==='intake'){if(window.VTA_PREVIEW){shell(note(t('Synthetic commercial handovers will appear after a confirmed booking.','Bàn giao mẫu sẽ hiển thị sau khi booking được xác nhận.')));return;}await window.mountOperationsIntake(root.querySelector('[data-op-content]'),{api,navigate,toast});return;}
    let content='',resources=[];
    if(id==='home'){
     if(can('operations.view')){let d;try{d=await operations();}catch(error){if(!alive(n))return;shell(failure(error)+cardGrid());bindCards();return;}
      content='<div class="ops-metrics">'+metric(d.movement.length,t('Services on '+date,'Dịch vụ ngày '+date))+metric(d.readiness.length,t('Bookings with services','Booking có dịch vụ'))+metric(d.issues.length,t('Open incidents · all dates','Sự cố đang mở · tất cả ngày'))+metric(d.readiness.filter(b=>Number(b.readiness_pct)<100).length,t('Readiness below 100%','Readiness dưới 100%'))+'</div>';
     }content+=cardGrid();
    }else if(['today','guides','transport','incidents','reports'].includes(id)){
     const d=await operations();
     if(['today','guides','transport'].includes(id)){resources=items(await request('v3/resources'));}
     if(id==='today')content=section(t('Daily movement','Dịch vụ trong ngày'),movementRows(d.movement))+section(t('Departure readiness','Sẵn sàng khởi hành'),readinessRows(d.readiness))+section(t('Open incidents · all dates','Sự cố đang mở · tất cả ngày'),issuesRows(d.issues));
     if(id==='guides'||id==='transport'){
      const kinds=id==='guides'?['GUIDE']:['DRIVER','VEHICLE'];const filtered=resources.filter(r=>kinds.includes(r.kind));
      content=(can('service.manage')?'<button class="btn primary" data-op-add-resource>'+t('Add resource','Thêm tài nguyên')+'</button>':'')+section(t('Resource directory','Danh bạ tài nguyên'),filtered.map(r=>'<article class="ops-row"><div><strong>'+safe(r.name)+'</strong><p>'+safe(r.kind)+' · '+safe(r.phone||t('No phone recorded','Chưa có số liên hệ'))+(r.capacity?' · '+safe(r.capacity)+' '+t('seats','chỗ'):'')+'</p></div>'+status(r.status)+'</article>').join('')||empty())+section(t('Assignments on '+date,'Phân công ngày '+date),d.readiness.flatMap(b=>list(b.services).flatMap(s=>list(s.assigned).filter(a=>kinds.includes(a.kind)&&a.starts_at?.slice(0,10)<=date&&a.ends_at?.slice(0,10)>=date).map(a=>'<article class="ops-row"><div><strong>'+safe(a.name)+' · '+safe(b.booking_ref)+'</strong><p>'+safe(s.service_name)+' · '+safe(a.starts_at)+' → '+safe(a.ends_at)+'</p></div>'+(can('service.manage')?'<button class="btn" data-op-unassign="'+Number(a.id)+'">'+t('Unassign','Hủy phân công')+'</button>':'')+'</article>'))).join('')||empty())+section(t('Services to assign','Dịch vụ để phân công'),movementRows(d.movement));
     }
     if(id==='incidents'){content=(can('service.manage')&&can('booking.view')?'<button class="btn primary" data-op-new-incident>'+t('Report incident','Báo sự cố')+'</button>':'')+section(t('Open incidents · all dates','Sự cố đang mở · tất cả ngày'),issuesRows(d.issues));}
     if(id==='reports'){
      const groups={};d.movement.forEach(s=>{const key=s.category||'OTHER';groups[key]=(groups[key]||0)+1;});
      content=note(t('Daily services and readiness; open incidents cover all dates. Amounts and financial reports remain in Finance.','Dịch vụ và readiness theo ngày; sự cố đang mở tính tất cả ngày.'))+'<div class="ops-metrics">'+metric(d.movement.length,t('Services','Dịch vụ'))+metric(d.movement.filter(s=>s.booking_status==='CONFIRMED').length,t('Confirmed services','Dịch vụ xác nhận'))+metric(d.readiness.length,t('Bookings','Booking'))+metric(d.issues.length,t('Open incidents','Sự cố đang mở'))+'</div>'+section(t('Services by category','Dịch vụ theo nhóm'),Object.entries(groups).map(([k,v])=>'<div class="ops-row"><strong>'+safe(k)+'</strong><span>'+v+'</span></div>').join('')||empty())+section(t('Readiness by booking','Readiness theo booking'),readinessRows(d.readiness));
     }
    }else if(id==='bookings'){const response=await request('bookings');content='<div class="ops-bookings">'+bookingCards(items(response))+'</div>';
    }else if(['arrivals','schedule','hotel','activities','vouchers','passengers'].includes(id)){
     const selected=await selectedBooking(n);if(!selected)return;const {bookings,detail}=selected;
     content=bookingPicker(bookings);if(!detail)content+=empty(t('Create a booking to use this section.','Cần có booking để sử dụng mục này.'));else{
      const b=detail.booking||{},services=list(detail.services);const action=tab=>'<button class="btn" data-op-open-booking="'+Number(b.id)+'" data-op-tab="'+tab+'">'+t('Open booking '+tab,'Mở booking · '+tab)+' →</button>';
      if(id==='arrivals')content+=section(t('Flights & movements','Chuyến bay và di chuyển'),list(detail.flights).map(f=>'<article class="ops-row"><div><strong>'+safe(f.flight_number)+' · '+safe(f.flight_type)+'</strong><p>'+safe(f.flight_date)+' · '+safe(f.origin_code)+' → '+safe(f.destination_code)+'</p><p>'+t('Arrival','Đến')+' '+safe(f.arrival_time||'—')+' · '+t('Departure','Đi')+' '+safe(f.departure_time||'—')+' · '+safe(f.terminal||'')+'</p></div>'+status(f.status)+'</article>').join('')||empty())+action('flights');
      if(['schedule','hotel','activities'].includes(id)){let rows=services;if(id==='hotel')rows=rows.filter(s=>s.category==='HOTEL');if(id==='activities')rows=rows.filter(s=>['CRUISE','ATTRACTION','TOUR','TICKET','ACTIVITY','SIGHTSEEING','ENTRANCE'].includes(s.category));content+=section(t('Booked services','Dịch vụ trong booking'),rows.map(s=>'<article class="ops-row"><div><strong>'+safe(s.service_name)+'</strong><p>'+safe(s.service_date)+' · '+safe(s.start_time||'—')+' · '+safe(s.supplier_name||'')+'</p>'+status(s.booking_status)+'</div>'+action('services')+'</article>').join('')||empty())+action('services');}
      if(id==='vouchers')content+=section(t('Booking document center','Bộ chứng từ booking'),note(t('Create and review service vouchers in the existing Travel Document Center.','Tạo và xem voucher trong Travel Document Center của booking.'))+(can('travel_document.view')?'<button class="btn primary" data-op-travel-docs>'+t('Open Voucher Center','Mở Voucher Center')+'</button>':note(t('Travel document access is required to generate or view vouchers.','Cần quyền travel_document.view để tạo hoặc xem voucher.'))))+action('documents');
      if(id==='passengers')content+=section(t('Passenger list','Danh sách khách'),list(detail.guests).map(g=>'<article class="ops-row"><div><strong>'+safe(g.full_name)+'</strong><p>'+safe(g.guest_type)+' · '+safe(g.nationality||'')+' · '+safe(g.dietary||'')+'</p><p>'+safe(g.room_preference||g.room_type||'')+' · '+safe(g.room_group||'')+'</p></div></article>').join('')||empty())+action('guests')+section(t('Rooming list','Danh sách xếp phòng'),services.filter(s=>s.category==='HOTEL'||s.category==='CRUISE').map(s=>'<article class="ops-row"><div><strong>'+safe(s.service_name)+'</strong><p>'+safe(s.service_date)+'</p></div>'+(can('service.manage')&&can('operations.view')?'<button class="btn" data-op-service-details="'+Number(s.id)+'">'+t('Rooming allocation','Phân phòng')+'</button>':'')+'</article>').join('')||empty())+action('documents')+note(t('Rooming allocations are saved with hotel/cruise service details; uploaded ROOMING_LIST files are available in booking documents.','Phân phòng được lưu trong thông tin dịch vụ khách sạn/du thuyền; file ROOMING_LIST được lưu tại chứng từ booking.'));
     }
    }else if(id==='confirmations'){const response=await request('supplier-orders');content=section(t('Supplier orders','Đơn nhà cung cấp'),items(response).map(o=>'<article class="ops-row"><div><strong>'+safe(o.order_ref)+' · '+safe(o.supplier_name)+'</strong><p>'+safe(o.booking_ref)+' · '+safe(o.start_date||'')+' · '+safe(o.followup_due_at||'')+'</p>'+status(o.status)+'</div>'+(can('booking.view')?'<button class="btn" data-op-open-booking="'+Number(o.booking_id)+'" data-op-tab="suppliers">'+t('Review confirmation','Xem xác nhận')+'</button>':'')+'</article>').join('')||empty());
    }else if(id==='tasks'){const response=await request('tasks');content=(['task.view','quote.approve','finance.close','operations.view'].some(can)?'<p><button class="btn" data-op-control>'+t('Tasks & approvals','Công việc & phê duyệt')+'</button></p>':'')+section(t('Open tasks','Công việc đang mở'),items(response).map(task=>'<article class="ops-row"><div><strong>'+safe(task.title)+'</strong><p>'+safe(task.owner_name||'')+' · '+safe(task.due_at||t('No deadline','Chưa có hạn'))+' · '+safe(task.priority||'')+'</p>'+status(task.status)+'</div><button class="btn" data-op-task-done="'+Number(task.id)+'">'+t('Complete','Hoàn thành')+'</button></article>').join('')||empty());
    }else if(id==='payments'){
     payables=items(await request('finance/ap'));
     content=(can('finance.view')?'<p><button class="btn" data-op-finance>'+t('Customer invoices & finance','Hóa đơn khách & tài chính')+'</button></p>':'')+note(t('Amounts remain in their original currency. Record a payment or open booking finance for reconciliation.','Số tiền hiển thị theo từng loại tiền. Ghi nhận thanh toán hoặc mở tài chính booking để đối soát.'))+section(t('Supplier payables','Công nợ nhà cung cấp'),payables.map(p=>'<article class="ops-row"><div><strong>'+safe(p.supplier_name)+' · '+safe(p.payable_ref)+'</strong><p>'+safe(p.booking_ref)+' · '+safe(p.label||'')+'</p><p>'+t('Balance','Còn phải trả')+': '+safe(p.balance)+' '+safe(p.currency)+' · '+safe(p.due_date||t('No due date','Chưa có hạn'))+'</p>'+status(p.status)+'</div><div class="ops-row-actions">'+(can('supplier_payment.record')&&Number(p.balance)>0&&p.status!=='CANCELLED'?'<button class="btn primary" data-op-pay="'+Number(p.id)+'">'+t('Record payment','Ghi nhận thanh toán')+'</button>':'')+(can('booking.view')&&can('finance.view')&&can('customer_ar.view')?'<button class="btn" data-op-open-booking="'+Number(p.booking_id)+'" data-op-tab="finance">'+t('Payment details','Chi tiết thanh toán')+'</button>':'')+'</div></article>').join('')||empty());
    }
    if(!alive(n))return;shell(content);if(id==='home')bindCards();bindPicker();bindOperational(resources);
    root.querySelectorAll('[data-op-travel-docs]').forEach(b=>b.onclick=()=>openTravelDocuments?.(Number(bookingId)));
    root.querySelectorAll('[data-op-pay]').forEach(b=>b.onclick=()=>{const payable=payables.find(p=>Number(p.id)===Number(b.dataset.opPay));if(payable&&can('supplier_payment.record'))paymentDialog(payable);});
    root.querySelectorAll('[data-op-task-done]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api.request('tasks/'+Number(b.dataset.opTaskDone)+'/complete',{method:'POST',body:{}});await go(view);}catch(error){toast(error.message,true);b.disabled=false;}});
    root.querySelectorAll('[data-op-unassign]').forEach(b=>b.onclick=()=>formDialog(t('Cancel assignment','Hủy phân công'),'<label>'+t('Reason','Lý do')+'<textarea name="reason" required></textarea></label>','resource-assignments/'+Number(b.dataset.opUnassign)+'/cancel'));
    root.querySelector('[data-op-new-incident]')?.addEventListener('click',async()=>{try{const response=await request('bookings');const bookings=items(response);if(!alive(n))return;if(!bookings.length)return toast(t('Create a booking first.','Cần có booking trước.'),true);const m=modal(t('Report incident','Báo sự cố'),'<form data-op-incident-form><label>Booking<select name="booking_id">'+bookings.map(b=>'<option value="'+Number(b.id)+'">'+safe(b.booking_ref)+'</option>').join('')+'</select></label>'+field(t('Title','Tiêu đề'),'title','text','','required maxlength="190"')+'<label>Category<select name="category"><option>OTHER</option><option>TRANSPORT</option><option>HOTEL</option><option>GUIDE</option></select></label><label>Severity<select name="severity"><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option><option>LOW</option></select></label><label>'+t('Description','Mô tả')+'<textarea name="description" required></textarea></label><button class="btn primary">'+t('Save','Lưu')+'</button><p role="alert"></p></form>');const form=m.querySelector('form');form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;try{const data=Object.fromEntries(new FormData(form));await api.request('bookings/'+Number(data.booking_id)+'/issues',{method:'POST',body:data});m.remove();await go(view);}catch(error){form.querySelector('[role=alert]').textContent=error.message;button.disabled=false;}};}catch(error){toast(error.message,true);}});
   }catch(error){if(!alive(n))return;shell(failure(error)+(id==='home'?cardGrid():''));if(id==='home')bindCards();}
  }
  const initial=options.initialModule;await go(tiles.some(x=>x[0]===initial&&can(x[5]))?initial:'home');
 };
})();
