(function(){
 'use strict';
 const array=x=>Array.isArray(x)?x:[];
 const clone=x=>JSON.parse(JSON.stringify(x));
 const fields=['title','destination','language','tags','status','included_text','excluded_text','terms_text'];
 const dayFields=['day','date','title','description','meals','overnight','notes'];
 const driveLink=value=>{try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&!u.hash&&((u.hostname==='drive.google.com'&&(/^\/file\/(?:u\/\d+\/)?d\/[\w-]{10,200}(?:\/(?:view|edit|preview))?\/?$/.test(u.pathname)||/^\/(open|uc|download)$/.test(u.pathname)&&/^[\w-]{10,200}$/.test(u.searchParams.get('id')||'')))||(u.hostname==='docs.google.com'&&/^\/document\/(?:u\/\d+\/)?d\/[\w-]{10,200}(?:\/(?:edit|view|preview|export))?\/?$/.test(u.pathname)))?u.href:'';}catch{return '';}};
 window.VTATourLibrary=async function(options){
  const {api,esc,can,navigate,modal,toast}=options;
  const root=document.querySelector('#workspace');if(!root)return;
  const instance='lib-'+Math.random().toString(36).slice(2);root.dataset.tourLibraryInstance=instance;
  const allowedView=()=>['tour_library.view','product.view','supplier.view'].some(can);
  const allowedManage=()=>['tour_library.manage','product.manage','document.upload'].some(can);
  const alive=()=>root.dataset.view==='product'&&root.dataset.tourLibraryInstance===instance;
  let items=[],batch=[],view='library',query='',destination='',language='',showArchived=false,ticket=0,busy=false,nextId=1;
  const safe=x=>esc(x??'');
  const request=(route,opt)=>api.request(route,opt);
  const errorText=e=>String(e?.message||e||'Không thể thực hiện. Vui lòng thử lại.');
  const sourceName=p=>p.source_name||({PC:'Tệp từ PC',GOOGLE_DRIVE:'Google Drive',TEXT:'Văn bản',MANUAL:'Văn bản thay thế'}[p.source_type]||'Chương trình tour');
  const metadata=p=>p.metadata?{...p,...p.metadata}:p;
  const normalize=p=>{const x=metadata(p||{});return {...x,title:x.title||'',destination:x.destination||'',language:x.language||'vi',tags:array(x.tags),status:['DRAFT','ARCHIVED'].includes(x.status)?x.status:'ACTIVE',days:array(x.days).map((d,i)=>({...d,day:d.day||i+1})),included_text:x.included_text||'',excluded_text:x.excluded_text||'',terms_text:x.terms_text||'',warnings:array(x.warnings)};};
  const message=(text,kind='note')=>'<div class="tl-'+kind+'">'+safe(text)+'</div>';
  function shell(body){if(!alive())return;if(root.__vtpsAbort)root.__vtpsAbort.abort();root.classList.remove('vtps-host');root.innerHTML='<div class="page tour-library" data-no-translate><header class="tl-heading"><div><h1>Kho chương trình tour</h1><p>Lưu, tìm và tái sử dụng nhiều chương trình tour</p></div><div class="tl-head-actions">'+(allowedManage()?'<a class="btn" href="partner.html" target="_blank" rel="noopener">B2B Partner Hub ↗</a><button class="btn primary" data-tl-new>+ Tạo chương trình</button>':'')+'<button class="btn" data-tl-refresh>Làm mới</button>'+(!window.VTA_PREVIEW&&can('product.view')?'<button class="btn" data-tl-inventory>Tour Inventory nâng cao</button>':'')+(['supplier.view','document.view','rate.view'].some(can)?'<button class="btn" data-tl-suppliers>Nhà cung cấp &amp; bảng giá</button>':'')+'</div></header><div class="tl-tabs"><button class="btn '+(view==='library'?'primary':'')+'" data-tl-tab="library">Chương trình tour</button>'+(allowedManage()?'<button class="btn '+(view==='import'?'primary':'')+'" data-tl-tab="import">Upload / Nhập chương trình'+(batch.length?' ('+batch.length+')':'')+'</button>':'')+'</div>'+(window.VTA_PREVIEW?message('PREVIEW · Dữ liệu mẫu. Chương trình bạn lưu chỉ tồn tại trong phiên xem thử.'): '')+'<div data-tl-body>'+body+'</div></div>';root.querySelector('[data-tl-refresh]').onclick=()=>load();root.querySelector('[data-tl-new]')?.addEventListener('click',()=>newProgram());root.querySelector('[data-tl-inventory]')?.addEventListener('click',()=>navigate('inventory'));root.querySelector('[data-tl-suppliers]')?.addEventListener('click',()=>navigate('suppliers',{productTab:'overview'}));root.querySelectorAll('[data-tl-tab]').forEach(b=>b.onclick=()=>{collectBatch();view=b.dataset.tlTab;render();});}
  function metric(n,label){return '<div class="tl-metric"><strong>'+safe(n)+'</strong><span>'+safe(label)+'</span></div>';}
  function render(){if(!alive())return;if(view==='import'){renderImport();return;}const visible=items.filter(p=>showArchived||p.status!=='ARCHIVED');const destinations=[...new Set(visible.map(p=>p.destination).filter(Boolean))].sort();const languages=[...new Set(visible.map(p=>p.language).filter(Boolean))].sort();shell('<div class="tl-metrics">'+metric(visible.length,'Chương trình')+metric(visible.filter(p=>p.status==='ACTIVE').length,'Đang sử dụng')+metric(destinations.length,'Điểm đến')+metric(languages.length,'Ngôn ngữ')+'</div><div class="tl-filters"><label>Tìm chương trình<input type="search" data-tl-search value="'+safe(query)+'" placeholder="Tên tour, điểm đến, tag…"></label><label>Điểm đến<select data-tl-destination><option value="">Tất cả</option>'+destinations.map(x=>'<option '+(x===destination?'selected':'')+'>'+safe(x)+'</option>').join('')+'</select></label><label>Ngôn ngữ<select data-tl-language><option value="">Tất cả</option>'+languages.map(x=>'<option '+(x===language?'selected':'')+'>'+safe(x)+'</option>').join('')+'</select></label><label class="tl-check"><input type="checkbox" data-tl-archived '+(showArchived?'checked':'')+'>Hiện đã lưu trữ</label></div><div class="tl-grid" data-tl-grid>'+visible.map(card).join('')+'</div><div class="tl-empty" data-tl-empty hidden>Chưa có chương trình phù hợp. '+(allowedManage()?'Chọn Upload / Nhập chương trình để thêm tour.':'')+'</div>');root.querySelector('[data-tl-search]').oninput=e=>{query=e.target.value;filter();};root.querySelector('[data-tl-destination]').onchange=e=>{destination=e.target.value;filter();};root.querySelector('[data-tl-language]').onchange=e=>{language=e.target.value;filter();};root.querySelector('[data-tl-archived]').onchange=e=>{showArchived=e.target.checked;render();};root.querySelectorAll('[data-tl-open]').forEach(b=>b.onclick=()=>openProgram(b.dataset.tlOpen,false));root.querySelectorAll('[data-tl-edit]').forEach(b=>b.onclick=()=>openProgram(b.dataset.tlEdit,true));root.querySelectorAll('[data-tl-archive]').forEach(b=>b.onclick=()=>archiveProgram(b.dataset.tlArchive));root.querySelectorAll('[data-tl-copy]').forEach(b=>b.onclick=()=>copyProgram(b.dataset.tlCopy));filter();}
  function card(p){return '<article class="tl-card" data-tl-card="'+Number(p.id)+'"><button class="tl-card-open" data-tl-open="'+Number(p.id)+'"><span class="tl-icon" aria-hidden="true">ITN</span><strong>'+safe(p.title)+'</strong><span>'+safe(p.destination||'Chưa ghi điểm đến')+' · '+safe(p.day_count||0)+' ngày</span><small>'+safe(p.language||'vi')+' · '+safe(p.status==='ARCHIVED'?'Đã lưu trữ':p.status==='DRAFT'?'Bản nháp':'Đang sử dụng')+'</small></button><p class="tl-source">'+safe(sourceName(p))+'</p><div class="tl-tags">'+array(p.tags).slice(0,6).map(t=>'<span>'+safe(t)+'</span>').join('')+'</div><div class="tl-card-actions">'+(p.status!=='ARCHIVED'&&can('quote.edit')?'<button class="btn" data-tl-copy="'+Number(p.id)+'">Dùng cho báo giá</button>':'')+(allowedManage()&&p.status!=='ARCHIVED'?'<button class="btn" data-tl-edit="'+Number(p.id)+'">Sửa</button><button class="btn ghost" data-tl-archive="'+Number(p.id)+'">Lưu trữ</button>':'')+'</div></article>';}
  function filter(){let count=0;const q=query.trim().toLocaleLowerCase('vi');root.querySelectorAll('[data-tl-card]').forEach(card=>{const p=items.find(p=>Number(p.id)===Number(card.dataset.tlCard));card.hidden=!(p&&(!destination||p.destination===destination)&&(!language||p.language===language)&&[p.title,p.destination,...array(p.tags)].join(' ').toLocaleLowerCase('vi').includes(q));if(!card.hidden)count++;});root.querySelector('[data-tl-empty]').hidden=count>0;}
  async function fetchItems(n){let rows=[],offset=0,total=0;do{const r=await request(offset?'tour-library?limit=100&offset='+offset:'tour-library');if(!Array.isArray(r?.items))throw Error('Dữ liệu kho chương trình chưa đầy đủ.');if(!alive()||ticket!==n)return null;rows.push(...r.items.map(metadata));total=Number(r.total??r.pagination?.total??rows.length);if(!Number.isFinite(total)||total<0)throw Error('Số chương trình trả về chưa hợp lệ.');if(!r.items.length)break;offset=rows.length;}while(offset<total);return [...new Map(rows.map(p=>[Number(p.id),p])).values()];}
  async function load(){const n=++ticket;if(!allowedView()){shell(message('Bạn chưa có quyền xem kho chương trình tour.','alert'));return;}if(view==='import')collectBatch();if(!items.length)shell(message('Đang tải chương trình…'));try{const loaded=await fetchItems(n);if(!loaded)return;items=loaded;render();}catch(e){if(!alive()||n!==ticket)return;shell(message(errorText(e),'alert')+'<button class="btn" data-tl-retry>Thử lại</button>');root.querySelector('[data-tl-retry]').onclick=()=>load();}}
  function input(label,name,value='',extra=''){return '<label>'+safe(label)+'<input name="'+name+'" value="'+safe(value)+'" '+extra+'></label>';}
  function textarea(label,name,value='',extra=''){return '<label>'+safe(label)+'<textarea name="'+name+'" '+extra+'>'+safe(value)+'</textarea></label>';}
  function editor(p,editable=true){const x=normalize(p),disabled=editable?'':'readonly';return '<div class="tl-editor"><div class="tl-meta-fields">'+input('Tên chương trình','title',x.title,'required maxlength="190" '+disabled)+input('Điểm đến','destination',x.destination,'maxlength="190" '+disabled)+input('Ngôn ngữ','language',x.language,'maxlength="16" '+disabled)+input('Tags (ngăn bằng dấu phẩy)','tags',x.tags.join(', '),'maxlength="1000" '+disabled)+'<label>Trạng thái<select name="status" '+(editable?'':'disabled')+'><option value="ACTIVE" '+(x.status==='ACTIVE'?'selected':'')+'>Đang sử dụng</option><option value="DRAFT" '+(x.status==='DRAFT'?'selected':'')+'>Bản nháp</option>'+(x.status==='ARCHIVED'?'<option value="ARCHIVED" selected>Đã lưu trữ</option>':'')+'</select></label></div><h3>Lịch trình theo ngày</h3><div data-tl-days>'+x.days.map((d,i)=>dayEditor(d,i,editable)).join('')+'</div>'+(editable?'<button class="btn" type="button" data-tl-add-day>+ Thêm ngày</button>':'')+'<div class="tl-sections">'+textarea('Included · Bao gồm','included_text',x.included_text,disabled)+textarea('Excluded · Không bao gồm','excluded_text',x.excluded_text,disabled)+textarea('Terms · Điều kiện','terms_text',x.terms_text,disabled)+'</div><details><summary>Văn bản nguồn</summary>'+textarea('Nội dung dùng để đối chiếu','source_text',x.source_text||'','readonly')+'</details></div>';}
  function dayEditor(d,i,editable=true){const disabled=editable?'':'readonly';return '<fieldset class="tl-day" data-tl-day><legend>Ngày '+(i+1)+'</legend><div class="tl-day-meta">'+input('Số ngày','day',d.day||i+1,'type="number" min="1" max="365" required '+disabled)+input('Ngày đi (tùy chọn)','date',d.date||'','type="date" '+disabled)+input('Tiêu đề','title',d.title||'','maxlength="190" '+disabled)+'</div>'+textarea('Nội dung','description',d.description||'',disabled)+'<div class="tl-day-meta">'+input('Bữa ăn','meals',d.meals||'',disabled)+input('Nghỉ đêm','overnight',d.overnight||'',disabled)+'</div>'+textarea('Ghi chú','notes',d.notes||'',disabled)+(editable?'<button class="btn ghost" type="button" data-tl-remove-day>Xóa ngày</button>':'')+'</fieldset>';}
  function readEditor(container,p){const result={...p};const area=container.querySelector('.tl-editor');if(!area)return result;for(const name of fields){const field=area.querySelector('.tl-meta-fields [name="'+name+'"],.tl-sections [name="'+name+'"]');if(field)result[name]=field.value;}result.tags=String(result.tags||'').split(',').map(x=>x.trim()).filter(Boolean);result.days=[...area.querySelectorAll('[data-tl-day]')].map((row,i)=>Object.fromEntries(dayFields.map(k=>[k,k==='day'?Number(row.querySelector('[name="day"]').value||i+1):row.querySelector('[name="'+k+'"]').value])));return result;}
  function wireEditor(container){container.querySelector('[data-tl-add-day]')?.addEventListener('click',()=>{const list=container.querySelector('[data-tl-days]');list.insertAdjacentHTML('beforeend',dayEditor({},list.children.length));wireDayRemoval(container);});wireDayRemoval(container);}
  function wireDayRemoval(container){container.querySelectorAll('[data-tl-remove-day]').forEach(b=>b.onclick=()=>b.closest('[data-tl-day]').remove());}
  function validate(p){if(!p.title.trim())throw Error('Cần nhập tên chương trình.');if(p.status!=='DRAFT'&&(!p.days.length||!p.days.some(d=>d.title.trim()||d.description.trim())))throw Error('Chương trình đang sử dụng cần ít nhất một ngày có nội dung. Bạn có thể lưu bản nháp để bổ sung sau.');}
  const sourceLink=p=>{const url=driveLink(p.source_url||'');return url?'<a class="btn" href="'+safe(url)+'" target="_blank" rel="noopener noreferrer">Mở nguồn Google Drive</a>':'';};
  function showStudio(program){
    if(!window.VTATourProposalStudio){toast('Không tải được Proposal Studio. Hãy làm mới trang.',true);return;}
    const back=async()=>{if(alive())await load();};
    window.VTATourProposalStudio.mount(root,{program,api,toast,canEdit:allowedManage(),onBack:back,onSaved:back});
   }
   function newProgram(){
    if(!allowedManage()||!alive())return;
    showStudio({title:'New Tour Program',destination:'',language:'en',tags:[],status:'DRAFT',days:[],included_text:'',excluded_text:'',terms_text:'',source_name:'',source_type:'MANUAL',source_url:'',source_text:''});
   }
   async function openProgram(id,editable){if(editable&&!allowedManage())return;const n=++ticket;try{const r=await request('tour-library/'+Number(id));if(!alive()||n!==ticket)return;if(!r?.program)throw Error('Chưa tải được nội dung chương trình.');const p=normalize(r.program);p.id=Number(id);if(window.VTATourProposalStudio){showStudio(p);return;}const m=modal(editable?'Sửa chương trình tour':'Chi tiết chương trình tour','<div class="tour-library tl-dialog" data-no-translate>'+sourceLink(p)+(p.has_source&&!window.VTA_PREVIEW?'<a class="btn" href="api/?route='+encodeURIComponent('tour-library/'+Number(id)+'/source')+'" target="_blank" rel="noopener noreferrer">Tải tệp gốc</a>':'')+'<form data-tl-edit-form>'+editor(p,editable)+(editable?'<button class="btn primary" type="submit">Lưu thay đổi</button>':'')+'<p role="alert"></p></form></div>','',true);wireEditor(m);const form=m.querySelector('form');if(editable)form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;try{const updated=readEditor(form,p);validate(updated);await request('tour-library/'+Number(id),{method:'PUT',body:updated});m.remove();if(alive()&&n===ticket){toast('Đã lưu chương trình.');await load();}}catch(e){if(m.isConnected){form.querySelector('[role=alert]').textContent=errorText(e);button.disabled=false;}}};}catch(e){if(alive()&&n===ticket)toast(errorText(e),true);}}
  function archiveProgram(id){if(!allowedManage())return;const p=items.find(p=>Number(p.id)===Number(id));const n=ticket;const m=modal('Lưu trữ chương trình','<div class="tour-library" data-no-translate><p>'+safe(p?.title)+'</p><p>Chương trình sẽ được ẩn khỏi danh sách đang sử dụng. Chọn “Hiện đã lưu trữ” để xem lại.</p><button class="btn primary" data-tl-confirm-archive>Lưu trữ</button><p role="alert"></p></div>');m.querySelector('[data-tl-confirm-archive]').onclick=async e=>{e.target.disabled=true;try{await request('tour-library/'+Number(id)+'/archive',{method:'POST',body:{}});m.remove();if(alive()&&ticket===n)await load();}catch(e){if(m.isConnected){m.querySelector('[role=alert]').textContent=errorText(e);m.querySelector('button').disabled=false;}}};}
  async function copyProgram(id){if(!can('quote.edit'))return;const n=++ticket;try{const r=await request('quotes');if(!alive()||ticket!==n)return;if(!Array.isArray(r?.items))throw Error('Danh sách báo giá chưa đầy đủ.');const drafts=r.items.filter(q=>['DRAFT','WORKING'].includes(q.version_status||q.status));const m=modal('Dùng chương trình cho báo giá','<div class="tour-library" data-no-translate>'+message('Chọn báo giá nháp chưa có lịch trình. Hệ thống sẽ kiểm tra lại trước khi chép, không ghi đè lịch trình đang có.')+'<form data-tl-copy-form><label>Báo giá nháp<select name="quote_id" required>'+drafts.map(q=>'<option value="'+Number(q.id)+'">'+safe((q.quote_ref||'#'+q.id)+' · '+(q.tour_name||q.title||''))+'</option>').join('')+'</select></label><button class="btn primary" type="submit" '+(!drafts.length?'disabled':'')+'>Chép vào báo giá</button>'+(!drafts.length?message('Chưa có báo giá nháp phù hợp. Tạo báo giá tại Kinh doanh.'): '')+'<p role="alert"></p></form></div>');const form=m.querySelector('form');form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;const quoteId=Number(form.elements.quote_id.value);try{if(!quoteId)throw Error('Cần chọn báo giá nháp.');await request('tour-library/'+Number(id)+'/copy-to-quote',{method:'POST',body:{quote_id:quoteId}});m.remove();if(alive()&&ticket===n)navigate('quote',{quoteId,quoteStep:'schedule'});}catch(e){if(m.isConnected){form.querySelector('[role=alert]').textContent=errorText(e);button.disabled=false;}}};}catch(e){if(alive()&&ticket===n)toast(errorText(e),true);}}
  function collectBatch(){if(!alive())return;root.querySelectorAll('[data-tl-import-item]').forEach(row=>{const item=batch.find(i=>i.id===Number(row.dataset.tlImportItem));if(item?.draft)item.draft=readEditor(row,item.draft);const fallback=row.querySelector('[data-tl-manual]');if(item&&fallback)item.manual=fallback.value;});}
  function renderImport(){if(!allowedManage()){view='library';render();return;}shell('<div class="tl-import-sources"><section class="tl-panel"><span class="tl-icon">PC</span><h2>Upload từ PC</h2><p>Chọn nhiều DOCX, PDF, TXT. Tối đa 20 tệp mỗi đợt, 10 MB mỗi tệp.</p><input type="file" data-tl-files multiple accept=".docx,.pdf,.txt"><button class="btn primary" data-tl-upload '+(busy?'disabled':'')+'>Đọc và xem lại</button><hr><p><strong>ZIP nhiều chương trình</strong> · Tối đa 50 tệp DOCX/PDF/TXT trong một ZIP, 10 MB/tệp. Từng tour phải được duyệt trước khi Publish.</p><input type="file" data-tl-zip accept=".zip,application/zip"><button class="btn" data-tl-upload-zip>Đọc ZIP & xem lại</button></section><section class="tl-panel"><span class="tl-icon">DR</span><h2>Google Drive / Google Docs</h2><p>Dán link chia sẻ <strong>từng tệp công khai</strong>, mỗi dòng một link. Link riêng tư: tải về PC rồi upload.</p><textarea data-tl-links placeholder="https://drive.google.com/file/d/…/view&#10;https://docs.google.com/document/d/…/edit"></textarea><button class="btn primary" data-tl-read-links '+(busy?'disabled':'')+'>Đọc các link</button></section><section class="tl-panel"><span class="tl-icon">TXT</span><h2>Dán văn bản</h2><p>Dùng khi tài liệu scan hoặc chưa đọc được tệp. Bao gồm lịch trình và Included / Excluded / Terms.</p><textarea data-tl-text placeholder="Ngày 1: Hà Nội…&#10;Included: …&#10;Excluded: …&#10;Terms: …"></textarea><button class="btn primary" data-tl-read-text '+(busy?'disabled':'')+'>Xem lại văn bản</button></section></div><p class="tl-alert" data-tl-import-error hidden></p>'+(batch.length?'<div class="tl-batch-bar"><div><h2>Xem lại trước khi lưu</h2><p>Mỗi mục tạo một chương trình mới. Nội dung chưa lưu có thể chỉnh sửa bên dưới.</p></div><button class="btn primary" data-tl-save-all '+(busy||!batch.some(i=>i.state==='READY')?'disabled':'')+'>Lưu tất cả mục hợp lệ</button></div><div data-tl-batch>'+batch.map(importItem).join('')+'</div>':message('Các chương trình đọc được sẽ xuất hiện ở đây để bạn xem và chỉnh sửa.')));wireImport();root.querySelectorAll('[data-tl-tab],[data-tl-refresh]').forEach(b=>b.disabled=busy);if(busy){root.querySelectorAll('input,textarea,select').forEach(el=>el.disabled=true);const progress=document.createElement('p');progress.className='tl-note';progress.setAttribute('role','status');progress.textContent='Đang xử lý đợt nhập. Chờ hoàn tất để chỉnh sửa hoặc lưu chương trình.';root.querySelector('[data-tl-body]').prepend(progress);}}
  function importItem(i){const names={QUEUED:'Chờ đọc',PREVIEWING:'Đang đọc…',READY:'Chờ kiểm tra và lưu',ERROR:'Chưa đọc được',SAVING:'Đang lưu…',SAVED:'Đã lưu'};return '<section class="tl-import-item" data-tl-import-item="'+i.id+'"><div class="tl-import-item-head"><strong>'+safe(i.name)+'</strong><span>'+safe(names[i.state])+'</span></div>'+(i.error?message(i.error,'alert'):'')+(i.draft?array(i.draft.warnings).map(w=>message(w,'alert')).join('')+editor(i.draft,!busy&&i.state!=='SAVED'&&i.state!=='SAVING'):'')+(i.state==='ERROR'?'<label>Dán nội dung văn bản thay thế<textarea data-tl-manual placeholder="Dán lịch trình để tiếp tục…">'+safe(i.manual||'')+'</textarea></label><button class="btn" data-tl-manual-preview="'+i.id+'" '+(busy?'disabled':'')+'>Đọc văn bản thay thế</button>':'')+'<div class="tl-import-actions">'+(['READY','ERROR'].includes(i.state)?'<button class="btn" data-tl-retry-item="'+i.id+'" '+(busy?'disabled':'')+'>Đọc lại nguồn</button>':'')+(i.state==='READY'?'<button class="btn primary" data-tl-save-item="'+i.id+'" '+(busy?'disabled':'')+'>Lưu chương trình mới</button>':'')+(!['PREVIEWING','SAVING'].includes(i.state)?'<button class="btn ghost" data-tl-remove-item="'+i.id+'" '+(busy?'disabled':'')+'>Bỏ khỏi đợt nhập</button>':'')+'</div></section>';}
  function wireImport(){root.querySelector('[data-tl-upload]').onclick=()=>{collectBatch();const files=[...root.querySelector('[data-tl-files]').files];if(!files.length)return importError('Cần chọn ít nhất một tệp.');if(files.length>20)return importError('Mỗi đợt tối đa 20 tệp.');const additions=files.map(file=>({id:nextId++,kind:'file',file,name:file.name,state:'QUEUED'}));for(const i of additions){if(!/\.(docx|pdf|txt)$/i.test(i.name)){i.state='ERROR';i.error='Chỉ hỗ trợ DOCX, PDF hoặc TXT.';}else if(i.file.size>10*1024*1024){i.state='ERROR';i.error='Tệp vượt giới hạn 10 MB.';}}batch.push(...additions);runPreviews(additions.filter(i=>i.state==='QUEUED'));};root.querySelector('[data-tl-upload-zip]').onclick=async()=>{
    collectBatch();
    if(busy)return;
    const file=root.querySelector('[data-tl-zip]').files[0];
    if(!file||!/\\.zip$/i.test(file.name))return importError('Chọn ZIP chứa DOCX/PDF/TXT.');
    if(file.size>200*1024*1024)return importError('ZIP vượt 200 MB.');
    busy=true;const n=ticket;renderImport();
    try{
      const form=new FormData();form.append('file',file);
      const result=await request('tour-library/preview-zip',{method:'POST',form});
      if(!Array.isArray(result.items))throw Error('ZIP preview không hợp lệ');
      for(const row of result.items){
        const item={id:nextId++,kind:'zip_entry',name:row.name,state:row.status==='READY'?'READY':'ERROR',error:row.message||''};
        if(row.status==='READY'&&row.preview)item.draft=normalize({...row.preview,status:'DRAFT'});
        batch.push(item);
      }
      toast('ZIP: '+result.ready+'/'+result.total+' chương trình đọc được. Vui lòng kiểm tra rồi lưu.');
    }catch(e){importError(e);}
    finally{busy=false;if(alive()&&n===ticket)renderImport();}
  };
  root.querySelector('[data-tl-read-links]').onclick=()=>{collectBatch();const links=root.querySelector('[data-tl-links]').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!links.length)return importError('Cần dán link từng tệp Google Drive / Google Docs.');if(links.length>20)return importError('Mỗi đợt tối đa 20 link.');const additions=links.map(url=>({id:nextId++,kind:'link',url,name:url,state:driveLink(url)?'QUEUED':'ERROR',error:driveLink(url)?'':'Chỉ nhận link HTTPS của tệp Google Drive hoặc Google Docs. Link thư mục chưa được hỗ trợ.'}));batch.push(...additions);runPreviews(additions.filter(i=>i.state==='QUEUED'));};root.querySelector('[data-tl-read-text]').onclick=()=>{collectBatch();const text=root.querySelector('[data-tl-text]').value;if(!text.trim())return importError('Cần dán nội dung lịch trình.');const i={id:nextId++,kind:'text',text,name:'Chương trình từ văn bản',state:'QUEUED'};batch.push(i);runPreviews([i]);};root.querySelectorAll('[data-tl-import-item]').forEach(wireEditor);root.querySelectorAll('[data-tl-save-item]').forEach(b=>b.onclick=()=>saveBatch([Number(b.dataset.tlSaveItem)]));root.querySelector('[data-tl-save-all]')?.addEventListener('click',()=>saveBatch(batch.filter(i=>i.state==='READY').map(i=>i.id)));root.querySelectorAll('[data-tl-retry-item]').forEach(b=>b.onclick=()=>{collectBatch();const i=batch.find(i=>i.id===Number(b.dataset.tlRetryItem));if(i?.kind==='zip_entry')return importError('Tải lại ZIP nếu tệp chưa đọc được.');runPreviews([i]);});root.querySelectorAll('[data-tl-manual-preview]').forEach(b=>b.onclick=()=>{collectBatch();const i=batch.find(i=>i.id===Number(b.dataset.tlManualPreview));if(!i.manual?.trim())return importError('Cần dán nội dung thay thế.');runPreviews([i],true);});root.querySelectorAll('[data-tl-remove-item]').forEach(b=>b.onclick=()=>{collectBatch();batch=batch.filter(i=>i.id!==Number(b.dataset.tlRemoveItem));renderImport();});}
  function importError(e){const node=root.querySelector('[data-tl-import-error]');if(node){node.hidden=false;node.textContent=errorText(e);}}
  async function runPreviews(rows,manual=false){if(busy||!allowedManage())return;busy=true;const n=ticket;for(const i of rows){i.state='PREVIEWING';i.error='';renderImport();try{if(!manual&&i.kind==='file'&&(!/\.(docx|pdf|txt)$/i.test(i.name)||i.file.size>10*1024*1024))throw Error('Chỉ hỗ trợ DOCX, PDF, TXT tối đa 10 MB mỗi tệp.');if(!manual&&i.kind==='link'&&!driveLink(i.url))throw Error('Link không phải tệp Google Drive / Google Docs công khai hợp lệ.');let opt;if(manual)opt={method:'POST',body:{text:i.manual,source_name:i.name+' · văn bản thay thế'}};else if(i.kind==='file'){const form=new FormData();form.append('file',i.file);opt={method:'POST',form};}else opt={method:'POST',body:i.kind==='link'?{source_url:i.url}:{text:i.text,source_name:i.name}};const r=await request('tour-library/preview',opt);if(!Array.isArray(r?.days))throw Error('Dữ liệu đọc lịch trình chưa đầy đủ.');i.draft=normalize({...r,status:r.status||(!r.days.length?'DRAFT':'ACTIVE')});i.state='READY';}catch(e){i.state='ERROR';i.error=errorText(e);}if(!alive()||n!==ticket){busy=false;return;}}busy=false;renderImport();}
  async function saveBatch(ids){if(busy||!allowedManage())return;collectBatch();busy=true;const n=ticket;for(const id of ids){const i=batch.find(i=>i.id===id);if(!i||i.state!=='READY')continue;try{validate(i.draft);i.state='SAVING';i.error='';renderImport();const signature=JSON.stringify(i.draft);if(i.creationSignature!==signature){i.creationSignature=signature;i.creationKey=crypto.randomUUID?crypto.randomUUID():'tl-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)+'-'+Math.random().toString(36).slice(2);}const r=await request('tour-library',{method:'POST',body:{...i.draft,creation_key:i.creationKey}});if(!r?.id)throw Error('Chưa nhận được xác nhận lưu. Vui lòng thử lại.');i.state='SAVED';i.savedId=Number(r.id);}catch(e){i.state='READY';i.error=errorText(e);}if(!alive()||n!==ticket){busy=false;return;}}busy=false;if(alive()){renderImport();try{const loaded=await fetchItems(n);if(loaded)items=loaded;}catch(e){if(alive())toast('Đã giữ kết quả nhập; làm mới kho để tải danh sách mới.',true);}}}
  await load();
 };
})();
