<?php
declare(strict_types=1);
require_once __DIR__.'/QuoteProposal.php';

/** All formats consume these public blocks, never a costing snapshot or live rate. */
final class ProposalOutput {
 public static function blocks(array $s):array{
  $p=$s['presentation']??[];$c=$p['settings']??[];$template=$c['template']??'VTA_STANDARD_B2B';$white=$template==='VTA_B2B_WHITE_LABEL';$b2b=str_contains($template,'B2B');$brand=$white?($c['brand_name']??''):(($c['brand_name']??'')?:'Vietnam Travel Advisor');$b=[['type'=>'brand','text'=>$brand],['type'=>'title','text'=>(string)($s['tour_name']??'Quotation')],['type'=>'text','text'=>($s['quote_ref']??'').' · V'.($s['version_no']??'').' · '.($s['start_date']??'').' – '.($s['end_date']??'').' · '.($s['total_guests']??'').' guests / '.($s['paying_pax']??'').' paying']];
  $section=function(string $title,string $text)use(&$b){if(trim($text)!==''){$b[]=['type'=>'heading','text'=>$title];$b[]=['type'=>'text','text'=>$text];}};
  $media=function(string $role,string $day='')use(&$b,$p){foreach($p['media']??[] as $m)if($m['role']===$role&&$m['day_key']===$day)$b[]=['type'=>'image','asset_id'=>(int)$m['asset_id'],'caption'=>$m['caption'],'width'=>$m['width'],'height'=>$m['height']];};
  $media('COVER');if($b2b){$section('Prepared for',trim(($c['agent_company']??'').' · '.($c['contact_person']??''),' ·'));$section('Market',$c['market']??'');}
  $section('Briefing',$c['briefing']??'');$section('Highlights',$c['highlights']??'');$b[]=['type'=>'heading','text'=>'Schedule summary'];$b[]=['type'=>'table','headers'=>['Day','Date','Journey','Meals','Overnight'],'rows'=>array_map(fn($d)=>[(string)$d['day'],$d['date'],$d['title'],$d['meals'],$d['overnight']],$s['schedule']??[])];
  $options=$s['options']??[['label'=>'Package','hotel_level'=>$s['hotel_level']??'','currency'=>$s['currency']??'USD','selling_per_pax'=>$s['selling_per_pax']??0,'total_selling'=>$s['total_selling']??0]];
  $b[]=['type'=>'heading','text'=>$b2b?'Best Price Offer · B2B Net':'Choose your journey'];$b[]=['type'=>'table','headers'=>['Option','Mode','Hotel','Cruise','Per paying guest','Group total'],'rows'=>array_map(fn($o)=>[$o['label']??'', $o['costing_mode']??'', $o['hotel_level']??'', $o['cruise_level']??'',($o['currency']??'USD').' '.number_format((float)($o['selling_per_pax']??0),2),($o['currency']??'USD').' '.number_format((float)($o['total_selling']??0),2)],$options)];
  $section('Quote validity',$c['quote_valid_until']??'');foreach(['HOTEL'=>'Hotel list','CRUISE'=>'Halong Cruise list'] as $type=>$title){$rows=array_values(array_filter($c['accommodation']??[],fn($r)=>$r['type']===$type));if($rows){$b[]=['type'=>'heading','text'=>$title];$b[]=['type'=>'table','headers'=>['Destination','3★','4★','5★','Nights'],'rows'=>array_map(fn($r)=>[$r['destination'],$r['three_star'],$r['four_star'],$r['five_star'],(string)$r['nights']],$rows)];}$media($type);}
  $b[]=['type'=>'heading','text'=>'Detailed itinerary'];foreach($s['schedule']??[] as $i=>$d){$day=$p['days'][$i]??[];$key=$day['key']??'';$f=$day['fields']??[];$b[]=['type'=>'heading','text'=>'Day '.($i+1).' · '.($d['title']??'')];$media('DAY_HERO',$key);$b[]=['type'=>'text','text'=>(string)($d['description']??'')];foreach(['route'=>'Route','activities'=>'Activities','transport_mode'=>'Transport','hotel'=>'Hotel','cruise'=>'Cruise','public_notes'=>'Notes'] as $field=>$label)if(!empty($f[$field]))$b[]=['type'=>'text','text'=>$label.': '.$f[$field]];$b[]=['type'=>'text','text'=>'Meals: '.($d['meals']??'').' · Overnight: '.($d['overnight']??'')];$media('DAY_GALLERY',$key);foreach(['HOTEL','CRUISE','SERVICE'] as $r)$media($r,$key);}$media('SERVICE');
  foreach(['included'=>'Included','excluded'=>'Excluded','terms'=>'Booking terms'] as $k=>$title)$section($title,$s[$k]??'');foreach(['children_policy'=>'Children policy','payment_terms'=>'Payment terms','cancellation_policy'=>'Cancellation policy','important_notes'=>'Important notes'] as $k=>$title)$section($title,$c[$k]??'');
  $email=($c['contact_email']??'')?:($white?'':'info@vietnamtraveladvisor.com.vn');$phone=($c['contact_phone']??'')?:($white?'':'+84 582 230 993');$section('Contact',trim($brand."\n".$email.' · '.$phone,' ·'));if(!$b2b&&!empty($c['cta_label']))$b[]=['type'=>'cta','text'=>$c['cta_label'],'url'=>$c['cta_url']??''];return $b;
 }
 public static function html(array $s,callable $imageUrl,bool $draft=false):string{
  $e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');$template=$s['presentation']['settings']['template']??'VTA_STANDARD_B2B';$theme=match($template){'VTA_EXPLORER_B2C'=>['#087e8b','#eff9f8'],'VTA_PREMIUM_B2C'=>['#80612a','#f7f3ea'],'VTA_B2B_WHITE_LABEL'=>['#34485c','#f5f7fa'],default=>['#163b60','#eef4f9']};$lang=($s['document_language']??'en')==='vi'?'vi':'en';
  $html='<!doctype html><html lang="'.$lang.'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.$e($s['tour_name']??'Proposal').'</title><style>body{font:15px/1.65 Arial,sans-serif;color:#233442;background:#edf1f4;margin:0}main{max-width:980px;margin:24px auto;background:white;padding:42px;border-top:8px solid '.$theme[0].'}h1{font-size:34px;line-height:1.2;color:'.$theme[0].'}h2{color:'.$theme[0].';font-size:22px;margin-top:30px}.brand{letter-spacing:.08em;font-weight:bold;text-transform:uppercase}.draft{background:#fff3c8;padding:10px;text-align:center}p{white-space:pre-line}.table-scroll{overflow:auto}table{width:100%;border-collapse:collapse;font-size:13px}th{background:'.$theme[1].'}td,th{padding:10px;border-bottom:1px solid #dce4ec;text-align:left;vertical-align:top}figure{margin:20px 0}img{width:100%;max-height:410px;object-fit:cover;border-radius:8px}figcaption{color:#5f6d7a;font-size:12px}.cta{display:inline-block;background:'.$theme[0].';color:white;padding:12px 22px;text-decoration:none;border-radius:6px}footer{margin-top:30px;border-top:1px solid #dce4ec;padding-top:16px}@media(max-width:600px){main{margin:0;padding:20px}h1{font-size:27px}}@media print{body{background:white}main{margin:0;padding:10mm;max-width:none}h2{break-after:avoid}figure,tr{break-inside:avoid}.draft{display:block}}</style></head><body><main>';
  if($draft)$html.='<div class="draft">DRAFT · Review before sending</div>';foreach(self::blocks($s) as $b){$t=$b['type'];if(in_array($t,['brand','title','heading','text'],true)){$tag=match($t){'title'=>'h1','heading'=>'h2',default=>'p'};$html.='<'.$tag.($t==='brand'?' class="brand"':'').'>'.$e($b['text']).'</'.$tag.'>';}
   elseif($t==='image')$html.='<figure><img src="'.$e($imageUrl($b['asset_id'])).'" alt="'.$e($b['caption']).'"><figcaption>'.$e($b['caption']).'</figcaption></figure>';
   elseif($t==='table'){$html.='<div class="table-scroll"><table><thead><tr>';foreach($b['headers'] as $v)$html.='<th>'.$e($v).'</th>';$html.='</tr></thead><tbody>';foreach($b['rows'] as $row){$html.='<tr>';foreach($row as $v)$html.='<td>'.$e($v).'</td>';$html.='</tr>';}$html.='</tbody></table></div>';}
   elseif($t==='cta')$html.='<p><a class="cta" href="'.$e($b['url']).'" rel="noopener noreferrer">'.$e($b['text']).'</a></p>';
  }return $html.'</main></body></html>';
 }
 public static function pdf(array $s,array $cfg,callable $imagePath,bool $draft=false):string{
  require_once __DIR__.'/../vendor/tfpdf/font/unifont/ttfonts.php';require_once __DIR__.'/../vendor/tfpdf/tfpdf.php';
  $cache=MediaLibrary::directory($cfg).'/pdf-fonts';if(!is_dir($cache.'/unifont')&&!mkdir($cache.'/unifont',0770,true)&&!is_dir($cache.'/unifont'))throw new RuntimeException('PDF font cache unavailable');RuntimeGuard::privatePath($cache);$font=$cache.'/unifont/DejaVuSans.ttf';if(!is_file($font)&&!copy(__DIR__.'/../vendor/tfpdf/font/unifont/DejaVuSans.ttf',$font))throw new RuntimeException('PDF font unavailable');
  $pdf=new class($cache) extends tFPDF {public function __construct(string $cache){parent::__construct();$this->fontpath=$cache.'/';}public function Footer(){$this->SetY(-12);$this->SetFont('VTA','',8);$this->SetTextColor(100,110,120);$this->Cell(0,5,(string)$this->PageNo(),0,0,'R');}};
  $pdf->AddFont('VTA','','DejaVuSans.ttf',true);$pdf->SetAutoPageBreak(true,18);$pdf->SetMargins(18,18,18);$pdf->AddPage();$pdf->SetTitle($s['tour_name']??'Proposal',true);
  if($draft){$pdf->SetFont('VTA','',10);$pdf->SetTextColor(150,90,0);$pdf->MultiCell(0,7,'DRAFT · Review before sending');}
  $accent=match($s['presentation']['settings']['template']??''){'VTA_PREMIUM_B2C'=>[128,97,42],'VTA_EXPLORER_B2C'=>[8,126,139],default=>[20,55,85]};
  $blocks=self::blocks($s);
  foreach($blocks as $index=>$b){$type=$b['type'];if($type==='heading'){$next=$blocks[$index+1]['type']??'';$reserve=$next==='image'?115:($next==='table'?45:25);if($pdf->GetY()+$reserve>277)$pdf->AddPage();}if($type==='image'){$w=174;$h=min(95,$w*$b['height']/$b['width']);$w=$h*$b['width']/$b['height'];if($pdf->GetY()+$h+12>277)$pdf->AddPage();$pdf->Image($imagePath($b['asset_id']),18,$pdf->GetY(),$w,$h,'JPG');$pdf->SetY($pdf->GetY()+$h+2);$pdf->SetFont('VTA','',9);$pdf->MultiCell(0,5,$b['caption']);$pdf->Ln(3);}
   elseif($type==='table'){
    $widths=count($b['headers'])===6?[43,22,17,17,40,35]:($b['headers'][0]==='Day'?[16,27,65,25,41]:[31,38,38,42,25]);
    $wrap=function(string $text,float $width)use($pdf):string{$out=[];foreach(explode("\n",$text) as $line){$part='';foreach(preg_split('//u',$line,-1,PREG_SPLIT_NO_EMPTY) as $char){if($part!==''&&$pdf->GetStringWidth($part.$char)>$width){$out[]=$part;$part='';}$part.=$char;}$out[]=$part;}return implode("\n",$out);};
    $row=function(array $cells,bool $header=false)use($pdf,$widths,$wrap,$accent):void{$pdf->SetFont('VTA','',$header?9:9);$texts=[];$height=10;foreach($cells as $i=>$cell){$t=$wrap((string)$cell,$widths[$i]-4);$texts[]=$t;$height=max($height,5.5*(substr_count($t,"\n")+1)+4);}$y=$pdf->GetY();$x=18;$pdf->SetDrawColor(210,220,230);$pdf->SetFillColor(239,245,249);$pdf->SetTextColor(...($header?$accent:[35,50,65]));foreach($texts as $i=>$t){$pdf->Rect($x,$y,$widths[$i],$height,$header?'DF':'D');$pdf->SetXY($x+2,$y+2);$pdf->MultiCell($widths[$i]-4,5.5,$t);$x+=$widths[$i];}$pdf->SetXY(18,$y+$height);};
    if($pdf->GetY()+25>277)$pdf->AddPage();$row($b['headers'],true);foreach($b['rows'] as $cells){$pdf->SetFont('VTA','',9);$height=10;foreach($cells as $i=>$cell)$height=max($height,5.5*(substr_count($wrap((string)$cell,$widths[$i]-4),"\n")+1)+4);if($pdf->GetY()+$height>277){$pdf->AddPage();$row($b['headers'],true);}$row($cells);}$pdf->Ln(4);
   }else{$size=match($type){'title'=>23,'heading'=>15,'brand'=>12,default=>10};$pdf->SetFont('VTA','',$size);$pdf->SetTextColor(...(in_array($type,['title','heading','brand'],true)?$accent:[35,50,65]));if($type==='heading')$pdf->Ln(4);$text=$b['text'].($type==='cta'&&$b['url']!==''?' · '.$b['url']:'');$pdf->MultiCell(0,$type==='title'?11:7,$text);$pdf->Ln(2);}
  }return $pdf->Output('S');
 }
 public static function docx(array $s,callable $imagePath,bool $draft=false):string{
  if(!class_exists('ZipArchive'))throw new RuntimeException('PHP ZipArchive required for DOCX');$e=fn($v)=>htmlspecialchars((string)$v,ENT_XML1|ENT_QUOTES,'UTF-8');$paragraph=function(string $text,string $style='Normal')use($e){$runs='';foreach(explode("\n",$text) as $i=>$line)$runs.=($i?'<w:r><w:br/></w:r>':'').'<w:r><w:t xml:space="preserve">'.$e($line).'</w:t></w:r>';return '<w:p><w:pPr><w:pStyle w:val="'.$style.'"/></w:pPr>'.$runs.'</w:p>';};
  $tmp=tempnam(sys_get_temp_dir(),'vta-docx-');if($tmp===false)throw new RuntimeException('Cannot create DOCX');$zip=new ZipArchive();try{if($zip->open($tmp,ZipArchive::OVERWRITE)!==true)throw new RuntimeException('Cannot create DOCX ZIP');$xml='';$relationships=[];$images=[];$drawing=1;if($draft)$xml.=$paragraph('DRAFT · Review before sending','Heading2');
   foreach(self::blocks($s) as $b){if($b['type']==='image'){$id=$b['asset_id'];if(!isset($images[$id])){$name='image'.$id.'.jpg';$zip->addFile($imagePath($id),'word/media/'.$name);$rid='rIdImage'.$id;$relationships[]='<Relationship Id="'.$rid.'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/'.$name.'"/>';$images[$id]=$rid;}$cx=5943600;$cy=(int)min(3429000,$cx*$b['height']/$b['width']);$cx=(int)($cy*$b['width']/$b['height']);$xml.='<w:p><w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="'.$cx.'" cy="'.$cy.'"/><wp:docPr id="'.$drawing++.'" name="Photo" descr="'.$e($b['caption']).'"/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="0" name="Photo"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="'.$images[$id].'"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="'.$cx.'" cy="'.$cy.'"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>'.$paragraph($b['caption']);}
    elseif($b['type']==='table'){$xml.='<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/><w:tblBorders><w:bottom w:val="single" w:sz="4" w:color="DCE4EC"/><w:insideH w:val="single" w:sz="4" w:color="DCE4EC"/></w:tblBorders></w:tblPr>';foreach([$b['headers'],...$b['rows']] as $i=>$row){$xml.='<w:tr>'.($i===0?'<w:trPr><w:tblHeader/></w:trPr>':'');foreach($row as $v)$xml.='<w:tc><w:tcPr>'.($i===0?'<w:shd w:fill="EEF4F9"/>':'').'</w:tcPr>'.$paragraph((string)$v).'</w:tc>';$xml.='</w:tr>';}$xml.='</w:tbl>';}
    else $xml.=$paragraph($b['text'].($b['type']==='cta'?' · '.$b['url']:''),match($b['type']){'title'=>'Title','heading'=>'Heading1','brand'=>'Heading2',default=>'Normal'});
   }
   $document='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><w:body>'.$xml.'<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1000" w:right="1000" w:bottom="1000" w:left="1000"/></w:sectPr></w:body></w:document>';
   $zip->addFromString('word/document.xml',$document);$zip->addFromString('word/_rels/document.xml.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdStyles" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>'.implode('',$relationships).'</Relationships>');
   $styles='<?xml version="1.0"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:sz w:val="22"/></w:rPr></w:rPrDefault></w:docDefaults>';foreach(['Normal'=>22,'Title'=>48,'Heading1'=>30,'Heading2'=>24] as $name=>$size)$styles.='<w:style w:type="paragraph" w:styleId="'.$name.'"><w:name w:val="'.$name.'"/><w:pPr><w:spacing w:after="140"/>'.($name!=='Normal'?'<w:keepNext/>':'').'</w:pPr><w:rPr><w:sz w:val="'.$size.'"/>'.($name!=='Normal'?'<w:b/><w:color w:val="163B60"/>':'').'</w:rPr></w:style>';$zip->addFromString('word/styles.xml',$styles.'</w:styles>');
   $zip->addFromString('[Content_Types].xml','<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="jpg" ContentType="image/jpeg"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>');$zip->addFromString('_rels/.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');$zip->close();return (string)file_get_contents($tmp);
  }finally{if(is_file($tmp))unlink($tmp);}
 }
 public static function respond(string $format,array $s,array $cfg,callable $imageUrl,callable $imagePath,bool $draft):never{
  header('Cache-Control: private, no-store');header("Content-Security-Policy: default-src 'none'; img-src 'self'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'self'");header('Referrer-Policy: no-referrer');header('X-Robots-Tag: noindex, nofollow');
  if($format==='html'){header('Content-Type: text/html; charset=utf-8');echo self::html($s,$imageUrl,$draft);exit;}
  $bytes=$format==='pdf'?self::pdf($s,$cfg,$imagePath,$draft):self::docx($s,$imagePath,$draft);$name=preg_replace('/[^A-Za-z0-9_-]/','_',$s['quote_ref']??'Proposal').($draft?'_DRAFT':'').'.'.$format;header('Content-Type: '.($format==='pdf'?'application/pdf':'application/vnd.openxmlformats-officedocument.wordprocessingml.document'));header('Content-Disposition: attachment; filename="'.$name.'"');header('Content-Length: '.strlen($bytes));echo $bytes;exit;
 }
}
