<?php
declare(strict_types=1);
require_once __DIR__.'/QuoteProposal.php';

/** All formats consume these public blocks, never a costing snapshot or live rate. */
final class ProposalOutput {
 public static function blocks(array $s):array {
  if(isset($s['presentation']['blocks']))return $s['presentation']['blocks'];
  $p=$s['presentation']??[];$c=$p['settings']??[];$template=$c['template']??'VTA_STANDARD_B2B';$white=$template==='VTA_B2B_WHITE_LABEL';$b2b=str_contains($template,'B2B');
  $document=$c['document']??[];
  $brand=$white?($c['brand_name']??'Partner'): 'Vietnam Travel Advisor';$b=[['type'=>'brand','text'=>$brand],['type'=>'title','text'=>(string)($s['tour_name']??'Proposal')],['type'=>'text','text'=>($s['quote_ref']??'').' · V'.($s['version_no']??'').' · '.($s['start_date']??'').' – '.($s['end_date']??'')]];
  $media=function(string $role,string $day='')use(&$b,$p){foreach($p['media']??[] as $m)if($m['role']===$role&&$m['day_key']===$day)$b[]=['type'=>'image','asset_id'=>(int)$m['asset_id'],'caption'=>$m['caption'],'width'=>$m['width'],'height'=>$m['height']];};
  $text=function(string $heading,string $content)use(&$b){if(trim($content)!==''){$b[]=['type'=>'heading','text'=>$heading];$b[]=['type'=>'text','text'=>$content];}};
  $table=function(string $heading,array $headers,array $rows)use(&$b){$b[]=['type'=>'heading','text'=>$heading];$b[]=['type'=>'table','headers'=>$headers,'rows'=>$rows];};
  if(!empty($document['title']))$b[1]['text']=$document['title'];
  $rich=function(array $blocks)use(&$b){foreach($blocks as $x){if($x['type']==='table'){$rows=$x['rows'];$head=array_shift($rows);$flat=fn($r)=>implode('',array_column($r,'text'));$b[]=['type'=>'table','headers'=>array_map($flat,$head),'rows'=>array_map(fn($row)=>array_map($flat,$row),$rows),'rich_headers'=>$head,'rich_rows'=>$rows,'document_table'=>true];}else{$b[]=['type'=>$x['type']==='heading'?'heading':'text','text'=>QuoteProposal::blockText([$x]),'rich'=>$x];}}};
  $docSection=function(string $key,string $heading,string $fallback='')use(&$b,$document,$rich,$text):void{if(array_key_exists($key,$document['sections']??[])){$blocks=$document['sections'][$key];if($blocks){$b[]=['type'=>'heading','text'=>$heading];$rich($blocks);}}else $text($heading,$fallback);};
  if($white)$media('LOGO');$media('COVER');
  foreach($c['sections']??QuoteProposal::SECTIONS as $section){switch($section){
   case 'briefing':
    $modes=implode(' / ',array_unique(array_filter(array_column($s['options']??[],'costing_mode'))));
    $days=count($s['schedule']??[]);$rows=[['Tour type',$modes?:'Tour'],['Guests',(string)($s['total_guests']??0).' total / '.($s['paying_pax']??0).' paying / '.($s['foc']??0).' FOC'],['Duration',$days.' days'],['Travel date',($s['start_date']??'').' – '.($s['end_date']??'')],['Tour code',$s['quote_ref']??''],['Hotel / Cruise',implode(' / ',array_unique(array_map(fn($o)=>($o['hotel_level']??'').' hotel + '.($o['cruise_level']??'N/A').' cruise',$s['options']??[])))]];
    if($b2b)foreach(['agent_company'=>'Agent / Company','contact_person'=>'Contact Person','market'=>'Market'] as $key=>$label)if(!empty($c[$key]))$rows[]=[$label,$c[$key]];
    $b[]=['type'=>'heading','text'=>'Briefing'];foreach($rows as [$label,$value])$b[]=['type'=>'text','text'=>$label.': '.$value];if(isset($document['sections']['briefing']))$rich($document['sections']['briefing']);elseif(!empty($c['briefing']))$b[]=['type'=>'text','text'=>$c['briefing']];break;
   case 'highlights':$docSection('highlights',$b2b?'Highlights':"Why you'll love this trip",$c['highlights']??'');break;
   case 'schedule':$table('Schedule Summary',['Day','Date','Journey','Meals','Overnight'],array_map(fn($d)=>[(string)$d['day'],$d['date'],$d['title'],$d['meals'],$d['overnight']],$s['schedule']??[]));break;
   case 'price':
    if(isset($s['commercial'])){
     $commercial=$s['commercial'];$groups=[];$mix=[];
     foreach($commercial['cells'] as $cell){
      if(($c['pricing_display']??'')==='SELECTED_OPTION'&&(int)$cell['variant_id']!==(int)($c['selected_variant_id']??0))continue;
      $value=$cell['currency'].' '.number_format((float)$cell['selling_per_pax'],2).($cell['recommended']?' · Recommended':'');
      $band=$cell['pax_min']===$cell['pax_max']?(string)$cell['pax_min']:$cell['pax_min'].'–'.$cell['pax_max'];
      $hotel=rtrim((string)$cell['hotel_level'],'*★');$cruise=rtrim((string)($cell['cruise_level']??''),'*★');
      if(in_array($hotel,['3','4','5'],true)&&($cruise===$hotel||$cruise===''))$groups[$cell['mode']][$band][$hotel]=$value;
      else $mix[]=[$band,$cell['mode'],$hotel.'★',$cruise!==''?$cruise.'★':'N/A',$value,$cell['label']];
     }
     foreach($groups as $mode=>$bands){$rows=[];foreach($bands as $band=>$levels)$rows[]=[$band,$levels['3']??'—',$levels['4']??'—',$levels['5']??'—','Per paying guest'];$table(($b2b?'Best Price Offer':'Choose Your Stay').' · '.$mode,['Pax','3★','4★','5★','Price basis'],$rows);}
     if($mix)$table('Custom Mix',['Pax','Mode','Hotel','Cruise','Per paying guest','Option'],$mix);
     if(!$groups&&!$mix)$b[]=['type'=>'text','text'=>'No commercial option selected.'];
     $text('Quote validity',$commercial['valid_until']??'');
     $b[]=['type'=>'text','text'=>'Prices apply to the offered paying-pax bands. Final confirmation requires an exact guest profile review.'];
     if($b2b)foreach($commercial['cells'] as $cell)if((float)($cell['commission_pct']??0)>0){$b[]=['type'=>'text','text'=>$cell['label'].': net '.$cell['currency'].' '.$cell['net_per_pax'].' per paying guest; agent commission '.$cell['commission_pct'].'%.'];break;}
     if(!$b2b)foreach($commercial['cells'] as $cell){$b[]=['type'=>'text','text'=>'Deposit '.$cell['deposit_pct'].'%; balance payable under the payment terms.'];break;}
     break;
    }
    $options=$s['options']??[];$display=$c['pricing_display']??'NET';if($display==='SELECTED_OPTION')$options=array_values(array_filter($options,fn($o)=>(int)($o['variant_id']??$o['id'])===(int)$c['selected_variant_id']));
    $heading=$b2b?'Best Price Offer':'Choose Your Stay · Price';
    if($display==='PAX_BAND')$heading.=' · Exact '.($s['paying_pax']??0).' paying pax';
    elseif($display==='PRIVATE_SIC')$heading.=' · PRIVATE / SIC / HYBRID';
    elseif($b2b&&$display==='NET')$heading.=' · Net Group Rate';
    $table($heading,['Option','Mode','Hotel','Cruise','Per paying guest','Group total'],array_map(fn($o)=>[$o['label']??'',$o['costing_mode']??'',str_replace('*','★',$o['hotel_level']??''),!empty($o['cruise_level'])?$o['cruise_level'].'★':'N/A',($o['currency']??'USD').' '.number_format((float)($o['selling_per_pax']??0),2),($o['currency']??'USD').' '.number_format((float)($o['total_selling']??0),2)],$options));
    if(!$options)$b[]=['type'=>'text','text'=>'Price pending reviewed rates.'];
    if($display==='PAX_BAND')$b[]=['type'=>'text','text'=>'This offer applies to the exact guest profile above. Additional pax-band scenarios require separately reviewed costing.'];
    $text('Quote validity',$c['quote_valid_until']??'');break;
   case 'hotel':case 'cruise':
    $type=strtoupper($section);$rows=array_values(array_filter($c['accommodation']??[],fn($r)=>$r['type']===$type));
    if($rows)$table($section==='hotel'?'Hotel List':'Halong Cruise List',['Destination','3★','4★','5★','Nights'],array_map(fn($r)=>[$r['destination'],$r['three_star'],$r['four_star'],$r['five_star'],(string)$r['nights']],$rows));
    if($section==='hotel'&&!empty($document['sections']['services']))$docSection('services','Services / Accommodation');$media($type);$media($type.'_GALLERY');break;
   case 'itinerary':
    $b[]=['type'=>'heading','text'=>'Detailed Itinerary'];foreach($s['schedule']??[] as $i=>$d){$day=$p['days'][$i]??[];$key=$day['key']??'';$f=$day['fields']??[];
     $b[]=['type'=>'heading','text'=>'Day '.($i+1).' · '.($d['date']??'').' · '.($d['title']??'')];$media('DAY_HERO',$key);if(isset($document['days'][$key]))$rich($document['days'][$key]);else $b[]=['type'=>'text','text'=>(string)($d['description']??'')];
     foreach(['route'=>'Route','destination'=>'Destination','activities'=>'Activities','transport_mode'=>'Transport','hotel'=>'Hotel','cruise'=>'Cruise','public_notes'=>'Notes'] as $field=>$label)if(!empty($f[$field]))$b[]=['type'=>'text','text'=>$label.': '.$f[$field]];
     $b[]=['type'=>'text','text'=>'Meals: '.($d['meals']??'').' · Overnight: '.($d['overnight']??'')];$media('DAY_GALLERY',$key);foreach(['HOTEL','HOTEL_GALLERY','CRUISE','CRUISE_GALLERY','SERVICE'] as $role)$media($role,$key);
    }$media('SERVICE');break;
   case 'included':$docSection('included','Included',$s['included']??'');break;
   case 'excluded':$docSection('excluded','Excluded',$s['excluded']??'');break;
   case 'children':$docSection('children','Children Policy',$c['children_policy']??'');break;
   case 'payment':if(isset($s['commercial']))$text('Payment Terms',implode("\n",array_unique(array_column($s['commercial']['cells'],'payment_terms'))));else $docSection('payment','Payment Terms',($c['payment_terms']??'')?:($s['terms']??''));break;
   case 'cancellation':if(isset($s['commercial']))$text('Cancellation Policy',implode("\n",array_unique(array_column($s['commercial']['cells'],'cancellation_policy'))));else $docSection('cancellation','Cancellation Policy',$c['cancellation_policy']??'');break;
   case 'notes':$docSection('terms','Terms & Conditions');$docSection('notes','Important Notes',$c['important_notes']??'');break;
   case 'contact':$text('Contact Details',trim($brand."\n".($c['contact_email']??'')."\n".($c['contact_phone']??'')."\n".($c['contact_address']??'')));if(!$b2b)$b[]=['type'=>'cta','text'=>($c['cta_label']??'')?:'Book Now / Request Change','url'=>($c['cta_url']??'')?:'#contact'];break;
  }}return $b;
 }
 public static function html(array $s,callable $imageUrl,bool $draft=false):string{
  if(isset($s['presentation']['public_html'])){$html=preg_replace_callback('/@@MEDIA_(\d+)@@/',fn($m)=>htmlspecialchars($imageUrl((int)$m[1]),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'),$s['presentation']['public_html']);return $draft?str_replace('<main>','<main><div class="draft">DRAFT · Review before sending</div>',$html):$html;}
  $e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');$template=$s['presentation']['settings']['template']??'VTA_STANDARD_B2B';$theme=match($template){'VTA_EXPLORER_B2C'=>['#087e8b','#eff9f8'],'VTA_PREMIUM_B2C'=>['#80612a','#f7f3ea'],'VTA_B2B_WHITE_LABEL'=>['#34485c','#f5f7fa'],default=>['#163b60','#eef4f9']};if($template==='VTA_B2B_WHITE_LABEL')$theme[0]=$s['presentation']['settings']['brand_color']??$theme[0];$lang=($s['document_language']??'en')==='vi'?'vi':'en';
  $html='<!doctype html><html lang="'.$lang.'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.$e($s['tour_name']??'Proposal').'</title><style>body{font:15px/1.65 Arial,sans-serif;color:#233442;background:#edf1f4;margin:0}main{max-width:980px;margin:24px auto;background:white;padding:42px;border-top:8px solid '.$theme[0].'}h1{font-size:34px;line-height:1.2;color:'.$theme[0].'}h2{color:'.$theme[0].';font-size:22px;margin-top:30px}.brand{letter-spacing:.08em;font-weight:bold;text-transform:uppercase}.draft{background:#fff3c8;padding:10px;text-align:center}p{white-space:pre-line}.table-scroll{overflow:auto}table{width:100%;border-collapse:collapse;font-size:13px}th{background:'.$theme[1].'}td,th{padding:10px;border-bottom:1px solid #dce4ec;text-align:left;vertical-align:top}figure{margin:20px 0}img{width:100%;max-height:'.($template==='VTA_PREMIUM_B2C'?'560':'410').'px;object-fit:cover;border-radius:8px}figcaption{color:#5f6d7a;font-size:12px}.cta{display:inline-block;background:'.$theme[0].';color:white;padding:12px 22px;text-decoration:none;border-radius:6px}footer{margin-top:30px;border-top:1px solid #dce4ec;padding-top:16px}@media(max-width:600px){main{margin:0;padding:20px}h1{font-size:27px}}@media print{body{background:white}main{margin:0;padding:10mm;max-width:none}h2{break-after:avoid}figure,tr{break-inside:avoid}.draft{display:block}}</style></head><body><main>';
  $runs=function(array $r)use($e):string{$out='';foreach($r as $x){$v=nl2br($e($x['text']),false);if($x['bold'])$v='<strong>'.$v.'</strong>';if($x['italic'])$v='<em>'.$v.'</em>';$out.=$v;}return $out;};
  if($draft)$html.='<div class="draft">DRAFT · Review before sending</div>';foreach(self::blocks($s) as $b){$t=$b['type'];if(in_array($t,['brand','title','heading','text'],true)){$tag=match($t){'title'=>'h1','heading'=>'h2',default=>'p'};if(($b['rich']['type']??'')==='list'){$tag=$b['rich']['ordered']?'ol':'ul';$html.='<'.$tag.'>';foreach($b['rich']['items'] as $item)$html.='<li>'.$runs($item).'</li>';$html.='</'.$tag.'>';}else $html.='<'.$tag.($t==='brand'?' class="brand"':'').'>'.(isset($b['rich']['runs'])?$runs($b['rich']['runs']):$e($b['text'])).'</'.$tag.'>';}
   elseif($t==='image')$html.='<figure><img src="'.$e($imageUrl($b['asset_id'])).'" alt="'.$e($b['caption']).'"><figcaption>'.$e($b['caption']).'</figcaption></figure>';
   elseif($t==='table'){$html.='<div class="table-scroll"><table><thead><tr>';foreach($b['headers'] as $i=>$v)$html.='<th>'.(isset($b['rich_headers'][$i])?$runs($b['rich_headers'][$i]):$e($v)).'</th>';$html.='</tr></thead><tbody>';foreach($b['rows'] as $j=>$row){$html.='<tr>';foreach($row as $i=>$v)$html.='<td>'.(isset($b['rich_rows'][$j][$i])?$runs($b['rich_rows'][$j][$i]):$e($v)).'</td>';$html.='</tr>';}$html.='</tbody></table></div>';}
   elseif($t==='cta')$html.='<p><a id="contact" class="cta" href="'.$e($b['url']).'" rel="noopener noreferrer">'.$e($b['text']).'</a></p>';
  }return $html.'<footer>'.$e(($s['presentation']['settings']['brand_mode']??'VTA')==='WHITE_LABEL'?($s['presentation']['settings']['brand_name']??'Partner'):'Vietnam Travel Advisor').' · '.$e($s['quote_ref']??'').'</footer></main></body></html>';
 }
 public static function pdf(array $s,array $cfg,callable $imagePath,bool $draft=false):string{
  require_once __DIR__.'/../vendor/tfpdf/font/unifont/ttfonts.php';require_once __DIR__.'/../vendor/tfpdf/tfpdf.php';
  $cache=MediaLibrary::directory($cfg).'/pdf-fonts';if(!is_dir($cache.'/unifont')&&!mkdir($cache.'/unifont',0770,true)&&!is_dir($cache.'/unifont'))throw new RuntimeException('PDF font cache unavailable');RuntimeGuard::privatePath($cache);$font=$cache.'/unifont/DejaVuSans.ttf';if(!is_file($font)&&!copy(__DIR__.'/../vendor/tfpdf/font/unifont/DejaVuSans.ttf',$font))throw new RuntimeException('PDF font unavailable');
  $brand=($s['presentation']['settings']['brand_mode']??'VTA')==='WHITE_LABEL'?($s['presentation']['settings']['brand_name']??'Partner'):'Vietnam Travel Advisor';
  $pdf=new class($cache,$brand.' · '.($s['quote_ref']??'')) extends tFPDF {private string $footer;public function __construct(string $cache,string $footer){parent::__construct();$this->fontpath=$cache.'/';$this->footer=$footer;}public function Footer(){$this->SetY(-12);$this->SetFont('VTA','',8);$this->SetTextColor(100,110,120);$this->Cell(0,5,$this->footer.' · '.$this->PageNo(),0,0,'R');}};
  $pdf->AddFont('VTA','','DejaVuSans.ttf',true);$pdf->SetAutoPageBreak(true,18);$pdf->SetMargins(18,18,18);$pdf->AddPage();$pdf->SetTitle($s['tour_name']??'Proposal',true);
  if($draft){$pdf->SetFont('VTA','',10);$pdf->SetTextColor(150,90,0);$pdf->MultiCell(0,7,'DRAFT · Review before sending');}
  $accent=match($s['presentation']['settings']['template']??''){'VTA_PREMIUM_B2C'=>[128,97,42],'VTA_EXPLORER_B2C'=>[8,126,139],default=>[20,55,85]};
  if(($s['presentation']['settings']['brand_mode']??'')==='WHITE_LABEL'){$hex=ltrim($s['presentation']['settings']['brand_color']??'#163b60','#');$accent=[hexdec(substr($hex,0,2)),hexdec(substr($hex,2,2)),hexdec(substr($hex,4,2))];}
  $blocks=array_values(array_filter(self::blocks($s),fn($b)=>$b['type']!=='text'||trim($b['text'])!==''));
  foreach($blocks as $index=>$b){$type=$b['type'];if($type==='heading'){$reserve=15;$look=$index+1;while(($blocks[$look]['type']??'')==='heading'){$reserve+=15;$look++;}$next=$blocks[$look]['type']??'';$reserve+=$next==='image'?110:($next==='table'?40:35);if($pdf->GetY()+$reserve>277)$pdf->AddPage();}if($type==='image'){$w=174;$h=min(95,$w*$b['height']/$b['width']);$w=$h*$b['width']/$b['height'];if($pdf->GetY()+$h+12>277)$pdf->AddPage();$pdf->Image($imagePath($b['asset_id']),18,$pdf->GetY(),$w,$h,'JPG');$pdf->SetY($pdf->GetY()+$h+2);$pdf->SetFont('VTA','',9);$pdf->MultiCell(0,5,$b['caption']);$pdf->Ln(3);}
   elseif($type==='table'){
    $widths=!empty($b['document_table'])?array_fill(0,count($b['headers']),174/count($b['headers'])):(count($b['headers'])===6?[43,22,17,17,40,35]:($b['headers'][0]==='Day'?[16,27,65,25,41]:[31,38,38,42,25]));
    // Measure and paint exactly the same lines. MultiCell's second wrapping pass
    // can otherwise overflow a row whose height was measured independently.
    $wrap=function(string $text,float $width)use($pdf):array{$out=[];foreach(explode("\n",$text) as $line){$part='';foreach(preg_split('//u',$line,-1,PREG_SPLIT_NO_EMPTY) as $char){if($part!==''&&$pdf->GetStringWidth($part.$char)>$width){$space=mb_strrpos($part,' ');if($space!==false&&$space>0){$out[]=mb_substr($part,0,$space);$part=mb_substr($part,$space+1);}else{$out[]=$part;$part='';}}$part.=$char;}$out[]=$part;}return $out;};
    $lines=function(array $cells)use($pdf,$widths,$wrap):array{$pdf->SetFont('VTA','',9);$out=[];foreach($cells as $i=>$cell)$out[]=$wrap((string)$cell,$widths[$i]-4);return $out;};
    $row=function(array $texts,bool $header=false)use($pdf,$widths,$accent):void{$pdf->SetFont('VTA','',9);$height=max(10,5.5*max(array_map('count',$texts))+4);$y=$pdf->GetY();$x=18;$pdf->SetDrawColor(210,220,230);$pdf->SetFillColor(239,245,249);$pdf->SetTextColor(...($header?$accent:[35,50,65]));foreach($texts as $i=>$text){$pdf->Rect($x,$y,$widths[$i],$height,$header?'DF':'D');foreach($text as $j=>$line){$pdf->SetXY($x+2,$y+2+$j*5.5);$pdf->Cell($widths[$i]-4,5.5,$line);}$x+=$widths[$i];}$pdf->SetXY(18,$y+$height);};
    $headers=$lines($b['headers']);if($pdf->GetY()+25>277)$pdf->AddPage();$row($headers,true);foreach($b['rows'] as $cells){$texts=$lines($cells);$offset=0;$count=max(array_map('count',$texts));while($offset<$count){$available=(int)floor((277-$pdf->GetY()-4)/5.5);$remaining=$count-$offset;if($available<1||($offset===0&&$remaining>$available&&$remaining<=35)){$pdf->AddPage();$row($headers,true);$available=(int)floor((277-$pdf->GetY()-4)/5.5);}$take=min($remaining,$available);$chunk=array_map(fn($text)=>array_slice($text,$offset,$take),$texts);$row($chunk);$offset+=$take;if($offset<$count){$pdf->AddPage();$row($headers,true);}}}$pdf->Ln(4);
   }else{$size=match($type){'title'=>23,'heading'=>15,'brand'=>12,default=>10};$pdf->SetFont('VTA','',$size);$pdf->SetTextColor(...(in_array($type,['title','heading','brand'],true)?$accent:[35,50,65]));if($type==='heading')$pdf->Ln(4);$text=$b['text'].($type==='cta'&&$b['url']!==''?' · '.$b['url']:'');$pdf->MultiCell(0,$type==='title'?11:7,$text);$pdf->Ln(2);}
  }return $pdf->Output('S');
 }
 public static function docx(array $s,callable $imagePath,bool $draft=false):string{
  if(!class_exists('ZipArchive'))throw new RuntimeException('PHP ZipArchive required for DOCX');$e=fn($v)=>htmlspecialchars((string)$v,ENT_XML1|ENT_QUOTES,'UTF-8');$paragraph=function(string $text,string $style='Normal')use($e){$runs='';foreach(explode("\n",$text) as $i=>$line)$runs.=($i?'<w:r><w:br/></w:r>':'').'<w:r><w:t xml:space="preserve">'.$e($line).'</w:t></w:r>';return '<w:p><w:pPr><w:pStyle w:val="'.$style.'"/></w:pPr>'.$runs.'</w:p>';};
  $richParagraph=function(array $runs,string $style='Normal')use($e){$xml='';foreach($runs as $run){$props=(!empty($run['bold'])?'<w:b/>':'').(!empty($run['italic'])?'<w:i/>':'');foreach(explode("\n",$run['text']) as $i=>$line)$xml.=($i?'<w:r><w:br/></w:r>':'').'<w:r><w:rPr>'.$props.'</w:rPr><w:t xml:space="preserve">'.$e($line).'</w:t></w:r>';}return '<w:p><w:pPr><w:pStyle w:val="'.$style.'"/></w:pPr>'.$xml.'</w:p>';};
  $tmp=tempnam(sys_get_temp_dir(),'vta-docx-');if($tmp===false)throw new RuntimeException('Cannot create DOCX');$zip=new ZipArchive();try{if($zip->open($tmp,ZipArchive::OVERWRITE)!==true)throw new RuntimeException('Cannot create DOCX ZIP');$xml='';$relationships=[];$images=[];$drawing=1;if($draft)$xml.=$paragraph('DRAFT · Review before sending','Heading2');
   foreach(self::blocks($s) as $b){if($b['type']==='image'){$id=$b['asset_id'];if(!isset($images[$id])){$name='image'.$id.'.jpg';$zip->addFile($imagePath($id),'word/media/'.$name);$rid='rIdImage'.$id;$relationships[]='<Relationship Id="'.$rid.'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/'.$name.'"/>';$images[$id]=$rid;}$cx=5943600;$cy=(int)min(3429000,$cx*$b['height']/$b['width']);$cx=(int)($cy*$b['width']/$b['height']);$xml.='<w:p><w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="'.$cx.'" cy="'.$cy.'"/><wp:docPr id="'.$drawing++.'" name="Photo" descr="'.$e($b['caption']).'"/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="0" name="Photo"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="'.$images[$id].'"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="'.$cx.'" cy="'.$cy.'"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>'.$paragraph($b['caption']);}
    elseif($b['type']==='table'){$xml.='<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/><w:tblBorders><w:bottom w:val="single" w:sz="4" w:color="DCE4EC"/><w:insideH w:val="single" w:sz="4" w:color="DCE4EC"/></w:tblBorders></w:tblPr>';foreach([$b['headers'],...$b['rows']] as $i=>$row){$richRow=$i===0?($b['rich_headers']??[]):($b['rich_rows'][$i-1]??[]);$xml.='<w:tr>'.($i===0?'<w:trPr><w:tblHeader/></w:trPr>':'');foreach($row as $j=>$v)$xml.='<w:tc><w:tcPr>'.($i===0?'<w:shd w:fill="EEF4F9"/>':'').'</w:tcPr>'.(isset($richRow[$j])?$richParagraph($richRow[$j]):$paragraph((string)$v)).'</w:tc>';$xml.='</w:tr>';}$xml.='</w:tbl>';}
    elseif(isset($b['rich']['runs']))$xml.=$richParagraph($b['rich']['runs'],$b['type']==='heading'?'Heading1':'Normal');
    elseif(($b['rich']['type']??'')==='list')foreach($b['rich']['items'] as $i=>$item)$xml.=$richParagraph([['text'=>$b['rich']['ordered']?($i+1).'. ':'• ','bold'=>false,'italic'=>false],...$item]);
    else $xml.=$paragraph($b['text'].($b['type']==='cta'?' · '.$b['url']:''),match($b['type']){'title'=>'Title','heading'=>'Heading1','brand'=>'Heading2',default=>'Normal'});
   }
   $document='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><w:body>'.$xml.'<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1000" w:right="1000" w:bottom="1000" w:left="1000"/></w:sectPr></w:body></w:document>';
   $zip->addFromString('word/document.xml',$document);$zip->addFromString('word/_rels/document.xml.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdStyles" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>'.implode('',$relationships).'</Relationships>');
   $color=match($s['presentation']['settings']['template']??''){'VTA_PREMIUM_B2C'=>'80612A','VTA_EXPLORER_B2C'=>'087E8B','VTA_B2B_WHITE_LABEL'=>ltrim($s['presentation']['settings']['brand_color']??'#163b60','#'),default=>'163B60'};
   $styles='<?xml version="1.0"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:sz w:val="22"/></w:rPr></w:rPrDefault></w:docDefaults>';foreach(['Normal'=>22,'Title'=>48,'Heading1'=>30,'Heading2'=>24] as $name=>$size)$styles.='<w:style w:type="paragraph" w:styleId="'.$name.'"><w:name w:val="'.$name.'"/><w:pPr><w:spacing w:after="140"/>'.($name!=='Normal'?'<w:keepNext/>':'').'</w:pPr><w:rPr><w:sz w:val="'.$size.'"/>'.($name!=='Normal'?'<w:b/><w:color w:val="'.$e($color).'"/>':'').'</w:rPr></w:style>';$zip->addFromString('word/styles.xml',$styles.'</w:styles>');
   $zip->addFromString('[Content_Types].xml','<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="jpg" ContentType="image/jpeg"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>');$zip->addFromString('_rels/.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');$zip->close();return (string)file_get_contents($tmp);
  }finally{if(is_file($tmp))unlink($tmp);}
 }
 public static function respond(string $format,array $s,array $cfg,callable $imageUrl,callable $imagePath,bool $draft):never{
  header('Cache-Control: private, no-store');header("Content-Security-Policy: default-src 'none'; img-src 'self'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'self'");header('Referrer-Policy: no-referrer');header('X-Content-Type-Options: nosniff');header('X-Robots-Tag: noindex, nofollow');
  if($format==='html'){header('Content-Type: text/html; charset=utf-8');echo self::html($s,$imageUrl,$draft);exit;}
  $bytes=$format==='pdf'?self::pdf($s,$cfg,$imagePath,$draft):self::docx($s,$imagePath,$draft);$name=preg_replace('/[^A-Za-z0-9_-]/','_',$s['quote_ref']??'Proposal').($draft?'_DRAFT':'').'.'.$format;header('Content-Type: '.($format==='pdf'?'application/pdf':'application/vnd.openxmlformats-officedocument.wordprocessingml.document'));header('Content-Disposition: attachment; filename="'.$name.'"');header('Content-Length: '.strlen($bytes));echo $bytes;exit;
 }
}
