<?php
declare(strict_types=1);
require_once __DIR__.'/MediaLibrary.php';

/** Opt-in presentation over a single quote. Only explicit public fields enter output. */
final class QuoteProposal {
 public const TEMPLATES=['VTA_STANDARD_B2B'=>'VTA Standard B2B','VTA_B2B_WHITE_LABEL'=>'VTA B2B White Label','VTA_EXPLORER_B2C'=>'VTA Explorer B2C','VTA_PREMIUM_B2C'=>'VTA Premium B2C'];
 private static function q(PDO $db,string $s,array $a=[]):PDOStatement{return MediaLibrary::q($db,$s,$a);}
 private static function json($v):string{return MediaLibrary::json($v);}
 public static function signature(array $d):string{$clean=[];foreach(['date','title','description','meals','overnight'] as $k)$clean[$k]=(string)($d[$k]??'');return hash('sha256',self::json($clean));}
 public static function settings(array $b):array{
  $template=$b['template']??'VTA_STANDARD_B2B';if(!isset(self::TEMPLATES[$template]))throw new InvalidArgumentException('Choose a proposal template');$s=['template'=>$template];
  foreach(['briefing','highlights','children_policy','payment_terms','cancellation_policy','important_notes'] as $k)$s[$k]=MediaLibrary::text($b[$k]??'',12000);
  foreach(['agent_company','contact_person','market','quote_valid_until','brand_name','contact_email','contact_phone','cta_label','cta_url'] as $k)$s[$k]=MediaLibrary::text($b[$k]??'',500);
  if($s['quote_valid_until']!=='')ScheduleImport::date($s['quote_valid_until']);if($s['contact_email']!==''&&!filter_var($s['contact_email'],FILTER_VALIDATE_EMAIL))throw new InvalidArgumentException('Valid contact email required');
  if($s['cta_url']!==''&&!preg_match('#^https://[^\s<>"\x00-\x1f]+$#D',$s['cta_url']))throw new InvalidArgumentException('CTA must be an HTTPS URL');
  if($template==='VTA_B2B_WHITE_LABEL'&&$s['brand_name']==='')throw new InvalidArgumentException('White-label brand name required');
  $rows=$b['accommodation']??[];if(!is_array($rows)||!array_is_list($rows)||count($rows)>50)throw new InvalidArgumentException('Maximum 50 accommodation rows');$s['accommodation']=[];
  foreach($rows as $r){if(!is_array($r)||!in_array($r['type']??'',['HOTEL','CRUISE'],true))throw new InvalidArgumentException('Accommodation type required');$n=$r['nights']??0;if(!is_numeric($n)||(int)$n!=(float)$n||$n<0||$n>90)throw new InvalidArgumentException('Valid nights required');$row=['type'=>$r['type'],'nights'=>(int)$n];foreach(['destination','three_star','four_star','five_star'] as $k)$row[$k]=MediaLibrary::text($r[$k]??'',500);$s['accommodation'][]=$row;}
  return $s;
 }
 private static function fields(array $b):array{$f=[];foreach(['route','activities','transport_mode','hotel','cruise','public_notes','special_requests'] as $k)$f[$k]=MediaLibrary::text($b[$k]??'',6000);$f['guide_required']=!empty($b['guide_required']);return $f;}
 public static function context(PDO $db,array $u,array $v):array{
  $raw=self::q($db,'SELECT settings_json FROM quote_proposals WHERE quote_version_id=?',[$v['id']])->fetchColumn();$settings=$raw?json_decode($raw,true):self::settings([]);
  $stored=self::q($db,'SELECT * FROM quote_visual_days WHERE quote_version_id=? ORDER BY sort_order',[$v['id']])->fetchAll(PDO::FETCH_ASSOC);$days=[];$used=[];$changed=false;
  foreach(ScheduleImport::normalize(json_decode($v['schedule_json']?:'[]',true)) as $d){$sig=self::signature($d);$matched=null;foreach($stored as $row)if($row['schedule_signature']===$sig&&!isset($used[$row['day_key']])){$matched=$row;break;}$key=$matched?$matched['day_key']:'day_'.bin2hex(random_bytes(12));$used[$key]=true;if(!$matched)$changed=true;$days[]=['key'=>$key,'schedule'=>$d,'fields'=>$matched?json_decode($matched['fields_json'],true):self::fields([])];}
  if(count($stored)!==count($days))$changed=true;$links=self::q($db,'SELECT asset_id,role,day_key,caption,sort_order FROM quote_media_links WHERE quote_version_id=? ORDER BY sort_order,id',[$v['id']])->fetchAll(PDO::FETCH_ASSOC);$orphan=[];foreach($links as $l)if($l['day_key']!==''&&!isset($used[$l['day_key']]))$orphan[]=$l;
  return ['enabled'=>(bool)$raw,'settings'=>$settings,'days'=>$days,'links'=>$links,'needs_day_review'=>$changed&&$raw!==false,'orphan_links'=>$orphan,'immutable'=>in_array($v['version_status'],['SENT','CONFIRMED','SUPERSEDED'],true),'templates'=>self::TEMPLATES];
 }
 public static function assertMutable(PDO $db,array $v):void{if(in_array($v['version_status'],['SENT','CONFIRMED','SUPERSEDED'],true)||self::q($db,'SELECT 1 FROM quote_sent_bundles WHERE quote_version_id=?',[$v['id']])->fetchColumn())throw new DomainException('Issued proposal is immutable; create a revision');}
 public static function invalidate(PDO $db,array $v):void{self::q($db,'DELETE FROM quote_bundle_approvals WHERE quote_version_id=?',[$v['id']]);self::q($db,"UPDATE quote_versions SET version_status='DRAFT',approved_by=NULL,approved_at=NULL WHERE id=?",[$v['id']]);self::q($db,"UPDATE quotes SET status='DRAFT' WHERE id=?",[$v['quote_id']]);}
 public static function save(PDO $db,array $u,int $version,array $b):array{
  $db->beginTransaction();try{$v=QuoteOptions::version($db,(int)$u['company_id'],$version,true);self::assertMutable($db,$v);$settings=self::settings($b['settings']??[]);$days=$b['days']??[];if(!is_array($days)||!array_is_list($days)||count($days)<1||count($days)>90)throw new InvalidArgumentException('One–90 itinerary days required');$schedule=[];$rows=[];$keys=[];
   foreach($days as $i=>$d){if(!is_array($d))throw new InvalidArgumentException('Invalid day');$key=MediaLibrary::text($d['key']??'',80);if(!preg_match('/^day_[A-Za-z0-9_-]{12,76}$/D',$key)||isset($keys[$key]))throw new InvalidArgumentException('Unique stable day key required');$keys[$key]=true;$s=ScheduleImport::normalize([$d['schedule']??[]])[0];$s['day']=$i+1;$schedule[]=$s;$rows[]=['key'=>$key,'schedule'=>$s,'fields'=>self::fields($d['fields']??[])];}
   $links=$b['links']??[];if(!is_array($links)||!array_is_list($links)||count($links)>60)throw new InvalidArgumentException('Maximum 60 images per quote');$valid=[];$unique=[];$single=[];$bytes=0;
   foreach($links as $i=>$l){if(!is_array($l))throw new InvalidArgumentException('Invalid image assignment');$role=$l['role']??'';$key=$l['day_key']??'';if(!in_array($role,['COVER','DAY_HERO','DAY_GALLERY','HOTEL','CRUISE','SERVICE'],true)||!is_string($key)||($key!==''&&!isset($keys[$key]))||($role==='COVER'&&$key!=='')||(in_array($role,['DAY_HERO','DAY_GALLERY'],true)&&$key===''))throw new InvalidArgumentException('Choose a valid image role/day');$a=MediaLibrary::asset($db,$u,(int)($l['asset_id']??0));if($a['status']==='ARCHIVED')throw new DomainException('Archived image cannot be newly assigned');$id=$role.'|'.$key.'|'.$a['id'];if(isset($unique[$id]))throw new InvalidArgumentException('Duplicate image assignment');$unique[$id]=true;$slot=$role.'|'.$key;$single[$slot]=($single[$slot]??0)+1;if((in_array($role,['COVER','DAY_HERO'],true)&&$single[$slot]>1)||($role==='DAY_GALLERY'&&$single[$slot]>3))throw new InvalidArgumentException('Use one cover/day hero and up to three day gallery images');$bytes+=(int)$a['byte_size'];if($bytes>12582912)throw new InvalidArgumentException('Assigned optimized images exceed 12 MB');$valid[]=['asset_id'=>$a['id'],'role'=>$role,'day_key'=>$key,'caption'=>MediaLibrary::text($l['caption']??'',500),'sort_order'=>$i];}
   self::q($db,'DELETE FROM quote_visual_days WHERE quote_version_id=?',[$version]);foreach($rows as $i=>$r)self::q($db,'INSERT INTO quote_visual_days(quote_version_id,day_key,sort_order,schedule_signature,fields_json) VALUES(?,?,?,?,?)',[$version,$r['key'],$i,self::signature($r['schedule']),self::json($r['fields'])]);
   self::q($db,'DELETE FROM quote_media_links WHERE quote_version_id=?',[$version]);foreach($valid as $l)self::q($db,'INSERT INTO quote_media_links(quote_version_id,asset_id,role,day_key,caption,sort_order) VALUES(?,?,?,?,?,?)',[$version,$l['asset_id'],$l['role'],$l['day_key'],$l['caption'],$l['sort_order']]);
   self::q($db,'INSERT INTO quote_proposals(quote_version_id,settings_json,updated_by) VALUES(?,?,?) ON DUPLICATE KEY UPDATE settings_json=VALUES(settings_json),updated_by=VALUES(updated_by)',[$version,self::json($settings),$u['id']]);self::q($db,'UPDATE quote_versions SET schedule_json=? WHERE id=?',[self::json($schedule),$version]);self::invalidate($db,$v);$nv=QuoteOptions::version($db,(int)$u['company_id'],$version);QuoteSmartCosting::refresh($db,$u,$nv);Audit::log($db,(int)$u['company_id'],(int)$u['id'],'VS2_PROPOSAL_SAVED','quote_version',$version,null,['template'=>$settings['template'],'days'=>count($days),'media'=>count($links)]);$out=self::context($db,$u,$nv);$db->commit();return $out;
  }catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
 }
 /** Returns null for legacy quotes, so their approval fingerprints do not change. */
 public static function snapshot(PDO $db,array $v):?array{
  $raw=self::q($db,'SELECT settings_json FROM quote_proposals WHERE quote_version_id=?',[$v['id']])->fetchColumn();if(!$raw)return null;$settings=self::settings(json_decode($raw,true));$days=self::q($db,'SELECT * FROM quote_visual_days WHERE quote_version_id=? ORDER BY sort_order',[$v['id']])->fetchAll(PDO::FETCH_ASSOC);$schedule=ScheduleImport::normalize(json_decode($v['schedule_json']?:'[]',true));if(count($days)!==count($schedule))throw new DomainException('Review visual day assignments after itinerary changes');$publicDays=[];$keys=[];
  foreach($days as $i=>$d){if(!hash_equals($d['schedule_signature'],self::signature($schedule[$i])))throw new DomainException('Review visual day assignments after itinerary changes');$keys[$d['day_key']]=true;$f=json_decode($d['fields_json'],true);unset($f['special_requests']);$publicDays[]=['key'=>$d['day_key'],'fields'=>$f];}
  $media=[];$links=self::q($db,'SELECT l.*,a.company_id,a.status,a.visibility,a.content_sha256,a.width,a.height FROM quote_media_links l JOIN media_assets a ON a.id=l.asset_id WHERE l.quote_version_id=? ORDER BY l.sort_order,l.id',[$v['id']])->fetchAll(PDO::FETCH_ASSOC);
  foreach($links as $l){if((int)$l['company_id']!==(int)$v['company_id']||$l['status']==='ARCHIVED'||($l['visibility']!=='PERSONAL'&&$l['status']!=='APPROVED')||($l['day_key']!==''&&!isset($keys[$l['day_key']])))throw new DomainException('Approve company media and review all image assignments before finalization');$media[]=['asset_id'=>(int)$l['asset_id'],'role'=>$l['role'],'day_key'=>$l['day_key'],'caption'=>$l['caption'],'sha256'=>$l['content_sha256'],'width'=>(int)$l['width'],'height'=>(int)$l['height']];}
  return ['schema'=>'VS2.2','settings'=>$settings,'days'=>$publicDays,'media'=>$media];
 }
 public static function extend(PDO $db,array $v,array $bundle):array{$p=self::snapshot($db,$v);if($p!==null)$bundle['presentation']=$p;return $bundle;}
 public static function copy(PDO $db,int $source,int $target,int $uid):void{
  self::q($db,'INSERT INTO quote_proposals(quote_version_id,settings_json,updated_by) SELECT ?,settings_json,? FROM quote_proposals WHERE quote_version_id=?',[$target,$uid,$source]);
  self::q($db,'INSERT INTO quote_visual_days(quote_version_id,day_key,sort_order,schedule_signature,fields_json) SELECT ?,day_key,sort_order,schedule_signature,fields_json FROM quote_visual_days WHERE quote_version_id=?',[$target,$source]);self::q($db,'INSERT INTO quote_media_links(quote_version_id,asset_id,role,day_key,caption,sort_order) SELECT ?,asset_id,role,day_key,caption,sort_order FROM quote_media_links WHERE quote_version_id=?',[$target,$source]);
 }
 public static function publicQuote(PDO $db,array $v):array{
  $sent=self::q($db,'SELECT public_snapshot_json FROM quote_sent_bundles WHERE quote_version_id=?',[$v['id']])->fetchColumn()?:$v['sent_snapshot_json'];if($sent)return json_decode($sent,true,512,JSON_THROW_ON_ERROR);
  $has=self::q($db,'SELECT 1 FROM quote_options WHERE quote_version_id=?',[$v['id']])->fetchColumn();if($has)return QuoteOptions::publicBundle(QuoteOptions::bundle($db,$v));
  return self::extend($db,$v,['document_language'=>$v['document_language']??'en','quote_ref'=>$v['quote_ref'],'version_no'=>(int)$v['version_no'],'tour_name'=>$v['tour_name'],'start_date'=>$v['start_date'],'end_date'=>$v['end_date'],'total_guests'=>(int)$v['total_guests'],'paying_pax'=>(int)$v['paying_pax'],'foc'=>(int)$v['foc'],'schedule'=>QuoteOptions::publicSchedule(json_decode($v['schedule_json'],true)),'included'=>$v['included_text'],'excluded'=>$v['excluded_text'],'terms'=>$v['terms_text'],'options'=>[['label'=>'Package','hotel_level'=>$v['hotel_level'],'currency'=>$v['selling_currency'],'selling_per_pax'=>$v['selling_per_pax'],'total_selling'=>$v['total_selling']]]]);
 }
 public static function createLink(PDO $db,array $u,int $version,int $days=14):array{
  $db->beginTransaction();try{$v=QuoteOptions::version($db,(int)$u['company_id'],$version,true);if(!in_array($v['version_status'],['SENT','CONFIRMED'],true))throw new DomainException('Send/lock this quote before creating a customer link');$s=self::publicQuote($db,$v);if(empty($s['presentation']))throw new DomainException('Use a VS2.2 proposal before creating a link');if($days<1||$days>90)throw new InvalidArgumentException('Link lifetime must be 1–90 days');$token=bin2hex(random_bytes(32));$expiry=date('Y-m-d H:i:s',time()+$days*86400);self::q($db,'INSERT INTO quote_proposal_links(company_id,quote_version_id,token_hash,expires_at,created_by) VALUES(?,?,?,?,?)',[$u['company_id'],$version,hash('sha256',$token),$expiry,$u['id']]);$id=(int)$db->lastInsertId();Audit::log($db,(int)$u['company_id'],(int)$u['id'],'PROPOSAL_LINK_CREATED','quote_version',$version,null,['link_id'=>$id,'expires_at'=>$expiry]);$db->commit();return ['id'=>$id,'token'=>$token,'expires_at'=>$expiry];}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
 }
 public static function token(PDO $db,string $token):array{if(!preg_match('/^[a-f0-9]{64}$/D',$token))throw new OutOfBoundsException('Proposal unavailable');$r=self::q($db,'SELECT * FROM quote_proposal_links WHERE token_hash=? AND revoked_at IS NULL AND expires_at>?',[hash('sha256',$token),date('Y-m-d H:i:s')])->fetch(PDO::FETCH_ASSOC);if(!$r)throw new OutOfBoundsException('Proposal unavailable');$v=QuoteOptions::version($db,(int)$r['company_id'],(int)$r['quote_version_id']);return ['version'=>$v,'snapshot'=>self::publicQuote($db,$v)];}
 public static function snapshotAsset(PDO $db,array $v,array $snapshot,int $id):array{$found=null;foreach($snapshot['presentation']['media']??[] as $m)if((int)$m['asset_id']===$id)$found=$m;if(!$found)throw new OutOfBoundsException('Proposal image unavailable');$a=self::q($db,'SELECT * FROM media_assets WHERE company_id=? AND id=?',[$v['company_id'],$id])->fetch(PDO::FETCH_ASSOC);if(!$a||!hash_equals($found['sha256'],$a['content_sha256']))throw new OutOfBoundsException('Proposal image unavailable');return $a;}
 public static function handle(string $route,string $method,PDO $db,array $cfg,array $u):void{
  if(!preg_match('#^quote-versions/(\d+)/proposal(?:/(.*))?$#',$route,$m))return;Auth::requirePermission($db,$u,'sales.view');$id=(int)$m[1];$action=$m[2]??'';
  try{$v=QuoteOptions::version($db,(int)$u['company_id'],$id);
   if($method==='GET'&&$action==='')Http::json(['ok'=>true]+self::context($db,$u,$v));
   if($method==='PUT'&&$action===''){Auth::requirePermission($db,$u,'quote.edit');Auth::requirePermission($db,$u,'media.view');Http::json(['ok'=>true]+self::save($db,$u,$id,Http::body()));}
   if($method==='GET'&&preg_match('#^images/(\d+)$#',$action,$im)){$s=self::publicQuote($db,$v);MediaLibrary::stream($cfg,self::snapshotAsset($db,$v,$s,(int)$im[1]));}
   if($method==='GET'&&in_array($action,['html','pdf','docx'],true)){ProposalOutput::respond($action,self::publicQuote($db,$v),$cfg,fn($asset)=>'index.php?route=quote-versions/'.$id.'/proposal/images/'.$asset,fn($asset)=>MediaLibrary::path($cfg,self::snapshotAsset($db,$v,self::publicQuote($db,$v),$asset)),!in_array($v['version_status'],['SENT','CONFIRMED','SUPERSEDED'],true));}
   if($action==='links'&&$method==='POST'){Auth::requirePermission($db,$u,'quote.send');$b=Http::body();Http::json(['ok'=>true]+self::createLink($db,$u,$id,(int)($b['days']??14)),201);}
   if($action==='links'&&$method==='GET'){Auth::requirePermission($db,$u,'quote.send');Http::json(['ok'=>true,'items'=>self::q($db,'SELECT id,expires_at,revoked_at FROM quote_proposal_links WHERE company_id=? AND quote_version_id=? ORDER BY id DESC',[$u['company_id'],$id])->fetchAll(PDO::FETCH_ASSOC)]);}
   if($method==='DELETE'&&preg_match('#^links/(\d+)$#',$action,$lm)){Auth::requirePermission($db,$u,'quote.send');self::q($db,'UPDATE quote_proposal_links SET revoked_at=NOW() WHERE company_id=? AND quote_version_id=? AND id=?',[$u['company_id'],$id,$lm[1]]);Audit::log($db,(int)$u['company_id'],(int)$u['id'],'PROPOSAL_LINK_REVOKED','quote_version',$id,null,['link_id'=>(int)$lm[1]]);Http::json(['ok'=>true]);}
  }catch(OutOfBoundsException $e){Http::json(['ok'=>false,'error'=>'NOT_FOUND'],404);}catch(InvalidArgumentException $e){Http::json(['ok'=>false,'error'=>'VALIDATION','message'=>$e->getMessage()],422);}catch(DomainException $e){Http::json(['ok'=>false,'error'=>'CONFLICT','message'=>$e->getMessage()],409);}
 }
 public static function publicHandle(string $route,string $method,PDO $db,array $cfg):void{
  if($method!=='GET'||!preg_match('#^public-proposals/([a-f0-9]{64})(?:/(images/\d+|pdf|docx))?$#D',$route,$m))return;
  try{$r=self::token($db,$m[1]);$s=$r['snapshot'];$v=$r['version'];$action=$m[2]??'html';if(str_starts_with($action,'images/'))MediaLibrary::stream($cfg,self::snapshotAsset($db,$v,$s,(int)substr($action,7)));$token=$m[1];ProposalOutput::respond($action,$s,$cfg,fn($asset)=>'index.php?route=public-proposals/'.$token.'/images/'.$asset,fn($asset)=>MediaLibrary::path($cfg,self::snapshotAsset($db,$v,$s,$asset)),false);
  }catch(OutOfBoundsException $e){Http::json(['ok'=>false,'error'=>'PROPOSAL_UNAVAILABLE'],404);}
 }
}
