<?php
declare(strict_types=1);
require_once __DIR__.'/BookingIntegrity.php';

/** Intake workflow over existing bookings; confirmed snapshots are read-only sources. */
final class SalesHandover {
    public const CHECKLIST=['customer_confirmed','dates_confirmed','pax_confirmed','composition_reviewed','hotel_confirmed','cruise_confirmed','itinerary_confirmed','inclusions_confirmed','exclusions_confirmed','special_requests_reviewed','payment_terms_confirmed','issues_reviewed'];
    public const CATEGORIES=['HOTEL','TRANSFER','CAR','GUIDE','RESTAURANT','MEAL','CRUISE','TICKET','ACTIVITY','SIC_TOUR','FLIGHT','TRAIN','FERRY','OTHER'];
    private static function q(PDO $db,string $s,array $a=[]): PDOStatement {return QuoteVs2Repository::q($db,$s,$a);}
    /** A public projection of the accepted source, never current draft/cost data. */
    public static function bookingSummary(PDO $db,int $company,int $booking): array {
        $b=self::q($db,'SELECT b.*,q.quote_ref,t.customer_id,t.agent_id,c.full_name customer_name,a.company_name agency_name FROM bookings b JOIN trips t ON t.id=b.trip_id AND t.company_id=b.company_id LEFT JOIN quotes q ON q.id=b.quote_id AND q.company_id=b.company_id LEFT JOIN customers c ON c.id=t.customer_id AND c.company_id=b.company_id LEFT JOIN agents a ON a.id=t.agent_id AND a.company_id=b.company_id WHERE b.company_id=? AND b.id=?',[$company,$booking])->fetch()?:throw new OutOfBoundsException('Booking not found');
        $raw=self::q($db,'SELECT public_snapshot_json FROM booking_quote_snapshots WHERE booking_id=?',[$booking])->fetchColumn();
        if(!$raw)$raw=self::q($db,'SELECT sent_snapshot_json FROM quote_versions WHERE quote_id=? AND version_no=?',[$b['quote_id'],$b['confirmed_quote_version_no']])->fetchColumn();
        $s=$raw?QuoteVs2Repository::decode($raw):[];$option=$s['options'][0]??[];$schedule=empty($s['schedule'])?[]:QuoteOptions::publicSchedule($s['schedule'],true);
        $out=['quote_id'=>$b['quote_id'],'quote_ref'=>$b['quote_ref'],'quote_version_no'=>$b['confirmed_quote_version_no'],'customer_name'=>$b['customer_name']?:$b['lead_guest_name'],'agency_name'=>$b['agency_name']??'','tour_name'=>$s['tour_name']??'','hotel_level'=>$option['hotel_level']??'','cruise_level'=>$option['cruise_level']??'','selling_currency'=>$b['selling_currency'],'total_selling'=>$b['confirmed_selling'],'schedule'=>$schedule,'included'=>$s['included']??'','excluded'=>$s['excluded']??'','terms'=>$s['terms']??'','special_requests'=>$b['special_requests']??'','notes'=>$b['client_promises']??'','can_handover'=>(bool)self::q($db,'SELECT 1 FROM booking_quote_snapshots WHERE booking_id=?',[$booking])->fetchColumn()];
        // Typed document blocks are already sanitized by the proposal snapshot machinery.
        $out['document']=$s['presentation']['settings']['document']??$s['presentation']['document']??null;
        return $out;
    }
    private static function snapshot(PDO $db,int $company,int $booking): array {
        $s=self::q($db,'SELECT s.* FROM booking_quote_snapshots s JOIN bookings b ON b.id=s.booking_id WHERE b.company_id=? AND b.id=?',[$company,$booking])->fetch();if(!$s)throw new OutOfBoundsException('Accepted booking snapshot required');return $s;
    }
    private static function sourceHash(array $s): string {return QuoteVs2Domain::hash([$s['quote_version_id'],$s['source_hash'],$s['internal_snapshot_json'],$s['public_snapshot_json']]);}
    private static function event(PDO $db,array $u,array $h,string $event,string $reason=''): void {
        self::q($db,'INSERT INTO booking_handover_events(booking_id,event,stage,intake_status,reason,actor_id) VALUES(?,?,?,?,?,?)',[$h['booking_id'],$event,$h['stage'],$h['intake_status'],$reason,$u['id']]);Audit::log($db,(int)$u['company_id'],(int)$u['id'],$event,'booking',(int)$h['booking_id'],null,['stage'=>$h['stage'],'intake_status'=>$h['intake_status'],'reason'=>$reason]);
    }
    public static function create(PDO $db,array $u,int $booking): array {
        return QuoteVs2Repository::atomic($db,function()use($db,$u,$booking){BookingIntegrity::lock($db,(int)$u['company_id'],$booking);$old=self::q($db,'SELECT * FROM booking_handovers WHERE booking_id=?',[$booking])->fetch();if($old)return $old;
            $snapshot=self::snapshot($db,(int)$u['company_id'],$booking);$internal=QuoteVs2Repository::decode($snapshot['internal_snapshot_json']);$quote=$internal['quote'];$option=$internal['accepted_option'];$commit=$quote['commercial_commitment']??null;
            self::q($db,"INSERT INTO booking_handovers(booking_id,checklist_json,source_hash,sales_notes,created_by) VALUES(?,'{}',?,'',?)",[$booking,self::sourceHash($snapshot),$u['id']]);
            $guests=$commit['guests']??array_intersect_key($option['snapshot'],array_flip([...QuoteVs2Domain::BASE,...QuoteVs2Domain::PROFILE]));$variant=$option['snapshot']['variant']??['costing_mode'=>'PRIVATE','hotel_level'=>$option['hotel_level'],'cruise_level'=>null];$lines=$option['snapshot']['cost_lines']??[];$byReq=[];foreach($lines as $l)if($l['line_kind']==='SERVICE')$byReq[$l['requirement_id']]=$l;
            $requirements=$quote['requirements']??array_map(fn($l)=>['id'=>null,'category'=>$l['category'],'service_name'=>$l['service_name'],'service_date'=>$l['service_date'],'service_end_date'=>null,'default_quantity_source'=>'TOTAL_GUESTS','service_units'=>(int)$l['qty'],'scope_json'=>'{}','metadata_json'=>'{}','service_mode'=>'BOTH','requirement_state'=>'REQUIRED'],$option['snapshot']['lines']);
            foreach($requirements as $req){$line=$byReq[$req['id']]??null;if(!QuoteVs2Domain::applies($req,$variant,$line))continue;$scope=QuoteVs2Repository::decode($req['scope_json']);$metadata=QuoteVs2Repository::decode($req['metadata_json']);$cat=match($req['category']){'TRANSPORT'=>'TRANSFER','ATTRACTION'=>'TICKET','TOUR'=>'SIC_TOUR','FLIGHT_SERVICE'=>'FLIGHT',default=>$req['category']};if(isset($metadata['handover_category'])&&in_array($metadata['handover_category'],self::CATEGORIES,true))$cat=$metadata['handover_category'];if(!in_array($cat,self::CATEGORIES,true))$cat='OTHER';
                $pax=(int)($guests[strtolower($req['default_quantity_source'])]??$guests['total_guests']??0);$qty=(int)($line['resolved_quantity']??$req['service_units']??1);
                $spec=['required_specification'=>array_intersect_key($scope,array_flip(QuoteVs2Domain::OPERATIONAL_SCOPE)),'hotel_level'=>$commit['hotel_level']??$option['hotel_level'],'cruise_level'=>$commit['cruise_level']??$option['cruise_level']??null,'service_units'=>$req['service_units'],'quantity_source'=>$line['quantity_source']??$req['default_quantity_source'],'selected_accommodation'=>$commit['accommodation']??[],'customer_special_requests'=>$metadata['customer_special_requests']??'','meal_cuisine'=>$metadata['cuisine']??'','coverage'=>$line['coverage_state']??'PRICED','itinerary'=>QuoteOptions::publicSchedule($quote['schedule']??[],true),'included'=>$quote['included']??'','excluded'=>$quote['excluded']??'','selling_terms'=>$commit?['currency'=>$commit['selling_currency'],'deposit'=>$commit['pricing']['deposit'],'balance'=>$commit['pricing']['balance']]:[]];
                $sid=self::q($db,'SELECT id FROM booking_services WHERE booking_id=? AND service_name=? AND (service_date=? OR (service_date IS NULL AND ? IS NULL)) ORDER BY id LIMIT 1',[$booking,$req['service_name'],$req['service_date'],$req['service_date']])->fetchColumn()?:null;
                $source=['quote_version_id'=>(int)$snapshot['quote_version_id'],'sent_content_hash'=>$snapshot['source_hash'],'variant_id'=>$option['variant_id']??null,'requirement_id'=>$req['id'],'booking_snapshot_hash'=>self::sourceHash($snapshot)];
                self::q($db,"INSERT INTO booking_handover_services(booking_id,booking_service_id,source_requirement_id,category,service_name,service_date,service_end_date,destination,pax,quantity,specification_json,source_reference_json,sales_notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, '')",[$booking,$sid,$req['id'],$cat,$req['service_name'],$req['service_date'],$req['service_end_date'],QuoteVs2Domain::destination($scope),$pax,$qty,QuoteVs2Repository::json($spec),QuoteVs2Repository::json($source)]);
            }
            $h=self::q($db,'SELECT * FROM booking_handovers WHERE booking_id=?',[$booking])->fetch();self::event($db,$u,$h,'SALES_COMMERCIAL_CONFIRMED');return $h;
        });
    }
    private static function lock(PDO $db,array $u,int $booking,array $b): array {
        BookingIntegrity::lock($db,(int)$u['company_id'],$booking);$h=self::q($db,'SELECT * FROM booking_handovers WHERE booking_id=? FOR UPDATE',[$booking])->fetch()?:throw new DomainException('HANDOVER_NEEDED');
        if(!isset($b['expected_revision'])||QuoteVs2Domain::count($b['expected_revision'])!==(int)$h['revision'])throw new DomainException('STALE_HANDOVER_REVISION');$s=self::snapshot($db,(int)$u['company_id'],$booking);if(!hash_equals($h['source_hash'],self::sourceHash($s)))throw new DomainException('BOOKING_SNAPSHOT_CHANGED');return $h;
    }
    public static function transition(PDO $db,array $u,int $booking,string $action,array $b): array {
        return QuoteVs2Repository::atomic($db,function()use($db,$u,$booking,$action,$b){$h=self::lock($db,$u,$booking,$b);$reason=QuoteVs2Domain::text($b['reason']??'',1000,true);
            if($action==='prepare'){
                if($h['stage']==='HANDED_TO_OPERATIONS')throw new DomainException('RETURN_OR_CHANGE_REQUEST_REQUIRED');$check=$b['checklist']??QuoteVs2Repository::decode($h['checklist_json']);if(!is_array($check)||array_diff(array_keys($check),[...self::CHECKLIST,'flights']))throw new InvalidArgumentException('Invalid handover checklist');$clean=[];foreach(self::CHECKLIST as $key)$clean[$key]=($check[$key]??false)===true;$clean['flights']=$check['flights']??'NOT_PROVIDED';if(!in_array($clean['flights'],['CAPTURED','NOT_PROVIDED'],true))throw new InvalidArgumentException('Flights must be captured if available');
                $notes=QuoteVs2Domain::text($b['sales_notes']??$h['sales_notes'],12000,true);
                foreach($b['services']??[] as $change){$s=self::q($db,'SELECT * FROM booking_handover_services WHERE booking_id=? AND id=?',[$booking,(int)($change['id']??0)])->fetch()?:throw new OutOfBoundsException('Handover service not found');$class=$change['classification']??$s['classification'];$match=$change['match_rule']??$s['match_rule'];$source=$change['source']??$s['source'];
                    if(!in_array($class,['REQUESTED_BY_CUSTOMER','CONFIRMED_BY_SALES','TO_BE_ARRANGED_BY_OPERATIONS'],true)||!in_array($match,['MUST_MATCH','FLEXIBLE_EQUIVALENT_ALLOWED'],true)||!in_array($source,['QUOTE','PROPOSAL','CUSTOMER_MESSAGE','AGENT_MESSAGE','CONTRACT','SALES_NOTE'],true))throw new InvalidArgumentException('Invalid commitment classification');$ref=QuoteVs2Repository::decode($s['source_reference_json']);if(!in_array($source,['QUOTE','PROPOSAL'],true))$ref['external_reference']=QuoteVs2Domain::text($change['external_reference']??'',500);
                    self::q($db,'UPDATE booking_handover_services SET classification=?,match_rule=?,source=?,source_reference_json=?,sales_notes=? WHERE id=?',[$class,$match,$source,QuoteVs2Repository::json($ref),QuoteVs2Domain::text($change['sales_notes']??$s['sales_notes'],2000,true),$s['id']]);
                }
                self::q($db,"UPDATE booking_handovers SET stage='HANDOVER_PREPARATION',checklist_json=?,sales_notes=?,revision=revision+1 WHERE booking_id=?",[QuoteVs2Repository::json($clean),$notes,$booking]);$event='SALES_HANDOVER_PREPARED';
            }elseif($action==='submit'){
                if($h['stage']!=='HANDOVER_PREPARATION')throw new DomainException('PREPARE_HANDOVER_FIRST');$c=QuoteVs2Repository::decode($h['checklist_json']);foreach(self::CHECKLIST as $key)if(($c[$key]??false)!==true)throw new DomainException('HANDOVER_CHECKLIST_INCOMPLETE: '.$key);
                $flights=(int)self::q($db,"SELECT COUNT(*) FROM flights WHERE booking_id=? AND status<>'CANCELLED'",[$booking])->fetchColumn();if($flights&&($c['flights']??'')!=='CAPTURED')throw new DomainException('FLIGHTS_REVIEW_REQUIRED');if(!self::q($db,'SELECT 1 FROM booking_handover_services WHERE booking_id=? LIMIT 1',[$booking])->fetchColumn())throw new DomainException('SERVICE_HANDOVER_NEEDED');
                self::q($db,"UPDATE booking_handovers SET stage='HANDED_TO_OPERATIONS',intake_status='NEW_HANDOVER',submitted_by=?,submitted_at=NOW(),accepted_by=NULL,accepted_at=NULL,revision=revision+1 WHERE booking_id=?",[$u['id'],$booking]);$event='SALES_HANDOVER_SUBMITTED';
            }elseif(in_array($action,['accept','return'],true)){
                if($h['stage']!=='HANDED_TO_OPERATIONS'||$h['intake_status']!=='NEW_HANDOVER')throw new DomainException('NEW_HANDOVER_REQUIRED');
                if($action==='return'){$reason=QuoteVs2Domain::text($b['reason']??'',1000);self::q($db,"UPDATE booking_handovers SET stage='HANDOVER_PREPARATION',intake_status='NEEDS_REVIEW',revision=revision+1 WHERE booking_id=?",[$booking]);$event='OPERATIONS_HANDOVER_RETURNED';}
                else{self::q($db,"UPDATE booking_handovers SET intake_status='READY_TO_BOOK',accepted_by=?,accepted_at=NOW(),revision=revision+1 WHERE booking_id=?",[$u['id'],$booking]);$event='OPERATIONS_HANDOVER_ACCEPTED';}
            }else throw new InvalidArgumentException('Unknown handover transition');
            $h=self::q($db,'SELECT * FROM booking_handovers WHERE booking_id=?',[$booking])->fetch();self::event($db,$u,$h,$event,$reason);return self::context($db,$u,$booking);
        });
    }
    public static function context(PDO $db,array $u,int $booking): array {
        $b=self::q($db,'SELECT id,booking_ref,start_date,end_date,operations_status,readiness_pct,customer_payment_status FROM bookings WHERE company_id=? AND id=?',[$u['company_id'],$booking])->fetch()?:throw new OutOfBoundsException('Booking not found');$h=self::q($db,'SELECT * FROM booking_handovers WHERE booking_id=?',[$booking])->fetch();if(!$h)return ['booking'=>$b,'handover'=>null];
        $services=self::q($db,'SELECT * FROM booking_handover_services WHERE booking_id=? ORDER BY service_date,id',[$booking])->fetchAll();foreach($services as &$s){$s['specification']=QuoteVs2Repository::decode($s['specification_json']);$s['source_reference']=QuoteVs2Repository::decode($s['source_reference_json']);unset($s['specification_json'],$s['source_reference_json']);}unset($s);
        $snapshot=self::snapshot($db,(int)$u['company_id'],$booking);$internal=QuoteVs2Repository::decode($snapshot['internal_snapshot_json']);$commit=$internal['quote']['commercial_commitment']??null;$h['checklist']=QuoteVs2Repository::decode($h['checklist_json']);unset($h['checklist_json']);
        $progress=self::q($db,'SELECT booking_status,COUNT(*) services FROM booking_services WHERE booking_id=? GROUP BY booking_status',[$booking])->fetchAll();$b['payment_summary']=$b['customer_payment_status'];unset($b['customer_payment_status']);
        return ['booking'=>$b,'handover'=>$h,'commitment'=>$commit?PriceMatrix::publicCommitment($commit):null,'services'=>$services,'supplier_progress'=>$progress,'changes'=>self::q($db,'SELECT id,source,description,commercial_impact,status,revision,created_at FROM booking_change_requests WHERE booking_id=? ORDER BY id DESC',[$booking])->fetchAll(),'timeline'=>self::q($db,'SELECT e.*,u.full_name actor FROM booking_handover_events e JOIN users u ON u.id=e.actor_id WHERE e.booking_id=? ORDER BY e.id',[$booking])->fetchAll()];
    }
    public static function changeRequest(PDO $db,array $u,int $booking,array $b,?int $id=null): array {
        return QuoteVs2Repository::atomic($db,function()use($db,$u,$booking,$b,$id){BookingIntegrity::lock($db,(int)$u['company_id'],$booking);
            if($id===null){$description=QuoteVs2Domain::text($b['description']??'',12000);$source=$b['source']??'CUSTOMER_MESSAGE';if(!in_array($source,['QUOTE','PROPOSAL','CUSTOMER_MESSAGE','AGENT_MESSAGE','CONTRACT','SALES_NOTE'],true))throw new InvalidArgumentException('Invalid change source');$services=$b['affected_services']??[];if(!is_array($services)||!array_is_list($services)||count($services)>100)throw new InvalidArgumentException('Invalid affected services');$services=array_map(fn($x)=>QuoteVs2Domain::count($x),$services);foreach($services as $service)if(!self::q($db,'SELECT 1 FROM booking_handover_services WHERE booking_id=? AND id=?',[$booking,$service])->fetchColumn())throw new OutOfBoundsException('Affected service is outside this booking');$impact=$b['commercial_impact']??'UNKNOWN';if(!in_array($impact,['UNKNOWN','KNOWN'],true))throw new InvalidArgumentException('Invalid commercial impact');$detail=QuoteVs2Domain::text($b['impact_description']??'',12000,true);if($impact==='KNOWN'&&$detail==='')throw new InvalidArgumentException('Describe known commercial impact');
                self::q($db,'INSERT INTO booking_change_requests(booking_id,requested_by,source,description,affected_services_json,commercial_impact,impact_description,updated_by) VALUES(?,?,?,?,?,?,?,?)',[$booking,$u['id'],$source,$description,QuoteVs2Repository::json($services),$impact,$detail,$u['id']]);$id=(int)$db->lastInsertId();$event='BOOKING_CHANGE_REQUEST_CREATED';
            }else{$old=self::q($db,'SELECT * FROM booking_change_requests WHERE booking_id=? AND id=? FOR UPDATE',[$booking,$id])->fetch()?:throw new OutOfBoundsException('Change request not found');if(!isset($b['expected_revision'])||(int)$b['expected_revision']!==(int)$old['revision'])throw new DomainException('STALE_CHANGE_REVISION');$allowed=['OPEN'=>['UNDER_REVIEW'],'UNDER_REVIEW'=>['APPROVED','REJECTED'],'APPROVED'=>['IMPLEMENTED'],'REJECTED'=>[],'IMPLEMENTED'=>[]];$status=$b['status']??'';if(!in_array($status,$allowed[$old['status']],true))throw new DomainException('INVALID_CHANGE_TRANSITION');$reason=QuoteVs2Domain::text($b['reason']??'',1000);self::q($db,'UPDATE booking_change_requests SET status=?,revision=revision+1,updated_by=? WHERE id=?',[$status,$u['id'],$id]);$event='BOOKING_CHANGE_REQUEST_'. $status;}
            Audit::log($db,(int)$u['company_id'],(int)$u['id'],$event,'booking_change_request',$id,null,['booking_id'=>$booking,'reason'=>$reason??null]);return self::q($db,'SELECT id,booking_id,source,description,commercial_impact,impact_description,status,revision,created_at FROM booking_change_requests WHERE id=?',[$id])->fetch();
        });
    }
    public static function handle(string $route,string $method,PDO $db,array $u): void {
        if($route==='operations/intake'&&$method==='GET'){Auth::requirePermission($db,$u,'operations.view');$view=$_GET['view']??'NEW_HANDOVERS';$where=match($view){'NEW_HANDOVERS'=>"h.stage='HANDED_TO_OPERATIONS' AND h.intake_status='NEW_HANDOVER'",'NEEDS_REVIEW'=>"h.intake_status='NEEDS_REVIEW'",'READY_TO_BOOK'=>"h.intake_status='READY_TO_BOOK'",'CHANGES_ISSUES'=>"EXISTS(SELECT 1 FROM booking_change_requests c WHERE c.booking_id=b.id AND c.status IN ('OPEN','UNDER_REVIEW','APPROVED'))",'UPCOMING_DEPARTURES'=>"b.start_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 30 DAY)",default=>null};if($where===null)Http::json(['ok'=>false,'error'=>'VALIDATION'],422);Http::json(['ok'=>true,'items'=>self::q($db,"SELECT b.id,b.booking_ref,b.start_date,b.end_date,b.operations_status,b.readiness_pct,h.stage,h.intake_status,h.revision FROM bookings b JOIN booking_handovers h ON h.booking_id=b.id WHERE b.company_id=? AND $where ORDER BY b.start_date,b.id LIMIT 200",[$u['company_id']])->fetchAll()]);}
        if(!preg_match('#^bookings/(\d+)/(handover(?:/(prepare|submit|accept|return))?|change-requests(?:/(\d+))?)$#',$route,$m))return;Auth::requirePermission($db,$u,'booking.view');$booking=(int)$m[1];
        try{if(str_starts_with($m[2],'change-requests')){Auth::requirePermission($db,$u,'booking.change_request_manage');if(in_array($method,['POST','PUT'],true))Http::json(['ok'=>true,'change_request'=>self::changeRequest($db,$u,$booking,Http::body(),isset($m[4])?(int)$m[4]:null)],$method==='POST'?201:200);return;}
            $action=$m[3]??'';if($method==='GET'&&$action==='')Http::json(['ok'=>true]+self::context($db,$u,$booking));if($method!=='POST')return;$b=Http::body();$permission=match($action){'submit'=>'sales.handover_submit','accept'=>'operations.handover_accept','return'=>'operations.handover_return',default=>'sales.handover_create'};Auth::requirePermission($db,$u,$permission);if(in_array($action,['accept','return'],true))Auth::requirePermission($db,$u,'operations.view');if($action===''){self::create($db,$u,$booking);Http::json(['ok'=>true]+self::context($db,$u,$booking),201);}Http::json(['ok'=>true]+self::transition($db,$u,$booking,$action,$b));
        }catch(InvalidArgumentException|JsonException $e){Http::json(['ok'=>false,'error'=>'VALIDATION','message'=>$e->getMessage()],422);}catch(OutOfBoundsException $e){Http::json(['ok'=>false,'error'=>'NOT_FOUND'],404);}catch(DomainException $e){Http::json(['ok'=>false,'error'=>'CONFLICT','message'=>$e->getMessage()],409);}
    }
}
