<?php
declare(strict_types=1);
require_once __DIR__.'/../api/lib/Auth.php';
require_once __DIR__.'/../api/lib/AiChat.php';
$count=0;
function contextCheck(bool $ok,string $label):void {global $count;if(!$ok)throw new RuntimeException($label);$count++;echo "PASS $label\n";}
function contextReject(callable $fn,string $class,string $label):void {try{$fn();}catch(Throwable $e){contextCheck($e instanceof $class,$label);return;}throw new RuntimeException($label.' was accepted');}
$db=new PDO('sqlite::memory:',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$db->exec("CREATE TABLE users(id INTEGER,role_id INTEGER); INSERT INTO users VALUES(7,1),(8,2); CREATE TABLE permissions(id INTEGER PRIMARY KEY,code TEXT); CREATE TABLE role_permissions(role_id INTEGER,permission_id INTEGER); CREATE TABLE user_permissions(user_id INTEGER,permission_id INTEGER,effect TEXT);
CREATE TABLE campaigns(id INTEGER,company_id INTEGER,name TEXT); INSERT INTO campaigns VALUES(1,10,'Family Vietnam'),(2,20,'SECRET OTHER CAMPAIGN');
CREATE TABLE marketing_briefs(company_id INTEGER,campaign_id INTEGER,market TEXT,offer TEXT,audience TEXT,budget TEXT); INSERT INTO marketing_briefs VALUES(10,1,'India','Vietnam journey','Families','SECRET BUDGET');
CREATE TABLE marketing_content(id INTEGER,company_id INTEGER,campaign_id INTEGER,topic TEXT,channel TEXT,content_format TEXT,body TEXT,status TEXT,rights_note TEXT); INSERT INTO marketing_content VALUES(3,10,1,'Hanoi','Facebook','POST','Public draft','DRAFT','SECRET RIGHTS'),(4,20,2,'Secret','Facebook','POST','SECRET OTHER CONTENT','DRAFT','');
CREATE TABLE trips(id INTEGER,company_id INTEGER,title TEXT,market TEXT,start_date TEXT,end_date TEXT,total_guests INTEGER); INSERT INTO trips VALUES(10,10,'Vietnam','India','2027-01-01','2027-01-04',4),(20,20,'SECRET OTHER TRIP','Secret','2027-01-01','2027-01-04',1);
CREATE TABLE inquiries(id INTEGER,company_id INTEGER,trip_id INTEGER,inquiry_ref TEXT,status TEXT,destination_text TEXT,hotel_level TEXT,meals TEXT,transport_type TEXT,guide_language TEXT,budget_amount TEXT,lost_note TEXT); INSERT INTO inquiries VALUES(5,10,10,'INQ-5','WORKING','Hanoi','4*','B/L','Sedan','English','SECRET BUDGET','SECRET NOTE'),(6,20,20,'SECRET OTHER INQUIRY','NEW','Secret','','','','','','');
CREATE TABLE customers(id INTEGER,company_id INTEGER,customer_ref TEXT,full_name TEXT,company_name TEXT,country TEXT,market TEXT,preferred_language TEXT,email TEXT,notes TEXT); INSERT INTO customers VALUES(7,10,'CUS-7','Sample Guest','Family','India','India','en','SECRET EMAIL','SECRET NOTE'),(8,20,'SECRET OTHER CUSTOMER','Secret','','','','','','');
CREATE TABLE quotes(id INTEGER,company_id INTEGER,quote_ref TEXT,status TEXT,current_version_no INTEGER); INSERT INTO quotes VALUES(9,10,'QUO-9','DRAFT',2),(10,20,'SECRET OTHER QUOTE','SENT',1);
CREATE TABLE quote_versions(quote_id INTEGER,version_no INTEGER,tour_name TEXT,start_date TEXT,end_date TEXT,total_guests INTEGER,foc INTEGER,hotel_level TEXT,guide_language TEXT,meals TEXT,schedule_json TEXT,total_cost TEXT,internal_notes TEXT);
CREATE TABLE bookings(id INTEGER,company_id INTEGER,booking_ref TEXT,start_date TEXT,end_date TEXT,total_guests INTEGER,operations_status TEXT,confirmed_selling TEXT,special_requests TEXT); INSERT INTO bookings VALUES(11,10,'BKG-11','2027-01-01','2027-01-04',4,'READY','SECRET PRICE','SECRET NOTE'),(12,20,'SECRET OTHER BOOKING','2027-01-01','2027-01-04',2,'READY','','');
CREATE TABLE booking_services(id INTEGER,booking_id INTEGER,category TEXT,service_name TEXT,service_date TEXT,start_time TEXT,end_time TEXT,pickup_location TEXT,dropoff_location TEXT,pax INTEGER,qty INTEGER,booking_status TEXT,driver_name TEXT,vehicle_type TEXT,guide_name TEXT,planned_cost TEXT,driver_mobile TEXT,notes TEXT); INSERT INTO booking_services VALUES(13,11,'TRANSPORT','Airport pickup','2027-01-01','08:00','09:00','Airport','Hotel',4,1,'CONFIRMED','Driver A','Sedan','Guide A','SECRET COST','SECRET PHONE','SECRET NOTE'),(14,12,'HOTEL','SECRET OTHER SERVICE','2027-01-01','','','','',2,1,'CONFIRMED','','','','','','');
CREATE TABLE ai_threads(id INTEGER PRIMARY KEY AUTOINCREMENT,company_id INTEGER,user_id INTEGER,title TEXT,profile TEXT,context_json TEXT);");
$permissions=['ai.chat','lead.view','sales.view','booking.view','operations.view'];foreach($permissions as $i=>$code){$id=$i+1;$db->prepare('INSERT INTO permissions VALUES(?,?)')->execute([$id,$code]);$db->prepare('INSERT INTO role_permissions VALUES(1,?)')->execute([$id]);}
$schedule=[['day'=>1,'date'=>'2027-01-01','title'=>'Hanoi','description'=>'Arrival day','meals'=>'B','overnight'=>'Hanoi','price'=>'SECRET PRICE','internal_notes'=>'SECRET NOTE','passport'=>'SECRET PASSPORT']];
$db->prepare('INSERT INTO quote_versions VALUES(9,2,?,?,?,?,?,?,?,?,?,?,?)')->execute(['Vietnam','2027-01-01','2027-01-04',4,0,'4*','English','B',json_encode($schedule),'SECRET COST','SECRET NOTE']);
$db->prepare('INSERT INTO quote_versions VALUES(10,1,?,?,?,?,?,?,?,?,?,?,?)')->execute(['SECRET OTHER QUOTE','2027-01-01','2027-01-04',1,0,'4*','English','B','[]','','']);
$u=['company_id'=>10,'id'=>7];
contextCheck(AiChat::resolveContext($db,$u,['workspace'=>'sales'])['data']===[],'workspace guidance includes no inferred business data');
$entities=[['marketing','campaign',1,2],['marketing','content',3,4],['sales','inquiry',5,6],['sales','customer',7,8],['sales','quote',9,10],['operations','booking',11,12],['operations','service',13,14]];
foreach($entities as [$workspace,$type,$id,$other]){
 $context=AiChat::resolveContext($db,$u,['workspace'=>$workspace,'type'=>$type,'id'=>$id]);$json=json_encode($context);
 contextCheck($context['reference']===['workspace'=>$workspace,'type'=>$type,'id'=>$id]&&isset($context['frozen_at'])&&$context['data']!==[],"$type resolves explicit company-scoped reference");
 contextCheck(!str_contains($json,'SECRET')&&!preg_match('/"(price|cost|total_cost|planned_cost|margin|payment|passport|internal_notes|notes|budget_amount|driver_mobile|email)"/',$json),"$type allowlist removes confidential columns and nested fields");
 contextReject(fn()=>AiChat::resolveContext($db,$u,['workspace'=>$workspace,'type'=>$type,'id'=>$other]),OutOfBoundsException::class,"$type rejects another company entity");
}
contextCheck(AiChat::resolveContext($db,$u,['workspace'=>'sales','type'=>'quote','id'=>9])['data']['schedule'][0]['description']==='Arrival day','quote context retains structured customer itinerary');
foreach([null,'sales',[],['workspace'=>'finance'],['workspace'=>'sales','type'=>'booking','id'=>11],['workspace'=>'operations','type'=>'service','id'=>'13'],['workspace'=>'sales','type'=>'quote','id'=>0],['workspace'=>'sales','type'=>'quote','id'=>true],['workspace'=>'sales','type'=>'quote','id'=>1.5],['workspace'=>'sales','id'=>9],['workspace'=>'sales','type'=>'quote'],['workspace'=>'sales','type'=>'quote','id'=>2147483648],['workspace'=>'sales','context'=>['price'=>5]]] as $bad)contextReject(fn()=>AiChat::resolveContext($db,$u,$bad),InvalidArgumentException::class,'malformed or mismatched reference rejected');
$db->exec("INSERT INTO user_permissions VALUES(7,3,'DENY')");contextReject(fn()=>AiChat::resolveContext($db,$u,['workspace'=>'sales','type'=>'quote','id'=>9]),OutOfBoundsException::class,'explicit sales denial blocks quote context');$db->exec('DELETE FROM user_permissions');
foreach($entities as [$workspace,$type,$id]){$permission=match($type){'campaign','content'=>2,'quote','inquiry','customer'=>3,'booking'=>4,'service'=>5};$db->exec("INSERT INTO user_permissions VALUES(7,$permission,'DENY')");contextReject(fn()=>AiChat::resolveContext($db,$u,['workspace'=>$workspace,'type'=>$type,'id'=>$id]),OutOfBoundsException::class,"$type respects its source permission denial");$db->exec('DELETE FROM user_permissions');}
$db->exec('UPDATE inquiries SET trip_id=20 WHERE id=5');contextReject(fn()=>AiChat::resolveContext($db,$u,['workspace'=>'sales','type'=>'inquiry','id'=>5]),OutOfBoundsException::class,'inquiry cannot pull a cross-company related trip');$db->exec('UPDATE inquiries SET trip_id=10 WHERE id=5');
$db->exec('UPDATE marketing_content SET campaign_id=2 WHERE id=3');contextReject(fn()=>AiChat::resolveContext($db,$u,['workspace'=>'marketing','type'=>'content','id'=>3]),OutOfBoundsException::class,'content cannot pull a cross-company campaign');$db->exec('UPDATE marketing_content SET campaign_id=1 WHERE id=3');
$db->prepare('UPDATE quote_versions SET schedule_json=? WHERE quote_id=9')->execute([json_encode(array_fill(0,31,$schedule[0]))]);$limited=AiChat::resolveContext($db,$u,['workspace'=>'sales','type'=>'quote','id'=>9]);contextCheck(count($limited['data']['schedule'])===30&&$limited['data']['schedule_truncated']===true,'bounded itinerary context declares omitted days');
$db->prepare('UPDATE marketing_content SET body=? WHERE id=3')->execute([str_repeat('x',4000)]);$limited=AiChat::resolveContext($db,$u,['workspace'=>'marketing','type'=>'content','id'=>3]);contextCheck(strlen($limited['data']['body'])===3000&&$limited['limits']['field_chars']===3000,'long reference text is bounded with explicit limit metadata');
contextReject(fn()=>AiChat::resolveContext($db,['company_id'=>10,'id'=>8],['workspace'=>'sales']),OutOfBoundsException::class,'AI permission required even for empty workspace reference');
contextReject(fn()=>AiChat::resolveContext($db,$u,['workspace'=>'sales','type'=>'quote','id'=>999]),OutOfBoundsException::class,'missing entity rejects without placeholder data');
$created=AiChat::createThread($db,$u,['title'=>'Operations check','profile'=>'operations','context_ref'=>['workspace'=>'operations','type'=>'booking','id'=>11],'context'=>['price'=>'client spoof']]);
$frozen=$db->query('SELECT context_json FROM ai_threads WHERE id='.$created['id'])->fetchColumn();$db->exec("UPDATE bookings SET booking_ref='Changed later' WHERE id=11; UPDATE booking_services SET service_name='Changed later' WHERE id=13");
contextCheck($db->query('SELECT context_json FROM ai_threads WHERE id='.$created['id'])->fetchColumn()===$frozen&&str_contains($frozen,'Airport pickup')&&!str_contains($frozen,'client spoof'),'thread freezes server reference and ignores client-injected context');
$legacy=AiChat::createThread($db,$u,['title'=>'Legacy campaign','profile'=>'marketing','campaign_id'=>1]);$legacyContext=json_decode($db->query('SELECT context_json FROM ai_threads WHERE id='.$legacy['id'])->fetchColumn(),true);
contextCheck(array_keys($legacyContext)===['name','market','offer','audience'],'legacy campaign_id preserves four-field context contract');
contextReject(fn()=>AiChat::createThread($db,$u,['campaign_id'=>1,'context_ref'=>['workspace'=>'sales']]),InvalidArgumentException::class,'ambiguous references rejected');
contextReject(fn()=>AiChat::createThread($db,['company_id'=>10,'id'=>8],['title'=>'Forbidden']),OutOfBoundsException::class,'thread creation retains AI permission gate');
$payload=AiProvider::payload(AiProvider::settings([]),'operations',json_decode($frozen,true),[],'Check pickup');contextCheck(!isset($payload['tools'])&&$payload['store']===false,'context assistant remains stateless draft-only with no tools');
echo "$count context checks passed. SQLite query fixtures; no provider, MariaDB, or live HTTP calls.\n";
