'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const code=fs.readFileSync(path.join(__dirname,'../ai-chat.js'),'utf8');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const submit=form=>form.onsubmit({preventDefault(){},target:form});
let count=0;
async function test(label,fn){await fn();count++;console.log('PASS '+label);}
function setup({preview=false,contextRef={workspace:'operations',type:'booking',id:11},contextFailure=false,frozen=false,ready=true}={}){
 const dom=new JSDOM('<main id="workspace" data-view="operations">Operations remains visible</main><aside id="vtaAiOverlay" role="dialog"><div id="vtaAiRoot" data-view="ai"></div></aside>',{url:'https://localhost/',runScripts:'outside-only'}),w=dom.window;
 w.TextEncoder=TextEncoder;w.VTA_PREVIEW=preview;w.VTA_I18N={language:'vi'};w.eval(code);
 const root=w.document.querySelector('#vtaAiRoot'),overlay=w.document.querySelector('#vtaAiOverlay'),workspace=w.document.querySelector('#workspace'),calls=[],toast=[],navigated=[];
 let open=true,refreshes=0,post=null,modalElement,intercept=null;
 const reference={reference:contextRef,label:'Operations · Booking · <b>BKG-11</b>',frozen_at:'2026-10-01T00:00:00Z',data:{booking_ref:'BKG-11',services:[{service_name:'Airport pickup'}]}};
 const records=[{id:1,title:'Existing chat',profile:'sales',context:frozen?{...reference,reference:{workspace:'sales',type:'quote',id:9},label:'Sales · Quote · QUO-9',data:{quote_ref:'QUO-9',tour_name:'Vietnam'}}:{}}];
 const api={user:{id:7},request:async(route,opt={})=>{
  calls.push({route,opt});if(intercept){const value=intercept(route,opt);if(value!==undefined)return value;}
  if(opt.method==='POST'){if(post)return post(route,opt);if(route==='ai/threads'){const record={id:2,title:opt.body.title,profile:opt.body.profile,context:opt.body.context_ref?reference:{}};records.push(record);return {id:2};}return {id:8};}
  if(route==='ai/status')return {ready,daily_limit:30};if(route==='ai/threads')return {items:records};if(route==='ai/campaigns')return {items:[{id:5,name:'Family Vietnam'}]};
  if(route.startsWith('ai/context?')){if(contextFailure)throw Error('Context not available');return {context:reference};}
  if(/^ai\/threads\/\d+$/.test(route))return {thread:records.find(x=>x.id===Number(route.split('/').at(-1))),items:[{id:3,prompt:'Check pickup',reply:'<script>bad()</script> draft'}]};
  throw Error('Unexpected route: '+route);
 }};
 const options={api,esc,can:p=>p==='campaign.manage',root,active:()=>open&&overlay.isConnected,contextRef,navigate:async v=>navigated.push(v),toast:(...v)=>toast.push(v),closeModal:()=>modalElement?.remove(),modal:(title,body)=>{modalElement=w.document.createElement('div');modalElement.className='modal';modalElement.innerHTML='<button data-close>Close</button>'+body;w.document.body.append(modalElement);return modalElement;},renderAgain:async()=>{refreshes++;await w.VTAChat(options);}};
 return {w,root,workspace,overlay,calls,toast,navigated,options,records,render:()=>w.VTAChat(options),close:()=>{open=false;overlay.remove();},setPost:fn=>post=fn,intercept:fn=>intercept=fn,get refreshes(){return refreshes;},get modal(){return modalElement;}};
}
(async()=>{
 await test('Drawer mounts independently and never replaces the active Operations workspace',async()=>{const h=setup();await h.render();assert(h.root.querySelector('.ai-page'));assert.equal(h.workspace.textContent,'Operations remains visible');assert(!h.root.querySelector('b,script'));assert(h.root.textContent.includes('BKG-11'));assert.equal(h.navigated.length,0);});
 await test('Context resolver receives only a reference and its result is visibly separate from an existing thread',async()=>{const h=setup();await h.render();assert(h.calls.some(c=>c.route==='ai/context?workspace=operations&type=booking&id=11'));assert(h.root.querySelector('.ai-reference-note').textContent.includes('Hội thoại cũ'));assert.equal(h.root.querySelector('.ai-context'),null);});
 await test('New chat defaults to the workspace profile and submits server-resolved context_ref',async()=>{const h=setup();await h.render();h.root.querySelector('#aiNew').click();const form=h.modal.querySelector('form');assert.equal(form.elements.profile.value,'operations');assert(form.elements.campaign_id.disabled);form.elements.title.value='Pickup checklist';await submit(form);const created=h.calls.find(c=>c.route==='ai/threads'&&c.opt.method==='POST');assert.deepEqual(JSON.parse(JSON.stringify(created.opt.body.context_ref)),{workspace:'operations',type:'booking',id:11});assert.equal(created.opt.body.campaign_id,null);assert(!Object.hasOwn(created.opt.body,'context'));assert.equal(h.refreshes,1);assert.equal(h.navigated.length,0);assert(h.root.querySelector('.ai-context').textContent.includes('Tham chiếu cố định'));});
 await test('Existing legacy campaign selection remains available when workspace attachment is deselected',async()=>{const h=setup();await h.render();h.root.querySelector('#aiNew').click();const form=h.modal.querySelector('form'),check=form.elements.use_context;check.checked=false;check.onchange();assert(!form.elements.campaign_id.disabled);form.elements.campaign_id.value='5';form.elements.title.value='Campaign brief';await submit(form);const body=h.calls.find(c=>c.route==='ai/threads'&&c.opt.method==='POST').opt.body;assert.equal(body.campaign_id,5);assert(!Object.hasOwn(body,'context_ref'));});
 await test('Frozen thread reference is labelled and never replaced with the currently open workspace',async()=>{const h=setup({frozen:true});await h.render();const context=h.root.querySelector('.ai-context');assert(context.textContent.includes('QUO-9'));assert(context.textContent.includes('Tham chiếu cố định'));assert(!context.textContent.includes('BKG-11'));});
 await test('Missing or forbidden context offers a chat without silent placeholder data',async()=>{const h=setup({contextFailure:true});await h.render();assert(h.root.querySelector('.ai-reference-note').textContent.includes('Chưa tải'));h.root.querySelector('#aiNew').click();assert.equal(h.modal.querySelector('[name=use_context]'),null);const form=h.modal.querySelector('form');form.elements.title.value='General help';await submit(form);const body=h.calls.find(c=>c.route==='ai/threads'&&c.opt.method==='POST').opt.body;assert(!Object.hasOwn(body,'context_ref'));});
 await test('Consent remains required, successful send reloads the same drawer and preserves workspace',async()=>{const h=setup();await h.render();h.root.querySelector('#aiMessage').value='Check route';await submit(h.root.querySelector('#aiComposer'));assert(!h.calls.some(c=>c.opt.method==='POST'));h.root.querySelector('#aiConsent').checked=true;await submit(h.root.querySelector('#aiComposer'));assert(h.calls.some(c=>c.route==='ai/threads/1/messages'));assert.equal(h.refreshes,1);assert.equal(h.workspace.textContent,'Operations remains visible');assert.equal(h.navigated.length,0);});
 await test('Failed sends keep request keys for a deliberate retry and block duplicate submission',async()=>{const h=setup();await h.render();h.root.querySelector('#aiMessage').value='Draft test';h.root.querySelector('#aiConsent').checked=true;h.setPost(async()=>{throw Error('Timeout');});await submit(h.root.querySelector('#aiComposer'));const key=h.calls.at(-1).opt.body.request_key;let finish;h.setPost(()=>new Promise(resolve=>finish=resolve));const pending=submit(h.root.querySelector('#aiComposer'));await Promise.resolve();const length=h.calls.length;await submit(h.root.querySelector('#aiComposer'));assert.equal(h.calls.length,length);assert.equal(h.calls.at(-1).opt.body.request_key,key);finish({id:3});await pending;});
 await test('Closing while initial requests load cannot reopen or overwrite any workspace',async()=>{const h=setup();let finish;h.intercept(route=>route==='ai/status'?new Promise(resolve=>finish=resolve):undefined);const pending=h.render();h.close();h.workspace.textContent='Sales';finish({ready:true});await pending;assert.equal(h.root.innerHTML,'');assert.equal(h.workspace.textContent,'Sales');assert.equal(h.refreshes,0);});
 await test('Closing while a message is being generated discards late UI updates without reopening',async()=>{const h=setup();await h.render();let finish;h.setPost(()=>new Promise(resolve=>finish=resolve));h.root.querySelector('#aiMessage').value='Check tour';h.root.querySelector('#aiConsent').checked=true;const pending=submit(h.root.querySelector('#aiComposer'));h.close();finish({id:4});await pending;assert.equal(h.refreshes,0);assert.equal(h.navigated.length,0);assert.equal(h.workspace.textContent,'Operations remains visible');});
 await test('A closed create dialog cannot close an unrelated dialog after its late response',async()=>{const h=setup();await h.render();h.root.querySelector('#aiNew').click();const captured=h.modal,form=captured.querySelector('form');form.elements.title.value='Delayed creation';let finish;h.setPost(()=>new Promise(resolve=>finish=resolve));const pending=submit(form);captured.remove();const unrelated=h.options.modal('Unrelated','<p>Keep me</p>');finish({id:2});await pending;assert(unrelated.isConnected);assert.equal(h.refreshes,0);});
 await test('Preview is illustrative, follows the suggested workspace profile and performs no context/provider calls',async()=>{const h=setup({preview:true});await h.render();assert.equal(h.calls.length,0);assert(h.root.textContent.includes('DEMO'));assert(h.root.textContent.includes('Trợ lý điều hành'));assert(h.root.querySelector('#aiSend').disabled);});
 await test('Unconfigured provider preserves setup state and disabled sending in the drawer',async()=>{const h=setup({ready:false});await h.render();assert(h.root.querySelector('#aiSend').disabled);assert(h.root.querySelector('.ai-setup'));});
 console.log(count+' AI drawer groups passed. jsdom and simulated API; no provider calls.');
})().catch(error=>{console.error(error);process.exitCode=1;});
