<?php
declare(strict_types=1);
require_once __DIR__.'/../api/lib/QuoteOptions.php';
require_once __DIR__.'/../api/lib/DocumentParser.php';
require_once __DIR__.'/../api/lib/RuntimeGuard.php';
function ffcheck(bool $ok,string $label):void{if(!$ok)throw new RuntimeException('FAIL '.$label);echo "PASS $label\n";}
function ffreject(callable $fn,string $label):void{try{$fn();}catch(InvalidArgumentException|DomainException $e){ffcheck(true,$label);return;}throw new RuntimeException('FAIL accepted '.$label);}
$dir=getenv('FREEFORM_FIXTURE_DIR')?:throw new RuntimeException('Private FREEFORM_FIXTURE_DIR required');RuntimeGuard::privatePath($dir);if(!is_dir($dir))mkdir($dir,0770,true);
$text=fn($value,$marks=[])=>['type'=>'text','text'=>$value]+($marks?['marks'=>$marks]:[]);$p=fn($value)=>['type'=>'paragraph','content'=>[$text($value)]];$cell=fn($value)=>['type'=>'tableCell','attrs'=>['colspan'=>1,'rowspan'=>1,'colwidth'=>null],'content'=>[$p($value)]];
$empty=['schema'=>'VTA_DOC_2','title'=>'Untitled document','content'=>['type'=>'doc','content'=>[['type'=>'paragraph']]]];$empty=QuoteProposal::document($empty);$snapshot=['quote_ref'=>'LOCAL-FREEFORM','presentation'=>['settings'=>['document'=>$empty],'media'=>[]]];
$html=ProposalOutput::html($snapshot,fn($id)=>'');ffcheck(!str_contains($html,'Briefing')&&!str_contains($html,'Itinerary')&&!str_contains($html,'Untitled document</h'),'blank output has no forced heading, commercial sections or generated days');
$im=imagecreatetruecolor(800,450);imagefill($im,0,0,imagecolorallocate($im,80,155,185));imagejpeg($im,$dir.'/fixture.jpg');imagedestroy($im);
$nodes=[['type'=>'heading','attrs'=>['level'=>2],'content'=>[$text('Imported Word heading')]],$p('  Exact leading and trailing spaces  '),['type'=>'paragraph','attrs'=>['textAlign'=>'center'],'content'=>[$text('Formatted text',[['type'=>'bold'],['type'=>'italic'],['type'=>'underline'],['type'=>'textStyle','attrs'=>['fontSize'=>'18pt','color'=>'#cc3333']]])]],['type'=>'bulletList','content'=>[['type'=>'listItem','content'=>[$p('Word list item')]],['type'=>'listItem','content'=>[$p('Second Word item')]]]],['type'=>'orderedList','attrs'=>['start'=>3],'content'=>[['type'=>'listItem','content'=>[$p('Numbered item')]]]],['type'=>'table','content'=>[['type'=>'tableRow','content'=>[$cell('Word time'),$cell('Word activity')]],['type'=>'tableRow','content'=>[$cell('10:00'),$cell('Editable table')]]]],['type'=>'image','attrs'=>['assetId'=>99,'alt'=>'Embedded image','width'=>320]],['type'=>'pageBreak'],$p('After page break')];
$legacy=QuoteProposal::document(['schema'=>'VTA_DOC_1','title'=>'Saved legacy','sections'=>['included'=>[['type'=>'paragraph','runs'=>[['text'=>'Legacy rich text','bold'=>true,'italic'=>false]]]]],'days'=>[]]);
$document=QuoteProposal::document(['schema'=>'VTA_DOC_2','title'=>'Word fixture','content'=>['type'=>'doc','content'=>$nodes],'legacy'=>$legacy]);
ffcheck($document['content']['content'][1]['content'][0]['text']==='  Exact leading and trailing spaces  ','text nodes keep spaces exactly');
ffcheck($document['legacy']===$legacy,'legacy rich proposal survives conversion through compatibility field');
ffcheck(QuoteProposal::document(json_decode(MediaLibrary::json($document),true))===$document,'typed model serializes and reopens losslessly');
ffcheck(FreeformDocument::imageIds($document)===[99],'image references are unique owned asset IDs');
ffcheck(FreeformDocument::color('rgb(204, 51, 51)')==='#cc3333','browser CSS colors canonicalize safely');
ffreject(fn()=>FreeformDocument::color('red;position:fixed'),'CSS injection rejected');
ffreject(fn()=>QuoteProposal::document(['schema'=>'VTA_DOC_2','content'=>['type'=>'doc','content'=>[['type'=>'script']]]]),'executable and unsupported nodes rejected');
ffreject(fn()=>QuoteProposal::document(['schema'=>'VTA_DOC_2','content'=>['type'=>'doc','content'=>[['type'=>'paragraph','content'=>[$text('unsafe',[['type'=>'link','attrs'=>['href'=>'javascript:bad()']]])]]]]]),'unapproved link / code marks rejected');
ffreject(fn()=>QuoteProposal::document(['schema'=>'VTA_DOC_2','content'=>['type'=>'doc','content'=>[['type'=>'image','attrs'=>['src'=>'https://external.example/image.jpg']]]]]),'external unowned images rejected');
ffreject(fn()=>QuoteProposal::document(['schema'=>'VTA_DOC_2','content'=>['type'=>'doc','content'=>[['type'=>'table','content'=>[['type'=>'tableRow','content'=>[$cell('A'),$cell('B')]],['type'=>'tableRow','content'=>[$cell('C')]]]]]]]),'ragged table is rejected before storage');
$snapshot['presentation']=['settings'=>['document'=>$document],'media'=>[['asset_id'=>99,'width'=>800,'height'=>450]]];$image=fn($id)=>$dir.'/fixture.jpg';
$html=ProposalOutput::html($snapshot,fn($id)=>'image-'.$id.'.jpg');ffcheck(str_contains($html,'font-size:18pt')&&str_contains($html,'color:#cc3333')&&str_contains($html,'<ul>')&&str_contains($html,'start="3"')&&str_contains($html,'image-99.jpg'),'HTML exports one unified tree with formatting, lists, tables and image');
$docx=ProposalOutput::docx($snapshot,$image);file_put_contents($dir.'/import.docx',$docx);$zip=new ZipArchive();ffcheck($zip->open($dir.'/import.docx')===true,'DOCX is a readable native Word ZIP');$xml=$zip->getFromName('word/document.xml');$numbering=$zip->getFromName('word/numbering.xml');$dom=new DOMDocument();ffcheck($dom->loadXML($xml,LIBXML_NONET),'native Word XML well formed');ffcheck(str_contains($xml,'<w:numPr>')&&str_contains($numbering,'startOverride w:val="3"'),'DOCX uses real editable Word lists and starting numbers');ffcheck(str_contains($xml,'<w:tbl>')&&str_contains($xml,'<w:drawing>')&&str_contains($xml,'w:type="page"'),'DOCX includes native table, embedded image and page break');ffcheck($zip->getFromName('word/media/image99.jpg')!==false&&str_contains($zip->getFromName('[Content_Types].xml'),'numbering+xml'),'DOCX packages embedded image and list relationship/content type');$zip->close();
$reimport=DocumentParser::proposal($dir.'/import.docx','docx');ffcheck(str_contains($reimport['text'],'Imported Word heading')&&count($reimport['images'])===1&&count(array_filter($reimport['blocks'],fn($b)=>$b['type']==='table'))===1,'DOCX reimports editable content and image bytes');
$pdf=ProposalOutput::pdf($snapshot,['storage'=>['local_path'=>$dir.'/storage']],$image);file_put_contents($dir.'/import.pdf',$pdf);ffcheck(str_starts_with($pdf,'%PDF-')&&str_contains(substr($pdf,-40),'%%EOF'),'PDF exports a complete Unicode printable document');
$merged=$cell('Merged');$merged['attrs']['colspan']=2;$table=['type'=>'table','content'=>[['type'=>'tableRow','content'=>[$merged]],['type'=>'tableRow','content'=>[$cell('C'),$cell('D')]]]];$mergeDoc=QuoteProposal::document(['schema'=>'VTA_DOC_2','title'=>'Merged','content'=>['type'=>'doc','content'=>[$table]]]);$snapshot['presentation']['settings']['document']=$mergeDoc;file_put_contents($dir.'/merged.docx',ProposalOutput::docx($snapshot,$image));$zip->open($dir.'/merged.docx');ffcheck(str_contains($zip->getFromName('word/document.xml'),'w:gridSpan w:val="2"'),'DOCX preserves merged column cells');$zip->close();
$withCellImage=$mergeDoc;$withCellImage['content']['content'][0]['content'][1]['content'][0]['content'][]=['type'=>'pageBreak'];$withCellImage['content']['content'][0]['content'][1]['content'][0]['content'][]=['type'=>'image','attrs'=>['assetId'=>99,'width'=>160]];$snapshot['presentation']['settings']['document']=QuoteProposal::document($withCellImage);ffcheck(QuoteProposal::document($snapshot['presentation']['settings']['document'])===$snapshot['presentation']['settings']['document'],'page breaks and uploaded images inside table cells save and reopen');file_put_contents($dir.'/cell-image.docx',ProposalOutput::docx($snapshot,$image));$cellImport=DocumentParser::proposal($dir.'/cell-image.docx','docx',true);ffcheck(in_array('Embedded images inside DOCX table cells require separate image upload.',$cellImport['warnings'],true),'DOCX table-cell image limitation is explicitly reported');
$bad=$empty;$bad['legacy']=['schema'=>'VTA_DOC_2'];ffreject(fn()=>QuoteProposal::document($bad),'recursive legacy documents rejected');
echo "Freeform unit/import/export checks complete; no database.\n";