<?php
declare(strict_types=1);
// Reuse legacy, VS2.1 and media/output acceptance on a disposable local database.
require __DIR__.'/vs22-native.php';
require_once __DIR__.'/../api/lib/DocumentParser.php';
require_once __DIR__.'/../api/lib/ScheduleImport.php';
$historical=v2q('SELECT * FROM quote_sent_bundles ORDER BY quote_version_id')->fetchAll();
$historicalBookings=v2q('SELECT * FROM booking_quote_snapshots ORDER BY booking_id')->fetchAll();
$qvid=$revision;v2q("UPDATE quotes SET current_version_no=2,status='DRAFT' WHERE id=?",[v2v()['quote_id']]);
$text="# Vietnam 7D6N\nTour type: PRIVATE\nGuests: 16 adults + 1 FOC\nDuration: 7D6N\nSchedule\n";
for($i=1;$i<=7;$i++)$text.="Day $i — Journey $i (B/L/D)\n";
$text.="Detailed Itinerary\n";for($i=1;$i<=7;$i++)$text.="Day $i — Journey $i (B/L/D)\nOvernight: Hanoi\nMorning **visit** and *relax*.\n- Reviewed activity\n";
$text.="Included\n- Accommodation\nExcluded\n- Flights\nChildren Policy\nSupplier-specific policy\nBooking / Payment Terms\nPay as agreed\nCancellation Policy\nContract applies\nTerms & Conditions\nReviewed terms\nPrice\nReference only 999 USD\n";
$parsed=ScheduleImport::documentPreview($text);check(count($parsed['days'])===7&&$parsed['source_numbers']===range(1,7),'UX paste detects seven detailed days without duplicate schedule days');
check($parsed['days'][0]['meals']==='B/L/D'&&isset($parsed['sections']['included'],$parsed['sections']['excluded'],$parsed['sections']['payment'],$parsed['sections']['children'],$parsed['sections']['cancellation']),'UX meals and public policies classified');
check(str_contains(QuoteProposal::blockText($parsed['days'][0]['blocks']),'visit'),'UX editable typed content preserves prose');
$duplicate=ScheduleImport::documentPreview(str_replace('Day 7','Day 6',$text));check((bool)array_filter($duplicate['warnings'],fn($s)=>str_contains($s,'numbering')),'UX duplicate day flagged without silent correction');
rejects(fn()=>QuoteProposal::richBlocks([['type'=>'html','text'=>'<script>']]),InvalidArgumentException::class,'UX uncontrolled HTML rejected');
rejects(fn()=>QuoteProposal::richBlocks([['type'=>'table','rows'=>[[[]],[[],[]]]]]),InvalidArgumentException::class,'UX malformed tables rejected');
// Document-only changes use the same public presentation, not commercial fields.
$before=QuoteVs2Repository::graph($db,v2v());$days=QuoteProposal::days(v2v());$settings=QuoteProposal::config(v2v());
$settings['document']=['schema'=>'VTA_DOC_1','title'=>'Reviewed document title','sections'=>['included'=>$parsed['sections']['included'],'payment'=>$parsed['sections']['payment']],'days'=>[$days[0]['day_key']=>$parsed['days'][0]['blocks']],'review'=>['source_numbers'=>[],'duration_days'=>0,'acknowledged'=>true]];
$days[0]['description']=trim(QuoteProposal::blockText($parsed['days'][0]['blocks']));
QuoteProposal::save($db,$user,$qvid,['expected_revision'=>v2v()['costing_revision'],'settings'=>$settings,'days'=>$days,'links'=>[]]);
check(v2v()['paying_pax']===$before['version']['paying_pax']&&v2v()['fx_rate']===$before['version']['fx_rate'],'UX proposal import leaves paying pax and FX unchanged');
$public=QuoteProposal::publicQuote($db,v2v());$html=ProposalOutput::html($public,fn($a)=>'image');check(str_contains($html,'<strong>visit</strong>')&&str_contains($html,'<em>relax</em>'),'UX HTML output renders escaped rich runs');
$word=ProposalOutput::docx($public,fn($a)=>'');file_put_contents($output.'/ux-rich.docx',$word);check(str_contains(DocumentParser::extract($output.'/ux-rich.docx','docx')['text'],'visit'),'UX DOCX export reimports document prose');
$docx=DocumentParser::proposal($output.'/ux-rich.docx','docx');check(count($docx['blocks'])>0,'UX ordered DOCX import supports exported document');
$pdf=ProposalOutput::pdf($public,$cfg,fn($a)=>'',true);file_put_contents($output.'/ux-rich.pdf',$pdf);check(str_starts_with($pdf,'%PDF'),'UX PDF output generated');
$extracted=DocumentParser::proposal($output.'/ux-rich.pdf','pdf');check(isset($extracted['quality'],$extracted['text']),'UX PDF import returns explicit extraction quality');
$sheet=function(array $b)use($db,$user){return v2command($b,fn($v)=>QuoteVs2::sheet($db,$user,$v,$b));};
$out=$sheet(['action'=>'init','mode'=>'PRIVATE']);$ids=$out['variant_ids'];check(count($ids)===3,'UX three variants reuse one itinerary');
foreach(QuoteVs2Repository::graph($db,v2v())['requirements'] as $r)QuoteSmartCosting::requirement($db,$user,$qvid,['id'=>$r['id'],'requirement_state'=>'NOT_APPLICABLE','metadata'=>['reason'=>'Synthetic sheet fixture excludes original services']]);
$manual=['custom_quantity'=>3,'supplier_id'=>1,'unit_amount_original'=>'100000','original_currency'=>'VND','manual_reason'=>'Reviewed supplier fixture','manual_contract'=>['formula_code'=>'CUSTOM','evidence'=>'Reviewed supplier fixture','tax_basis'=>'NET']];
$out=$sheet(['variant_ids'=>$ids,'requirement'=>['category'=>'OTHER','service_name'=>'Shared service','service_date'=>v2v()['start_date'],'service_units'=>2,'default_quantity_source'=>'CUSTOM_QTY','service_mode'=>'BOTH','requirement_state'=>'REQUIRED','scope'=>['service_key'=>'ux-shared']],'line'=>$manual]);$rid=$out['requirement_id'];
$get=fn()=>v2q('SELECT l.* FROM quote_variant_cost_lines l WHERE l.requirement_id=? ORDER BY l.variant_id',[$rid])->fetchAll();
$lines=array_values(array_filter($get(),fn($l)=>in_array((int)$l['variant_id'],$ids)));check(count($lines)===3&&array_unique(array_column($lines,'total_vnd'))===['600000.00'],'UX shared cost calculated three times by existing authoritative formula');
$separate=[];foreach($ids as $i=>$id)$separate[$id]=$manual+[];foreach($ids as $i=>$id)$separate[$id]['unit_amount_original']=(string)(100000*($i+1));
$sheet(['variant_ids'=>$ids,'requirement_id'=>$rid,'shared'=>false,'lines'=>$separate]);$lines=array_values(array_filter($get(),fn($l)=>in_array((int)$l['variant_id'],$ids)));check(array_column($lines,'total_vnd')===['600000.00','1200000.00','1800000.00'],'UX separate cost calculates all three option totals');
$state=$get();$broken=$separate;$broken[$ids[1]]['supplier_id']=999999;
rejects(fn()=>$sheet(['variant_ids'=>$ids,'requirement_id'=>$rid,'shared'=>false,'lines'=>$broken]),InvalidArgumentException::class,'UX multi-option failure rolls back');check($get()===$state,'UX no partial shared or separate writes');
$sheet(['action'=>'variant','variant_ids'=>[$ids[0]],'changes'=>['pricing_mode'=>'MARKUP','pricing_value'=>'20','is_offered'=>true]]);
$sheet(['action'=>'variant','variant_ids'=>[$ids[1]],'changes'=>['pricing_mode'=>'TARGET_MARGIN','pricing_value'=>'20','is_offered'=>true]]);
$sheet(['action'=>'variant','variant_ids'=>[$ids[2]],'changes'=>['pricing_mode'=>'MANUAL','pricing_value'=>'10','is_offered'=>true]]);
$dto=QuoteVs2::optionsDto($db,$user,v2v());$ps=array_values(array_filter($dto['items'],fn($p)=>in_array($p['variant_id'],$ids)));check($ps[0]['pricing']['selling_per_pax']!==$ps[1]['pricing']['selling_per_pax']&&$ps[2]['pricing']['selling_per_pax']==='10.00','UX markup margin and manual price remain distinct');
$settings=QuoteProposal::config(v2v());$settings['accommodation']=[['type'=>'HOTEL','destination'=>'Hanoi','nights'=>3,'three_star'=>'Hotel A / Deluxe','four_star'=>'Hotel B / Deluxe','five_star'=>'Hotel C / Suite'],['type'=>'CRUISE','destination'=>'Halong','nights'=>1,'three_star'=>'Cruise A','four_star'=>'Cruise B','five_star'=>'Cruise C']];
QuoteProposal::save($db,$user,$qvid,['expected_revision'=>v2v()['costing_revision'],'settings'=>$settings,'days'=>QuoteProposal::days(v2v()),'links'=>[]]);
$context=QuoteProposal::context($db,$user,v2v());check(count($context['selling_options'])===3&&!str_contains(json_encode($context['selling_options']),'cost_total_vnd')&&!str_contains(json_encode($context['selling_options']),'profit'),'UX document price projection contains three selling prices only');
$sheet(['action'=>'review','variant_ids'=>$ids,'requirement_id'=>$rid,'review_reason'=>'Reviewed synthetic supplier amounts and quantities']);
// Other copied variants are draft-only; explicitly offer the selected three.
v2q('UPDATE quote_option_variants c JOIN quote_options o ON o.id=c.quote_option_id SET c.is_offered=0 WHERE o.quote_version_id=?',[$qvid]);$sheet(['action'=>'variant','variant_ids'=>$ids,'changes'=>['is_offered'=>true]]);
check(QuoteVs2Validator::validate($db,v2v())['valid'],'UX three reviewed packages validate with central validator');
QuoteOptions::approve($db,$user,$qvid,'Reviewed document and three packages');$sent=QuoteOptions::send($db,$user,$qvid);$frozen=v2q('SELECT * FROM quote_sent_bundles WHERE quote_version_id=?',[$qvid])->fetch();
check(count($sent['customer_safe_snapshot']['options'])===3&&str_contains($sent['customer_safe_snapshot']['presentation']['public_html'],'Hotel C / Suite'),'UX three prices and independent accommodation reach frozen proposal');
rejects(fn()=>$sheet(['variant_ids'=>$ids,'requirement_id'=>$rid,'line'=>$manual]),DomainException::class,'UX Sent sheet immutable');
$off=$sent['customer_safe_snapshot']['options'][1];QuoteOptions::confirm($db,$user,$qvid,(int)$off['id'],(int)$off['variant_id'],$frozen['content_hash']);$book=QuoteOptions::booking($db,$user,$qvid);check((int)$book['id']>0,'UX Quote Cost Price Proposal Approve Send Accept Booking');
check(v2q('SELECT * FROM quote_sent_bundles ORDER BY quote_version_id')->fetchAll()!==$historical&&array_slice(v2q('SELECT * FROM quote_sent_bundles ORDER BY quote_version_id')->fetchAll(),0,count($historical))===$historical,'UX all prior sent rows byte-stable');
check(array_slice(v2q('SELECT * FROM booking_quote_snapshots ORDER BY booking_id')->fetchAll(),0,count($historicalBookings))===$historicalBookings,'UX all prior booking rows byte-stable');
file_put_contents($output.'/ux-fixture.json',MediaLibrary::json(['database'=>$database,'version_id'=>$qvid,'quote_id'=>v2v()['quote_id'],'revision_id'=>$revision,'variant_ids'=>$ids,'config'=>$cfg,'result'=>'PASS']));
echo "Document and Cost Sheet native acceptance complete.\n";
