const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const settle=async()=>{for(let i=0;i<15;i++)await new Promise(r=>setImmediate(r));};
async function harness(cost=true,status='DRAFT'){
 const dom=new JSDOM('<main></main><aside id="modals"></aside>',{url:'http://127.0.0.1:18874',runScripts:'outside-only'}),w=dom.window,root=w.document.querySelector('main'),calls=[];
 w.structuredClone=structuredClone;w.eval(fs.readFileSync(path.join(__dirname,'../cost-sheet.js'),'utf8'));
 const ctx={costing_revision:7,guests:{adults:16,children:0,infants:0,foc:1,paying_pax:16,total_guests:17},profile:{hotel_pax:17,cruise_pax:17},schedule:[{day_key:'d1',date:'2027-01-01',title:'Hanoi',route:'Hanoi'}],requirements:[{id:9,category:'OTHER',service_name:'Supplier service',service_date:'2027-01-01',service_units:2,default_quantity_source:'CUSTOM_QTY',requirement_state:'REQUIRED',scope:{}}]};
 const data={items:[3,4,5].map(s=>({variant_id:s,variant_key:'private-'+s+'-'+s,hotel_level:s+'*',cruise_level:s,costing_mode:'PRIVATE',label:s+' stars',pricing_mode:'MARKUP',pricing_value:'15',selling_currency:'USD',pricing:{cost_total_vnd:'600',selling_per_pax:'1',total_selling:'16',profit_vnd:'50'},lines:[{id:s+10,requirement_id:9,line_kind:'SERVICE',active:true,unit_rate_vnd:'100',total_vnd:'600',custom_quantity:3,review_required:1,coverage_state:'PRICED',supplier_id:1,manual_reason:'Supplier evidence',trace:{sentence:'3 × 2 × 100 VND = 600 VND'}}]})),supplier_choices:[{id:1,name:'Supplier A'}]};
 const api={request:async(route,opt={})=>{calls.push({route,...opt});if(route.endsWith('/proposal'))return {settings:{accommodation:[{type:'HOTEL',destination:'Hanoi',nights:1,three_star:'Hotel A',four_star:'Hotel B',five_star:'Hotel C'}]},days:ctx.schedule,links:[]};return {costing_revision:8,errors:[],warnings:[],valid:true};}};
 const modal=(title,body,footer='')=>{const m=w.document.createElement('section');m.innerHTML='<h2>'+title+'</h2>'+body+footer;w.document.querySelector('#modals').replaceChildren(m);return m;};
 await w.mountCostSheet(root,{api,quoteData:{quote:{id:2,quote_ref:'QT-UX'},version:{id:5,tour_name:'Vietnam',version_no:1,version_status:status,start_date:'2027-01-01',end_date:'2027-01-01',fx_rate:'25000'}},can:p=>p==='quote.view_cost'?cost:true,navigate:()=>{},modal,closeModal:()=>w.document.querySelector('#modals').replaceChildren(),toast:()=>{},refresh:async()=>{},onProposal:()=>calls.push({route:'proposal-nav'}),ctx,data:cost?data:{items:[]}});return {dom,w,root,calls};
}
(async()=>{
 let h=await harness();assert.equal(h.root.querySelectorAll('[data-summary]').length,3);assert.equal(h.root.querySelectorAll('[data-row]').length,1);assert.equal(h.root.querySelectorAll('[data-unit]').length,3);assert(!h.root.textContent.includes('Match Approved Rate'));assert(!h.root.querySelector('[data-line-duplicate]'));console.log('PASS UX one spreadsheet, three option cards, compact guest summary');
 const adults=h.root.querySelector('[name=adults]');adults.value='18';adults.dispatchEvent(new h.w.Event('input'));assert.equal(h.root.querySelector('[name=paying_pax]').value,'18');assert.equal(h.root.querySelector('[name=total_guests]').value,'19');adults.dispatchEvent(new h.w.Event('change'));await settle();assert.equal(h.calls.at(-1).body.foc,1);assert.equal(h.calls.at(-1).body.expected_revision,7);console.log('PASS UX adults recalculate additional FOC and paying using existing non-paying offset');
 const unit=h.root.querySelector('[data-unit]');unit.value='850000';unit.dispatchEvent(new h.w.Event('change'));const m=h.w.document.querySelector('#modals section');m.querySelector('[name=supplier_id]').value='1';m.querySelector('[name=manual_reason]').value='Reviewed contract';m.querySelector('[data-manual-save]').click();await settle();const save=h.calls.filter(c=>c.route.endsWith('/sheet')).at(-1);assert.deepEqual(Array.from(save.body.variant_ids),[3,4,5]);assert.equal(save.body.line.unit_amount_original,'850000');assert.equal(save.body.line.manual_contract.evidence,'Reviewed contract');assert(!('total_vnd' in save.body.line));console.log('PASS UX inline common price keeps supplier evidence and never submits client totals');
 const share=h.root.querySelector('[data-shared]');share.checked=false;share.dispatchEvent(new h.w.Event('change'));assert(!h.root.querySelector('[data-unit="4"]').disabled);const u4=h.root.querySelector('[data-unit="4"]');u4.value='900000';u4.dispatchEvent(new h.w.Event('change'));h.w.document.querySelector('[name=supplier_id]').value='1';h.w.document.querySelector('[name=manual_reason]').value='Separate supplier terms';h.w.document.querySelector('[data-manual-save]').click();await settle();const one=h.calls.filter(c=>c.route.endsWith('/sheet')).at(-1);assert.deepEqual(Array.from(one.body.variant_ids),[4]);assert.equal(one.body.lines[4].unit_amount_original,'900000');console.log('PASS UX separate option writes target only selected variant');
 h.root.querySelector('[data-remove]').click();h.w.document.querySelector('[name=reason]').value='Not part of this itinerary';h.w.document.querySelector('[data-confirm-remove]').click();await settle();assert.equal(h.calls.at(-1).body.action,'remove');assert(h.calls.at(-1).body.reason);console.log('PASS UX remove preserves requirement evidence instead of destructive deletion');
 const accommodation=h.root.querySelector('[data-accommodation]');accommodation.value='Hotel A / Deluxe';accommodation.dispatchEvent(new h.w.Event('change'));await settle();const p=h.calls.at(-1);assert.equal(p.body.settings.accommodation[0].three_star,'Hotel A / Deluxe');assert.equal(p.body.settings.accommodation[0].four_star,'Hotel B');console.log('PASS UX accommodation editing preserves independent option selections');h.dom.window.close();
 h=await harness(false);assert(!h.root.querySelector('.sheet-table'));assert(!h.calls.some(c=>c.route.endsWith('/options')||c.route.includes('supplier')));console.log('PASS UX no financial view or financial requests without cost permission');h.dom.window.close();
 h=await harness(true,'SENT');assert(!h.root.querySelector('[data-remove]'));assert(!h.root.querySelector('[data-add]'));assert([...h.root.querySelectorAll('[data-unit]')].every(x=>x.disabled));assert(!h.root.querySelector('[data-pricing]'));console.log('PASS UX Sent sheet cannot edit prices or guest quantities');h.dom.window.close();
 // Document default and editing projection are independent of supplier data.
 const dom=new JSDOM('<main></main><aside id="modals"></aside>',{url:'http://local.test',runScripts:'outside-only'}),w=dom.window;w.eval(fs.readFileSync(path.join(__dirname,'../visual-proposal.js'),'utf8'));const calls=[];
 const ctx={costing_revision:3,immutable:false,settings:{template:'VTA_STANDARD_B2B',sections:['schedule','itinerary'],accommodation:[]},days:[{day_key:'stable-01',date:'2027-01-01',title:'Hanoi',description:'Morning visit',meals:'B/L',overnight:'Hanoi',overnight_type:'HOTEL'}],links:[],requirements:[],templates:{VTA_STANDARD_B2B:'VTA B2B'},selling_options:[]};
 const root=w.document.querySelector('main');const api={request:async(route,opt={})=>{calls.push({route,...opt});if(opt.method==='PUT'){Object.assign(ctx,{settings:opt.body.settings,days:opt.body.days,links:opt.body.links});}return structuredClone(ctx);}};
 await w.mountVisualProposal(root,{api,quoteData:{quote:{id:2,quote_ref:'QT-UX'},version:{id:5,tour_name:'Vietnam',version_status:'DRAFT'}},can:()=>true,modal:()=>{},closeModal:()=>{},toast:()=>{},refresh:()=>{},onBack:()=>{}});assert(root.querySelector('.df-document'));assert(!calls.some(c=>c.route.startsWith('media')));const title=root.querySelector('[data-day-field=title]');title.textContent='New Hanoi title';title.dispatchEvent(new w.Event('input'));assert(root.querySelector('[data-schedule-summary]').textContent.includes('New Hanoi title'));root.querySelector('[data-v22-save]').click();await settle();const saveDoc=calls.find(c=>c.method==='PUT');assert.equal(saveDoc.body.days[0].day_key,'stable-01');assert.equal(saveDoc.body.settings.document.schema,'VTA_DOC_1');assert(!('cost' in saveDoc.body));console.log('PASS UX Document default, lazy media, live schedule and typed save with stable day identity');dom.window.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
