<?php
declare(strict_types=1);
require_once __DIR__.'/../api/lib/QuoteOptions.php';
require_once __DIR__.'/../api/lib/DocumentParser.php';
require_once __DIR__.'/../api/lib/ScheduleImport.php';
require_once __DIR__.'/../api/lib/RuntimeGuard.php';
function editorCheck(bool $ok,string $label):void {if(!$ok)throw new RuntimeException('FAIL '.$label);echo "PASS $label\n";}
$output=getenv('DOCUMENT_EDITOR_OUTPUT')?:throw new RuntimeException('Set DOCUMENT_EDITOR_OUTPUT to a private disposable directory');
if(!is_dir($output)&&!mkdir($output,0770,true))throw new RuntimeException('Fixture directory unavailable');
RuntimeGuard::privatePath($output);
$source='<h1>Vietnam Document Fixture</h1><h2>Detailed Itinerary</h2><h3>Day 1 - Hanoi (B/L/D)</h3><p style="font-size:18pt;text-align:center;font-weight:700">Morning <i>visit</i> and <u>relax</u><br>Second line.</p><ul><li>Reviewed activity</li><li>Lunch</li></ul><table><tr><th>Time</th><th>Activity</th></tr><tr><td>09:00</td><td><b>City tour</b></td></tr></table><p><a href="javascript:bad()"><img src=x onerror="bad()"><script>bad()</script>Reviewed only</a></p><h2>Included</h2><p>Reviewed accommodation</p>';
$parsed=ScheduleImport::documentHtmlPreview($source);
editorCheck(count($parsed['days'])===1&&$parsed['days'][0]['meals']==='B/L/D','rich import maps existing itinerary day / meals');
editorCheck($parsed['extraction_quality']==='HIGH'&&$parsed['note']!=='','import returns extraction quality and actual parser note');
$blocks=$parsed['days'][0]['blocks'];$first=$blocks[0];
editorCheck($first['alignment']==='center'&&$first['runs'][0]['font_size']===18&&$first['runs'][0]['bold'],'rich parser preserves paragraph-level size / alignment / marks');
editorCheck(QuoteProposal::blockText([$first])==="Morning visit and relax\nSecond line.",'rich import / canonical save keeps run spaces and hard breaks');
editorCheck($first['runs'][1]['italic']&&!empty($first['runs'][3]['underline']),'nested inline marks survive typed validation');
editorCheck(!str_contains(json_encode($blocks),'bad()')&&(bool)array_filter($parsed['warnings'],fn($s)=>str_contains($s,'images were skipped')),'rich parser strips active content and reports skipped images');
editorCheck($blocks[1]['type']==='list'&&$blocks[2]['type']==='table','rich import retains ordered content / lists / tables');
$document=QuoteProposal::document(['schema'=>'VTA_DOC_1','title'=>$parsed['title'],'sections'=>array_intersect_key($parsed['sections'],array_flip(QuoteProposal::DOCUMENT_SECTIONS)),'days'=>['fixture-day'=>$blocks],'image_sizes'=>[],'review'=>['source_numbers'=>[1],'duration_days'=>1,'acknowledged'=>false]]);
$longKey=str_repeat('d',80).'|HOTEL_GALLERY|99999999999999999999|'.str_repeat('r',190);$document['image_sizes'][$longKey]=50;$document=QuoteProposal::document($document);editorCheck(isset($document['image_sizes'][$longKey]),'image-size identity preserves maximum day / supplier reference lengths');
file_put_contents($output.'/draft.json',MediaLibrary::json($document));
$reopened=QuoteProposal::document(json_decode(file_get_contents($output.'/draft.json'),true,512,JSON_THROW_ON_ERROR));
editorCheck($reopened===$document,'canonical draft serialization / independent reopen is lossless');
$snapshot=['tour_name'=>$document['title'],'quote_ref'=>'LOCAL-DOC-ONLY','version_no'=>1,'start_date'=>'2027-01-02','end_date'=>'2027-01-02','schedule'=>[['day'=>1,'day_key'=>'fixture-day','date'=>'2027-01-02','title'=>'Hanoi','description'=>QuoteProposal::blockText($blocks),'meals'=>'B/L/D','overnight'=>'Hanoi']],'presentation'=>['days'=>[['key'=>'fixture-day','fields'=>[]]],'settings'=>['template'=>'VTA_STANDARD_B2B','sections'=>['itinerary','included'],'document'=>$reopened],'media'=>[]]];
$html=ProposalOutput::html($snapshot,fn($a)=>'',true);
file_put_contents($output.'/document-editor.html',$html);
editorCheck(str_contains($html,'<strong>Morning </strong>')&&str_contains($html,'<u><em>')===false&&str_contains($html,'<u><strong>relax</strong></u>')&&str_contains($html,'text-align:center'),'HTML export keeps editable imported formatting and spaces');
$word=ProposalOutput::docx($snapshot,fn($a)=>'',true);file_put_contents($output.'/document-editor.docx',$word);
$zip=new ZipArchive();editorCheck($zip->open($output.'/document-editor.docx')===true,'DOCX export is a real readable ZIP');
$xml=$zip->getFromName('word/document.xml');$dom=new DOMDocument();editorCheck($dom->loadXML($xml,LIBXML_NONET),'DOCX document XML is well formed');$zip->close();
editorCheck(str_contains($xml,'<w:u w:val="single"/>')&&str_contains($xml,'<w:sz w:val="36"/>')&&str_contains($xml,'<w:jc w:val="center"/>'),'DOCX export retains underline / size / paragraph alignment');
$imported=DocumentParser::proposal($output.'/document-editor.docx','docx');
editorCheck(str_contains($imported['text'],"Morning visit and relax\nSecond line.")&&str_contains($imported['text'],'City tour'),'real DOCX reimport preserves formatted content and table prose');
$second=ScheduleImport::documentPreview($imported['text'],$imported);
editorCheck(count($second['days'])===1&&count($second['days'][0]['blocks'])>0,'exported DOCX imports again as editable itinerary');
$pdf=ProposalOutput::pdf($snapshot,['storage'=>['local_path'=>$output.'/storage']],fn($a)=>'',true);file_put_contents($output.'/document-editor.pdf',$pdf);
editorCheck(str_starts_with($pdf,'%PDF-')&&str_contains(substr($pdf,-40),'%%EOF')&&strlen($pdf)>15000,'PDF export produces a complete Unicode PDF');
$unavailable=DocumentParser::proposal($output.'/document-editor.pdf','pdf');
editorCheck(in_array($unavailable['quality'],['LOW','MEDIUM'],true)&&$unavailable['note']!=='','PDF import reports extractor availability / quality without inventing content');
file_put_contents($output.'/roundtrip-result.json',MediaLibrary::json(['result'=>'PASS','database'=>'NOT USED','pdf_import_quality'=>$unavailable['quality'],'pdf_import_note'=>$unavailable['note'],'pdf_inline_formatting'=>'Existing PDF renderer exports searchable text; inline marks/sizes are not rendered']));
echo "Document editor native roundtrip complete; no database connection.\n";
