const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const settle=async()=>{for(let i=0;i<18;i++)await new Promise(r=>setImmediate(r));};
const copy=x=>structuredClone(x),code=fs.readFileSync(path.join(__dirname,'../visual-proposal.js'),'utf8');
const rich=[{type:'heading',level:3,runs:[{text:'Morning programme',bold:true,italic:false}]},{type:'paragraph',runs:[{text:'Visit Hanoi\nwith guide',bold:true,italic:false},{text:' and relax',bold:false,italic:true}]},{type:'list',ordered:false,items:[[{text:'Temple visit',bold:false,italic:true}],[{text:'Lunch',bold:true,italic:false}]]},{type:'table',rows:[[[{text:'Time',bold:true,italic:false}],[{text:'Activity',bold:true,italic:false}]],[[{text:'09:00',bold:false,italic:false}],[{text:'City tour',bold:false,italic:true}]]]}];
function text(blocks){return blocks.flatMap(b=>b.runs?[b.runs.map(x=>x.text).join('')]:b.type==='list'?b.items.map((r,i)=>(b.ordered?(i+1)+'. ':'• ')+r.map(x=>x.text).join('')):b.rows.map(row=>row.map(c=>c.map(r=>r.text).join('')).join('\t'))).join('\n').trim();}
function seed(n=7){return {costing_revision:3,immutable:false,settings:{template:'VTA_STANDARD_B2B',sections:['schedule','itinerary','included'],accommodation:[],document:{schema:'VTA_DOC_1',title:'Vietnam 7D6N',sections:{included:[{type:'paragraph',runs:[{text:'Reviewed accommodation',bold:false,italic:false}]}]},days:Object.fromEntries(Array.from({length:n},(_,i)=>['day-'+(i+1),copy(rich)])),review:{source_numbers:[],duration_days:0,acknowledged:false}}},days:Array.from({length:n},(_,i)=>({day:i+1,day_key:'day-'+(i+1),date:'2027-01-'+String(i+2).padStart(2,'0'),title:'Journey '+(i+1),description:text(rich),meals:'B/L/D',overnight:'Hanoi',hotel:'Reviewed hotel',transport_mode:'private',activities:'City sightseeing',guide_required:true,overnight_type:'HOTEL',route:'Hanoi',destination:'Hanoi',public_notes:'Meet in lobby',internal_notes:'Synthetic private note'})),links:n?[{asset_id:1,role:'DAY_HERO',day_key:'day-2',reference_key:'',caption:'Hanoi',sort_order:0}]:[],requirements:[],templates:{VTA_STANDARD_B2B:'B2B'},selling_options:[]};}
async function open(store,locked=false){const dom=new JSDOM('<main></main><aside id="modals"></aside>',{url:'http://local.test',runScripts:'outside-only'}),w=dom.window,root=w.document.querySelector('main'),calls=[];w.eval(code);let fail=false;
 const api={request:async(route,opt={})=>{calls.push({route,...opt});if(opt.method==='PUT'){if(fail)throw Error('Synthetic stale save');assert.equal(opt.body.expected_revision,store.value.costing_revision);store.value=copy({...store.value,settings:opt.body.settings,days:opt.body.days,links:opt.body.links,costing_revision:store.value.costing_revision+1});}return copy({...store.value,immutable:locked});}};
 const modal=(title,body,footer='')=>{const m=w.document.createElement('section');m.innerHTML='<h2>'+title+'</h2>'+body+footer;w.document.querySelector('#modals').replaceChildren(m);return m;};
 await w.mountVisualProposal(root,{api,quoteData:{quote:{id:2,quote_ref:'LOCAL-P0'},version:{id:5,version_no:1,tour_name:'Vietnam',version_status:locked?'SENT':'DRAFT',start_date:'2027-01-02'}},can:()=>true,modal,closeModal:()=>w.document.querySelector('#modals').replaceChildren(),toast:()=>{},refresh:()=>{},onBack:()=>{}});
 return {dom,w,root,calls,failSave:x=>fail=x,save:async()=>{root.querySelector('[data-v22-save]').click();await settle();},action:(a,key)=>{const section=root.querySelector('[data-rich-day="'+key+'"]')?.closest('.df-day');assert(section,'Day exists');section.querySelector('[data-day-action="'+a+'"]').click();},edit:(selector,html)=>{const el=root.querySelector(selector);assert(el);el.innerHTML=html;el.dispatchEvent(new w.Event('input'));},keys:()=>[...root.querySelectorAll('[data-rich-day]')].map(x=>x.dataset.richDay)};
}
(async()=>{
 let store={value:seed()},h=await open(store);
 assert(h.root.querySelector('.df-document'));assert(h.root.querySelector('[data-add]'));assert.equal(h.root.querySelectorAll('[data-day-action=duplicate]').length,7);
 console.log('PASS P0 direct Add/Duplicate/Delete/Reorder controls stay in Document View');
 h.root.querySelector('[data-add]').click();const added=h.keys().at(-1);assert.equal(h.keys().length,8);assert.notEqual(added,'day-8');assert(h.root.querySelector('[data-day-field=title][data-key="'+added+'"]').matches(':focus'));
 h.edit('[data-day-field=title][data-key="'+added+'"]','Owner added day');h.edit('[data-rich-day="'+added+'"]','<p><strong>Owner added prose</strong><br>Second line</p>');await h.save();assert.equal(store.value.days.at(-1).title,'Owner added day');
 console.log('PASS P0 Add Day creates a unique immediately editable day and saves typed prose');
 h.root.querySelector('[data-add]').click();assert.equal(h.keys().length,9);h.root.querySelector('[data-undo]').click();assert.equal(h.keys().length,8);h.root.querySelector('[data-redo]').click();assert.equal(h.keys().length,9);h.root.querySelector('[data-undo]').click();
 console.log('PASS P0 Add Day undo/redo restores the complete draft in one operation');
 const sourceBefore=copy(store.value.days[1]),blocksBefore=copy(store.value.settings.document.days['day-2']);h.action('duplicate','day-2');const duplicate=h.keys()[2];assert.notEqual(duplicate,'day-2');assert.equal(h.keys().length,9);await h.save();
 const saved=store.value,duplicateDay=saved.days.find(d=>d.day_key===duplicate);for(const key of ['title','description','meals','hotel','transport_mode','activities','guide_required','route','destination','public_notes','internal_notes'])assert.equal(duplicateDay[key],sourceBefore[key]);assert.deepEqual(saved.settings.document.days[duplicate],blocksBefore);assert.equal(duplicateDay.date,'');assert.notStrictEqual(saved.settings.document.days[duplicate],saved.settings.document.days['day-2']);
 assert(h.root.querySelector('[data-rich-day="'+duplicate+'"] strong'));assert(h.root.querySelector('[data-rich-day="'+duplicate+'"] em'));assert(h.root.querySelector('[data-rich-day="'+duplicate+'"] ul'));assert(h.root.querySelector('[data-rich-day="'+duplicate+'"] table'));assert(h.root.querySelector('[data-rich-day="'+duplicate+'"] br'));assert.equal(saved.links.filter(l=>l.day_key===duplicate).length,1);
 console.log('PASS P0 Duplicate Day preserves paragraphs, breaks, bold/italic, lists, tables, structured day data and media');
 h.edit('[data-day-field=title][data-key="'+duplicate+'"]','Independent copied journey');h.edit('[data-rich-day="'+duplicate+'"]','<h3>Copied programme</h3><p><strong>Edited copy only</strong><br><em>Evening visit</em></p><ol><li>Separate activity</li></ol><table><tbody><tr><td>Time</td><td>Copy activity</td></tr><tr><td>17:00</td><td>Walk</td></tr></tbody></table>');await h.save();assert.deepEqual(store.value.settings.document.days['day-2'],blocksBefore);assert.equal(store.value.days.find(d=>d.day_key==='day-2').description,sourceBefore.description);assert.notEqual(store.value.days.find(d=>d.day_key===duplicate).description,sourceBefore.description);
 console.log('PASS P0 editing a duplicated day never changes source data or formatting');
 h.action('down',duplicate);assert.equal(h.keys()[3],duplicate);h.action('up',duplicate);assert.equal(h.keys()[2],duplicate);h.action('remove','day-7');h.action('remove','day-6');assert.equal(h.keys().length,7);assert(h.keys().includes(duplicate));assert(h.keys().includes(added));await h.save();assert.deepEqual(store.value.days.map(d=>d.day),[1,2,3,4,5,6,7]);assert(!store.value.settings.document.days['day-6']);assert(!store.value.settings.document.days['day-7']);
 console.log('PASS P0 duplicate/reorder/delete keeps independent day keys and consecutive numbering');
 h.action('remove',duplicate);assert(!h.keys().includes(duplicate));h.root.querySelector('[data-undo]').click();assert(h.keys().includes(duplicate));await h.save();assert(store.value.links.some(l=>l.day_key===duplicate));
 console.log('PASS P0 deleting and undoing a duplicate restores its formatted content and media assignments');
 const persisted=copy(store.value);h.dom.window.close();h=await open(store);assert.deepEqual(h.keys(),persisted.days.map(d=>d.day_key));assert(h.root.querySelector('[data-rich-day="'+duplicate+'"] strong'));assert(h.root.querySelector('[data-rich-day="'+duplicate+'"] table'));await h.save();assert.deepEqual(store.value.settings.document.days,persisted.settings.document.days);
 console.log('PASS P0 save/reload/reopen preserves all day identities and independent formatted copies');
 h.root.querySelector('[data-preview]').click();assert(h.w.document.querySelector('iframe').src.includes('proposal%2Fhtml'));assert(h.w.document.querySelector('a[href*="proposal%2Fpdf"]'));assert(h.w.document.querySelector('a[href*="proposal%2Fdocx"]'));
 console.log('PASS P0 reopened document preview/PDF/DOCX uses existing proposal output routes');
 h.failSave(true);h.edit('[data-day-field=title][data-key="'+duplicate+'"]','Retry copied title');await h.save();assert.equal(h.root.querySelector('[data-save-state]').textContent,'Save failed');assert.equal(store.value.days.find(d=>d.day_key===duplicate).title,'Independent copied journey');h.root.querySelector('[data-preview]').click();assert(h.root.querySelector('[data-v22-notice]').textContent.includes('Save'));h.failSave(false);await h.save();assert.equal(store.value.days.find(d=>d.day_key===duplicate).title,'Retry copied title');
 console.log('PASS P0 failed save preserves edits, reports failure and blocks stale preview until retry');
 h.root.querySelector('[data-advanced-view]').click();const originalIndex=store.value.days.findIndex(d=>d.day_key==='day-2');h.root.querySelector('[data-day="'+originalIndex+'"]').click();h.root.querySelector('[data-duplicate]').click();await h.save();const advancedCopy=store.value.days[originalIndex+1];assert.deepEqual(store.value.settings.document.days[advancedCopy.day_key],store.value.settings.document.days['day-2']);h.root.querySelector('[data-document-view]').click();h.action('remove',advancedCopy.day_key);await h.save();
 console.log('PASS P0 Advanced View reuses the same deep-copy day operation');
 const fixture=copy(store.value);if(process.env.VS2_DAY_UI_OUTPUT)fs.writeFileSync(process.env.VS2_DAY_UI_OUTPUT,JSON.stringify({settings:fixture.settings,days:fixture.days,links:fixture.links,duplicate_key:duplicate,source_key:'day-2',added_key:added}));h.dom.window.close();
 h=await open({value:seed(0)});h.root.querySelector('[data-add]').click();assert.equal(h.keys().length,1);await h.save();h.action('remove',h.keys()[0]);assert.equal(h.keys().length,1);h.dom.window.close();
 console.log('PASS P0 empty itinerary can add its first day and cannot delete its last day');
 h=await open({value:fixture},true);assert(!h.root.querySelector('[data-add]'));assert(!h.root.querySelector('[data-day-action]'));assert(!h.root.querySelector('[data-v22-save]'));assert.equal(h.root.querySelector('[data-rich-day]').getAttribute('contenteditable'),'false');h.dom.window.close();
 console.log('PASS P0 Sent/accepted document retains read-only controls and content');
 const chromeStore={value:seed(1)};h=await open(chromeStore);h.edit('[data-rich-day="day-1"]','<div><strong>Before list</strong><ul><li><b><i>Morning visit</i></b></li><li>Reviewed activity</li></ul><div><h3>Afternoon</h3><p><em>Second paragraph</em><br>Next line</p></div><div class="df-table-wrap"><table><tr><td>Cell</td><td><strong>Value</strong></td></tr></table></div></div>');const chromeList=h.root.querySelector('[data-rich-day] ul'),chromeParagraph=h.w.document.createElement('p');chromeList.replaceWith(chromeParagraph);chromeParagraph.append(chromeList);h.action('duplicate','day-1');await h.save();const chromeCopy=chromeStore.value.days[1],cb=chromeStore.value.settings.document.days[chromeCopy.day_key];assert.deepEqual(cb,chromeStore.value.settings.document.days['day-1']);assert.deepEqual(cb.map(b=>b.type),['paragraph','list','heading','paragraph','table']);assert.equal(cb[1].items[0][0].bold,true);assert.equal(cb[1].items[0][0].italic,true);assert.equal(cb[1].items.length,2);assert.equal(cb[2].level,3);assert.equal(cb[4].rows[0][1][0].bold,true);assert.equal(chromeCopy.description,'Before list\n• Morning visit\n• Reviewed activity\nAfternoon\nSecond paragraph\nNext line\nCell\tValue');h.dom.window.close();
 console.log('PASS P0 Chromium nested paragraph/list/div formatting survives duplicate and save in order');
})().catch(e=>{console.error(e);process.exitCode=1;});
