<?php
declare(strict_types=1);
require __DIR__.'/procurement-documents.php';
require_once __DIR__.'/../api/lib/FinanceLedger.php';
require_once __DIR__.'/../api/lib/InvoiceCommercial.php';
check(FinanceLedger::cents('0.10')+FinanceLedger::cents('0.20')===30,'ledger uses exact minor units');
rejects(fn()=>FinanceLedger::cents('1.001'),InvalidArgumentException::class,'fractional cents rejected');
$schedule=FinanceLedger::paymentSchedule($db,$user,$bid,['items'=>[['label'=>'Deposit','amount'=>'50.00','due_date'=>'2027-01-04'],['label'=>'Balance','amount'=>'87.50','due_date'=>'2027-01-04']]]);
rejects(fn()=>FinanceLedger::paymentSchedule($db,$user,$bid,['items'=>[['label'=>'Extra','amount'=>'1','due_date'=>'2027-01-04']]]),DomainException::class,'schedule cannot exceed booking value');
$i1=FinanceLedger::createInvoice($db,$user,$bid,['invoice_type'=>'PROFORMA','payment_schedule_id'=>$schedule['ids'][0],'issue_date'=>'2027-01-03']);
rejects(fn()=>FinanceLedger::paymentSchedule($db,$user,$bid,['replace'=>true,'items'=>[['label'=>'Replacement','amount'=>'1','due_date'=>'2027-01-04']]]),DomainException::class,'invoiced schedule cannot be replaced');
$i2=FinanceLedger::createInvoice($db,$user,$bid,['invoice_type'=>'CUSTOMER_INVOICE','subtotal'=>'87.50','issue_date'=>'2027-01-03','due_date'=>'2027-01-04']);
rejects(fn()=>FinanceLedger::createInvoice($db,$user,$bid,['subtotal'=>'137.50']),DomainException::class,'duplicate commercial/proforma billing rejected');
FinanceLedger::issueInvoice($db,$user,$i1['id']);FinanceLedger::issueInvoice($db,$user,$i2['id']);
$invoiceSnapshot=$db->query('SELECT public_snapshot_json FROM invoice_issue_snapshots WHERE invoice_id='.(int)$i1['id'])->fetchColumn();
check(str_contains($invoiceSnapshot,'not a Vietnamese VAT e-invoice'),'commercial invoice carries required disclaimer');
$receiptBody=['amount'=>'137.50','currency'=>'USD','payment_date'=>'2027-01-05','transaction_reference'=>'BANK-ONE','idempotency_key'=>'one-bank-transaction'];
$receipt=FinanceLedger::receipt($db,$user,$bid,$receiptBody);
check(FinanceLedger::receipt($db,$user,$bid,$receiptBody)===$receipt,'receipt retry creates one bank transaction');
rejects(fn()=>FinanceLedger::receipt($db,$user,$bid,array_replace($receiptBody,['amount'=>'150'])),DomainException::class,'receipt retry with changed amount rejected');
$allocation=['request_key'=>'split-one-payment','allocation_date'=>'2027-01-05','items'=>[['invoice_id'=>$i1['id'],'amount'=>'50.00'],['invoice_id'=>$i2['id'],'amount'=>'87.50']]];
FinanceLedger::allocate($db,$user,$receipt['id'],$allocation);FinanceLedger::allocate($db,$user,$receipt['id'],$allocation);
check($db->query('SELECT status FROM payment_schedules WHERE id='.(int)$schedule['ids'][0])->fetchColumn()==='PAID','allocation updates linked schedule');
check($db->query('SELECT customer_payment_status FROM bookings WHERE id='.$bid)->fetchColumn()==='PAID','allocation updates booking payment status');
check((int)$db->query('SELECT COUNT(*) FROM customer_receipts')->fetchColumn()===1&&(int)$db->query('SELECT COUNT(*) FROM payment_allocations')->fetchColumn()===2,'one receipt allocated to two invoices without duplicate bank transactions');
rejects(fn()=>FinanceLedger::allocate($db,$user,$receipt['id'],['request_key'=>'overallocate','allocation_date'=>'2027-01-05','items'=>[['invoice_id'=>$i1['id'],'amount'=>'0.01']]]),DomainException::class,'receipt over-allocation rejected');
$statement=FinanceLedger::statement($db,1,'CUSTOMER',$conversion['customer_id'],'2027-01-01','2027-01-05');
check((float)$statement['currencies']['USD']['closing']===0.0 && count($statement['outstanding'])===0,'partner statement reconciles issued invoices minus one receipt');
$historical=FinanceLedger::statement($db,1,'CUSTOMER',$conversion['customer_id'],'2027-01-01','2027-01-04');
check((float)$historical['currencies']['USD']['closing']===137.5 && count($historical['outstanding'])===2,'historical statement excludes later receipt and allocations');
$reconciliation=FinanceLedger::reconcile($db,$user,(int)$ap['id'],['supplier_invoice_no'=>'SUPINV-1','invoice_amount'=>'120.00','currency'=>'USD','reason'=>'Supplier documented additional parking']);
check($reconciliation['status']==='REVIEW_REQUIRED'&&$reconciliation['variance']===5,'supplier invoice variance needs review');
$profit=FinanceLedger::profit($db,1,$bid);check($profit['actual_profit']===null&&!$profit['actual_final'],'unreconciled supplier invoice prevents final actual profit');
FinanceLedger::approveReconciliation($db,$user,$reconciliation['id']);
$paymentBody=['amount'=>'120.00','currency'=>'USD','payment_date'=>'2027-01-06','transaction_reference'=>'SUPPLIER-BANK-ONE','idempotency_key'=>'supplier-payment-one'];
$payment=FinanceLedger::supplierPayment($db,$user,(int)$ap['id'],$paymentBody);
check((int)FinanceLedger::supplierPayment($db,$user,(int)$ap['id'],$paymentBody)['id']===(int)$payment['id'],'supplier payment retry idempotent');
rejects(fn()=>FinanceLedger::supplierPayment($db,$user,(int)$ap['id'],array_replace($paymentBody,['idempotency_key'=>'overpay','amount'=>'1.00'])),DomainException::class,'supplier overpayment rejected');
$profit=FinanceLedger::profit($db,1,$bid);
$beforeCommercial=FinanceLedger::statement($db,1,'CUSTOMER',$conversion['customer_id'],'2027-01-01','2027-01-05');
check($profit['actual_profit']===null,'paid proforma alone does not establish commercial actual profit');
$commercial=InvoiceCommercial::issue($db,$user,(int)$i1['id'],'2027-01-05');
check(InvoiceCommercial::issue($db,$user,(int)$i1['id'],'2027-01-05')===$commercial,'commercial issuance retry is idempotent');
rejects(fn()=>InvoiceCommercial::issue($db,$user,(int)$i1['id'],'2027-01-06'),DomainException::class,'commercial date immutable after issuance');
rejects(fn()=>InvoiceCommercial::issue($db,['id'=>2,'company_id'=>2],(int)$i1['id'],'2027-01-05'),OutOfBoundsException::class,'commercial document tenant isolation');
check((int)$db->query('SELECT COUNT(*) FROM customer_invoices')->fetchColumn()===2,'commercial document does not create another receivable');
check(FinanceLedger::statement($db,1,'CUSTOMER',$conversion['customer_id'],'2027-01-01','2027-01-05')===$beforeCommercial,'commercial issuance preserves statement and allocations');
$profit=FinanceLedger::profit($db,1,$bid);
check($profit['expected_profit']===27.5&&$profit['forecast_profit']===22.5&&$profit['actual_profit']===17.5,'expected forecast actual profit use distinct planned confirmed actual costs');
check(!$profit['actual_final'],'financial settlement alone does not finalize unfinished operations');
$db->exec("UPDATE bookings SET operation_completed_at=NOW() WHERE id=$bid");
$profit=FinanceLedger::profit($db,1,$bid);check($profit['actual_final'],'settled reconciled completed booking has final actual profit');
check($db->query('SELECT public_snapshot_json FROM invoice_issue_snapshots WHERE invoice_id='.(int)$i1['id'])->fetchColumn()===$invoiceSnapshot,'payment allocation preserves issued invoice snapshot');
echo "Lead to selected quote, booking, supplier confirmation, Travel Pack, invoices, allocation, statement, supplier payment and profit integration chain passed.\n";
