const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const base=path.join(__dirname,'..'),source=new JSDOM('',{url:'https://vta.test/',runScripts:'outside-only'}),w=source.window;
for(const f of ['marketing-model.js','landing-model.js','landing-extensions.js'])w.eval(fs.readFileSync(path.join(base,f),'utf8'));
const M=w.VTALandingModel,token='a'.repeat(64),ok=x=>console.log('PASS '+x);
function live(page,{preview=false,url='https://vta.test/landing/tour.html?utm_source=facebook&utm_campaign=india'}={}){const d=new JSDOM(M.html(page,{preview}),{url,runScripts:'outside-only'});d.window.eval(d.window.document.querySelector('script').textContent);return d;}
function fill(d){const f=d.window.document.querySelector('form');for(const [k,v] of Object.entries({contact_name:'Synthetic Guest',email:'test@example.invalid',total_guests:4,paying_pax:4,foc:0,message:'Synthetic test'}))f.elements[k].value=v;f.elements.consent.checked=true;return f;}
const submit=async(d,f)=>{f.dispatchEvent(new d.window.Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,0));};
(async()=>{
 const standard=M.normalize(M.template('standard')),pro=M.normalize(M.template('pro'));assert.equal(standard.blocks.length,12);assert.equal(pro.blocks[0].type,'hero_form');assert(pro.blocks.some(b=>b.type==='countdown'));assert.equal(M.normalize(JSON.parse(JSON.stringify(pro))).blocks.length,9);ok('Standard 6D5N and Pro templates serialize all supplied module types');
 const custom=M.template('standard');const gallery=custom.blocks.find(b=>b.type==='destinations_gallery');gallery.items=[{...M.item(),title:'Halong Bay',image:'https://example.invalid/photo.jpg',alt:'Tour photo',rights:'Owned by VTA'}];const review=custom.blocks.find(b=>b.type==='reviews');review.items=[{...M.item(),title:'Verified test',text:'<script>bad()</script>',url:'https://example.invalid/review'}];const itinerary=custom.blocks.find(b=>b.type==='itinerary');itinerary.items[0].text='Detailed day description';const html=M.html(custom),parsed=new JSDOM(html);assert.equal(parsed.window.document.querySelector('img').alt,'Tour photo');assert(!html.includes('cdn.tailwindcss.com'));assert(parsed.window.document.body.textContent.includes('<script>bad()</script>'));assert(parsed.window.document.body.textContent.includes('Detailed day description'));assert.equal(parsed.window.document.querySelectorAll('script').length,1);parsed.window.close();ok('gallery, detailed itinerary and reviews render escaped content without CDN dependencies');
 const page=M.template('pro');page.blocks[0].form_url='https://vta.test/request.html?form='+token;page.blocks.find(b=>b.type==='countdown').deadline='2000-01-01T00:00:00Z';let d=live(page);assert.equal(d.window.document.querySelector('[data-deadline]').textContent,'This offer has ended.');ok('expired countdown remains ended rather than resetting');
 let calls=[],fail=true;d.window.fetch=async(url,opt)=>{calls.push({url,body:JSON.parse(opt.body),credentials:opt.credentials});if(fail)throw Error('Simulated timeout');return {ok:true,json:async()=>({ok:true,id:55})};};let f=fill(d);await submit(d,f);assert.equal(calls.length,1);assert.equal(calls[0].url,'https://vta.test/api/lead-submit.php?form='+token);assert.equal(calls[0].body.contact_name,'Synthetic Guest');assert.equal(calls[0].body.total_guests,4);assert.equal(calls[0].body.utm_source,'facebook');assert.equal(calls[0].body.landing_url,'https://vta.test/landing/tour.html');assert.equal(calls[0].credentials,'omit');assert(!f.querySelector('button').disabled);ok('form maps actual Lead Hub JSON fields, public token and ad attribution');
 fail=false;await submit(d,f);assert.equal(calls[0].body.submission_key,calls[1].body.submission_key);assert(f.querySelector('fieldset').disabled);assert(f.textContent.includes('has been received'));await submit(d,f);assert.equal(calls.length,2);ok('retry keeps submission key and success prevents duplicate submission');d.window.close();
 d=live(page);f=fill(d);calls=[];d.window.fetch=async(_,o)=>{calls.push(JSON.parse(o.body));throw Error('Failure');};await submit(d,f);f.elements.message.value='Changed request';await submit(d,f);assert.notEqual(calls[0].submission_key,calls[1].submission_key);ok('editing a failed request generates a new idempotency key');d.window.close();
 d=live(page,{url:'file:///D:/test/vta-landing.html'});f=fill(d);let sent=0;d.window.fetch=async()=>{sent++;throw Error();};await submit(d,f);assert.equal(sent,0);assert(f.textContent.includes('Open this landing page on'));d.window.close();ok('downloaded local file cannot accidentally submit to the live API');
 d=live(page,{preview:true});assert(d.window.document.querySelector('fieldset').disabled);const csp=d.window.document.querySelector('[http-equiv="Content-Security-Policy"]').content;assert(csp.includes("connect-src 'none'"));assert(csp.includes("script-src 'nonce-"));d.window.close();ok('builder preview disables lead capture and blocks outbound connections with CSP');
 const unconfigured=M.template('pro');d=live(unconfigured);assert(d.window.document.querySelector('fieldset').disabled);d.window.close();ok('unconfigured form is visibly disabled');
 assert.throws(()=>M.formURL('https://vta.test/request.html?form=bad'));const bad=M.template('pro');bad.blocks[1].deadline='2026-02-30T12:00:00Z';assert.throws(()=>M.normalize(bad));bad.blocks[1].deadline='';bad.blocks[0].items=Array.from({length:21},M.item);assert.throws(()=>M.normalize(bad));ok('invalid form tokens, calendar dates and item limits rejected');
 source.window.close();console.log('NOTE: generated-page runtime uses mocked fetch; no lead was sent to hosting.');
})().catch(e=>{console.error(e);process.exitCode=1;source.window.close();});
