const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const base=path.join(__dirname,'..');
const dom=new JSDOM('<main id="workspace" data-view="marketing"><div id="host"></div></main>',{url:'file:///D:/vta/preview.html',runScripts:'outside-only'}),w=dom.window,d=w.document,host=d.querySelector('#host');
w.VTA_PREVIEW=true;w.confirm=()=>true;const downloads=[],messages=[];let network=0;w.fetch=()=>{network++;throw Error('No network');};w.URL.createObjectURL=b=>{downloads.push(b);return 'blob:test';};w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){};
for(const f of ['marketing-model.js','landing-model.js','landing-extensions.js','landing-builder.js'])w.eval(fs.readFileSync(path.join(base,f),'utf8'));
const M=w.VTALandingModel,options={api:{user:{id:1,company_id:10},request(){network++;throw Error('Real API from demo');}},can:()=>true,toast:t=>messages.push(t),campaigns:[{id:1,name:'India to Vietnam'}]};
const click=async(a,id)=>{const target=host.querySelector(`[data-lp="${a}"]${id?'[data-id="'+id+'"]':''}`);assert(target,a);await host.onclick({target});};
function input(selector,value){const e=host.querySelector(selector);assert(e,selector);e.value=value;host.oninput({target:e});}
const ids=()=>[...host.querySelectorAll('[data-block]')].map(b=>b.dataset.block);
function drag(source,target){host.ondragstart({target:source,stopPropagation(){},dataTransfer:{setData(){}}});host.ondragover({target,preventDefault(){}});host.ondrop({target,preventDefault(){}});}
function ok(s){console.log('PASS '+s);}
(async()=>{
 await w.VTALandingBuilder(host,options);assert.equal(ids().length,12);ok('builder opens offline file preview with tour template');
 const original=ids();drag(host.querySelector('[data-add="image"]'),host.querySelector('[data-block]'));assert.equal(ids().length,13);assert(host.querySelector('[data-block]').textContent.includes('Ảnh'));ok('palette drag inserts block before the actual drop target');
 const photo=ids()[0];drag(host.querySelector('[data-drag="'+photo+'"]'),host.querySelector('[data-end]'));assert.equal(ids().at(-1),photo);ok('drag handle reorders existing block to page end');
 await click('undo');assert.equal(ids()[0],photo);await click('redo');assert.equal(ids().at(-1),photo);ok('undo and redo restore document order');
 await click('up',photo);assert.equal(ids().at(-2),photo);await click('duplicate',photo);assert.equal(ids().length,14);assert.equal(new Set(ids()).size,14);await click('remove',ids().at(-2));assert.equal(ids().length,13);ok('touch and keyboard buttons move, duplicate with fresh ID and delete');
 await click('select',original[0]);input('[data-prop="title"]','<img src=x onerror=bad()>');assert(!host.querySelector('.lp-mini img'));assert(host.textContent.includes('<img src=x onerror=bad()>'));input('[data-prop="url"]','javascript:alert(1)');await click('html');assert.equal(downloads.length,0);assert(messages.at(-1).includes('HTTPS'));input('[data-prop="url"]','https://wa.me/84000000000');ok('editor escapes text and rejects script URLs before export');
 await click('mobile');const frame=host.querySelector('iframe');assert(frame.classList.contains('mobile'));assert.equal(frame.getAttribute('sandbox'),'allow-scripts');const rendered=new JSDOM(frame.srcdoc);assert(!rendered.window.document.querySelector('img'));assert.equal(rendered.window.document.querySelectorAll('script').length,1);assert.equal(rendered.window.document.querySelector('a').href,'https://wa.me/84000000000');assert(rendered.window.document.querySelector('[http-equiv="Content-Security-Policy"]').content.includes("form-action 'none'"));rendered.window.close();await click('desktop');assert(!host.querySelector('iframe').classList.contains('mobile'));ok('responsive preview uses sandboxed, trusted runtime with isolated preview document');
 await click('edit');await click('save');assert(host.textContent.includes('Đã lưu v1'));await click('select',original[0]);input('[data-prop="title"]','Changed after save');await click('save');assert(host.textContent.includes('Đã lưu v2'));await click('json');await click('html');assert.equal(downloads.length,2);ok('demo save updates same record and exports JSON plus standalone HTML');
 host.querySelector('#lpTemplate').value='blank';await click('new');assert.equal(ids().length,0);host.querySelector('#lpOpen').value='1';await click('open');assert.equal(ids().length,13);assert(host.textContent.includes('Changed after save'));ok('saved page reopens with original content and block order');
 const imported=M.template('short');imported.title='Imported design';await host.onchange({target:{id:'lpImport',files:[{size:100,text:async()=>JSON.stringify(imported)}],value:'chosen'}});assert.equal(ids().length,3);assert.equal(host.querySelector('[data-setting="title"]').value,'Imported design');ok('JSON import restores editable design');
 host.querySelector('#lpTemplate').value='pro';await click('new');assert.equal(ids().length,9);const proIds=ids();await click('select',proIds[1]);input('[data-prop="deadline"]','2026-12-31T23:30');await click('tablet');assert(host.querySelector('iframe').classList.contains('tablet'));assert(host.querySelector('iframe').srcdoc.includes('2026-12-31T16:30:00Z'));await click('edit');await click('select',proIds[4]);await click('item-add',proIds[4]);assert.equal(host.querySelectorAll('.lp-item-editor fieldset').length,3);input('[data-item="2"][data-prop="title"]','Custom option');input('[data-item="2"][data-prop="price"]','On request');await click('save');await click('mobile');assert(host.querySelector('iframe').srcdoc.includes('Custom option'));await click('edit');console.log('PASS Pro template, fixed UTC+7 deadline, tablet preview and editable pricing items');
 const p=M.template();p.blocks[0].type='__proto__';assert.throws(()=>M.normalize(p));p.blocks[0].type='hero';p.blocks[1].id=p.blocks[0].id;assert.throws(()=>M.normalize(p));p.blocks=Array(41).fill(p.blocks[0]);assert.throws(()=>M.normalize(p));for(const u of ['http://bad.test','https://u:p@bad.test','data:text/html,bad','https:\\bad.test'])assert.throws(()=>M.url(u));const photoDoc=M.template();photoDoc.blocks[0].image='https://example.invalid/photo.jpg';assert.throws(()=>M.normalize(photoDoc));ok('import validates type allowlist, duplicate IDs, size, links and image attribution');
 assert.equal(network,0);ok('demo makes no API or provider call');
 w.VTA_PREVIEW=false;let writes=0;await w.VTALandingBuilder(host,{...options,can:()=>false,api:{user:{id:22,company_id:10},request:async(r,o)=>{if(o?.method==='POST')writes++;return {pages:[]};}}});assert(host.querySelector('[data-lp="save"]').disabled);await click('save');assert.equal(writes,0);assert(host.querySelector('[data-add]').disabled);ok('read-only account cannot save or add blocks');
 // Integration: evaluate the scripts named by the real preview HTML, in shipped order.
 const shell=new JSDOM('<div id="app"></div>',{url:'file:///D:/vta/preview.html',runScripts:'outside-only'}),sw=shell.window;sw.VTA_PREVIEW=true;sw.TextEncoder=TextEncoder;sw.confirm=()=>true;const observers=[],OriginalObserver=sw.MutationObserver;sw.MutationObserver=class extends OriginalObserver{constructor(cb){super(cb);observers.push(this);}};
 const scripts=[...fs.readFileSync(path.join(base,'preview.html'),'utf8').matchAll(/<script src="([^?" ]+)/g)].map(m=>m[1]);
 for(const f of scripts)sw.eval(fs.readFileSync(path.join(base,f),'utf8'));
 await new Promise(r=>setTimeout(r,100));const nav=sw.document.querySelector('[data-nav="marketing"]')||sw.document.querySelector('[data-module="marketing"]');assert(nav);nav.click();await new Promise(r=>setTimeout(r,100));const tab=sw.document.querySelector('[data-mk="tab"][data-id="webhooks"]');assert(tab,sw.document.querySelector("#workspace").textContent);assert(!sw.document.querySelector('[data-mk="tab"][data-id="landing"]'));tab.click();await new Promise(r=>setTimeout(r,20));assert(sw.document.querySelector('#mkWebhookCenter'));assert(sw.document.querySelector('#mkWebhookCenter').textContent.includes('Demo mode'));assert(!sw.document.querySelector('.lp-builder'));ok('real preview shell opens the current Webhooks tab; standalone landing builder stays covered above');observers.forEach(o=>o.disconnect());await Promise.resolve();shell.window.close();dom.window.close();
 console.log('NOTE: jsdom event simulation, not a real browser/device or live-host test.');
})().catch(e=>{console.error(e);process.exitCode=1;dom.window.close();});
