'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..');
const RealDate=Date;
class PreviewDate extends RealDate {
  constructor(...args){super(...(args.length?args:['2026-09-30T20:30:00Z']))}
  static now(){return new RealDate('2026-09-30T20:30:00Z').getTime()}
}
const context={window:{},URLSearchParams,Date:PreviewDate,console};vm.createContext(context);
const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
vm.runInContext(app.slice(app.indexOf('class ApiClient{'),app.indexOf('const api=PREVIEW?'))+'\nglobalThis.demoApi=new DemoApi();',context);
vm.runInContext(fs.readFileSync(path.join(root,'operations-demo.js'),'utf8'),context);
const api=context.demoApi,handle=(route,opt)=>context.window.VTAOperationsDemo.handle(api,route,opt),post=body=>({method:'POST',body}),put=body=>({method:'PUT',body}),plain=value=>JSON.parse(JSON.stringify(value));
const rejects=(fn,status)=>assert.throws(fn,error=>error.status===status);
let groups=0;
function test(name,fn){fn();groups++;console.log('PASS '+name)}
test('Unhandled routes are delegated without fabricating success',()=>{assert.equal(handle('travel-documents/123/generate',post({})),undefined);assert.equal(handle('v3/operations',{method:'DELETE'}),undefined)});
test('Default date uses current UTC+7 and does not move November demo services to today',()=>{const day=handle('v3/operations');assert.equal(day.date,'2026-10-01');assert.equal(day.movement.length,0);assert.equal(day.readiness.length,0)});
test('Both query styles return selected-day production-shaped movement and readiness',()=>{const day=handle('v3/operations&date=2026-11-15');assert.deepEqual(plain(day),plain(handle('v3/operations?date=2026-11-15')));assert.equal(day.movement.length,2);assert.equal(day.readiness.length,1);assert.equal(day.readiness[0].booking_id,1);assert.equal(day.readiness[0].guest_count,1);assert.equal(day.readiness[0].checks.guest_list,false);assert.equal(day.readiness[0].checks.no_critical_issues,false);assert.equal(handle('v3/operations?date=2026-11-17').movement.length,1);assert.equal(handle('v3/operations?date=2026-11-16').movement.length,0);rejects(()=>handle('v3/operations?date=2026-02-30'),422)});
test('Legacy departures honors the actual date window and timeline date',()=>{assert.equal(handle('operations/departures?days=30').items.length,0);assert.equal(handle('operations/departures&days=45').items.length,1);assert.equal(handle('operations/departures&days=45').items[0].service_count,3);assert.equal(handle('operations/timeline?date=2026-11-15').items.length,2);assert.equal(handle('operations/timeline?date=2026-11-17').items.length,1)});
test('Resource creation validates types and seat capacity',()=>{assert.equal(handle('v3/resources').items.length,3);const created=handle('v3/resources',post({kind:'VEHICLE',name:'Preview coach',capacity:'30'}));assert.equal(created.preview_only,true);assert.equal(handle('v3/resources').items.find(r=>r.id===created.id).capacity,30);rejects(()=>handle('v3/resources',post({kind:'VEHICLE',name:'Bad',capacity:0})),422);rejects(()=>handle('v3/resources',post({kind:'HOTEL',name:'Bad'})),422)});
let driverAssignment,vehicleAssignment;
const assignment={resource_id:2,starts_at:'2026-11-15 14:00:00',ends_at:'2026-11-15 18:00:00'};
test('Assignment retries are stable and readiness uses actual assigned resource capacity',()=>{driverAssignment=handle('services/1/assign',post(assignment));assert.equal(handle('services/1/assign',post(assignment)).id,driverAssignment.id);vehicleAssignment=handle('services/1/assign',post({...assignment,resource_id:3}));assert.equal(handle('bookings/1/readiness').checks.resource_assignment,true);assert.equal(api.services.find(s=>s.id===1).driver_name,'[Preview] Hanoi driver');assert.equal(handle('bookings/1/readiness').services.find(s=>s.service_id===1).assigned.length,2)});
test('Overlapping assignments, wrong dates, invalid timestamps and incomplete intervals are rejected',()=>{api.services.push({id:99,booking_id:1,service_name:'Preview overlapping transfer',service_date:'2026-11-15',start_time:'15:00',end_time:'16:00',category:'TRANSPORT',booking_status:'CONFIRMED'});rejects(()=>handle('services/99/assign',post(assignment)),409);rejects(()=>handle('services/1/assign',post({...assignment,starts_at:'2026-11-15 14:30:00'})),409);rejects(()=>handle('services/1/assign',post({...assignment,starts_at:'2026-11-16 14:00:00',ends_at:'2026-11-16 18:00:00'})),409);rejects(()=>handle('services/1/assign',post({...assignment,starts_at:'2026-11-15 25:00:00'})),422);rejects(()=>handle('services/99/assign',post({...assignment,resource_id:1,ends_at:'2026-11-15 15:30:00'})),409);api.services.pop()});
test('Cancellation removes assignments from readiness and updates legacy contacts',()=>{rejects(()=>handle('resource-assignments/'+driverAssignment.id+'/cancel',post({reason:''})),422);handle('resource-assignments/'+driverAssignment.id+'/cancel',post({reason:'Preview reassignment'}));assert.equal(api.services.find(s=>s.id===1).driver_name,null);assert.equal(handle('bookings/1/readiness').checks.resource_assignment,false);handle('assignments/'+vehicleAssignment.id+'/cancel',post({reason:'Preview reassignment'}));assert.equal(handle('bookings/1/readiness').services.find(s=>s.service_id===1).assigned.length,0)});
let issue;
test('Incident creation validates owner, severity, required content and booking',()=>{const before=handle('bookings/1/issues').items.length;rejects(()=>handle('bookings/1/issues',post({title:'Bad owner',description:'Preview',owner_user_id:999})),422);rejects(()=>handle('bookings/1/issues',post({title:'Bad severity',description:'Preview',severity:'URGENT'})),422);rejects(()=>handle('bookings/1/issues',post({title:'Missing content'})),422);rejects(()=>handle('bookings/999/issues',post({title:'Missing booking',description:'Preview'})),404);assert.equal(handle('bookings/1/issues').items.length,before);issue=handle('bookings/1/issues',post({title:'Preview guide delay',description:'Sample operational incident',severity:'CRITICAL'}));assert.equal(issue.preview_only,true);assert.equal(handle('bookings/1/issues').items.length,before+1)});
test('Incident resolution requires follow-up details and updates live readiness',()=>{const resolution={root_cause:'Supplier mismatch',resolution:'Guide reassigned',lessons_learned:'Check guide before arrival',financial_impact:'12.50',currency:'USD'};rejects(()=>handle('issues/'+issue.id+'/resolve',post({resolution:'Incomplete'})),422);rejects(()=>handle('issues/'+issue.id+'/resolve',post({...resolution,financial_impact:'-1'})),422);handle('issues/'+issue.id+'/resolve',post(resolution));assert.equal(handle('bookings/1/issues').items.find(i=>i.id===issue.id).financial_impact,12.5);rejects(()=>handle('issues/'+issue.id+'/resolve',post(resolution)),409);handle('issues/1/resolve',post({...resolution,financial_impact:'0'}));assert.equal(handle('v3/operations?date=2026-11-15').issues.length,0);assert.equal(handle('bookings/1/readiness').checks.no_critical_issues,true)});
test('Travel detail defaults use every customer-facing production field',()=>{const details=handle('services/2/travel-details').details;assert.deepEqual(Object.keys(details).sort(),['address','cabin_type','check_in','check_out','emergency_phone','guest_instructions','inclusions','meal_plan','meeting_point','room_type','rooming'].sort());assert.ok(Object.values(details).every(value=>value===''));rejects(()=>handle('services/999/travel-details'),404)});
test('Travel detail partial edits preserve old values and validate dates before mutation',()=>{const first=handle('services/2/travel-details',put({room_type:' Deluxe Twin ',address:'Hanoi',check_in:'2026-11-15',check_out:'2026-11-17'}));assert.equal(first.preview_only,true);assert.equal(first.details.room_type,'Deluxe Twin');handle('services/2/travel-details',put({meal_plan:'Breakfast'}));assert.equal(handle('services/2/travel-details').details.room_type,'Deluxe Twin');assert.equal(handle('services/2/travel-details').details.meal_plan,'Breakfast');rejects(()=>handle('services/2/travel-details',put({check_out:'2026-11-15'})),422);rejects(()=>handle('services/2/travel-details',put({check_in:'2026-02-30'})),422);rejects(()=>handle('services/2/travel-details',put({room_type:15})),422);rejects(()=>handle('services/2/travel-details',put({room_type:'ế'.repeat(64)})),422);assert.equal(handle('services/2/travel-details').details.check_out,'2026-11-17');const response=handle('services/2/travel-details');response.details.address='Mutated response';assert.equal(handle('services/2/travel-details').details.address,'Hanoi')});
const payment={amount:'1000000.00',payment_date:'2026-10-01',currency:'VND',transaction_reference:' PREVIEW-BANK-001 ',idempotency_key:'preview-payment-001'};
test('Supplier payments update AP and record one in-memory payment with integer cents',()=>{const p=api.payables.find(p=>p.id===1),beforePaid=Number(p.paid_amount),beforeBalance=Number(p.balance),result=handle('payables/1/payments',post(payment));assert.equal(result.preview_only,true);assert.match(result.payment_ref,/PREVIEW/);assert.equal(p.paid_amount,beforePaid+1000000);assert.equal(p.balance,beforeBalance-1000000);assert.equal(p.status,'PART_PAID');assert.equal(api.supplierPayments.length,1);assert.equal(api.supplierPayments[0].transaction_reference,'PREVIEW-BANK-001')});
test('Payment retry accepts equivalent amount formatting without reducing balance twice',()=>{const before=api.payables.find(p=>p.id===1).balance,first=api.supplierPayments[0],retry=handle('payables/1/payments',post({...payment,amount:1000000,transaction_reference:'PREVIEW-BANK-001'}));assert.equal(retry.id,first.id);assert.equal(retry.payment_ref,first.payment_ref);assert.equal(api.payables.find(p=>p.id===1).balance,before);assert.equal(api.supplierPayments.length,1);rejects(()=>handle('payables/1/payments',post({...payment,amount:'1000001'})),409);rejects(()=>handle('payables/2/payments',post(payment)),409)});
test('Invalid payment requests leave AP and payment lists untouched',()=>{const before=plain(api.payables),count=api.supplierPayments.length;for(const patch of [{amount:'0'},{amount:'-1'},{amount:'1.001'},{currency:'USD'},{payment_date:'2026-02-30'},{transaction_reference:''},{idempotency_key:''}])rejects(()=>handle('payables/1/payments',post({...payment,idempotency_key:'preview-invalid',...patch})),422);rejects(()=>handle('payables/1/payments',post({...payment,idempotency_key:'preview-overpay',amount:'999999999'})),409);rejects(()=>handle('payables/999/payments',post(payment)),404);assert.deepEqual(plain(api.payables),before);assert.equal(api.supplierPayments.length,count)});
test('Full payment marks the payable paid and its retry succeeds after the balance reaches zero',()=>{const p=api.payables.find(p=>p.id===1),body={...payment,amount:String(p.balance),idempotency_key:'preview-final-payment',transaction_reference:'PREVIEW-BANK-002'},result=handle('payables/1/payments',post(body));assert.equal(p.balance,0);assert.equal(p.paid_amount,p.total_amount);assert.equal(p.status,'PAID');assert.equal(handle('payables/1/payments',post(body)).id,result.id);assert.equal(api.supplierPayments.length,2);assert.equal(handle('finance/ap').items.find(row=>row.id===1).balance,0)});
test('Preview state is isolated per DemoApi and does not persist across a new instance',()=>{vm.runInContext('globalThis.secondApi=new DemoApi();',context);const second=context.secondApi,resourceList=context.window.VTAOperationsDemo.handle(second,'v3/resources');assert.equal(resourceList.items.length,3);assert.equal(context.window.VTAOperationsDemo.handle(second,'services/2/travel-details').details.room_type,'');assert.equal(second.supplierPayments.length,0);assert.equal(second.payables[0].balance,7750000)});
test('Internal approvals receives contract arrays and tasks created from the global form appear',()=>{const count=api.tasks.length,newTask=handle('tasks',post({title:'Check new program',priority:'HIGH',due_at:'2026-11-15 09:00:00'}));assert.equal(api.tasks.length,count+1);assert.equal(api.tasks.at(-1).id,newTask.id);const overview=handle('v3/control-center');for(const key of ['tasks','quote_reviews','supplier_reviews','alerts'])assert(Array.isArray(overview[key]));assert(overview.tasks.some(t=>t.title==='Check new program'));rejects(()=>handle('tasks',post({title:'Invalid task',priority:'INVALID'})),422);assert.equal(api.tasks.length,count+1)});
console.log(`${groups} operations preview behavior groups passed`);
