<?php
declare(strict_types=1);
require_once __DIR__.'/../api/lib/ServiceTravelDetails.php';
require __DIR__.'/quote-options.php';
require_once __DIR__.'/../api/lib/Procurement.php';
require_once __DIR__.'/../api/lib/TravelDocuments.php';
$bid=(int)$booking['id'];
$orders=Procurement::generate($db,$user,$bid);$oid=(int)$orders['items'][0]['id'];
check($orders['items'][0]['status']==='DRAFT','new procurement creates DRAFT');
check(Procurement::generate($db,$user,$bid)===$orders,'repeated order generation creates no duplicate');
rejects(fn()=>Procurement::confirm($db,$user,$oid,['status'=>'CONFIRMED']),DomainException::class,'draft cannot be confirmed before explicit send');
rejects(fn()=>TravelDocuments::create($db,$user,$bid,['kind'=>'TRAVEL_PACK']),DomainException::class,'unconfirmed services block Travel Pack');
Procurement::send($db,$user,$oid);
$confirmation=['status'=>'CONFIRMED','confirmation_no'=>'CONFIRMED-TEST','confirmation_source'=>'EMAIL','currency'=>'USD','confirmed_total'=>115];
rejects(fn()=>Procurement::confirm($db,$user,$oid,$confirmation+['service_ids'=>[999999]]),InvalidArgumentException::class,'unrelated service confirmation rejected');
Procurement::confirm($db,$user,$oid,$confirmation);
$ap=$db->query('SELECT * FROM supplier_payables WHERE supplier_order_id='.$oid)->fetch();
check((float)$ap['total_amount']===115.0,'AP uses explicit confirmed cost rather than planned amount');
Procurement::confirm($db,$user,$oid,$confirmation);
check((int)$db->query('SELECT COUNT(*) FROM supplier_payables WHERE supplier_order_id='.$oid)->fetchColumn()===1,'confirmation retry does not duplicate AP');
rejects(fn()=>Procurement::confirm($db,$user,$oid,array_replace($confirmation,['confirmed_total'=>130])),DomainException::class,'reconfirmation cannot silently desynchronize AP');
$doc=TravelDocuments::create($db,$user,$bid,['kind'=>'TRAVEL_PACK']);$docid=$doc['id'];
rejects(fn()=>TravelDocuments::transition($db,$user,$docid,'issue'),DomainException::class,'document cannot skip review');
TravelDocuments::transition($db,$user,$docid,'review');TravelDocuments::transition($db,$user,$docid,'ready');
TravelDocuments::transition($db,$user,$docid,'issue');
$row=$db->query('SELECT * FROM travel_document_versions WHERE id='.(int)$docid)->fetch();$before=$row['public_snapshot_json'];
check($row['status']==='ISSUED','Travel Pack issued');
$html=TravelDocuments::html($row);
check(str_contains($html,'Transfer to hotel')&&str_contains($html,'CONFIRMED-TEST'),'Travel Pack contains full itinerary and confirmation voucher');
check(!str_contains($before,'cost')&&!str_contains($before,'supplier')&&!str_contains($before,'margin')&&!str_contains($before,'package_price'),'hidden-price Travel Pack excludes financial internals');
$db->exec("UPDATE booking_services SET pickup_location='Changed pickup' WHERE booking_id=$bid");
check($db->query('SELECT public_snapshot_json FROM travel_document_versions WHERE id='.(int)$docid)->fetchColumn()===$before,'issued document remains unchanged after service edits');
$doc2=TravelDocuments::create($db,$user,$bid,['kind'=>'TRAVEL_PACK']);
TravelDocuments::transition($db,$user,$doc2['id'],'review');TravelDocuments::transition($db,$user,$doc2['id'],'ready');
$db->exec("UPDATE booking_services SET pickup_location='Changed again' WHERE booking_id=$bid");
rejects(fn()=>TravelDocuments::transition($db,$user,$doc2['id'],'issue'),DomainException::class,'stale reviewed document cannot issue');
$doc3=TravelDocuments::create($db,$user,$bid,['kind'=>'TRAVEL_PACK','visibility'=>'PACKAGE_PRICE']);
TravelDocuments::transition($db,$user,$doc3['id'],'review');TravelDocuments::transition($db,$user,$doc3['id'],'ready');TravelDocuments::transition($db,$user,$doc3['id'],'issue');
check($db->query('SELECT status FROM travel_document_versions WHERE id='.(int)$docid)->fetchColumn()==='SUPERSEDED','new issue supersedes old without overwriting content');
check($db->query('SELECT public_snapshot_json FROM travel_document_versions WHERE id='.(int)$docid)->fetchColumn()===$before,'superseded version retains exact original content');
rejects(fn()=>TravelDocuments::snapshot($db,2,$bid,'TRAVEL_PACK','HIDE_PRICE'),OutOfBoundsException::class,'travel documents enforce tenant ownership');
echo "Procurement and versioned Travel Pack integration checks complete.\n";
