<?php
declare(strict_types=1);
require __DIR__.'/lead-hub.php';
require_once __DIR__.'/../api/lib/QuoteOptions.php';
check(QuoteOptions::pricing(100,10,'MARKUP',20)['total_selling']===120.0,'20 percent markup on cost');
check(QuoteOptions::pricing(100,10,'TARGET_MARGIN',20)['total_selling']===125.0,'20 percent target margin differs from markup');
check(QuoteOptions::pricing(100,10,'MANUAL',9)['profit']===-10.0,'manual override recomputes real loss');
rejects(fn()=>QuoteOptions::pricing(100,10,'TARGET_MARGIN',100),InvalidArgumentException::class,'100 percent target margin rejected');
$db->exec("UPDATE rate_versions SET approval_status='APPROVED',tax_basis='NET' WHERE id=1");
$db->exec("INSERT INTO transport_rate_rules(rate_version_id,capacity,hours_included,km_included,overtime_rate,extra_km_rate) VALUES(1,16,8,100,10,2)");
$db->exec("UPDATE quote_versions SET adults=10,children=0,infants=0,total_guests=11,paying_pax=10,foc=1,start_date='2027-01-02',end_date='2027-01-02',schedule_json='[{\"title\":\"Arrival\",\"description\":\"Transfer to hotel\",\"internal_cost\":999,\"notes\":\"secret supplier rate\"}]' WHERE id=$qvid");
$body=['label'=>'Comfort','hotel_level'=>'4*','pricing_mode'=>'TARGET_MARGIN','pricing_value'=>20,'rounding_step'=>0,'lines'=>[['rate_version_id'=>1,'pax'=>1,'qty'=>1,'service_date'=>'2027-01-02']]];
$transportBody=$body;$transportBody['lines'][0]['transport_usage']=['vehicles'=>1,'days'=>1,'hours'=>9,'km'=>110];
$withExtras=QuoteOptions::save($db,$user,$qvid,$transportBody);check($withExtras['pricing']['cost_total']===140.0,'quote transport costing includes approved overtime and extra kilometres');
$savedLines=json_decode($db->query('SELECT snapshot_json FROM quote_options WHERE id='.(int)$withExtras['id'])->fetchColumn(),true)['lines'];
foreach($savedLines as $line)check(abs($line['total']-$line['pax']*$line['qty']*$line['unit_price'])<0.001,'each transport cost line preserves pax times qty times unit');
$transportBody['lines']=$savedLines;check(QuoteOptions::save($db,$user,$qvid,$transportBody)['pricing']['cost_total']===140.0,'recosting does not duplicate transport supplements');
$option4=QuoteOptions::save($db,$user,$qvid,$body);
check($option4['pricing']['cost_total']===110.0,'option uses seasonal approved amount from server');
$body3=$body;$body3['label']='Value';$body3['hotel_level']='3*';$body3['pricing_mode']='MARKUP';$body3['pricing_value']=10;$option3=QuoteOptions::save($db,$user,$qvid,$body3);
$body5=$body;$body5['label']='Luxury';$body5['hotel_level']='5*';$body5['pricing_value']=30;$option5=QuoteOptions::save($db,$user,$qvid,$body5);
check((int)$db->query('SELECT COUNT(*) FROM quote_options')->fetchColumn()===3,'three hotel options in one quote');
rejects(fn()=>QuoteOptions::send($db,$user,$qvid),DomainException::class,'unapproved bundle cannot send');
QuoteOptions::approve($db,$user,$qvid,'Reviewed all rates and margins');
$db->exec("UPDATE quote_versions SET tour_name='Changed title' WHERE id=$qvid");
rejects(fn()=>QuoteOptions::send($db,$user,$qvid),DomainException::class,'content change invalidates approval fingerprint');
QuoteOptions::approve($db,$user,$qvid,'Reviewed changed title');
$sent=QuoteOptions::send($db,$user,$qvid);$public=json_encode($sent,JSON_THROW_ON_ERROR);
check(!str_contains($public,'supplier')&&!str_contains($public,'margin')&&!str_contains($public,'internal_cost')&&!str_contains($public,'unit_price'),'customer snapshot strips internal fields including nested schedule');
check(count($sent['customer_safe_snapshot']['options'])===3,'sent customer snapshot contains all options');
check(QuoteOptions::send($db,$user,$qvid)===$sent,'send retry returns unchanged snapshot');
rejects(fn()=>QuoteOptions::save($db,$user,$qvid,$body),DomainException::class,'sent option immutable');
rejects(fn()=>QuoteOptions::approve($db,$user,$qvid,'Reapprove'),DomainException::class,'sent bundle cannot be reapproved');
rejects(fn()=>QuoteOptions::confirm($db,$user,$qvid,999999),InvalidArgumentException::class,'foreign option cannot be accepted');
QuoteOptions::confirm($db,$user,$qvid,$option4['id']);
rejects(fn()=>QuoteOptions::confirm($db,$user,$qvid,$option3['id']),DomainException::class,'accepted option cannot be switched');
$booking=QuoteOptions::booking($db,$user,$qvid);$retry=QuoteOptions::booking($db,$user,$qvid);
check((int)$booking['id']===(int)$retry['id'],'booking retry idempotent');
$bk=$db->query('SELECT * FROM bookings WHERE id='.(int)$booking['id'])->fetch();
check((float)$bk['confirmed_selling']===$option4['pricing']['total_selling'],'booking selling from accepted 4-star snapshot');
$svc=$db->query('SELECT * FROM booking_services WHERE booking_id='.(int)$booking['id'])->fetch();
check((float)$svc['planned_cost']===110.0 && (float)$svc['pax']===1.0,'booking services copied from accepted cost snapshot');
$db->exec('UPDATE rate_versions SET amount=999 WHERE id=1');
$snapshot=$db->query('SELECT internal_snapshot_json FROM booking_quote_snapshots WHERE booking_id='.(int)$booking['id'])->fetchColumn();
check((float)json_decode($snapshot,true)['accepted_option']['snapshot']['pricing']['cost_total']===110.0,'later supplier rate change cannot rewrite booking cost');
echo "Multi-option quote and accepted-booking checks complete.\n";
