<?php
declare(strict_types=1);
// The imported fixture creates a fresh random database on the explicitly configured local test server.
require __DIR__.'/document-freeform-native.php';
require_once __DIR__.'/../api/lib/TourLibrary.php';
$clone=QuoteReuse::clone($db,$user,(int)v2v()['id'],(int)v2v()['inquiry_id'],'FULL_DRAFT');$qvid=(int)$clone['version_id'];
$historical=v2q('SELECT * FROM quote_sent_bundles ORDER BY quote_version_id')->fetchAll();
$bookingsBefore=v2q('SELECT * FROM booking_quote_snapshots ORDER BY booking_id')->fetchAll();
$p=fn($s)=>['type'=>'paragraph','content'=>[['type'=>'text','text'=>$s]]];$cell=fn($s)=>['type'=>'tableCell','content'=>[$p($s)]];
$companyImage=MediaLibrary::ingest($db,$cfg,$user,$bytes,['title'=>'Program public landscape','visibility'=>'COMPANY']);$companyId=(int)$companyImage['asset']['id'];MediaLibrary::review($db,$user,$companyId,['status'=>'APPROVED']);
$doc=['schema'=>'VTA_DOC_2','title'=>'Library Word master','content'=>['type'=>'doc','content'=>[$p('MASTER PROGRAM PROSE'),['type'=>'table','content'=>[['type'=>'tableRow','content'=>[$cell('09:00'),$cell('Hanoi visit')]]]],['type'=>'image','attrs'=>['assetId'=>$companyId,'width'=>320]],['type'=>'table','attrs'=>['vtaSection'=>'pricing'],'content'=>[['type'=>'tableRow','content'=>[$cell('UNREVIEWED_PRICE_CANARY')]]]]]]];
$created=TourLibrary::save($db,$user,['title'=>'Reusable Hanoi','destination'=>'Hanoi','language'=>'en','status'=>'ACTIVE','days'=>[],'proposal'=>['tour_code'=>'VTA-NATIVE','tour_type'=>'PRIVATE','document'=>$doc]]);$programId=(int)$created['id'];
$masterBefore=TourProgramWorkspace::program($db,$user,$programId);$ctx=TourProgramWorkspace::context($db,$user,$masterBefore);
check(!str_contains(json_encode($ctx),'UNREVIEWED_PRICE_CANARY'),'Program native excludes marked sample prices');
$versionBefore=v2v();$identityKeys=['quote_id','inquiry_id','tour_name','start_date','end_date','paying_pax','total_guests','foc','fx_rate','schedule_json','total_cost','total_selling','cost_json'];
$identity=array_intersect_key($versionBefore,array_flip($identityKeys));
$graphBefore=QuoteVs2Repository::graph($db,v2v());
$applied=TourProgramWorkspace::apply($db,$user,$programId,$qvid,['expected_revision'=>(int)$versionBefore['costing_revision'],'program_revision'=>$ctx['costing_revision']]);
check(array_intersect_key(v2v(),array_flip($identityKeys))===$identity,'Program native apply preserves trip identity, customer link, pax, dates, FX, schedule and pricing totals');
$graphAfter=QuoteVs2Repository::graph($db,v2v());unset($graphBefore['version'],$graphAfter['version']);
check($graphBefore===$graphAfter,'Program native apply preserves every guest profile, requirement, variant and cost line byte');
check(TourProgramWorkspace::program($db,$user,$programId)===$masterBefore,'Program native copying never writes the master');
check($applied['settings']['document']['schema']==='VTA_DOC_2'&&FreeformDocument::imageIds($applied['settings']['document'])===[$companyId],'Program native copy preserves editable table and assigned approved photo');
$edited=$applied['settings'];$edited['document']['content']['content'][]=$p('TOUR COPY EDIT');
QuoteProposal::save($db,$user,$qvid,['expected_revision'=>$applied['costing_revision'],'settings'=>$edited,'links'=>$applied['links']]);
check(str_contains(json_encode(QuoteProposal::context($db,$user,v2v())['settings']),'TOUR COPY EDIT')&&TourProgramWorkspace::program($db,$user,$programId)===$masterBefore,'Program native edit/save/reload remains independent of the master');
$frozenVersion=v2v();
rejects(fn()=>TourProgramWorkspace::apply($db,$user,$programId,$qvid,['expected_revision'=>(int)$versionBefore['costing_revision'],'program_revision'=>$ctx['costing_revision']]),DomainException::class,'Program native stale quote revision blocked');
rejects(fn()=>TourProgramWorkspace::apply($db,$user,$programId,$qvid,['expected_revision'=>(int)v2v()['costing_revision'],'program_revision'=>str_repeat('0',64)]),DomainException::class,'Program native stale master preview blocked');
check(v2v()===$frozenVersion,'Program native rejected copies preserve the target bytes');
rejects(fn()=>TourProgramWorkspace::program($db,['company_id'=>2,'id'=>2],$programId),OutOfBoundsException::class,'Program native tenant boundary enforced');
$quoteImage=MediaLibrary::ingest($db,$cfg,$user,$bytes,['title'=>'Private quote photo','quote_id'=>v2v()['quote_id']]);$quoteImageId=(int)$quoteImage['asset']['id'];
$current=QuoteProposal::context($db,$user,v2v());$current['settings']['document']['content']['content'][]=['type'=>'image','attrs'=>['assetId'=>$quoteImageId,'width'=>160]];$current['links'][]=['asset_id'=>$quoteImageId,'role'=>'SERVICE','day_key'=>'','reference_key'=>'FREEFORM','caption'=>'Photo'];
QuoteProposal::save($db,$user,$qvid,['expected_revision'=>$current['costing_revision'],'settings'=>$current['settings'],'links'=>$current['links']]);
$request=['expected_revision'=>(int)v2v()['costing_revision'],'title'=>'Saved copy','destination'=>'Hanoi','language'=>'en','tour_type'=>'SIC','reviewed'=>true,'creation_key'=>'native-program-creation-0001'];
rejects(fn()=>TourProgramWorkspace::fromQuote($db,$cfg,$user,$qvid,array_replace($request,['reviewed'=>false])),InvalidArgumentException::class,'Program native saving requires content review');
$newMaster=TourProgramWorkspace::fromQuote($db,$cfg,$user,$qvid,$request);$replayed=TourProgramWorkspace::fromQuote($db,$cfg,$user,$qvid,$request);
check($newMaster['id']===$replayed['id']&&$replayed['replayed'],'Program native retries create one master');
$newDoc=$newMaster['program']['proposal']['document'];$ids=FreeformDocument::imageIds($newDoc);$personalId=(int)array_values(array_diff($ids,[$companyId]))[0];$personal=MediaLibrary::asset($db,$user,$personalId);
check($personalId!==$quoteImageId&&$personal['quote_id']===null&&$personal['visibility']==='PERSONAL'&&$personal['status']==='DRAFT','Program native quote photo becomes an unbound personal copy without broadening permissions');
check(MediaLibrary::asset($db,$user,$quoteImageId)['quote_id']==v2v()['quote_id'],'Program native source quote photo stays bound to its original quote');
$public=['quote_ref'=>'PROGRAM-TEST','presentation'=>['settings'=>['document'=>$newDoc],'media'=>TourProgramWorkspace::images($db,$user,$newDoc)]];
$imagePath=fn($id)=>MediaLibrary::path($cfg,MediaLibrary::asset($db,$user,$id));
$word=ProposalOutput::docx($public,$imagePath);file_put_contents($output.'/library-roundtrip.docx',$word);$reimport=DocumentParser::proposal($output.'/library-roundtrip.docx','docx');
check(str_contains($reimport['text'],'TOUR COPY EDIT')&&count($reimport['images'])===2&&count(array_filter($reimport['blocks'],fn($b)=>$b['type']==='table'))===1,'Program native Word export/reimport retains edited prose, table and embedded photos');
$pdf=ProposalOutput::pdf($public,$cfg,$imagePath);check(str_starts_with($pdf,'%PDF-'),'Program native PDF output renders the saved program');
$masterContext=TourProgramWorkspace::context($db,$user,$masterBefore);$masterContext['settings']['document']['content']['content'][]=$p('MASTER UPDATED');
$masterSaved=TourProgramWorkspace::saveDocument($db,$user,$programId,['expected_revision'=>$masterContext['costing_revision'],'settings'=>$masterContext['settings'],'metadata'=>['title'=>'Updated master','tour_type'=>'BOTH']]);
check($masterSaved['program']['title']==='Updated master'&&$masterSaved['program']['tour_type']==='BOTH','Program native Word canvas saves metadata and document through one revision guard');
rejects(fn()=>TourProgramWorkspace::saveDocument($db,$user,$programId,['expected_revision'=>$masterContext['costing_revision'],'settings'=>$masterContext['settings']]),DomainException::class,'Program native simultaneous master edits conflict');
rejects(fn()=>TourProgramWorkspace::apply($db,$user,$programId,$oldVersion,['expected_revision'=>(int)QuoteOptions::version($db,1,$oldVersion)['costing_revision'],'program_revision'=>$masterSaved['costing_revision']]),DomainException::class,'Program native issued version cannot accept a program');
check(v2q('SELECT * FROM quote_sent_bundles ORDER BY quote_version_id')->fetchAll()===$historical&&v2q('SELECT * FROM booking_quote_snapshots ORDER BY booking_id')->fetchAll()===$bookingsBefore,'Program native preserves historical sent and booking snapshot bytes');
echo "Tour program workspace native acceptance complete.\n";
