const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const appSource=fs.readFileSync(path.join(__dirname,'../app.js'),'utf8');
const workspaceSource=fs.readFileSync(path.join(__dirname,'../workspace-centers.js'),'utf8');
const copy=value=>JSON.parse(JSON.stringify(value));
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const keys=['new_leads','need_qualification','followup_today','overdue_followup','draft_quotes','sent_quotes','waiting_client','confirmed_today','lost'];
const stamp={as_of:'2026-10-01T09:00:00+07:00',timezone:'Asia/Ho_Chi_Minh',date_range:{today:'2026-10-01',start:'2026-10-01 00:00:00',end:'2026-10-02 00:00:00'}};
const unavailable={available:false,total:null,items:[],limit:8,offset:0};
function homeData(){return {ok:true,...copy(stamp),preview_only:true,access:{marketing:true,sales:true,operations:false,tasks:false},metrics:{marketing_pending:0,new_leads:1,sales_followups_due:null,departures_today:null,bookings_at_risk:null,my_tasks_due:null},attention:{sales:copy(unavailable),operations:copy(unavailable),tasks:copy(unavailable)}};}
function salesData(queue=''){return {ok:true,...copy(stamp),preview_only:true,metrics:Object.fromEntries(keys.map(k=>[k,['new_leads','need_qualification'].includes(k)?1:null])),definitions:Object.fromEntries(keys.map(k=>[k,'Definition '+k])),queues:Object.fromEntries((queue?[queue]:keys).map(k=>[k,['new_leads','need_qualification'].includes(k)?{available:true,total:1,limit:30,offset:0,items:[{entity_type:'lead_request',id:8,ref:'8',title:'Hanoi',contact:'Focus lead',status:'NEW'}]}:copy(unavailable)]))};}
function reportData(month='2026-10'){return {ok:true,month,timezone:'Asia/Ho_Chi_Minh',sales:{inquiries:10,confirmed:4,lost:2},bookings:{bookings:2,at_risk:1},revenue_by_currency:[{currency:'USD',amount:1000,bookings:1},{currency:'VND',amount:25000000,bookings:1}],profit_by_currency:[{currency:'USD',expected_profit:100,forecast_profit:80,actual_profit:null,actual_final_count:0,pending_actual_count:1,review_required_count:0},{currency:'VND',expected_profit:2500000,forecast_profit:2000000,actual_profit:0,actual_final_count:1,pending_actual_count:0,review_required_count:0}],profit_review_required:[]};}
function harness(permissions,{actualCenters=false,handle=null}={}){
 const dom=new JSDOM('<div id="app"></div>',{url:'https://localhost/',runScripts:'outside-only'}),w=dom.window,d=w.document,calls=[],errors=[];
 w.VTA_PREVIEW=true;w.VTA_I18N={language:'en',t:x=>x};w.addEventListener('error',e=>{errors.push(e.error||e.message);e.preventDefault();});
 const bridge='window.shellTest={api,state,can,renderShell,navigate,showDocumentReview,showInquiryForm,showCustomerForm,showAgentForm,renderBookingFinanceV3};';
 assert.equal(appSource.match(/\nboot\(\);/g)?.length,1,'boot bridge must replace one call');w.eval(appSource.replace('\nboot();','\n'+bridge));
 const a=w.shellTest;
 const booking=id=>copy({ok:true,booking:{...a.api.bookings[0],id,booking_ref:'BKG-'+id,lead_guest_name:'Guest '+id},trip:{...a.api.trip,title:'Trip '+id},guests:[],flights:[],services:[],orders:[],finance:{},documents:[],activity:[]});
 const quote=id=>copy({ok:true,quote:{...a.api.quote,id,quote_ref:'QT-'+id},trip:{...a.api.trip,title:'Quote trip '+id},version:{...a.api.qv,id:100+id,quote_id:id,tour_name:'Quote '+id,version_status:'SENT'},cost_items:[]});
 a.api.user={id:1,company_id:1,role_code:'TEST',permissions:[...permissions]};
 a.api.request=async(route,options={})=>{
  calls.push({route,options:copy(options)});
  if(handle){const response=await handle(route,options,{a,w,d,booking,quote,calls});if(response!==undefined)return response;}
  if(route==='workspace/home')return homeData();
  if(route.startsWith('workspace/sales'))return salesData(new URL(route,'https://test/').searchParams.get('queue')||'');
  if(/^bookings\/\d+$/.test(route))return booking(Number(route.split('/')[1]));
  if(/^quotes\/\d+$/.test(route))return quote(Number(route.split('/')[1]));
  if(route.startsWith('reports/summary?'))return reportData(new URL(route,'https://test/').searchParams.get('month'));
  if(['inquiries','quotes','customers','agents','documents','suppliers','bookings','finance/ar','finance/ap','finance/profitability'].includes(route)||route.startsWith('inquiries?id='))return {ok:true,items:[]};
  throw Error('Unexpected request '+route);
 };
 if(actualCenters)w.eval(workspaceSource);else{w.VTAWorkspaceHome=async()=>{d.querySelector('#workspace').innerHTML='<h1>Home dashboard</h1>';};w.VTAWorkspaceSales=async()=>{d.querySelector('#workspace').innerHTML='<h1>Sales center</h1>';};}
 w.VTAOperationsCenter=async()=>{d.querySelector('#workspace').innerHTML='<h1>Operations center</h1>';};
 a.renderShell();return {a,w,d,calls,errors,booking,quote,close:()=>w.close()};
}
async function settle(){for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r));}
async function click(h,selector){const element=h.d.querySelector(selector);assert(element,'Missing '+selector);element.click();await settle();return element;}
async function submit(h,selector){const form=h.d.querySelector(selector);assert(form,'Missing '+selector);form.dispatchEvent(new h.w.Event('submit',{bubbles:true,cancelable:true}));await settle();}
let groups=0;
async function test(name,permissions,fn,options={}){const h=harness(permissions,options);try{await fn(h);assert.equal(h.errors.length,0,'Unexpected DOM event errors');groups++;console.log('PASS '+name);}finally{h.close();}}
(async()=>{
 await test('Home New Leads forwards initialQueue into real Sales card/API filter',['lead.view'],async h=>{await h.a.navigate('home');await click(h,'[data-wsc-metric="new_leads"]');assert.equal(h.a.state.view,'sales');assert(h.calls.some(c=>c.route==='workspace/sales?queue=new_leads&limit=30&offset=0'));assert(h.d.querySelector('[data-wsc-queue="new_leads"]').classList.contains('active'));assert(h.d.querySelector('[data-wsc-queue-panel]').textContent.includes('Focus lead'));},{actualCenters:true});
 await test('Readonly Sales disables create controls and guards direct create handlers/forms',['sales.view'],async h=>{
  await h.a.navigate('sales-list',{salesTab:'inquiries'});assert(h.d.querySelector('#newInquiry').disabled);const quoteButton=h.d.querySelector('[data-create-quote]');assert(quoteButton.disabled);const count=h.calls.length;quoteButton.onclick();await settle();assert.equal(h.calls.length,count);h.a.showInquiryForm();h.a.showCustomerForm();h.a.showAgentForm();assert(!h.d.querySelector('.modal-backdrop'));assert.equal(h.calls.length,count);
 },{handle:route=>route==='inquiries'?{items:[{id:12,inquiry_ref:'INQ-12',title:'Read only',status:'NEW'}]}:undefined});
 for(const scenario of [{name:'empty supplier list',suppliers:[],permission:true,status:'REJECTED'},{name:'missing associated supplier',suppliers:[{id:2,name:'Other supplier'}],permission:true,status:'ARCHIVED'},{name:'no supplier read permission',suppliers:[],permission:false,status:'REJECTED'}]){
  const doc={id:9,supplier_id:77,supplier_name:'Associated supplier',original_filename:'Source.txt',document_ref:'DOC-9',document_type:'CONTRACT',review_status:scenario.status,notes:'Existing'};
  await test('Shared Document review preserves association/status with '+scenario.name,['document.view','document.review',...(scenario.permission?['supplier.view']:[])],async h=>{
   await h.a.navigate('documents');await click(h,'[data-shared-doc="9"]');const form=h.d.querySelector('#docReview');assert(form);assert.equal(form.elements.supplier_id.value,'77');assert.equal(form.elements.review_status.value,scenario.status);assert.equal(form.elements.supplier_id.disabled,!scenario.permission);form.elements.notes.value='Reviewed notes';await click(h,'#saveDocReview');const put=h.calls.find(c=>c.route==='documents/9/review');assert.equal(put.options.body.review_status,scenario.status);if(scenario.permission)assert.equal(put.options.body.supplier_id,'77');else assert(!Object.hasOwn(put.options.body,'supplier_id'),'disabled supplier field must be omitted for backend-preserve semantics');assert.equal(doc.supplier_id,77);assert.equal(doc.review_status,scenario.status);assert.equal(doc.notes,'Reviewed notes');assert.equal(h.a.state.view,'documents');assert(h.d.querySelector('[data-shared-doc="9"]'));if(!scenario.permission)assert(!h.calls.some(c=>c.route==='suppliers'));
  },{handle:(route,opt)=>{if(route==='documents')return {items:[copy(doc)]};if(route==='suppliers')return {items:copy(scenario.suppliers)};if(route==='documents/9/review'){Object.assign(doc,opt.body);if(Object.hasOwn(opt.body,'supplier_id'))doc.supplier_id=Number(opt.body.supplier_id)||null;return {ok:true,item:copy(doc)};}}});
 }
 await test('Booking role finance deep link cannot fetch ledger, statement or profit',['booking.view'],async h=>{await h.a.navigate('booking',{bookingId:1,bookingTab:'finance'});assert(h.d.querySelector('[data-booking-tab="overview"]').classList.contains('active'));assert(!h.d.querySelector('[data-booking-tab="finance"]'));assert.deepEqual(h.calls.map(c=>c.route),['bookings/1']);const count=h.calls.length;await h.a.renderBookingFinanceV3(h.d.querySelector('#bookingBody'),h.booking(1));assert.equal(h.calls.length,count);});
 for(const tab of ['ar','profitability'])await test('Finance '+tab+' rows cannot deep link booking without booking.view',['finance.view',tab==='ar'?'customer_ar.view':'profit.view'],async h=>{await h.a.navigate('finance',{financeTab:tab});const row=h.d.querySelector('#financeBody tbody tr');assert(row);assert(!row.hasAttribute('data-fin-booking'));assert(!row.classList.contains('clickable'));const count=h.calls.length;row.click();await settle();assert.equal(h.calls.length,count);assert.equal(h.a.state.view,'finance');},{handle:route=>route===(tab==='ar'?'finance/ar':'finance/profitability')?{items:[{id:1,booking_ref:'BKG-1',lead_guest_name:'Finance guest',currency:'USD',total:100,paid:0,balance:100,status:'UNPAID',confirmed_selling:100,selling_currency:'USD',expected_profit:30,forecast_profit:20,actual_profit:10,actual_final:true,start_date:'2026-10-01'}]}:undefined});
 await test('Reports separate currencies and distinguish pending actual from actual zero',['report.view','profit.view'],async h=>{await h.a.navigate('reports',{reportMonth:'2026-10'});const text=h.d.querySelector('#workspace').textContent;assert(text.includes('$1,000.00'));assert(text.includes('25,000,000'));const usd=[...h.d.querySelectorAll('h3')].find(e=>e.textContent==='USD').parentElement,vnd=[...h.d.querySelectorAll('h3')].find(e=>e.textContent==='VND').parentElement;assert(usd.textContent.includes('Pending reconciliation'));assert(!usd.textContent.includes('$0.00'));assert(vnd.textContent.includes('Finalized actual:'));assert(!vnd.textContent.includes('Pending reconciliation'));assert(text.includes('Currencies are shown separately'));});
 await test('Report without profit permission hides returned private profit data',['report.view'],async h=>{await h.a.navigate('reports',{reportMonth:'2026-10'});assert(h.d.querySelector('#workspace').textContent.includes('Profit access is restricted'));assert(!h.d.querySelector('h3'));assert(!h.d.querySelector('#workspace').textContent.includes('777,777'));},{handle:route=>{if(route.startsWith('reports/summary')){const r=reportData();r.profit_by_currency[0].actual_profit=777777;r.profit_review_required=[{booking_ref:'PRIVATE-PROFIT',currency:'USD',reason:'Private'}];return r;}}});
 await test('Report month form changes persisted period and API query',['report.view'],async h=>{await h.a.navigate('reports',{reportMonth:'2026-10'});h.d.querySelector('#reportPeriod [name=month]').value='2026-09';await submit(h,'#reportPeriod');assert.equal(h.a.state.reportMonth,'2026-09');assert.equal(h.calls.at(-1).route,'reports/summary?month=2026-09');assert.equal(h.d.querySelector('#reportPeriod [name=month]').value,'2026-09');});
 const reportSlow=deferred();await test('Delayed report cannot replace Home after navigation',['report.view'],async h=>{const loading=h.a.navigate('reports',{reportMonth:'2026-09'});await settle();await h.a.navigate('home');reportSlow.resolve(reportData('2026-09'));await loading;assert.equal(h.a.state.view,'home');assert(h.d.querySelector('#workspace').textContent.includes('Home dashboard'));},{handle:route=>route==='reports/summary?month=2026-09'?reportSlow.promise:undefined});
 const oldMonth=deferred();await test('Newer report month wins when older response resolves later',['report.view'],async h=>{const old=h.a.navigate('reports',{reportMonth:'2026-09'});await settle();await h.a.navigate('reports',{reportMonth:'2026-11'});oldMonth.resolve(reportData('2026-09'));await old;assert.equal(h.d.querySelector('#reportPeriod [name=month]').value,'2026-11');assert.equal(h.a.state.reportMonth,'2026-11');},{handle:route=>route==='reports/summary?month=2026-09'?oldMonth.promise:undefined});
 for(const kind of ['booking','quote']){
  const permission=kind==='booking'?'booking.view':'sales.view',idParam=kind==='booking'?'bookingId':'quoteId',slow=deferred();
  await test('Delayed '+kind+' detail cannot replace Home',[permission],async h=>{const pending=h.a.navigate(kind,{[idParam]:1});await settle();await h.a.navigate('home');slow.resolve(kind==='booking'?h.booking(1):h.quote(1));await pending;assert.equal(h.a.state.view,'home');assert(h.d.querySelector('#workspace').textContent.includes('Home dashboard'));},{handle:route=>route===kind+'s/1'?slow.promise:undefined});
  const older=deferred();await test('Delayed '+kind+' detail cannot replace newer record ID',[permission],async h=>{const pending=h.a.navigate(kind,{[idParam]:1});await settle();await h.a.navigate(kind,{[idParam]:2});older.resolve(kind==='booking'?h.booking(1):h.quote(1));await pending;assert.equal(h.a.state[idParam],2);assert(h.d.querySelector('#workspace').textContent.includes((kind==='booking'?'BKG-':'QT-')+'2'));assert(!h.d.querySelector('#workspace').textContent.includes((kind==='booking'?'BKG-':'QT-')+'1'));assert.equal(h.a.state[kind==='booking'?'bookingData':'quoteData'][kind].id,2);},{handle:route=>route===kind+'s/1'?older.promise:undefined});
 }
 await test('CRM customer button passes numeric ID into the actual Customer360 mount',['sales.view'],async h=>{
  await h.a.navigate('crm',{crmTab:'customers'});await click(h,'[data-customer-360="25"]');
  assert.equal(h.a.state.view,'customer-360');assert.equal(h.a.state.customerId,25);
  assert(h.calls.some(c=>c.route==='customers/25/360'));assert(h.d.querySelector('#workspace').textContent.includes('Customer 360 · Reviewed customer'));
 },{actualCenters:true,handle:route=>{
  if(route==='customers')return {items:[{id:25,full_name:'Reviewed customer',customer_ref:'CUS-25',status:'ACTIVE'}]};
  if(route==='customers/25/360')return {ok:true,customer:{id:25,full_name:'Reviewed customer'},sections:Object.fromEntries(['inquiries','quotes','activity'].map(k=>[k,{available:true,items:[],total:0,has_more:false}]))};
 }});
 console.log(groups+' VS0/VS1 shell interaction groups passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
