<?php
declare(strict_types=1);
// Production methods and SQL execute against SQLite fixtures. MySQL-specific locking/upsert
// syntax is adapted only in the test driver; this suite does not claim MariaDB or HTTP E2E coverage.
require_once __DIR__.'/../api/lib/CoreOS.php';
require_once __DIR__.'/../api/lib/QuoteOptions.php';
final class VS0Response extends RuntimeException {public function __construct(public array $body,public int $status){parent::__construct('HTTP '.$status);}}
final class Http {
    public static array $input=[];
    public static function body(): array {return self::$input;}
    public static function json(array $body,int $status=200): never {throw new VS0Response($body,$status);}
}
final class Auth {
    public static array $permissions=[];
    public static function can(PDO $db,int $uid,string $permission): bool {return in_array($permission,self::$permissions,true);}
    public static function requirePermission(PDO $db,array $u,string $permission): void {if(!self::can($db,(int)$u['id'],$permission))Http::json(['ok'=>false,'error'=>'FORBIDDEN'],403);}
}
final class Audit {public static function log(...$args): void {}public static function activity(...$args): void {}}
final class VS0PDO extends PDO {
    public array $queries=[];
    public function prepare(string $query,array $options=[]): PDOStatement|false {
        $this->queries[]=$query;$query=preg_replace('/\s+FOR UPDATE\b/i','',$query);
        if(str_contains($query,'INSERT INTO quote_bundle_approvals'))$query=str_replace('ON DUPLICATE KEY UPDATE content_hash=VALUES(content_hash),reason=VALUES(reason),approved_by=VALUES(approved_by),approved_at=NOW()','ON CONFLICT(quote_version_id) DO UPDATE SET content_hash=excluded.content_hash,reason=excluded.reason,approved_by=excluded.approved_by,approved_at=NOW()',$query);
        return parent::prepare($query,$options);
    }
}
$checks=0;
function vsSame(mixed $actual,mixed $expected,string $label): void {global $checks;if($actual!==$expected)throw new RuntimeException('FAIL '.$label.' expected '.var_export($expected,true).' got '.var_export($actual,true));$checks++;echo "PASS $label\n";}
function vsReject(callable $f,string $class,string $label): Throwable {global $db;try{$f();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();vsSame($e instanceof $class,true,$label);return $e;}throw new RuntimeException('FAIL accepted '.$label);}
function vsResponse(callable $f): VS0Response {global $db;try{$f();}catch(VS0Response $r){if($db->inTransaction())$db->rollBack();return $r;}throw new RuntimeException('Expected HTTP response');}
function vsInsert(PDO $db,string $table,array $row): int {$fields=array_keys($row);$s=$db->prepare('INSERT INTO '.$table.'('.implode(',',$fields).') VALUES('.implode(',',array_fill(0,count($fields),'?')).')');$s->execute(array_values($row));return (int)$db->lastInsertId();}
if(!in_array('sqlite',PDO::getAvailableDrivers(),true))throw new RuntimeException('PDO SQLite required; no unexecuted success is reported.');
$db=new VS0PDO('sqlite::memory:',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$db->sqliteCreateFunction('NOW',fn()=>'2026-10-01 12:00:00',0);$db->sqliteCreateFunction('DATABASE',fn()=>'fixture',0);
$db->exec("ATTACH DATABASE ':memory:' AS information_schema;CREATE TABLE information_schema.tables(table_schema TEXT,table_name TEXT);INSERT INTO information_schema.tables VALUES('fixture','trips')");
$schemas=[
 'users'=>'id INTEGER PRIMARY KEY,company_id INTEGER,status TEXT,full_name TEXT',
 'customers'=>'id INTEGER PRIMARY KEY,company_id INTEGER,customer_ref TEXT,customer_type TEXT,full_name TEXT,company_name TEXT,country TEXT,market TEXT,whatsapp TEXT,email TEXT,preferred_language TEXT,source TEXT,notes TEXT,sales_owner_id INTEGER,status TEXT,created_by INTEGER,updated_by INTEGER',
 'agents'=>'id INTEGER PRIMARY KEY,company_id INTEGER,status TEXT',
 'trips'=>'id INTEGER PRIMARY KEY,company_id INTEGER,trip_ref TEXT,title TEXT,customer_id INTEGER,agent_id INTEGER,lead_contact_name TEXT,lead_whatsapp TEXT,lead_email TEXT,market TEXT,start_date TEXT,end_date TEXT,adults INTEGER,children INTEGER,infants INTEGER,foc INTEGER,total_guests INTEGER,paying_pax INTEGER,currency TEXT,lifecycle_stage TEXT,sales_owner_id INTEGER,operations_owner_id INTEGER,created_by INTEGER,updated_by INTEGER',
 'inquiries'=>"id INTEGER PRIMARY KEY,company_id INTEGER,inquiry_ref TEXT,trip_id INTEGER,request_text TEXT,destination_text TEXT,hotel_level TEXT,meals TEXT,transport_type TEXT,guide_language TEXT,budget_amount NUMERIC,budget_currency TEXT,source TEXT,priority TEXT,status TEXT,next_action TEXT,next_action_due TEXT,created_by INTEGER,updated_by INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP",
 'tasks'=>'id INTEGER PRIMARY KEY,company_id INTEGER,title TEXT,entity_type TEXT,entity_id INTEGER,owner_user_id INTEGER,due_at TEXT,priority TEXT,status TEXT,source TEXT,rule_code TEXT',
 'quotes'=>'id INTEGER PRIMARY KEY,company_id INTEGER,trip_id INTEGER,inquiry_id INTEGER,quote_ref TEXT,status TEXT,current_version_no INTEGER,confirmed_version_no INTEGER,updated_by INTEGER,updated_at TEXT',
 'quote_versions'=>'id INTEGER PRIMARY KEY,quote_id INTEGER,version_no INTEGER,version_status TEXT,tour_name TEXT,start_date TEXT,end_date TEXT,adults INTEGER,children INTEGER,infants INTEGER,foc INTEGER,total_guests INTEGER,paying_pax INTEGER,hotel_level TEXT,tour_type TEXT,guide_language TEXT,meals TEXT,cost_currency TEXT,selling_currency TEXT,fx_rate NUMERIC,pricing_mode TEXT,pricing_value NUMERIC,rounding_step NUMERIC,total_cost NUMERIC,cost_per_paying_pax NUMERIC,selling_per_pax NUMERIC,total_selling NUMERIC,profit_amount NUMERIC,margin_pct NUMERIC,markup_pct NUMERIC,schedule_json TEXT,cost_json TEXT,proposal_json TEXT,included_text TEXT,excluded_text TEXT,terms_text TEXT,document_language TEXT,created_by INTEGER,approved_by INTEGER,approved_at TEXT,sent_by INTEGER,sent_at TEXT,sent_snapshot_json TEXT',
 'quote_options'=>'id INTEGER PRIMARY KEY,quote_version_id INTEGER,label TEXT,hotel_level TEXT,variant_key TEXT DEFAULT "",costing_mode TEXT,cruise_level TEXT,snapshot_json TEXT,created_by INTEGER',
 'quote_proposals'=>'quote_version_id INTEGER PRIMARY KEY,settings_json TEXT,updated_by INTEGER',
 'quote_visual_days'=>'quote_version_id INTEGER,day_key TEXT,sort_order INTEGER,schedule_signature TEXT,fields_json TEXT',
 'quote_media_links'=>'id INTEGER PRIMARY KEY,quote_version_id INTEGER,asset_id INTEGER,role TEXT,day_key TEXT,caption TEXT,sort_order INTEGER',
 'quote_guest_profiles'=>'quote_version_id INTEGER PRIMARY KEY,visa_pax INTEGER,meal_pax INTEGER,hotel_pax INTEGER,ticket_pax INTEGER,updated_by INTEGER',
 'quote_service_requirements'=>'id INTEGER PRIMARY KEY,quote_version_id INTEGER,requirement_key TEXT,sort_order INTEGER,category TEXT,service_name TEXT,service_date TEXT,quantity INTEGER,service_mode TEXT,scope TEXT,metadata_json TEXT',
 'quote_bundle_approvals'=>'quote_version_id INTEGER PRIMARY KEY,content_hash TEXT,reason TEXT,approved_by INTEGER,approved_at TEXT',
 'quote_sent_bundles'=>'quote_version_id INTEGER PRIMARY KEY,public_snapshot_json TEXT,internal_snapshot_json TEXT,content_hash TEXT,sent_by INTEGER',
 'quote_acceptances'=>'quote_version_id INTEGER PRIMARY KEY,option_id INTEGER,sent_content_hash TEXT,accepted_by INTEGER',
 'quote_program_sources'=>'id INTEGER PRIMARY KEY,quote_version_id INTEGER,program_version_id INTEGER,variant_id INTEGER,snapshot_json TEXT,created_by INTEGER',
 'tour_library_quote_sources'=>'id INTEGER PRIMARY KEY,company_id INTEGER,quote_version_id INTEGER,program_id INTEGER,snapshot_json TEXT,created_by INTEGER',
 'quote_cost_items'=>'id INTEGER PRIMARY KEY,quote_version_id INTEGER,sort_order INTEGER,category TEXT,service_name TEXT,service_date TEXT,pax NUMERIC,qty NUMERIC,unit_price NUMERIC,currency TEXT,total NUMERIC,supplier_id INTEGER,rate_id INTEGER,rate_version_id INTEGER,source_document_id INTEGER,source_type TEXT,manual_pax INTEGER,notes TEXT,charge_basis TEXT,review_required INTEGER',
 'suppliers'=>'id INTEGER PRIMARY KEY,company_id INTEGER,status TEXT',
 'bookings'=>'id INTEGER PRIMARY KEY,company_id INTEGER,booking_ref TEXT,trip_id INTEGER,quote_id INTEGER,confirmed_quote_version_no INTEGER,lead_guest_name TEXT,lead_whatsapp TEXT,lead_email TEXT,start_date TEXT,end_date TEXT,adults INTEGER,children INTEGER,infants INTEGER,foc INTEGER,total_guests INTEGER,paying_pax INTEGER,selling_currency TEXT,confirmed_selling NUMERIC,operations_status TEXT,sales_owner_id INTEGER,operations_owner_id INTEGER,created_by INTEGER,updated_by INTEGER,operation_completed_at TEXT,finance_closed_at TEXT,risk_level TEXT,readiness_pct NUMERIC',
 'booking_services'=>'id INTEGER PRIMARY KEY,booking_id INTEGER,service_ref TEXT,category TEXT,service_name TEXT,service_date TEXT,pax NUMERIC,qty NUMERIC,supplier_id INTEGER,booking_status TEXT,planned_cost NUMERIC,confirmed_cost NUMERIC,actual_cost NUMERIC,cost_currency TEXT,source_type TEXT,source_ref TEXT',
 'booking_quote_snapshots'=>'booking_id INTEGER PRIMARY KEY,quote_version_id INTEGER,option_id INTEGER,public_snapshot_json TEXT,internal_snapshot_json TEXT,source_hash TEXT',
 'customer_invoices'=>'id INTEGER PRIMARY KEY,booking_id INTEGER,status TEXT,invoice_type TEXT,currency TEXT,total NUMERIC,paid_amount NUMERIC,balance NUMERIC',
 'payment_allocations'=>'id INTEGER PRIMARY KEY,invoice_id INTEGER,amount NUMERIC,allocation_date TEXT',
 'customer_payments'=>'id INTEGER PRIMARY KEY,invoice_id INTEGER,booking_id INTEGER,amount NUMERIC,payment_date TEXT',
 'supplier_payables'=>'id INTEGER PRIMARY KEY,company_id INTEGER,booking_id INTEGER,service_id INTEGER,status TEXT,currency TEXT,total_amount NUMERIC,paid_amount NUMERIC,balance NUMERIC',
 'supplier_invoice_reconciliations'=>'id INTEGER PRIMARY KEY,payable_id INTEGER,status TEXT',
 'invoice_commercial_documents'=>'id INTEGER PRIMARY KEY,invoice_id INTEGER',
 'guests'=>'id INTEGER PRIMARY KEY,booking_id INTEGER,guest_type TEXT,full_name TEXT,gender TEXT,date_of_birth TEXT,nationality TEXT,passport_number TEXT,passport_expiry TEXT,passport_country TEXT,whatsapp TEXT,email TEXT,dietary TEXT,special_needs TEXT,room_preference TEXT,notes TEXT',
 'resource_assignments'=>'id INTEGER PRIMARY KEY,service_id INTEGER,resource_id INTEGER,starts_at TEXT,ends_at TEXT,status TEXT',
 'operation_resources'=>'id INTEGER PRIMARY KEY,company_id INTEGER,kind TEXT,name TEXT,capacity INTEGER,status TEXT',
 'operational_issues'=>'id INTEGER PRIMARY KEY,company_id INTEGER,booking_id INTEGER,severity TEXT,status TEXT',
 'travel_documents'=>'id INTEGER PRIMARY KEY,company_id INTEGER,booking_id INTEGER,kind TEXT',
 'travel_document_versions'=>'id INTEGER PRIMARY KEY,document_id INTEGER,version_no INTEGER,status TEXT,visibility TEXT,content_hash TEXT'
];foreach($schemas as $table=>$columns)$db->exec("CREATE TABLE $table($columns)");
$db->exec("INSERT INTO users VALUES(1,1,'ACTIVE','Owner'),(2,2,'ACTIVE','Foreign'),(3,1,'INACTIVE','Inactive');INSERT INTO customers(id,company_id,status) VALUES(11,1,'ACTIVE'),(12,1,'INACTIVE'),(99,2,'ACTIVE');INSERT INTO agents VALUES(11,1,'ACTIVE'),(12,1,'INACTIVE'),(99,2,'ACTIVE');INSERT INTO suppliers VALUES(21,1,'ACTIVE')");
$u=['id'=>1,'company_id'=>1];$_GET=[];Auth::$permissions=['customer.manage','inquiry.manage','quote.edit','booking.manage','report.view','profit.view','finance.close','service.manage'];
foreach([2,3,-1,'1.0',['1'],'1 OR 1=1'] as $owner){Http::$input=['full_name'=>'Manual','sales_owner_id'=>$owner];$before=count($db->queries);vsReject(fn()=>CoreOS::handle('customers','POST',$db,[],$u),InvalidArgumentException::class,'invalid customer owner '.json_encode($owner));vsSame(count(array_filter(array_slice($db->queries,$before),fn($sql)=>preg_match('/^(INSERT|UPDATE) /',$sql))),0,'customer validation precedes writes '.json_encode($owner));}
foreach(['sales_owner_id','customer_id','agent_id'] as $field)foreach(($field==='sales_owner_id'?[2,3,['1']]:[99,12,['1']]) as $value){Http::$input=['lead_contact_name'=>'Manual',$field=>$value];$before=count($db->queries);vsReject(fn()=>CoreOS::handle('inquiries','POST',$db,[],$u),InvalidArgumentException::class,'invalid inquiry '.$field.' '.json_encode($value));vsSame(count(array_filter(array_slice($db->queries,$before),fn($sql)=>preg_match('/^(INSERT|UPDATE) /',$sql))),0,'inquiry link validation precedes writes '.$field.' '.json_encode($value));}
Http::$input=['full_name'=>'Manual customer','sales_owner_id'=>'1'];$customer=vsResponse(fn()=>CoreOS::handle('customers','POST',$db,[],$u));vsSame($customer->status,201,'active same-company customer owner accepted');
Http::$input=['lead_contact_name'=>'Manual guest','customer_id'=>$customer->body['id'],'agent_id'=>'11','adults'=>6,'children'=>2,'infants'=>1,'foc'=>1,'total_guests'=>10,'paying_pax'=>8,'sales_owner_id'=>'1'];$inquiry=vsResponse(fn()=>CoreOS::handle('inquiries','POST',$db,[],$u));vsSame($inquiry->status,201,'active same-company inquiry links accepted');$tripId=$inquiry->body['trip_id'];
$trip=$db->query('SELECT * FROM trips WHERE id='.$tripId)->fetch();vsSame([$trip['customer_id'],$trip['agent_id'],$trip['sales_owner_id']],[$customer->body['id'],11,1],'validated numeric link ids persisted');
vsSame(TenantLinks::active($db,1,'agents','0','agent_id'),null,'explicit unassigned optional link preserved');
vsInsert($db,'quotes',['id'=>10,'company_id'=>1,'trip_id'=>$tripId,'quote_ref'=>'QT-10','status'=>'DRAFT','current_version_no'=>1]);
$version=['id'=>10,'quote_id'=>10,'version_no'=>1,'version_status'=>'DRAFT','tour_name'=>'Reviewed family tour','start_date'=>'2027-01-02','end_date'=>'2027-01-03','adults'=>6,'children'=>2,'infants'=>1,'foc'=>1,'total_guests'=>10,'paying_pax'=>8,'fx_rate'=>25000,'schedule_json'=>'[{"title":"Arrival","description":"Welcome"}]','included_text'=>'Hotel','excluded_text'=>'Flights','terms_text'=>'Subject to availability','document_language'=>'en'];vsInsert($db,'quote_versions',$version);
$body=['label'=>'Comfort','hotel_level'=>'4*','pricing_mode'=>'MARKUP','pricing_value'=>20,'lines'=>[['supplier_id'=>21,'category'=>'HOTEL','service_name'=>'Reviewed hotel','pax'=>1,'qty'=>1,'unit_price'=>60,'currency'=>'USD','service_date'=>'2027-01-02','reason'=>'Supplier confirmed manual rate']]];
$saved=QuoteOptions::save($db,$u,10,$body);$optionId=$saved['id'];$snap=json_decode($db->query('SELECT snapshot_json FROM quote_options WHERE id='.$optionId)->fetchColumn(),true);
vsSame([$snap['adults'],$snap['children'],$snap['infants']],[6,2,1],'new option freezes each passenger segment');
$db->exec('UPDATE quote_versions SET adults=5,children=3 WHERE id=10');vsReject(fn()=>QuoteOptions::bundle($db,QuoteOptions::version($db,1,10)),DomainException::class,'segment redistribution requires recost even unchanged total');$db->exec('UPDATE quote_versions SET adults=6,children=2 WHERE id=10');
QuoteOptions::approve($db,$u,10,'Segments and costs reviewed');$sent=QuoteOptions::send($db,$u,10);$hash=$db->query('SELECT content_hash FROM quote_sent_bundles WHERE quote_version_id=10')->fetchColumn();vsSame([$sent['customer_safe_snapshot']['adults'],$sent['customer_safe_snapshot']['children'],$sent['customer_safe_snapshot']['infants']],[6,2,1],'sent public bundle includes frozen segments');
vsSame(QuoteOptions::send($db,$u,10),$sent,'sent bundle retry preserves exact snapshot');QuoteOptions::confirm($db,$u,10,$optionId);
$db->exec('UPDATE quote_versions SET adults=9,children=0,infants=0 WHERE id=10');$booking=QuoteOptions::booking($db,$u,10);$book=$db->query('SELECT * FROM bookings WHERE id='.$booking['id'])->fetch();vsSame([$book['adults'],$book['children'],$book['infants'],$book['foc'],$book['total_guests'],$book['paying_pax']],[6,2,1,1,10,8],'booking takes accepted immutable segments rather than changed version');vsSame($db->query('SELECT content_hash FROM quote_sent_bundles WHERE quote_version_id=10')->fetchColumn(),$hash,'booking never rehashes old sent bundle');
vsSame((int)QuoteOptions::booking($db,$u,10)['id'],(int)$booking['id'],'booking retry remains idempotent');
// A genuine old acceptance has no segment evidence. It can be re-read but cannot create a guessed booking.
vsInsert($db,'quotes',['id'=>11,'company_id'=>1,'trip_id'=>$tripId,'quote_ref'=>'QT-LEGACY','status'=>'CONFIRMED','current_version_no'=>1,'confirmed_version_no'=>1]);$legacyVersion=array_replace($version,['id'=>11,'quote_id'=>11,'version_status'=>'CONFIRMED']);vsInsert($db,'quote_versions',$legacyVersion);
$legacy=json_decode($db->query('SELECT internal_snapshot_json FROM quote_sent_bundles WHERE quote_version_id=10')->fetchColumn(),true);foreach(['adults','children','infants'] as $field){unset($legacy[$field],$legacy['options'][0]['snapshot'][$field]);}$legacyOption=vsInsert($db,'quote_options',['quote_version_id'=>11,'label'=>'Old','hotel_level'=>'4*','snapshot_json'=>json_encode($legacy['options'][0]['snapshot']),'created_by'=>1]);$legacy['options'][0]['id']=$legacyOption;$legacyPublic=QuoteOptions::publicBundle($legacy);
vsInsert($db,'quote_sent_bundles',['quote_version_id'=>11,'public_snapshot_json'=>json_encode($legacyPublic),'internal_snapshot_json'=>json_encode($legacy),'content_hash'=>'preserve-legacy-hash','sent_by'=>1]);vsInsert($db,'quote_acceptances',['quote_version_id'=>11,'option_id'=>$legacyOption,'sent_content_hash'=>'preserve-legacy-hash','accepted_by'=>1]);
Http::$input=[];$legacyError=vsResponse(fn()=>QuoteOptions::handle('quotes/11/create-booking','POST',$db,$u));vsSame([$legacyError->status,$legacyError->body['error']],[409,'PAX_SEGMENT_REVIEW_REQUIRED'],'legacy acceptance exposes explicit review strategy');vsSame((int)$db->query('SELECT COUNT(*) FROM bookings WHERE quote_id=11')->fetchColumn(),0,'legacy missing segments create no guessed booking');vsSame($db->query('SELECT content_hash FROM quote_sent_bundles WHERE quote_version_id=11')->fetchColumn(),'preserve-legacy-hash','legacy hash stays unchanged');vsSame(QuoteOptions::send($db,$u,11)['customer_safe_snapshot'],$legacyPublic,'old sent snapshot stays readable without segmentation backfill');
vsInsert($db,'bookings',['id'=>200,'company_id'=>1,'quote_id'=>11,'booking_ref'=>'BKG-OLD']);vsSame((int)QuoteOptions::booking($db,$u,11)['id'],200,'existing legacy booking can be reopened without new data inference');
// Both independent itinerary source systems survive revision with the original snapshot bytes.
vsInsert($db,'quote_program_sources',['quote_version_id'=>10,'program_version_id'=>70,'variant_id'=>71,'snapshot_json'=>'{"origin":"008 frozen"}','created_by'=>1]);vsInsert($db,'tour_library_quote_sources',['company_id'=>1,'quote_version_id'=>10,'program_id'=>80,'snapshot_json'=>'{"origin":"021 frozen"}','created_by'=>1]);vsInsert($db,'tour_library_quote_sources',['company_id'=>2,'quote_version_id'=>10,'program_id'=>99,'snapshot_json'=>'{"origin":"foreign"}','created_by'=>2]);
Http::$input=[];$revision=vsResponse(fn()=>CoreOS::handle('quotes/10/new-version','POST',$db,[],$u));vsSame($revision->status,201,'new revision created');$newVersion=$revision->body['version_id'];vsSame($db->query('SELECT snapshot_json FROM quote_program_sources WHERE quote_version_id='.$newVersion)->fetchColumn(),'{"origin":"008 frozen"}','008 source snapshot copied exactly');$source=$db->query('SELECT company_id,program_id,snapshot_json FROM tour_library_quote_sources WHERE quote_version_id='.$newVersion)->fetchAll();vsSame($source,[['company_id'=>1,'program_id'=>80,'snapshot_json'=>'{"origin":"021 frozen"}']],'021 provenance copied exactly and tenant scoped');
Http::$input=['adults'=>5,'children'=>3,'infants'=>1];vsSame(vsResponse(fn()=>CoreOS::handle('quote-versions/'.$newVersion,'PUT',$db,[],$u))->status,200,'draft segment edits use existing quote patch');$revisedOption=json_decode($db->query('SELECT snapshot_json FROM quote_options WHERE quote_version_id='.$newVersion)->fetchColumn(),true);vsSame($revisedOption['review_required'],true,'segment edit invalidates copied option review even same total');
// Report cohort covers the last second of the month and excludes next-month midnight, cancelled and foreign bookings.
$db->exec("UPDATE inquiries SET created_at='2026-09-01 00:00:00'");foreach([[401,1,'CONFIRMED','2026-10-31 23:59:59'],[402,1,'CONFIRMED','2026-11-01 00:00:00'],[403,1,'NEW','2026-09-30 23:59:59'],[404,1,'LOST','2026-10-01 00:00:00'],[405,2,'CONFIRMED','2026-10-15 10:00:00']] as [$id,$cid,$status,$created])vsInsert($db,'inquiries',['id'=>$id,'company_id'=>$cid,'status'=>$status,'created_at'=>$created]);
foreach([[300,1,'USD',100,'2026-10-31','OPERATION_COMPLETED','HIGH'],[301,1,'USD',200,'2026-10-01','OPERATION_COMPLETED','LOW'],[302,1,'VND',2500000,'2026-10-10','NEW_BOOKING','LOW'],[303,1,'USD',1000,'2026-10-10','CANCELLED','CRITICAL'],[304,1,'USD',999,'2026-11-01','NEW_BOOKING','LOW'],[305,2,'USD',999,'2026-10-10','NEW_BOOKING','LOW']] as [$id,$cid,$currency,$amount,$date,$status,$risk])vsInsert($db,'bookings',['id'=>$id,'company_id'=>$cid,'trip_id'=>$tripId,'quote_id'=>10,'confirmed_quote_version_no'=>1,'booking_ref'=>'BKG-'.$id,'selling_currency'=>$currency,'confirmed_selling'=>$amount,'start_date'=>$date,'operations_status'=>$status,'risk_level'=>$risk,'operation_completed_at'=>'2026-10-31 15:00:00']);
foreach([[401,300,30,32,35],[402,301,50,55,60]] as [$id,$bid,$planned,$confirmed,$actual])vsInsert($db,'booking_services',['id'=>$id,'booking_id'=>$bid,'booking_status'=>'COMPLETED','cost_currency'=>'USD','planned_cost'=>$planned,'confirmed_cost'=>$confirmed,'actual_cost'=>$actual]);
vsInsert($db,'supplier_payables',['id'=>1,'company_id'=>1,'booking_id'=>300,'service_id'=>401,'status'=>'PAID','currency'=>'USD','total_amount'=>35,'paid_amount'=>35,'balance'=>0]);vsInsert($db,'supplier_invoice_reconciliations',['payable_id'=>1,'status'=>'APPROVED']);
foreach([[1,300,100],[2,301,200]] as [$iid,$bid,$amount]){vsInsert($db,'customer_invoices',['id'=>$iid,'booking_id'=>$bid,'status'=>'ISSUED','invoice_type'=>'CUSTOMER_INVOICE','currency'=>'USD','total'=>$amount,'paid_amount'=>999,'balance'=>999]);vsInsert($db,'payment_allocations',['invoice_id'=>$iid,'amount'=>$amount,'allocation_date'=>'2026-10-31']);}
$report=CoreOS::reportSummary($db,$u,'2026-10');vsSame($report['sales'],['inquiries'=>2,'confirmed'=>1,'lost'=>1],'full calendar month inquiry timestamps included');vsSame($report['bookings'],['bookings'=>3,'at_risk'=>1],'report booking cohort excludes cancelled foreign next month');vsSame($report['revenue_by_currency'],[['currency'=>'USD','amount'=>300.0,'bookings'=>2],['currency'=>'VND','amount'=>2500000.0,'bookings'=>1]],'report revenue never sums mixed currencies');vsSame(isset($report['actual_profit']),false,'unsafe scalar actual profit removed');
$usd=$report['profit_by_currency'][0];vsSame([$usd['currency'],$usd['expected_profit'],$usd['forecast_profit'],$usd['actual_profit'],$usd['actual_final_count'],$usd['pending_actual_count']],['USD',220,213,65,1,1],'modern allocations and reconciliations determine final profit with pending count');$vnd=$report['profit_by_currency'][1];vsSame([$vnd['currency'],$vnd['expected_profit'],$vnd['actual_profit'],$vnd['review_required_count']],['VND',null,null,1],'unsupported conversion remains explicit review without fabricated profit');vsSame($report['date_range'],['start'=>'2026-10-01','end_exclusive'=>'2026-11-01'],'report exposes half-open monthly bounds');
Auth::$permissions=['report.view'];$before=count($db->queries);$restricted=CoreOS::reportSummary($db,$u,'2026-10');vsSame($restricted['profit_by_currency'],null,'no-profit role receives restricted value not zero');vsSame($restricted['profit_review_required'],[],'no-profit role sees no private cost review detail');vsSame(count(array_filter(array_slice($db->queries,$before),fn($sql)=>preg_match('/quote_versions|booking_services|payables|invoices|allocations|customer_payments/',$sql))),0,'no-profit role never queries private ledger domains');
foreach(['2026-13','2026-00','2026-10-extra',['2026-10'],'2026-1'] as $month)vsReject(fn()=>CoreOS::reportSummary($db,$u,$month),InvalidArgumentException::class,'malformed month rejected '.json_encode($month));
Auth::$permissions=['finance.close','service.manage'];$db->exec("UPDATE bookings SET finance_closed_at='2026-10-01 10:00:00' WHERE id=300");Http::$input=['service_name'=>'Forbidden cost change'];$before=(int)$db->query('SELECT COUNT(*) FROM booking_services')->fetchColumn();vsReject(fn()=>CoreOS::handle('bookings/300/services','POST',$db,[],$u),DomainException::class,'legacy CoreOS service creation cannot bypass financial close');vsSame((int)$db->query('SELECT COUNT(*) FROM booking_services')->fetchColumn(),$before,'closed booking service count unchanged');
Http::$input=['reason'=>'Review corrected supplier statement'];vsSame(vsResponse(fn()=>CoreOS::handle('bookings/300/finance-reopen','POST',$db,[],$u))->status,200,'authorized reasoned reopen works under booking lock');vsSame($db->query('SELECT finance_closed_at FROM bookings WHERE id=300')->fetchColumn(),null,'reopen removes close marker');vsSame(vsResponse(fn()=>CoreOS::handle('bookings/300/finance-close','POST',$db,[],$u))->status,200,'modern final profit permits close under shared lock');vsSame($db->query('SELECT operations_status FROM bookings WHERE id=300')->fetchColumn(),'COMPLETED','financial close completes operation-completed booking');
// Legacy CoreOS recalculation and completion use the same five checks as the Operations API.
$db->exec("UPDATE bookings SET total_guests=1,readiness_pct=100,operations_status='READY',operation_completed_at=NULL,lead_guest_name='Guest',lead_whatsapp='123' WHERE id=304");vsInsert($db,'booking_services',['id'=>500,'booking_id'=>304,'category'=>'HOTEL','service_name'=>'Confirmed hotel','service_date'=>'2026-11-01','booking_status'=>'CONFIRMED','cost_currency'=>'USD','planned_cost'=>0]);
Auth::$permissions=['guest.manage','booking.complete'];Http::$input=['full_name'=>'Reviewed passenger'];vsSame(vsResponse(fn()=>CoreOS::handle('bookings/304/guests','POST',$db,[],$u))->status,201,'legacy guest write recalculates canonical projection');$projected=$db->query('SELECT readiness_pct,operations_status FROM bookings WHERE id=304')->fetch();vsSame($projected,['readiness_pct'=>80,'operations_status'=>'ALL_CONFIRMED'],'stored READY is corrected when current Travel Pack is missing');Http::$input=[];$blocked=vsResponse(fn()=>CoreOS::handle('bookings/304/complete-operations','POST',$db,[],$u));vsSame([$blocked->status,$blocked->body['error']],[409,'OPERATIONS_NOT_READY'],'completion cannot bypass missing fifth readiness check');vsSame($db->query('SELECT operation_completed_at FROM bookings WHERE id=304')->fetchColumn(),null,'blocked completion leaves finalization timestamp unchanged');
echo "VS0 commercial: $checks checks executed against SQLite. MariaDB/HTTP validation is separate.\n";
