<?php
declare(strict_types=1);
require __DIR__.'/../api/lib/Migrations.php';require __DIR__.'/../api/lib/Auth.php';
$password=getenv('VTA_TEST_DB_PASSWORD');if(!$password)throw new RuntimeException('Disposable test password required');$db=new PDO('mysql:host=127.0.0.1;port=33317;charset=utf8mb4','root',$password,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$name='vta_media_upgrade_'.bin2hex(random_bytes(5));$temp=sys_get_temp_dir().'/vs22-migrations-'.bin2hex(random_bytes(5));mkdir($temp);$db->exec("CREATE DATABASE `$name`");$db->exec("USE `$name`");
try{
 foreach(glob(__DIR__.'/../api/migrations/*.sql') as $f)if(basename($f)<='023_vs2_costing.sql')copy($f,$temp.'/'.basename($f));Migrations::run($db,$temp);
 $db->exec("INSERT INTO companies(code,name) VALUES('UP','Upgrade');INSERT INTO roles(company_id,code,name) VALUES(1,'ADMIN','Admin');INSERT INTO users(company_id,role_id,full_name,email,password_hash) VALUES(1,1,'Test','upgrade-media@example.invalid','unused');INSERT INTO trips(company_id,trip_ref,title,created_by,updated_by) VALUES(1,'UPTRIP','Trip',1,1);INSERT INTO quotes(company_id,quote_ref,trip_id,created_by,updated_by) VALUES(1,'UPQUOTE',1,1,1);INSERT INTO quote_versions(quote_id,version_no,version_status,tour_name,sent_snapshot_json,created_by) VALUES(1,1,'SENT','Historical','{\"original\":true}',1);INSERT INTO quote_options(quote_version_id,label,hotel_level,variant_key,snapshot_json,created_by) VALUES(1,'VS2.1','4*','private4','{\"snapshot\":1}',1);INSERT INTO quote_sent_bundles(quote_version_id,public_snapshot_json,internal_snapshot_json,content_hash,sent_by) VALUES(1,'{\"public\":1}','{\"internal\":1}',REPEAT('a',64),1)");
 $db->exec("INSERT INTO role_permissions(role_id,permission_id) SELECT 1,id FROM permissions WHERE code IN ('document.view','document.upload');INSERT INTO user_permissions(user_id,permission_id,effect) SELECT 1,id,'DENY' FROM permissions WHERE code='document.view';INSERT INTO user_permissions(user_id,permission_id,effect) SELECT 1,id,'ALLOW' FROM permissions WHERE code='document.review'");
 $before=$db->query('SELECT sent_snapshot_json FROM quote_versions')->fetchColumn();$option=$db->query('SELECT snapshot_json FROM quote_options')->fetchColumn();$sent=$db->query('SELECT public_snapshot_json,internal_snapshot_json,content_hash FROM quote_sent_bundles')->fetch(PDO::FETCH_ASSOC);
 if(Migrations::run($db,__DIR__.'/../api/migrations')!==['024_vs2_media_proposals'])throw new RuntimeException('Expected migration024 only');if(Migrations::run($db,__DIR__.'/../api/migrations')!==[])throw new RuntimeException('Retry must be no-op');if($before!==$db->query('SELECT sent_snapshot_json FROM quote_versions')->fetchColumn()||$option!==$db->query('SELECT snapshot_json FROM quote_options')->fetchColumn()||$sent!==$db->query('SELECT public_snapshot_json,internal_snapshot_json,content_hash FROM quote_sent_bundles')->fetch(PDO::FETCH_ASSOC))throw new RuntimeException('Historical snapshot changed');
 if(Auth::can($db,1,'media.view')||!Auth::can($db,1,'media.upload')||!Auth::can($db,1,'media.review'))throw new RuntimeException('Permission overrides not preserved');if((int)$db->query('SELECT COUNT(*) FROM quote_proposals')->fetchColumn()!==0)throw new RuntimeException('Historical quote silently opted in');
 echo "PASS upgrade023→024 only; no-op retry; historical VS2.1 snapshots unchanged; role and explicit user permission overrides preserved; no automatic proposal opt-in\n";
}finally{foreach(glob($temp.'/*') as $f)unlink($f);rmdir($temp);$db->exec("DROP DATABASE `$name`");}
