<?php
declare(strict_types=1);
require __DIR__.'/../api/lib/Migrations.php';
$pass=getenv('VTA_TEST_DB_PASSWORD');if(!$pass)throw new RuntimeException('Disposable local DB password required');
$db=new PDO('mysql:host=127.0.0.1;port=33317;charset=utf8mb4','root',$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$name='vta_upgrade_'.bin2hex(random_bytes(5));$db->exec("CREATE DATABASE `$name`");$db->exec("USE `$name`");$temp=sys_get_temp_dir().'/vs2-migrations-'.bin2hex(random_bytes(5));mkdir($temp);
try {
 foreach(glob(__DIR__.'/../api/migrations/*.sql') as $f)if(basename($f)<='022_lead_sales_handover.sql')copy($f,$temp.'/'.basename($f));
 Migrations::run($db,$temp);$db->exec("INSERT INTO companies(code,name) VALUES('UPGRADE','Upgrade');INSERT INTO roles(company_id,code,name) VALUES(1,'ADMIN','Admin');INSERT INTO users(company_id,role_id,full_name,email,password_hash) VALUES(1,1,'Test','upgrade@example.invalid','unused');INSERT INTO trips(company_id,trip_ref,title,created_by,updated_by) VALUES(1,'UPGRADE-TRIP','Trip',1,1);INSERT INTO quotes(company_id,quote_ref,trip_id,created_by,updated_by) VALUES(1,'UPGRADE-QUOTE',1,1,1);INSERT INTO quote_versions(quote_id,version_no,version_status,tour_name,sent_snapshot_json,created_by) VALUES(1,1,'SENT','Historical','{\"immutable\":true}',1);INSERT INTO quote_options(quote_version_id,label,hotel_level,snapshot_json,created_by) VALUES(1,'Historical','4*','{\"historical\":true}',1);INSERT INTO quote_sent_bundles(quote_version_id,public_snapshot_json,internal_snapshot_json,content_hash,sent_by) VALUES(1,'{\"public\":true}','{\"private\":true}',REPEAT('a',64),1)");
 $before=$db->query('SELECT sent_snapshot_json FROM quote_versions')->fetchColumn();$option=$db->query('SELECT snapshot_json FROM quote_options')->fetchColumn();$sent=$db->query('SELECT public_snapshot_json,internal_snapshot_json,content_hash FROM quote_sent_bundles')->fetch(PDO::FETCH_ASSOC);
 $applied=Migrations::run($db,__DIR__.'/../api/migrations');if($applied!==['023_vs2_costing','024_vs2_media_proposals'])throw new RuntimeException('Expected migrations023/024 only');if(Migrations::run($db,__DIR__.'/../api/migrations')!==[])throw new RuntimeException('Migration retry must be a no-op');
 if($before!==$db->query('SELECT sent_snapshot_json FROM quote_versions')->fetchColumn()||$option!==$db->query('SELECT snapshot_json FROM quote_options')->fetchColumn()||$sent!==$db->query('SELECT public_snapshot_json,internal_snapshot_json,content_hash FROM quote_sent_bundles')->fetch(PDO::FETCH_ASSOC))throw new RuntimeException('Historical snapshot changed');
 if($db->query('SELECT variant_key FROM quote_options')->fetchColumn()!=='')throw new RuntimeException('Legacy key changed');
 echo "PASS upgrade022→024, no-op retry, historical sent/version/option/bundle snapshot bytes unchanged\n";
}finally{foreach(glob($temp.'/*') as $f)unlink($f);rmdir($temp);$db->exec("DROP DATABASE `$name`");}
