<?php
declare(strict_types=1);
require __DIR__.'/lead-hub.php';
require_once __DIR__.'/../api/lib/CoreOS.php';
require_once __DIR__.'/../api/lib/RuntimeGuard.php';
require_once __DIR__.'/../api/lib/MediaDrive.php';
require_once __DIR__.'/../api/lib/ProposalOutput.php';
$folder=dirname(__DIR__,2).'/runtime/media-test-'.bin2hex(random_bytes(5));mkdir($folder,0770,true);$cfg=['storage'=>['local_path'=>$folder]];
$im=imagecreatetruecolor(1400,800);imagefill($im,0,0,imagecolorallocate($im,40,130,150));ob_start();imagepng($im);$bytes=ob_get_clean();imagedestroy($im);
$u2=['id'=>2,'company_id'=>2];$u3=['id'=>3,'company_id'=>1];$db->exec("INSERT INTO users(company_id,role_id,full_name,email,password_hash) VALUES(1,1,'Colleague','colleague@example.invalid','unused')");
$one=MediaLibrary::ingest($db,$cfg,$user,$bytes,['title'=>'Hạ Long — ảnh duyệt','visibility'=>'PERSONAL','destination'=>'Halong','tags'=>['cruise','bay']]);$id=(int)$one['asset']['id'];
check($one['asset']['width']===1400&&!$one['asset']['low_resolution'],'optimized image metadata and resolution warning');check(is_file(MediaLibrary::asset($db,$user,$id)['thumbnail_path']),'thumbnail generated in private storage');
check(MediaLibrary::ingest($db,$cfg,$user,$bytes,['title'=>'Duplicate','visibility'=>'PERSONAL'])['duplicate'],'identical own image detected without another binary');
rejects(fn()=>MediaLibrary::asset($db,$u2,$id),OutOfBoundsException::class,'media tenant isolation');rejects(fn()=>MediaLibrary::asset($db,$u3,$id,true),OutOfBoundsException::class,'personal image hidden from other users including reviewers');
rejects(fn()=>MediaLibrary::image('<svg onload="alert(1)"></svg>',$folder),InvalidArgumentException::class,'SVG/script image rejected');rejects(fn()=>MediaLibrary::image(str_repeat('a',MediaLibrary::MAX_BYTES+1),$folder),InvalidArgumentException::class,'oversized image rejected');
MediaLibrary::review($db,$user,$id,['visibility'=>'COMPANY','status'=>'APPROVED']);check(MediaLibrary::asset($db,$u3,$id)['id']===$id,'approved company image reusable by company colleague');
$db->exec("INSERT INTO media_favourites(user_id,asset_id) VALUES(1,$id)");check(count(MediaLibrary::list($db,$user,['favourites'=>1])['items'])===1,'favourites per user');check(count(MediaLibrary::list($db,$u3,['favourites'=>1])['items'])===0,'favourites do not leak across users');
$db->exec("UPDATE quote_versions SET adults=10,children=0,infants=0,foc=1,total_guests=11,paying_pax=10,start_date='2027-01-02',end_date='2027-01-04',schedule_json='[{\"date\":\"2027-01-02\",\"title\":\"Hanoi\",\"description\":\"Explore Hanoi\"},{\"date\":\"2027-01-03\",\"title\":\"Halong\",\"description\":\"Cruise\"}]' WHERE id=$qvid");
$v=QuoteOptions::version($db,1,$qvid);check(QuoteProposal::snapshot($db,$v)===null,'legacy proposal has no new snapshot field');$context=QuoteProposal::context($db,$user,$v);$body=['settings'=>QuoteProposal::settings(['briefing'=>'Vietnam journey','highlights'=>'Private discovery','accommodation'=>[['type'=>'HOTEL','destination'=>'Hanoi','three_star'=>'Hotel 3','four_star'=>'Hotel 4','five_star'=>'Hotel 5','nights'=>1],['type'=>'CRUISE','destination'=>'Halong','three_star'=>'Cruise 3','four_star'=>'Cruise 4','five_star'=>'Cruise 5','nights'=>1]]]),'days'=>$context['days'],'links'=>[['asset_id'=>$id,'role'=>'COVER','day_key'=>'','caption'=>'Hạ Long'],['asset_id'=>$id,'role'=>'DAY_HERO','day_key'=>$context['days'][0]['key'],'caption'=>'Hanoi']]];$body['days'][0]['fields']['special_requests']='INTERNAL_PASSPORT_SECRET';$body['days'][0]['fields']['route']='Hanoi Old Quarter';
$saved=QuoteProposal::save($db,$user,$qvid,$body);check(!$saved['needs_day_review']&&count($saved['links'])===2,'visual proposal normalized and media assigned');$firstKey=$saved['days'][0]['key'];$body['days']=array_reverse($saved['days']);$body['days'][0]['schedule']['date']='2027-01-02';$body['days'][1]['schedule']['date']='2027-01-03';$saved=QuoteProposal::save($db,$user,$qvid,$body);check($saved['links'][1]['day_key']===$firstKey&&$saved['days'][1]['key']===$firstKey,'reorder keeps image attached to its stable day key');
$bad=$body;$bad['days'][1]['key']=$bad['days'][0]['key'];rejects(fn()=>QuoteProposal::save($db,$user,$qvid,$bad),InvalidArgumentException::class,'duplicate day keys blocked');$bad=$body;$bad['links'][0]['asset_id']=999999;rejects(fn()=>QuoteProposal::save($db,$user,$qvid,$bad),OutOfBoundsException::class,'foreign/unknown assigned image blocked');
$opts=['hotel_level'=>'4*','label'=>'Private Recommended','fx_rate'=>25000,'pricing_mode'=>'MARKUP','pricing_value'=>20,'lines'=>[['category'=>'HOTEL','service_name'=>'Hotel','service_date'=>'2027-01-02','supplier_id'=>1,'pax'=>11,'qty'=>1,'unit_price'=>500000,'currency'=>'VND','reason'=>'Reviewed supplier quote']]];QuoteOptions::save($db,$user,$qvid,$opts);
$v=QuoteOptions::version($db,1,$qvid);$public=QuoteProposal::publicQuote($db,$v);$encoded=json_encode($public);check(!str_contains($encoded,'supplier')&&!str_contains($encoded,'unit_price')&&!str_contains($encoded,'INTERNAL_PASSPORT_SECRET')&&!str_contains($encoded,'storage_path')&&!str_contains($encoded,'drive_file_id'),'public projection strips financial, private note and storage/source details');
$resolver=fn($asset)=>MediaLibrary::path($cfg,QuoteProposal::snapshotAsset($db,$v,$public,$asset));
check(str_contains(ProposalOutput::html(['tour_name'=>'Legacy','selling_per_pax'=>125,'total_selling'=>1250,'currency'=>'USD','schedule'=>[]],fn($asset)=>'/image/'.$asset),'USD 125.00'),'legacy single-package selling price preserved in new renderer');
foreach(QuoteProposal::TEMPLATES as $template=>$label){$s=$public;$s['presentation']['settings']['template']=$template;$s['presentation']['settings']['brand_name']=$template==='VTA_B2B_WHITE_LABEL'?'Partner Agency':'';$html=ProposalOutput::html($s,fn($asset)=>'/image/'.$asset);check(str_contains($html,'Detailed itinerary')&&str_contains($html,'Cruise 4')&&!str_contains($html,'INTERNAL_PASSPORT_SECRET'),'customer-safe template '.$template);if($template==='VTA_B2B_WHITE_LABEL')check(!str_contains($html,'Vietnam Travel Advisor')&&!str_contains($html,'vietnamtraveladvisor'),'white label contains no VTA contact branding');}
$pdf=ProposalOutput::pdf($public,$cfg,$resolver);check(str_starts_with($pdf,'%PDF-')&&strlen($pdf)>15000,'native Unicode PDF with embedded image');$docx=ProposalOutput::docx($public,$resolver);$temp=$folder.'/test.docx';file_put_contents($temp,$docx);$zip=new ZipArchive();$zip->open($temp);check($zip->locateName('word/media/image'.$id.'.jpg')!==false&&str_contains($zip->getFromName('word/document.xml'),'Hạ Long'),'native DOCX OpenXML with embedded image and Unicode');check(!str_contains($zip->getFromName('word/document.xml'),'INTERNAL_PASSPORT_SECRET'),'DOCX omits internal notes');$zip->close();
// Approval content includes presentation; editing it invalidates approval.
QuoteOptions::approve($db,$user,$qvid,'Reviewed proposal');$body['settings']['briefing']='Updated public briefing';QuoteProposal::save($db,$user,$qvid,$body);check($db->query('SELECT content_hash FROM quote_bundle_approvals WHERE quote_version_id='.$qvid)->fetchColumn()===false,'presentation edit invalidates approval');rejects(fn()=>QuoteOptions::send($db,$user,$qvid),DomainException::class,'changed draft cannot be sent under old approval');
QuoteOptions::approve($db,$user,$qvid,'Reviewed updated proposal');$sent=QuoteOptions::send($db,$user,$qvid);$raw=$db->query('SELECT public_snapshot_json FROM quote_sent_bundles WHERE quote_version_id='.$qvid)->fetchColumn();$link=QuoteProposal::createLink($db,$user,$qvid);check(QuoteProposal::token($db,$link['token'])['snapshot']===$sent['customer_safe_snapshot'],'web link reads frozen public snapshot');rejects(fn()=>QuoteProposal::save($db,$user,$qvid,$body),DomainException::class,'sent presentation immutable');
MediaLibrary::review($db,$user,$id,['status'=>'ARCHIVED','title'=>'Edited library title']);check(QuoteProposal::publicQuote($db,QuoteOptions::version($db,1,$qvid))===$sent['customer_safe_snapshot'],'archiving/retitling library does not alter sent proposal');check(is_file(MediaLibrary::path($cfg,QuoteProposal::snapshotAsset($db,$v,$sent['customer_safe_snapshot'],$id))),'frozen proposal image remains readable after archive');check($raw===$db->query('SELECT public_snapshot_json FROM quote_sent_bundles WHERE quote_version_id='.$qvid)->fetchColumn(),'sent snapshot bytes unchanged');
$expiryLink=QuoteProposal::createLink($db,$user,$qvid);$db->exec("UPDATE quote_proposal_links SET expires_at='2000-01-01' WHERE id=".$expiryLink['id']);rejects(fn()=>QuoteProposal::token($db,$expiryLink['token']),OutOfBoundsException::class,'expired web link blocked');
$db->exec("UPDATE quote_proposal_links SET revoked_at=NOW() WHERE id=".$link['id']);rejects(fn()=>QuoteProposal::token($db,$link['token']),OutOfBoundsException::class,'revoked web link blocked');rejects(fn()=>QuoteProposal::token($db,str_repeat('a',64)),OutOfBoundsException::class,'unknown token blocked');
$db->exec("INSERT INTO quote_versions(quote_id,version_no,tour_name,created_by) VALUES(1,2,'Revision',1)");$revision=(int)$db->lastInsertId();QuoteProposal::copy($db,$qvid,$revision,1);check((int)$db->query('SELECT COUNT(*) FROM quote_media_links WHERE quote_version_id='.$revision)->fetchColumn()===2,'revision copies reference IDs, not binaries');check((int)$db->query('SELECT COUNT(*) FROM quote_proposal_links WHERE quote_version_id='.$revision)->fetchColumn()===0,'revision never copies customer token');
// Selective read-only Drive transport fixture: real adapter, synthetic provider response.
$folderId='FolderAllow12345';$fileId='ImageSource12345';$time='2026-10-05T06:00:00Z';$calls=[];$foreign=false;$adapter=new MediaDrive(['allowed_folder_ids'=>[$folderId],'oauth_refresh_token'=>'TEST_ONLY','oauth_client_id'=>'TEST_ONLY','oauth_client_secret'=>'TEST_ONLY'],function($url,$method,$headers,$payload,$limit)use(&$calls,&$time,&$foreign,$folderId,$fileId,$bytes){$calls[]=$url;if(str_contains($url,'oauth2'))return [200,'{"access_token":"TEST_ONLY"}'];parse_str(parse_url($url,PHP_URL_QUERY),$q);if(str_contains($url,'files/'.$folderId))return [200,json_encode(['id'=>$folderId,'name'=>'Halong','mimeType'=>'application/vnd.google-apps.folder'])];if(($q['alt']??'')==='media')return [200,$bytes];if(str_contains($url,'files/'.$fileId))return [200,json_encode(['id'=>$fileId,'name'=>'Drive image','mimeType'=>'image/png','size'=>strlen($bytes),'modifiedTime'=>$time,'parents'=>[$foreign?'Unmapped12345':$folderId]])];return [200,json_encode(['files'=>[['id'=>$fileId,'name'=>'Drive image','modifiedTime'=>$time]]])];});
check(count($adapter->browse($folderId)['files'])===1,'Drive picker lists only selected allowlisted folder');rejects(fn()=> $adapter->browse('Unmapped12345'),DomainException::class,'Drive root/unknown folders never browsed');$foreign=true;rejects(fn()=> $adapter->download($folderId,$fileId),DomainException::class,'Drive import verifies actual file parent');$foreign=false;
$db->prepare('INSERT INTO media_drive_folders(company_id,folder_id,destination,category,tags_json,created_by) VALUES(1,?,?,?,\'[]\',1)')->execute([$folderId,'Halong','Cruise']);$mapping=MediaDrive::mapping($db,$user,(int)$db->lastInsertId());$import=MediaDrive::import($db,$cfg,$user,$mapping,$fileId,true,null,$adapter);$old=MediaLibrary::asset($db,$user,(int)$import['asset']['id']);$time='2026-10-05T07:00:00Z';$sync=MediaDrive::import($db,$cfg,$user,$mapping,$fileId,true,$old,$adapter);check($sync['asset']['id']!==$old['id']&&$sync['asset']['supersedes_id']===$old['id'],'Drive sync imports immutable replacement asset');check(MediaLibrary::asset($db,$user,(int)$old['id'])['source_modified_time']==='2026-10-05T06:00:00Z','Drive refresh leaves original media source snapshot intact');check(!array_filter($calls,fn($url)=>str_contains($url,'files?')&&!str_contains(urldecode($url),"'$folderId' in parents")),'every Drive list request has folder constraint');
echo "VS2.2 media/proposal MariaDB suite complete.\n";
