<?php
declare(strict_types=1);
require __DIR__.'/vs21-native.php';
function coverageError(callable $fn,string $code,string $label): void {try{$fn();}catch(Throwable $e){check(str_starts_with($e->getMessage(),$code),$label.' actual '.$e->getMessage());return;}throw new RuntimeException('FAIL accepted '.$label);}
$qvid=$new;$g=QuoteVs2Repository::graph($db,v2v());$variant=(int)array_values(array_filter($g['variants'],fn($x)=>$x['variant_key']==='sic-4-4'))[0]['id'];
v2context(['hotel_pax'=>20,'cruise_pax'=>20,'meal_pax'=>20,'visa_pax'=>null,'ticket_pax'=>null]);v2context(['adults'=>19,'total_guests'=>22]);$p=QuoteVs2Repository::graph($db,v2v())['profile'];check((int)$p['hotel_pax']===20&&(int)$p['cruise_pax']===20&&(int)$p['meal_pax']===20&&$p['visa_pax']===null,'L12 accepted suggestions remain explicit after total changes');v2context(['adults'=>17,'total_guests'=>20,'hotel_pax'=>16,'cruise_pax'=>16,'visa_pax'=>12,'meal_pax'=>15,'ticket_pax'=>13]);
$specs=['GUIDE'=>['dates'=>['2027-01-03']],'MEAL'=>['occurrences'=>['day2-lunch'],'meal_key'=>'lunch'],'ATTRACTION'=>['attraction_key'=>'Bana','eligibility_group'=>'adult'],'TRANSPORT'=>['transport_leg'=>'sic-day','route'=>'Bana shared transfer'],'TOUR'=>[]];$updates=[];
foreach($g['requirements'] as $r)$updates[]=['id'=>(int)$r['id'],'requirement_state'=>isset($specs[$r['category']])?'REQUIRED':'NOT_APPLICABLE','service_date'=>'2027-01-03','service_units'=>1,'service_mode'=>'BOTH','day_key'=>'day-2','scope'=>$specs[$r['category']]??[],'metadata'=>['reason'=>'Synthetic reviewed Hybrid service scope']];v2context(['requirements'=>$updates]);
$rules=[];foreach(['GUIDE'=>1,'MEAL'=>15,'ATTRACTION'=>13,'TRANSPORT'=>1] as $cat=>$qty)$rules[]=['component_key'=>strtolower($cat),'included_category'=>$cat,'scope'=>['service_date'=>'2027-01-03','day_key'=>'day-2']+$specs[$cat],'coverage'=>['quantity'=>$qty,'units'=>1],'description'=>'Documented exact '.$cat.' inclusion'];$packageRate=v2rate('TOUR','900000','SIC_PAX',null,[],$rules);
foreach(['GUIDE','MEAL','ATTRACTION'] as $cat){$l=v2line($variant,$cat);v2edit($variant,(int)$l['id'],['rate_version_id'=>$rates[$cat]]+($cat==='GUIDE'?['custom_quantity'=>1]:[]));}
$t=v2line($variant,'TRANSPORT');v2edit($variant,(int)$t['id'],['formula_code'=>'CUSTOM','quantity_source'=>'CUSTOM_QTY','custom_quantity'=>1,'rate_version_id'=>null,'supplier_id'=>1,'unit_amount_original'=>'100000','manual_reason'=>'Reviewed one local leg only','manual_contract'=>['formula_code'=>'CUSTOM','tax_basis'=>'NET','evidence'=>'Synthetic local-leg contract']]);$package=v2line($variant,'TOUR');v2edit($variant,(int)$package['id'],['quantity_source'=>'CUSTOM_QTY','custom_quantity'=>16,'rate_version_id'=>$packageRate]);
foreach(['GUIDE','MEAL','ATTRACTION','TRANSPORT'] as $cat)check(v2line($variant,$cat)['coverage_state']==='INCLUDED'&&v2line($variant,$cat)['total_vnd']==='0.00','L22 exact '.$cat.' suppressed');
foreach(['MEAL'=>['service_date'=>'2027-01-04','scope'=>['occurrences'=>['day3-dinner'],'meal_key'=>'dinner'],'quantity_source'=>'MEAL_PAX','rate_version_id'=>$rates['MEAL']],'ATTRACTION'=>['service_date'=>'2027-01-03','scope'=>['attraction_key'=>'Other','eligibility_group'=>'adult'],'quantity_source'=>'TICKET_PAX','rate_version_id'=>$rates['ATTRACTION']],'TRANSPORT'=>['service_date'=>'2027-01-03','scope'=>['transport_leg'=>'airport','route'=>'Airport pickup'],'quantity_source'=>'CUSTOM_QTY','custom_quantity'=>1,'formula_code'=>'CUSTOM','supplier_id'=>1,'unit_amount_original'=>'100000','manual_reason'=>'Separate airport leg','manual_contract'=>['formula_code'=>'CUSTOM','tax_basis'=>'NET','evidence'=>'Synthetic airport contract']]] as $cat=>$line){$req=['category'=>$cat,'service_name'=>'Unrelated '.$cat,'default_quantity_source'=>$line['quantity_source'],'service_units'=>1,'requirement_state'=>'REQUIRED','service_date'=>$line['service_date'],'scope'=>$line['scope']];unset($line['scope'],$line['service_date']);$x=v2command([],fn($v)=>Vs2LineEditor::write($db,$user,$v,$variant,['requirement'=>$req]+$line));check(v2q('SELECT coverage_state FROM quote_variant_cost_lines WHERE id=?',[$x['line_id']])->fetchColumn()==='PRICED','L22 unrelated '.$cat.' remains priced');v2review($variant,$x['line_id']);}
v2command([],fn($v)=>['id'=>Vs2Variants::save($db,$user,$v,['variant_id'=>$variant,'costing_mode'=>'HYBRID','is_offered'=>true])]);foreach(v2q('SELECT id FROM quote_variant_cost_lines WHERE variant_id=? AND coverage_state IN (\'PRICED\',\'INCLUDED\')',[$variant])->fetchAll() as $l)v2review($variant,(int)$l['id']);check(QuoteVs2Validator::validate($db,v2v())['valid'],'L28 reviewed Hybrid with exact coverage validates');
coverageError(fn()=>v2command([],fn($v)=>Vs2LineEditor::write($db,$user,$v,$variant,[],'duplicate',(int)$package['id'])),'DUPLICATE_PACKAGE_COVERAGE','L23 duplicate package rolls back');
// Direct corruption fixture proves the validator also catches a renamed included/charged duplicate.
$l=v2line($variant,'MEAL');v2q("UPDATE quote_variant_cost_lines SET coverage_state='PRICED',total_vnd=3000000 WHERE id=?",[$l['id']]);check(in_array('DUPLICATE_INCLUDED_COST',v2codes(),true)||in_array('STALE_CALCULATION',v2codes(),true),'L23 included plus chargeable duplicate cannot pass');Vs2Inclusions::apply($db,v2v());
$partialRules=$rules;$partialRules[1]['coverage']['quantity']=10;$partialRate=v2rate('TOUR','900000','SIC_PAX',null,[],$partialRules);v2edit($variant,(int)$package['id'],['rate_version_id'=>$partialRate]);v2edit($variant,(int)$l['id'],['rate_version_id'=>$rates['MEAL']]);check(in_array('PARTIAL_COVERAGE_REVIEW',v2codes(),true),'L24 central validator blocks 10/15 meal coverage');v2edit($variant,(int)$package['id'],['rate_version_id'=>$packageRate]);
$transport=v2line($variant,'TRANSPORT');v2context(['requirements'=>[['id'=>(int)$transport['requirement_id'],'scope'=>['transport_leg'=>'full-tour']]]]);v2edit($variant,(int)$transport['id'],['formula_code'=>'TRANSFER_PACKAGE','quantity_source'=>'CUSTOM_QTY','custom_quantity'=>2,'rate_version_id'=>$rates['TRANSPORT']]);check(in_array('TRANSFER_SCOPE_OVERLAP',v2codes(),true),'L25 full-tour transfer retained and overlap blocks Send');
// Declared requirement units, dates and unknown quantities establish completeness.
$guide=v2line($variant,'GUIDE');v2context(['requirements'=>[['id'=>(int)$guide['requirement_id'],'service_units'=>2]]]);check(in_array('GUIDE_DAYS_MISMATCH',v2codes(),true),'L43 guide day mismatch');$meal=v2line($variant,'MEAL');v2context(['requirements'=>[['id'=>(int)$meal['requirement_id'],'service_units'=>2]]]);check(in_array('MEAL_COUNT_MISMATCH',v2codes(),true),'L43 meal count mismatch');v2context(['ticket_pax'=>null]);check(!QuoteVs2Validator::validate($db,v2v())['valid'],'L43 unset ticket quantity blocks');
echo "VS2.1 native coverage checks complete.\n";
