<?php
declare(strict_types=1);
require_once __DIR__.'/../api/lib/Migrations.php';
function mcheck(bool $ok,string $label): void {if(!$ok)throw new RuntimeException('FAIL '.$label);echo "PASS $label\n";}
$password=getenv('VTA_TEST_DB_PASSWORD')?:throw new RuntimeException('Disposable server password required');
$db=new PDO('mysql:host=127.0.0.1;port=33317;charset=utf8mb4','root',$password,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$name='vta_vs21_migration_'.bin2hex(random_bytes(5));$db->exec("CREATE DATABASE `$name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");$db->exec("USE `$name`");
$baseline=sys_get_temp_dir().'/vs21-baseline-'.bin2hex(random_bytes(5));mkdir($baseline);$all=glob(__DIR__.'/../api/migrations/*.sql');sort($all);foreach($all as $file)if((int)basename($file)<=22)copy($file,$baseline.'/'.basename($file));
mcheck(count(Migrations::run($db,$baseline))===22,'L49 supported 022 baseline');
$db->exec("INSERT INTO companies(code,name) VALUES('OLD','Old tenant')");$db->exec("INSERT INTO roles(company_id,code,name) VALUES(1,'ADMIN','Admin')");$db->exec("INSERT INTO users(company_id,role_id,full_name,email,password_hash) VALUES(1,1,'Old','old@example.invalid','old-password-hash')");$db->exec("INSERT INTO trips(company_id,trip_ref,title,created_by,updated_by) VALUES(1,'OLD','Historical',1,1)");$db->exec("INSERT INTO quotes(company_id,quote_ref,trip_id,created_by,updated_by) VALUES(1,'OLD',1,1,1)");$db->exec("INSERT INTO quote_versions(quote_id,version_no,version_status,tour_name,created_by,sent_snapshot_json) VALUES(1,1,'SENT','Historical',1,'{\"exact\":\"old public bytes\"}')");$db->exec("INSERT INTO quote_options(quote_version_id,label,hotel_level,snapshot_json,created_by) VALUES(1,'Old','4*','{\"exact\":\"old internal bytes\"}',1)");$db->exec("INSERT INTO quote_sent_bundles(quote_version_id,public_snapshot_json,internal_snapshot_json,content_hash,sent_by) VALUES(1,'{\"public\":1}','{\"internal\":1}',REPEAT('a',64),1)");$db->exec("INSERT INTO quote_acceptances(quote_version_id,option_id,sent_content_hash,accepted_by) VALUES(1,1,REPEAT('a',64),1)");
$capture=fn()=>[$db->query('SELECT sent_snapshot_json FROM quote_versions')->fetchColumn(),$db->query('SELECT snapshot_json FROM quote_options')->fetchColumn(),$db->query('SELECT public_snapshot_json,internal_snapshot_json,content_hash FROM quote_sent_bundles')->fetchAll(),$db->query('SELECT sent_content_hash FROM quote_acceptances')->fetchColumn()];$before=$capture();
// Keep the approved VS2.1 gate scoped to its release; VS2.2 upgrades have their own test.
foreach($all as $file)if((int)basename($file)>22 && (int)basename($file)<=28)copy($file,$baseline.'/'.basename($file));
$new=Migrations::run($db,$baseline);mcheck($new===['025_vs21_shared_requirements','026_vs21_rate_terms','027_vs21_variant_costs','028_vs21_acceptance_links'],'L49 only four additive upgrades');mcheck($before===$capture(),'L49 issued snapshot bytes preserved');mcheck($db->query('SELECT costing_engine FROM quote_versions')->fetchColumn()==='VS1','L49 no silent opt in');mcheck($db->query('SELECT variant_id FROM quote_acceptances')->fetchColumn()===null,'L49 old acceptance remains null');mcheck(Migrations::run($db,$baseline)===[],'L49 rerun no-op');
$idx=$db->query("SHOW INDEX FROM quote_options WHERE Key_name='uq_option_level'")->fetchAll();mcheck(array_column($idx,'Column_name')===['quote_version_id','hotel_level'],'L49 parent unique index retained');
$db->exec("INSERT INTO schema_migrations(version) VALUES('023_smart_costing')");try{Migrations::run($db,$baseline);throw new LogicException('Accepted candidate history');}catch(RuntimeException $e){mcheck(str_contains($e->getMessage(),'Candidate 023/024'),'L49 incompatible candidate history stopped');}$db->exec("DELETE FROM schema_migrations WHERE version='023_smart_costing'");
$db->exec("UPDATE migration_checksums SET status='FAILED' WHERE version='027_vs21_variant_costs'");try{Migrations::run($db,$baseline);throw new LogicException('Accepted partial state');}catch(RuntimeException $e){mcheck(str_contains($e->getMessage(),'Partial migration'),'L49 partial DDL retry stopped');}
foreach(glob($baseline.'/*.sql') as $file)unlink($file);rmdir($baseline);
echo "VS2.1 migration upgrade checks complete.\n";
