const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const source=fs.readFileSync(path.join(__dirname,'../smart-costing.js'),'utf8');
const settle=async()=>{for(let i=0;i<6;i++)await new Promise(r=>setImmediate(r));};
async function harness(cost=true,status='DRAFT'){
 const dom=new JSDOM('<main></main>',{runScripts:'outside-only',url:'https://local.test'}),w=dom.window,calls=[];w.eval(source);
 const context={costing_revision:3,guests:{adults:17,children:1,infants:0,foc:2,total_guests:20,paying_pax:18},profile:{hotel_pax:16,cruise_pax:16,visa_pax:12,meal_pax:15,ticket_pax:13},schedule:[{day_key:'d1',title:'Arrival',date:'2027-01-02',route:'Hanoi'}],requirements:[{id:1,service_name:'Hotel',category:'HOTEL',service_mode:'BOTH',requirement_state:'REQUIRED',default_quantity_source:'HOTEL_PAX',scope:{dates:['2027-01-02']},metadata:{}}]};
 const options={costing_revision:3,items:[{variant_id:2,option_id:3,label:'Recommended',hotel_level:'4*',cruise_level:4,is_offered:1,pricing:{cost_total_vnd:'100000.00',selling_per_pax:'10.00'},lines:[{id:4,requirement_id:1,service_name:'Hotel',quantity_source:'HOTEL_PAX',quantity_override:null,resolved_quantity:16,resolved_units:3,unit_rate_vnd:'800000.00',total_vnd:'38400000.00',rate_status:'APPROVED_RATE',origin:'AUTO',review_required:0,active:true,trace:{sentence:'16 × 3 × 800000 VND = 38400000 VND'}}]}]};
 const api={request:async(route,opt={})=>{calls.push({route,...opt});if(route.endsWith('/context'))return structuredClone(context);if(route.endsWith('/options'))return structuredClone(options);if(route.endsWith('/validation'))return {valid:false,errors:[{code:'RATE_NEEDED'}],warnings:[]};return {costing_revision:4};}};
 const root=w.document.querySelector('main');await w.mountSmartQuote(root,{api,quoteData:{quote:{id:1,quote_ref:'Q1'},version:{id:10,version_no:1,version_status:status,tour_name:'Shared itinerary'}},can:p=>p==='quote.view_cost'?cost:p!=='quote.view_profit',navigate:()=>{},modal:()=>{throw Error('Unexpected modal');},closeModal:()=>{},toast:()=>{},refresh:async()=>{}});return {dom,w,root,calls};
}
(async()=>{
 let h=await harness();assert.equal(h.root.querySelectorAll('[data-days] article').length,1);assert(h.root.textContent.includes('Hotel'));h.root.querySelector('[data-guests] [name="hotel_pax"]').value='18';h.root.querySelector('[data-guests]').dispatchEvent(new h.w.Event('submit',{bubbles:true,cancelable:true}));await settle();const post=h.calls.find(c=>c.method==='PUT');assert.equal(post.body.hotel_pax,18);assert.equal(post.body.expected_revision,3);assert(!('unit_rate_vnd' in post.body));console.log('PASS L10/L12 guest inputs carry revision, not totals');h.root.querySelector('[data-view]').click();assert(h.root.textContent.includes('16 × 3 × 800000'));assert(h.root.textContent.includes('After booking'));console.log('PASS L31 Simple/Advanced shows trace and distinct financial stages');h.root.querySelector('[data-validate]').click();await settle();assert(h.root.textContent.includes('RATE_NEEDED'));console.log('PASS L42 validation blocks missing rates');h.dom.window.close();
 h=await harness(false);assert(!h.calls.some(x=>x.route.endsWith('/options')));assert(!h.root.textContent.includes('38400000'));assert(!h.root.querySelector('[data-costs]'));assert(h.root.querySelector('[data-guests]'));console.log('PASS L36 guest-only UI never loads supplier costing');h.dom.window.close();
 h=await harness(true,'SENT');assert(!h.root.querySelector('[data-add-line]'));assert(!h.root.querySelector('[data-save-day]'));assert(h.root.querySelector('[data-guests] input').disabled);console.log('PASS L45 issued quote editor read-only');h.dom.window.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
