<?php
declare(strict_types=1);
require __DIR__.'/vs21-native.php';
require_once __DIR__.'/../api/lib/FinanceLedger.php';
function v2error(callable $fn,string $code,string $label): void {try{$fn();}catch(Throwable $e){check(str_starts_with($e->getMessage(),$code),$label.' '.$code);return;}throw new RuntimeException('FAIL accepted '.$label);}
function edgeResolve(array $line,array $req,array $variant): array {global $db; $v=v2v();$g=QuoteVs2Repository::graph($db,$v);return Vs2RateResolver::resolve($db,$v,QuoteVs2Domain::guests($v,$g['profile']),$req,$variant,$line);}
function lifecycleParallel(string $action,array $extra=[]): array {global $database,$qvid;$processes=[];for($i=0;$i<2;$i++){$p=proc_open([PHP_BINARY,__DIR__.'/vs21-worker.php',$database,(string)$qvid,(string)v2v()['costing_revision'],$action,json_encode($extra)],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);if(!is_resource($p))throw new RuntimeException('Cannot create lifecycle worker');fclose($pipes[0]);$processes[]=[$p,$pipes];}$out=[];foreach($processes as [$p,$pipes]){$out[]=trim(stream_get_contents($pipes[1])).trim(stream_get_contents($pipes[2]));fclose($pipes[1]);fclose($pipes[2]);check(proc_close($p)===0,'L40 concurrent '.$action.' worker '.$out[count($out)-1]);}return $out;}
$issued=$snapshot;$source=$qvid;$qvid=$new;$g=QuoteVs2Repository::graph($db,v2v());$variant=(int)array_values(array_filter($g['variants'],fn($x)=>$x['variant_key']==='private-4-4'))[0]['id'];
v2context(['requirements'=>array_map(fn($r)=>['id'=>(int)$r['id'],'requirement_state'=>'NOT_APPLICABLE','metadata'=>['reason'=>'Not required in dependency test']],$g['requirements'])]);
// Eight live DB lines prove selection by returned arithmetic IDs and persisted trace bytes.
$probe=[];
foreach(QuoteVs2Domain::SOURCES as $sourceName){$x=v2command([],fn($v)=>Vs2LineEditor::write($db,$user,$v,$variant,['requirement'=>['category'=>'OTHER','service_name'=>'Dependency '.$sourceName,'default_quantity_source'=>$sourceName,'service_units'=>1,'service_date'=>'2027-01-02','requirement_state'=>'REQUIRED','scope'=>['probe'=>$sourceName]],'formula_code'=>'CUSTOM','quantity_source'=>$sourceName,'custom_quantity'=>1,'supplier_id'=>1,'unit_amount_original'=>'10.10','manual_reason'=>'Reviewed synthetic contract','manual_contract'=>['formula_code'=>'CUSTOM','tax_basis'=>'NET','evidence'=>'Synthetic published contract']]));$probe[$sourceName]=$x['line_id'];}
$sig=fn($id)=>v2q('SELECT total_vnd,input_hash,calculation_trace_json,calculated_at FROM quote_variant_cost_lines WHERE id=?',[$id])->fetch();
foreach(array_slice(QuoteVs2Domain::SOURCES,0,7) as $s){$before=[];foreach($probe as $k=>$lid)$before[$k]=$sig($lid);$v=v2v();$profile=QuoteVs2Repository::graph($db,$v)['profile'];$key=strtolower($s);$value=(int)($v[$key]??$profile[$key]);$body=$s==='TOTAL_GUESTS'?['total_guests'=>$value+1,'adults'=>(int)$v['adults']+1]:[$key=>$s==='PAYING_PAX'?$value-1:$value+1];$out=v2context($body);foreach($probe as $k=>$lid)check(in_array($lid,$out['recalculated_line_ids'],true)===($k===$s)&&($k===$s||$sig($lid)===$before[$k]),'L10 native '.$s.' → '.$k);$restore=$s==='TOTAL_GUESTS'?['total_guests'=>$value,'adults'=>(int)$v['adults']]:[$key=>$value];v2context($restore);}
$before=$sig($probe['HOTEL_PAX']);v2edit($variant,$probe['CUSTOM_QTY'],['custom_quantity'=>2]);check($sig($probe['HOTEL_PAX'])===$before&&$sig($probe['CUSTOM_QTY'])['total_vnd']==='20.20','L10 local CUSTOM_QTY targets one line');
// Native failure injection proves child, revision, summary and audit are one transaction.
$before=v2v();$profile=v2q('SELECT * FROM quote_guest_profiles WHERE quote_version_id=?',[$qvid])->fetch();$audit=v2q('SELECT COUNT(*) FROM audit_logs')->fetchColumn();
v2q("CREATE TRIGGER vs21_audit_failure BEFORE INSERT ON audit_logs FOR EACH ROW BEGIN IF NEW.action_code='VS21_CONTEXT_UPDATED' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Synthetic audit failure'; END IF; END");
rejects(fn()=>v2context(['visa_pax'=>13]),PDOException::class,'L39 audit write failure rejects command');v2q('DROP TRIGGER vs21_audit_failure');check(v2v()===$before&&v2q('SELECT * FROM quote_guest_profiles WHERE quote_version_id=?',[$qvid])->fetch()===$profile&&v2q('SELECT COUNT(*) FROM audit_logs')->fetchColumn()===$audit,'L39 all effects rolled back');
// Editor ownership, server-only fields, genuine zero and negative net.
$line=v2q('SELECT * FROM quote_variant_cost_lines WHERE id=?',[$probe['CUSTOM_QTY']])->fetch();
v2error(fn()=>v2edit($variant,(int)$line['id'],['total_vnd'=>'1']),'Unsupported cost input','L41 client final cost rejected');
v2error(fn()=>v2edit($variant,(int)$line['id'],['supplier_id'=>2]),'Supplier not in this company','L38 foreign supplier');
v2error(fn()=>v2edit($variant,(int)$line['id'],['requirement_id'=>$hotel['requirement_id']]),'Requirement not found','L38 same-company foreign version');
$dup=v2command([],fn($v)=>Vs2LineEditor::write($db,$user,$v,$variant,[],'duplicate',(int)$line['id']));v2command([],fn($v)=>Vs2LineEditor::write($db,$user,$v,$variant,['sort_order'=>77],'reorder',$dup['line_id']));check((int)v2q('SELECT sort_order FROM quote_variant_cost_lines WHERE id=?',[$dup['line_id']])->fetchColumn()===77,'L31 duplicate and reorder stable ID');v2command([],fn($v)=>Vs2LineEditor::write($db,$user,$v,$variant,[],'delete',$dup['line_id']));check(v2q('SELECT id FROM quote_variant_cost_lines WHERE id=?',[$dup['line_id']])->fetchColumn()===false,'L31 explicit removal');
v2edit($variant,(int)$line['id'],['no_cost'=>true,'manual_reason'=>'Supplier documented complimentary service','manual_contract'=>['evidence'=>'Written supplier complimentary commitment','formula_code'=>'CUSTOM','tax_basis'=>'NET']]);v2review($variant,(int)$line['id']);check(v2q('SELECT coverage_state FROM quote_variant_cost_lines WHERE id=?',[$line['id']])->fetchColumn()==='NO_COST','L32 genuine reviewed no-cost');
v2edit($variant,(int)$line['id'],['unit_amount_original'=>'10.10']);v2review($variant,(int)$line['id']);$neg=v2command([],fn($v)=>Vs2LineEditor::write($db,$user,$v,$variant,['requirement_id'=>$line['requirement_id'],'line_kind'=>'ADJUSTMENT','adjusts_line_id'=>$line['id'],'formula_code'=>'CUSTOM','quantity_source'=>'CUSTOM_QTY','custom_quantity'=>1,'adjustment_amount_vnd'=>'-30','manual_reason'=>'Synthetic overdiscount']));$v=v2v();$g=QuoteVs2Repository::graph($db,$v);$child=array_values(array_filter($g['variants'],fn($x)=>(int)$x['id']===$variant))[0];v2error(fn()=>QuoteVs2Validator::bookingLines($child['lines'],array_column($g['requirements'],null,'id'),(string)$v['fx_rate']),'NEGATIVE_SERVICE_NET','L33 overdiscount rejected');v2command([],fn($v)=>Vs2LineEditor::write($db,$user,$v,$variant,[],'delete',$neg['line_id']));
// Reuse approved hotel rate to exercise every contracting eligibility gate.
$hotelReq=v2q('SELECT * FROM quote_service_requirements WHERE id=?',[$hotel['requirement_id']])->fetch();$rateLine=$hotel;$hotelVariant=['hotel_level'=>'4*','cruise_level'=>4];$rid=$rates['HOTEL'];$rateMaster=v2q('SELECT rate_id FROM rate_versions WHERE id=?',[$rid])->fetchColumn();
foreach([['rate_versions','approval_status','UNREVIEWED','APPROVED',$rid],['rate_versions','valid_to','2026-01-01','2028-12-31',$rid],['rates','status','INACTIVE','ACTIVE',$rateMaster],['rates','market','FOREIGN',null,$rateMaster],['rates','min_pax',21,null,$rateMaster],['rates','max_pax',19,null,$rateMaster]] as [$table,$field,$invalid,$restore,$key]){v2q("UPDATE $table SET $field=? WHERE id=?",[$invalid,$key]);v2error(fn()=>edgeResolve($rateLine,$hotelReq,$hotelVariant),'RATE_UNAVAILABLE','L18 '.$field.' eligibility');v2q("UPDATE $table SET $field=? WHERE id=?",[$restore,$key]);}
v2q("INSERT INTO rate_date_periods(rate_version_id,period_type,start_date,end_date,adjustment_type) VALUES(?,'BLACKOUT','2027-01-03','2027-01-03','NONE')",[$rid]);v2error(fn()=>edgeResolve($rateLine,$hotelReq,$hotelVariant),'RATE_UNAVAILABLE','L18 blackout');v2q('DELETE FROM rate_date_periods WHERE rate_version_id=?',[$rid]);
v2q("INSERT INTO rate_date_periods(rate_version_id,period_type,start_date,end_date,adjustment_type,adjustment_value) VALUES(?,'PEAK','2027-01-03','2027-01-03','FIXED',0.10)",[$rid]);v2error(fn()=>edgeResolve($rateLine,$hotelReq,$hotelVariant),'SEGMENTED_RATE_REVIEW_REQUIRED','L18 differing daily rates');v2q('UPDATE rate_date_periods SET start_date=\'2027-01-02\',end_date=\'2027-01-04\' WHERE rate_version_id=?',[$rid]);check(edgeResolve($rateLine,$hotelReq,$hotelVariant)['amount']==='800000.10','L09 native decimal seasonal addition');v2q("INSERT INTO rate_date_periods(rate_version_id,period_type,start_date,end_date,adjustment_type,adjustment_value) VALUES(?,'HOLIDAY','2027-01-02','2027-01-04','FIXED',1)",[$rid]);v2error(fn()=>edgeResolve($rateLine,$hotelReq,$hotelVariant),'RATE_UNAVAILABLE','L18 overlapping seasonal conflict');v2q('DELETE FROM rate_date_periods WHERE rate_version_id=?',[$rid]);
v2q("UPDATE rate_version_vs2_terms SET rate_eligibility_source='VISA_PAX' WHERE rate_version_id=?",[$rid]);v2q('UPDATE rates SET max_pax=12 WHERE id=?',[$rateMaster]);check(edgeResolve($rateLine,$hotelReq,$hotelVariant)['amount']==='800000.00','L17 eligibility uses VISA_PAX independently of HOTEL_PAX');v2context(['visa_pax'=>13]);v2error(fn()=>edgeResolve($rateLine,$hotelReq,$hotelVariant),'RATE_UNAVAILABLE','L17 unbound guest change still revalidates eligibility');v2context(['visa_pax'=>12]);v2q('UPDATE rates SET max_pax=NULL WHERE id=?',[$rateMaster]);v2q("UPDATE rate_version_vs2_terms SET rate_eligibility_source='TOTAL_GUESTS' WHERE rate_version_id=?",[$rid]);
v2q('UPDATE rate_versions SET amount=0 WHERE id=?',[$rid]);check(edgeResolve($rateLine,$hotelReq,$hotelVariant)['amount']==='0.00','L19 published supplier zero is distinct from missing rate');v2q('UPDATE rate_versions SET amount=800000 WHERE id=?',[$rid]);
// Cycles and partial overlap cannot be hidden by requirement names.
$g=QuoteVs2Repository::graph($db,v2v());$tourReq=array_values(array_filter($g['requirements'],fn($r)=>$r['category']==='TOUR'))[0];$cruiseReq=array_values(array_filter($g['requirements'],fn($r)=>$r['category']==='CRUISE'))[0];v2context(['requirements'=>[['id'=>(int)$tourReq['id'],'package_requirement_id'=>(int)$cruiseReq['id']]]]);v2error(fn()=>v2context(['requirements'=>[['id'=>(int)$cruiseReq['id'],'package_requirement_id'=>(int)$tourReq['id']]]]),'INCLUSION_CYCLE','L23 requirement package cycle');v2context(['requirements'=>[['id'=>(int)$tourReq['id'],'package_requirement_id'=>null]]]);
$mealReq=v2q('SELECT * FROM quote_service_requirements WHERE id=?',[$meal['requirement_id']])->fetch();$rule=['included_category'=>'MEAL','component_key'=>'meal','scope_rule_json'=>json_encode(['service_date'=>$mealReq['service_date']]),'coverage_rule_json'=>json_encode(['quantity'=>10,'units'=>1])];check(Vs2Inclusions::overlaps($rule,$mealReq)&&!Vs2Inclusions::covers($rule,$mealReq,$meal,$tour,QuoteVs2Domain::guests(v2v(),$g['profile'])),'L24 partial meal scope flagged without guessed proration');
// Disable creation while keeping the shared reader alive.
putenv('VTA_VS21_CREATION=0');check(QuoteVs2::optionsDto($db,$user,v2v())['schema']==='VS2_1','L50 rollback flag retains existing reader');$pending=v2q("INSERT INTO quote_versions(quote_id,version_no,tour_name,created_by) VALUES(?,3,'Disabled creation probe',1)",[v2v()['quote_id']]);$pid=(int)$db->lastInsertId();v2error(fn()=>QuoteSmartCosting::activate($db,$user,$pid,['expected_revision'=>0]),'VS21_CREATION_DISABLED','L50 creation flag blocks opt in');putenv('VTA_VS21_CREATION');
// Real concurrent MariaDB writers: the first holds the quote lock; the second must lose on revision.
$revision=(int)v2v()['costing_revision'];$args=[PHP_BINARY,__DIR__.'/vs21-worker.php',$database,(string)$qvid,(string)$revision];$procs=[];
foreach(['FIRST','SECOND'] as $label){$p=proc_open([...$args,$label],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);if(!is_resource($p))throw new RuntimeException('Cannot start concurrent fixture');fclose($pipes[0]);$procs[]=[$p,$pipes];}
$messages=[];foreach($procs as [$p,$pipes]){$messages[]=trim(stream_get_contents($pipes[1])).trim(stream_get_contents($pipes[2]));fclose($pipes[1]);fclose($pipes[2]);check(proc_close($p)===0,'L40 parallel worker completes');}sort($messages);check($messages===['PASS','STALE_REVISION']&&(int)v2v()['costing_revision']===$revision+1,'L40 parallel writes exactly one succeeds');
check(v2q('SELECT internal_snapshot_json FROM quote_sent_bundles WHERE quote_version_id=?',[$source])->fetchColumn()===$issued,'L45 original sent bytes unchanged by all probes');
// Reuse at new dates, then hand a real original-currency USD service to existing finance.
v2q("UPDATE trips SET adults=17,children=1,infants=0,foc=2,total_guests=20,paying_pax=18,start_date='2027-02-12',end_date='2027-02-15' WHERE id=?",[$conversion['trip_id']]);
$cloned=QuoteReuse::clone($db,$user,$source,$conversion['inquiry_id'],'FULL_DRAFT');$qvid=(int)$cloned['version_id'];$g=QuoteVs2Repository::graph($db,v2v());check($g['profile']['visa_pax']===null&&$g['requirements'][0]['service_date']==='2027-02-12','L48 reused guest profile resets and typed dates shift');
v2context(['hotel_pax'=>16,'cruise_pax'=>16,'visa_pax'=>12,'meal_pax'=>15,'ticket_pax'=>13,'requirements'=>array_map(fn($r)=>['id'=>(int)$r['id'],'requirement_state'=>'NOT_APPLICABLE','metadata'=>['reason'=>'Only contracted custom service for synthetic USD case']],$g['requirements'])]);$variant=(int)array_values(array_filter($g['variants'],fn($x)=>$x['variant_key']==='private-4-4'))[0]['id'];
$usd=v2command([],fn($v)=>Vs2LineEditor::write($db,$user,$v,$variant,['requirement'=>['category'=>'OTHER','service_name'=>'Documented USD supplier service','default_quantity_source'=>'CUSTOM_QTY','service_units'=>1,'service_date'=>'2027-02-12','requirement_state'=>'REQUIRED','metadata'=>['internal_notes'=>'Reviewed handover notes']], 'formula_code'=>'LUMP_SUM','quantity_source'=>'CUSTOM_QTY','custom_quantity'=>1,'supplier_id'=>1,'original_currency'=>'USD','unit_amount_original'=>'100.00','manual_reason'=>'Supplier original USD contract','manual_contract'=>['formula_code'=>'LUMP_SUM','tax_basis'=>'NET','evidence'=>'Synthetic written USD contract']]));$usdLine=v2q('SELECT * FROM quote_variant_cost_lines WHERE id=?',[$usd['line_id']])->fetch();v2review($variant,(int)$usdLine['id']);check($usdLine['total_vnd']==='2500000.00','L47 original USD100 yields VND2500000 at frozen FX');
v2command([],fn($v)=>['id'=>Vs2Variants::save($db,$user,$v,['variant_id'=>$variant,'is_offered'=>true,'cruise_level'=>null])]);
$adjust=v2command([],fn($v)=>Vs2LineEditor::write($db,$user,$v,$variant,['requirement_id'=>$usdLine['requirement_id'],'line_kind'=>'ADJUSTMENT','adjusts_line_id'=>$usdLine['id'],'formula_code'=>'CUSTOM','quantity_source'=>'CUSTOM_QTY','custom_quantity'=>1,'adjustment_amount_vnd'=>'-1','manual_reason'=>'Synthetic unrepresentable USD adjustment']));check(in_array('CURRENCY_ADJUSTMENT_REVIEW',v2codes(),true),'L47 unrepresentable original-currency adjustment blocks Send');v2command([],fn($v)=>Vs2LineEditor::write($db,$user,$v,$variant,[],'delete',$adjust['line_id']));
check(QuoteVs2Validator::validate($db,v2v())['valid'],'L43 explicit custom basis and reviewed handover validate');$a=QuoteOptions::approve($db,$user,$qvid,'USD handover reviewed');check(lifecycleParallel('SEND')===['PASS','PASS']&&(int)v2q('SELECT COUNT(*) FROM quote_sent_bundles WHERE quote_version_id=?',[$qvid])->fetchColumn()===1,'L40 concurrent initial Send returns one frozen bundle');$parent=(int)QuoteVs2Repository::variant($db,$qvid,$variant)['quote_option_id'];check(lifecycleParallel('ACCEPT',['option_id'=>$parent,'variant_id'=>$variant,'hash'=>$a['content_hash']])===['PASS','PASS']&&(int)v2q('SELECT COUNT(*) FROM quote_acceptances WHERE quote_version_id=?',[$qvid])->fetchColumn()===1,'L40 concurrent exact acceptance idempotent');$books=lifecycleParallel('BOOK');check($books[0]===$books[1]&&str_starts_with($books[0],'BOOK:'),'L40 concurrent initial booking returns one ID');$usdBooking=QuoteOptions::booking($db,$user,$qvid);$bid=(int)$usdBooking['id'];$service=v2q('SELECT * FROM booking_services WHERE booking_id=?',[$bid])->fetch();check($service['planned_cost']==='100.00'&&$service['cost_currency']==='USD'&&$service['notes']==='Reviewed handover notes','L47 booking preserves USD and notes');
$orders=Procurement::generate($db,$user,$bid);check(count($orders['items'])===1,'L47 no duplicate payable for inactive/included lines');$oid=(int)$orders['items'][0]['id'];Procurement::send($db,$user,$oid);Procurement::confirm($db,$user,$oid,['status'=>'CONFIRMED','confirmation_no'=>'VS21-USD','confirmation_source'=>'EMAIL','currency'=>'USD','confirmed_total'=>'100.00']);$ap=v2q('SELECT * FROM supplier_payables WHERE booking_id=?',[$bid])->fetch();check($ap['total_amount']==='100.00','L47 existing confirmation and AP use original USD');
$recon=FinanceLedger::reconcile($db,$user,(int)$ap['id'],['supplier_invoice_no'=>'VS21-USD-INVOICE','invoice_amount'=>'100.00','currency'=>'USD','reason'=>'Original contracted cost confirmed']);FinanceLedger::approveReconciliation($db,$user,$recon['id']);FinanceLedger::supplierPayment($db,$user,(int)$ap['id'],['amount'=>'100.00','currency'=>'USD','payment_date'=>'2027-02-16','transaction_reference'=>'VS21-SUP-BANK','idempotency_key'=>'vs21-supplier-bank']);
$selling=v2q('SELECT confirmed_selling FROM bookings WHERE id=?',[$bid])->fetchColumn();$invoice=FinanceLedger::createInvoice($db,$user,$bid,['invoice_type'=>'CUSTOMER_INVOICE','subtotal'=>$selling,'issue_date'=>'2027-02-12','due_date'=>'2027-02-16']);FinanceLedger::issueInvoice($db,$user,$invoice['id']);$receipt=FinanceLedger::receipt($db,$user,$bid,['amount'=>$selling,'currency'=>'USD','payment_date'=>'2027-02-16','transaction_reference'=>'VS21-CUSTOMER-BANK','idempotency_key'=>'vs21-customer-bank']);FinanceLedger::allocate($db,$user,$receipt['id'],['request_key'=>'vs21-customer-allocation','allocation_date'=>'2027-02-16','items'=>[['invoice_id'=>$invoice['id'],'amount'=>$selling]]]);v2q('UPDATE bookings SET operation_completed_at=NOW() WHERE id=?',[$bid]);$profit=FinanceLedger::profit($db,1,$bid);check($profit['actual_final']&&$profit['expected_profit']===$profit['actual_profit']&&$profit['fx_rate']===25000.0,'L47 existing reconciliation payment and actual profit chain');
check(v2q('SELECT internal_snapshot_json FROM quote_sent_bundles WHERE quote_version_id=?',[$source])->fetchColumn()===$issued,'L48 reuse keeps exact issued source bytes');
echo "VS2.1 extended native checks complete.\n";
