<?php
declare(strict_types=1);
// Reuses the existing disposable native fixture and its original regression assertions.
require __DIR__.'/lead-hub.php';
require_once __DIR__.'/../api/lib/QuoteOptions.php';
require_once __DIR__.'/../api/lib/CoreOS.php';
require_once __DIR__.'/../api/lib/Procurement.php';
require_once __DIR__.'/../api/lib/QuoteReuse.php';

function v2q(string $sql,array $args=[]): PDOStatement {global $db;return QuoteVs2Repository::q($db,$sql,$args);}
function v2v(): array {global $db,$qvid;return QuoteOptions::version($db,1,$qvid);}
function v2command(array $body,callable $fn): array {global $db,$user,$qvid;return QuoteVs2::mutate($db,$user,$qvid,['expected_revision'=>(int)v2v()['costing_revision']]+$body,$fn,'VS21_TEST_COMMAND');}
function v2context(array $body): array {global $db,$user,$qvid;return QuoteSmartCosting::context($db,$user,$qvid,['expected_revision'=>(int)v2v()['costing_revision']]+$body);}
function v2rate(string $category,string $amount,string $formula,?int $star=null,array $scope=[],array $inclusions=[]): int {
    global $db,$user;$key='VS21-'.bin2hex(random_bytes(5));v2q("INSERT INTO rates(company_id,rate_ref,supplier_id,category,product_name,rate_type,source_origin,status,created_by,updated_by) VALUES(1,?,1,?,?,'MANUAL_OVERRIDE','MANUAL','ACTIVE',1,1)",[$key,$category,$key]);$rid=(int)$db->lastInsertId();
    v2q("INSERT INTO rate_versions(rate_id,version_no,amount,currency,rate_basis,tax_basis,approval_status,valid_from,valid_to,created_by) VALUES(?,1,?,'VND',?,'NET','APPROVED','2026-01-01','2028-12-31',1)",[$rid,$amount,$formula==='TRANSFER_PACKAGE'?'PER_VEHICLE':($formula==='GUIDE_DAY'?'PER_GUIDE_DAY':'PER_PAX')]);$id=(int)$db->lastInsertId();
    Vs2RateTerms::save($db,$user,$id,['formula_code'=>$formula,'star_level'=>$star,'capacity'=>16,'rate_eligibility_source'=>'TOTAL_GUESTS','basis_evidence'=>['evidence'=>'Reviewed synthetic supplier contract'],'package_scope'=>$scope,'inclusions'=>$inclusions,'publish'=>true]);return $id;
}
function v2edit(int $variant,int $line,array $body): array {global $db,$user;return v2command($body,fn($v)=>Vs2LineEditor::write($db,$user,$v,$variant,$body,'save',$line));}
function v2review(int $variant,int $line): void {global $db,$user;v2command([],fn($v)=>Vs2LineEditor::review($db,$user,$v,$variant,$line,['review_reason'=>'Supplier, scope and quantities reviewed']));}
function v2line(int $variant,string $category): array {return v2q('SELECT l.* FROM quote_variant_cost_lines l JOIN quote_service_requirements r ON r.id=l.requirement_id WHERE l.variant_id=? AND r.category=? AND l.line_kind=\'SERVICE\' ORDER BY l.id LIMIT 1',[$variant,$category])->fetch();}
function v2codes(): array {global $db;return array_column(QuoteVs2Validator::validate($db,v2v())['errors'],'code');}

v2q("UPDATE quote_versions SET adults=17,children=1,infants=0,foc=2,total_guests=20,paying_pax=18,start_date='2027-01-02',end_date='2027-01-05',schedule_json=? WHERE id=?",[json_encode([['day_key'=>'day-1','date'=>'2027-01-02','title'=>'Arrival','route'=>'Hanoi airport – Hanoi','transport_mode'=>'private'],['day_key'=>'day-2','date'=>'2027-01-03','title'=>'Hanoi','route'=>'Hanoi','transport_mode'=>'private'],['day_key'=>'day-3','date'=>'2027-01-04','title'=>'Halong','route'=>'Hanoi – Halong','transport_mode'=>'private'],['day_key'=>'day-4','date'=>'2027-01-05','title'=>'Departure','route'=>'Halong – airport','transport_mode'=>'private']]),$qvid]);
QuoteSmartCosting::activate($db,$user,$qvid,['expected_revision'=>0]);check(v2v()['costing_engine']==='VS2_1','L50 explicit activation strategy');check(v2q('SELECT hotel_pax FROM quote_guest_profiles WHERE quote_version_id=?',[$qvid])->fetchColumn()===null,'L12 populations initially unset');
v2context(['hotel_pax'=>16,'cruise_pax'=>16,'visa_pax'=>12,'meal_pax'=>15,'ticket_pax'=>13]);
v2command([],fn($v)=>['ids'=>Vs2Variants::generate($db,$user,$v,['modes'=>['PRIVATE','SIC']])]);$g=QuoteVs2Repository::graph($db,v2v());check(count($g['variants'])===6,'L29 six variants over one itinerary');check(count($g['requirements'])===8,'L26 union shared requirement defaults');
v2command([],fn($v)=>['ids'=>Vs2Variants::generate($db,$user,$v,['modes'=>['PRIVATE','SIC']])]);check(count(QuoteVs2Repository::graph($db,v2v())['variants'])===6,'L27 regeneration idempotent');
$variant=(int)array_values(array_filter($g['variants'],fn($x)=>$x['variant_key']==='private-4-4'))[0]['id'];
$reqs=[];foreach($g['requirements'] as $req){$units=match($req['category']){'GUIDE'=>4,'HOTEL'=>3,'MEAL'=>6,default=>1};$scope=['dates'=>array_slice(['2027-01-02','2027-01-03','2027-01-04','2027-01-05'],0,$units)];if($req['category']==='MEAL')$scope=['occurrences'=>['d1-lunch','d1-dinner','d2-lunch','d2-dinner','d3-lunch','d3-dinner']];if($req['category']==='ATTRACTION')$scope=['attraction_key'=>'museum-A','eligibility_group'=>'adult'];$reqs[]=['id'=>(int)$req['id'],'requirement_state'=>'REQUIRED','service_units'=>$units,'scope'=>$scope];}
v2context(['requirements'=>$reqs]);
$rates=[];foreach(['TRANSPORT'=>['14000000','TRANSFER_PACKAGE',null],'GUIDE'=>['1000000','GUIDE_DAY',null],'HOTEL'=>['800000','HOTEL_PAX_NIGHT',4],'CRUISE'=>['3000000','CRUISE_PAX',4],'VISA'=>['625000','VISA_PAX',null],'MEAL'=>['200000','MEAL_PAX_COUNT',null],'ATTRACTION'=>['100000','TICKET_PAX',null],'TOUR'=>['900000','SIC_PAX',null]] as $cat=>[$amount,$formula,$star])$rates[$cat]=v2rate($cat,$amount,$formula,$star,$cat==='TRANSPORT'?['itinerary_scope'=>QuoteVs2Domain::itineraryScope(v2v())]:[]);
foreach(Vs2Templates::PRIVATE_ORDER as $cat){$line=v2line($variant,$cat);$body=['rate_version_id'=>$rates[$cat]];if(in_array($cat,['TRANSPORT','GUIDE'],true))$body['custom_quantity']=2;v2edit($variant,(int)$line['id'],$body);v2review($variant,(int)$line['id']);}
v2command([],fn($v)=>['variant_id'=>Vs2Variants::save($db,$user,$v,['variant_id'=>$variant,'is_offered'=>true])]);
check(QuoteVs2Validator::validate($db,v2v())['valid'],'L43 complete reviewed PRIVATE option validates');check(v2line($variant,'HOTEL')['total_vnd']==='38400000.00','L03 native hotel formula');
$visa=v2line($variant,'VISA');$hotel=v2line($variant,'HOTEL');$meal=v2line($variant,'MEAL');$transfer=v2line($variant,'TRANSPORT');$signature=fn($line)=>array_intersect_key($line,array_flip(['total_vnd','input_hash','calculation_trace_json','calculated_at','resolved_quantity','resolved_units']));
$before=$signature($visa);$out=v2context(['hotel_pax'=>18]);check(in_array((int)$hotel['id'],$out['recalculated_line_ids'],true)&&!in_array((int)$visa['id'],$out['recalculated_line_ids'],true)&&$signature(v2line($variant,'VISA'))===$before,'L10 HOTEL_PAX only bound arithmetic');
$hotelAfter=$signature(v2line($variant,'HOTEL'));$out=v2context(['visa_pax'=>11]);check(!in_array((int)$hotel['id'],$out['recalculated_line_ids'],true)&&$signature(v2line($variant,'HOTEL'))===$hotelAfter,'L10 VISA_PAX leaves hotel bytes stable');
$out=v2context(['meal_pax'=>14]);check(in_array((int)$meal['id'],$out['recalculated_line_ids'],true),'L10 MEAL_PAX dependency');
v2edit($variant,(int)$hotel['id'],['quantity_override'=>16,'override_reason'=>'Different hotel population reviewed']);$before=$signature(v2line($variant,'HOTEL'));v2context(['hotel_pax'=>20]);check($signature(v2line($variant,'HOTEL'))===$before&&(int)v2line($variant,'HOTEL')['quantity_override']===16&&(int)v2line($variant,'HOTEL')['review_required']===1,'L11 override stable and review flagged');
$before=$signature(v2line($variant,'TRANSPORT'));v2context(['adults'=>18,'total_guests'=>21]);check($signature(v2line($variant,'TRANSPORT'))===$before,'L15 transfer capacity context preserves arithmetic');
$state=v2v();rejects(fn()=>v2context(['total_guests'=>15,'adults'=>12]),DomainException::class,'L14 invalid population reduction atomic');check(v2v()['total_guests']===$state['total_guests'],'L14 failed command rolls back');
v2context(['adults'=>17,'total_guests'=>20,'hotel_pax'=>16,'visa_pax'=>12,'meal_pax'=>15]);v2edit($variant,(int)$hotel['id'],['quantity_override'=>null]);check(v2line($variant,'HOTEL')['resolved_quantity']===16||v2line($variant,'HOTEL')['resolved_quantity']==='16','L31 clearing override restores binding');
$before=$signature(v2line($variant,'TRANSPORT'));v2context(['adults'=>40,'total_guests'=>43]);check($signature(v2line($variant,'TRANSPORT'))===$before&&in_array('REPRICING_REQUIRED',v2codes(),true),'L15 overcapacity does not invent package price');v2context(['adults'=>17,'total_guests'=>20]);
$days=QuoteVs2Repository::decode(v2v()['schedule_json']);$days[0]['title']='Cosmetic edit';v2context(['schedule'=>$days]);v2review($variant,(int)$transfer['id']);check(!in_array('REPRICING_REQUIRED',v2codes(),true),'L16 cosmetic scope accepted');$days[0]['route']='Changed material leg';v2context(['schedule'=>$days]);check(in_array('REPRICING_REQUIRED',v2codes(),true),'L16 route scope blocks');$days[0]['route']='Hanoi airport – Hanoi';v2context(['schedule'=>$days]);
rejects(fn()=>v2edit($variant,(int)$visa['id'],['unit_amount_original'=>'1']),InvalidArgumentException::class,'L41 posted stored-rate price rejected');rejects(fn()=>v2edit($variant,(int)$visa['id'],['included_keys'=>['visa']]),InvalidArgumentException::class,'L20 untrusted inclusion keys rejected');
rejects(fn()=>QuoteVs2::mutate($db,$user,$qvid,['expected_revision'=>0],fn($v)=>[],'STALE'),DomainException::class,'L40 stale command rejected');
rejects(fn()=>QuoteCostItems::write($db,$user,$qvid,['service_name'=>'Double counted']),DomainException::class,'L42 legacy writer blocked');
$other=(int)array_values(array_filter($g['variants'],fn($x)=>$x['variant_key']==='sic-4-4'))[0]['id'];$mix=v2command([],fn($v)=>['id'=>Vs2Variants::save($db,$user,$v,['hotel_level'=>'4*','cruise_level'=>5,'costing_mode'=>'HYBRID','label'=>'Hybrid 4/5'])]);check(QuoteVs2Repository::variant($db,$qvid,$mix['id'])['hotel_level']==='4*','L28/L29 custom mix shares hotel parent and itinerary');
$before=$signature(v2line($variant,'HOTEL'));v2command([],fn($v)=>['id'=>Vs2Variants::save($db,$user,$v,['variant_id'=>$variant,'cruise_level'=>5])]);check($signature(v2line($variant,'HOTEL'))===$before&&(int)v2line($variant,'CRUISE')['review_required']===1,'L30 cruise star change leaves hotel untouched');v2command([],fn($v)=>['id'=>Vs2Variants::save($db,$user,$v,['variant_id'=>$variant,'cruise_level'=>4])]);
$guide=v2line($other,'GUIDE');$tour=v2line($other,'TOUR');$guideReq=v2q('SELECT * FROM quote_service_requirements WHERE id=?',[$guide['requirement_id']])->fetch();$guideScope=QuoteVs2Repository::decode($guideReq['scope_json']);
// Change the shared guide to BOTH so it remains a visible SIC commitment covered by the package.
v2context(['requirements'=>[['id'=>(int)$guideReq['id'],'service_mode'=>'BOTH']]]);
$sicRules=[['component_key'=>'guide','included_category'=>'GUIDE','scope'=>['service_date'=>$guideReq['service_date'],'dates'=>$guideScope['dates']],'coverage'=>['quantity'=>2,'units'=>4],'description'=>'Supplier includes two guides on the reviewed days']];
$sic=v2rate('TOUR','900000','SIC_PAX',null,[],$sicRules);v2edit($other,(int)$guide['id'],['custom_quantity'=>2]);v2edit($other,(int)$tour['id'],['rate_version_id'=>$sic]);check(v2line($other,'GUIDE')['coverage_state']==='INCLUDED'&&v2line($other,'GUIDE')['total_vnd']==='0.00','L22 approved exact guide inclusion suppressed');
v2q('UPDATE rate_versions SET valid_to=\'2026-01-01\' WHERE id=?',[$sic]);Vs2Inclusions::apply($db,v2v());check(v2line($other,'GUIDE')['coverage_state']==='UNRESOLVED','L21 expired package cannot cover');v2q('UPDATE rate_versions SET valid_to=\'2028-12-31\' WHERE id=?',[$sic]);
// Approved metadata cannot be overwritten even by a rate approver.
rejects(fn()=>Vs2RateTerms::save($db,$user,$sic,['formula_code'=>'SIC_PAX']),DomainException::class,'L18 approved supplier terms immutable');
$unit=v2q('SELECT rate_basis FROM rate_versions WHERE id=?',[$rates['HOTEL']])->fetchColumn();v2q("UPDATE rate_versions SET rate_basis='PER_ROOM_NIGHT' WHERE id=?",[$rates['HOTEL']]);check(in_array('UNSUPPORTED_RATE_BASIS',v2codes(),true),'L19 no room-to-pax conversion');v2q('UPDATE rate_versions SET rate_basis=? WHERE id=?',[$unit,$rates['HOTEL']]);
$discount=v2command([],fn($v)=>Vs2LineEditor::write($db,$user,$v,$variant,['requirement_id'=>$hotel['requirement_id'],'line_kind'=>'ADJUSTMENT','adjusts_line_id'=>$hotel['id'],'formula_code'=>'CUSTOM','quantity_source'=>'CUSTOM_QTY','custom_quantity'=>1,'adjustment_amount_vnd'=>'-1000000','manual_reason'=>'Supplier-approved discount']));v2review($variant,$discount['line_id']);
v2command([],function($v)use($db){SmartCosting::refresh($db,$v,[],true);Vs2Inclusions::apply($db,$v);return [];});foreach(v2q('SELECT id FROM quote_variant_cost_lines WHERE variant_id=?',[$variant])->fetchAll() as $row)if((int)$row['id']!==(int)v2line($variant,'TOUR')['id'])v2review($variant,(int)$row['id']);
check(QuoteVs2Validator::validate($db,v2v())['valid'],'L33 reviewed signed adjustment valid');
v2q("INSERT INTO company_settings(company_id,setting_key,setting_value,updated_by) VALUES(1,'minimum_margin','99',1) ON DUPLICATE KEY UPDATE setting_value='99'");check(in_array('MINIMUM_MARGIN',v2codes(),true),'L35 configured margin blocks');v2q("UPDATE company_settings SET setting_value='0' WHERE company_id=1 AND setting_key='minimum_margin'");
$approval=QuoteOptions::approve($db,$user,$qvid,'Reviewed complete option');$oldAmount=v2q('SELECT amount FROM rate_versions WHERE id=?',[$rates['VISA']])->fetchColumn();v2q('UPDATE rate_versions SET amount=amount+1 WHERE id=?',[$rates['VISA']]);rejects(fn()=>QuoteOptions::send($db,$user,$qvid),DomainException::class,'L44 source drift blocks send');v2q('UPDATE rate_versions SET amount=? WHERE id=?',[$oldAmount,$rates['VISA']]);
$fx=v2v()['fx_rate'];v2q('UPDATE quote_versions SET fx_rate=25001 WHERE id=?',[$qvid]);rejects(fn()=>QuoteOptions::send($db,$user,$qvid),DomainException::class,'L44 FX drift blocks send');v2q('UPDATE quote_versions SET fx_rate=? WHERE id=?',[$fx,$qvid]);
v2q("UPDATE company_settings SET setting_value='1' WHERE company_id=1 AND setting_key='minimum_margin'");rejects(fn()=>QuoteOptions::send($db,$user,$qvid),DomainException::class,'L44 policy hash drift blocks send');v2q("UPDATE company_settings SET setting_value='0' WHERE company_id=1 AND setting_key='minimum_margin'");
$beforeTerms=v2q('SELECT capacity,updated_at FROM rate_version_vs2_terms WHERE rate_version_id=?',[$rates['TRANSPORT']])->fetch();v2q('UPDATE rate_version_vs2_terms SET capacity=17 WHERE rate_version_id=?',[$rates['TRANSPORT']]);rejects(fn()=>QuoteOptions::send($db,$user,$qvid),DomainException::class,'L44 approved terms drift blocks send');v2q('UPDATE rate_version_vs2_terms SET capacity=?,updated_at=? WHERE rate_version_id=?',[$beforeTerms['capacity'],$beforeTerms['updated_at'],$rates['TRANSPORT']]);
$storedScope=v2q('SELECT scope_json FROM quote_service_requirements WHERE id=?',[$guideReq['id']])->fetchColumn();$scope=json_decode($storedScope,true);$scope['dates'][0]='2027-01-06';v2q('UPDATE quote_service_requirements SET scope_json=? WHERE id=?',[json_encode($scope),$guideReq['id']]);rejects(fn()=>QuoteOptions::send($db,$user,$qvid),DomainException::class,'L44 scope drift blocks send');v2q('UPDATE quote_service_requirements SET scope_json=? WHERE id=?',[$storedScope,$guideReq['id']]);
v2q('UPDATE quote_option_variants SET is_offered=1 WHERE id=?',[$other]);rejects(fn()=>QuoteOptions::send($db,$user,$qvid),DomainException::class,'L44 offered set drift blocks send');v2q('UPDATE quote_option_variants SET is_offered=0 WHERE id=?',[$other]);
$sent=QuoteOptions::send($db,$user,$qvid);$snapshot=v2q('SELECT internal_snapshot_json FROM quote_sent_bundles WHERE quote_version_id=?',[$qvid])->fetchColumn();$public=json_encode($sent);check(!str_contains($public,'supplier')&&!str_contains($public,'margin')&&!str_contains($public,'internal_notes'),'L37 public projection safe');
rejects(fn()=>v2context(['hotel_pax'=>15]),DomainException::class,'L45 sent context immutable');rejects(fn()=>QuoteOptions::confirm($db,$user,$qvid,(int)QuoteVs2Repository::variant($db,$qvid,$variant)['quote_option_id']),DomainException::class,'L46 parent-only acceptance rejected');
$optionId=(int)QuoteVs2Repository::variant($db,$qvid,$variant)['quote_option_id'];rejects(fn()=>QuoteOptions::confirm($db,$user,$qvid,$optionId,$other,$approval['content_hash']),DomainException::class,'L46 unoffered sibling rejected');rejects(fn()=>QuoteOptions::confirm($db,$user,$qvid,$optionId,$variant,str_repeat('0',64)),DomainException::class,'L46 stale sent hash rejected');QuoteOptions::confirm($db,$user,$qvid,$optionId,$variant,$approval['content_hash']);$booking=QuoteOptions::booking($db,$user,$qvid);check(QuoteOptions::booking($db,$user,$qvid)['id']===$booking['id'],'L40 booking idempotent');
check(v2q('SELECT planned_cost FROM booking_services WHERE booking_id=? AND category=\'HOTEL\'',[$booking['id']])->fetchColumn()==='37400000.00','L47 signed adjustment folded into original VND service');
v2q('UPDATE rate_versions SET amount=999 WHERE id=?',[$rates['VISA']]);check(QuoteOptions::send($db,$user,$qvid)===$sent&&v2q('SELECT internal_snapshot_json FROM quote_sent_bundles WHERE quote_version_id=?',[$qvid])->fetchColumn()===$snapshot,'L45 sent retry ignores subsequent supplier change');
$copyQuote=v2q("INSERT INTO quote_versions(quote_id,version_no,tour_name,created_by,fx_rate,schedule_json,start_date,end_date,adults,children,infants,foc,total_guests,paying_pax) SELECT quote_id,2,tour_name,1,fx_rate,schedule_json,start_date,end_date,adults,children,infants,foc,total_guests,paying_pax FROM quote_versions WHERE id=?",[$qvid]);$new=(int)$db->lastInsertId();Vs2Snapshots::copy($db,$user,$qvid,$new);$newGraph=QuoteVs2Repository::graph($db,QuoteOptions::version($db,1,$new));check(count($newGraph['variants'])===7&&$newGraph['requirements'][0]['id']!==$g['requirements'][0]['id'],'L48 child IDs remapped on same revision system');check(v2q('SELECT 1 FROM quote_sent_bundles WHERE quote_version_id=?',[$new])->fetchColumn()===false,'L48 issued/accepted state never copied');
file_put_contents(getenv('VS21_FIXTURE_FILE')?:sys_get_temp_dir().'/vs21-fixture.json',json_encode(['database'=>$database,'quote_id'=>(int)v2v()['quote_id'],'version_id'=>$qvid,'booking_id'=>$booking['id'],'revision_id'=>$new,'variant_id'=>$variant,'rates'=>$rates],JSON_PRETTY_PRINT));
echo "VS2.1 native MariaDB checks complete.\n";
