const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('playwright');
const url=process.env.VS21_TEST_URL||'http://127.0.0.1:18862';if(!/^http:\/\/127\.0\.0\.1:\d+$/.test(url))throw Error('Disposable local browser URL required');
const output=process.env.VS21_BROWSER_OUTPUT||__dirname,results=[];
const check=(ok,label)=>{assert(ok,label);results.push({label,status:'PASS'});console.log('PASS '+label);};
const creds={email:'tester@example.invalid',password:process.env.VS21_BROWSER_PASSWORD};
if(!creds.password)throw Error('Synthetic browser password required');
let browser;
(async()=>{
 browser=await chromium.launch({headless:true,...(process.env.VS21_CHROME?{executablePath:process.env.VS21_CHROME}:{})});const ctx=await browser.newContext({viewport:{width:1440,height:1000}}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const endpoint=route=>url+'/api/index.php?route='+encodeURIComponent(route);
 const login=await ctx.request.post(endpoint('auth/login'),{data:creds});assert.equal(login.status(),200);let auth=await login.json();const csrf=auth.user.csrf||auth.csrf;
 console.log('Auth response keys',Object.keys(auth),Object.keys(auth.user));
 const api=async(route,body,method='POST',expected=200)=>{const r=await ctx.request.fetch(endpoint(route),{method,headers:{'X-VTA-CSRF':csrf},...(body===undefined?{}:{data:body})});const value=await r.json();if(r.status()!==expected)throw Error(route+' '+r.status()+' '+JSON.stringify(value));return value;};
 await page.goto(url);await page.waitForSelector('#workspace');
 const inquiry=await api('inquiries',{lead_contact_name:'Browser acceptance group',title:'VS21 browser tour',adults:17,children:1,infants:0,foc:2,total_guests:20,paying_pax:18,start_date:'2027-01-02',end_date:'2027-01-05',destination_text:'Hanoi Halong'},'POST',201);
 const quote=await api('inquiries/'+inquiry.id+'/create-quote',{},'POST',201);let view=await api('quotes/'+quote.id,undefined,'GET');let id=view.version.id;
 await api('inventory/versions/2/use',{quote_version_id:id});const imported=await api('quotes/'+quote.id,undefined,'GET');const importedDays=JSON.parse(imported.version.schedule_json).length;check(importedDays>0,'L52 inquiry and Program Library create the existing quote and itinerary');
 const openQuote=async()=>{await page.locator('[data-nav="sales"]').first().click();await page.getByRole('button',{name:'Quotes',exact:true}).click();await page.waitForSelector('[data-sales-tab="quotes"]');};
 await openQuote();
 await page.locator('[data-open-quote="'+quote.id+'"]').click({timeout:15000});
 await page.getByRole('button',{name:'Enable Smart Itinerary & Costing',exact:true}).click();await page.waitForSelector('[data-guests]');
 const firstSend=await api('quotes/'+quote.id+'/send',{expected_revision:1,ready:true},'POST',409);check(firstSend.error==='VS21_VALIDATION','L42 no-parent Send invokes central validator');
 check(await page.locator('[data-days] article').count()===importedDays,'L29 one imported itinerary');
 for(const [key,value] of Object.entries({hotel_pax:16,cruise_pax:16,visa_pax:12,meal_pax:15,ticket_pax:13}))await page.locator('[data-guests] [name="'+key+'"]').fill(String(value));
 await page.getByRole('button',{name:'Save guest quantities',exact:true}).click();await page.waitForTimeout(300);
 await page.getByRole('button',{name:'Generate PRIVATE + SIC presets',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('[data-variant] option').length===6);await page.waitForTimeout(750);
 check(await page.locator('[data-variant] option').count()===6,'L29 presets without itinerary copies');
 let prepared=await api('quotes/'+quote.id,undefined,'GET');let preOptions=await api('quote-versions/'+id+'/options',undefined,'GET');let chosen=preOptions.items.find(x=>x.variant_key==='private-4-4');await api('quote-versions/'+id+'/options',{expected_revision:Number(prepared.version.costing_revision),variant_id:chosen.variant_id,is_offered:true});
 await page.getByRole('button',{name:'Check quote',exact:true}).click();await page.waitForSelector('[data-validation] p');check((await page.locator('[data-validation]').textContent()).includes('RATE_NEEDED'),'L42 visible missing-rate validation');
 view=await api('quotes/'+quote.id,undefined,'GET');let revision=view.version.costing_revision;
 // Complete typed service requirements through the same authenticated API.
 let context=await api('quote-versions/'+id+'/smart-costing/context',undefined,'GET');const requirements=context.requirements.map(r=>({id:Number(r.id),requirement_state:r.category==='HOTEL'?'REQUIRED':'NOT_APPLICABLE',service_units:r.category==='HOTEL'?3:1,scope:r.category==='HOTEL'?{dates:['2027-01-02','2027-01-03','2027-01-04']}:r.scope,metadata:{reason:'Reviewed synthetic scope; only hotel required',internal_notes:'Quiet rooms confirmed'}}));
 const patch=await api('quote-versions/'+id+'/smart-costing/context',{expected_revision:revision,requirements},'PUT');revision=patch.costing_revision;
 let options=await api('quote-versions/'+id+'/options',undefined,'GET');const selected=options.items.find(x=>x.variant_key==='private-4-4');let variant=selected.variant_id;const line=selected.lines.find(x=>x.category==='HOTEL');const rate=options.rate_choices.find(x=>x.category==='HOTEL'&&Number(x.star_level)===4);assert(rate);
 await page.reload();await page.waitForSelector('#workspace');await openQuote();await page.locator('[data-open-quote="'+quote.id+'"]').click();await page.waitForSelector('[data-variant]');await page.locator('[data-variant]').selectOption(String(variant));
 await page.locator('[data-line-edit="'+line.id+'"]').click();await page.locator('select[name="rate_version_id"]').selectOption(String(rate.id));const saved=page.waitForResponse(r=>r.url().includes('lines')&&r.request().method()==='PUT');await page.locator('[data-save-line]').click();const sr=await saved;assert.equal(sr.status(),200,await sr.text());let change=await sr.json();revision=change.costing_revision;check(true,'L31 real browser edits a supplier-backed cost line');
 change=await api('quote-versions/'+id+'/smart-costing/variants/'+variant+'/lines/'+line.id+'/review',{expected_revision:revision,review_reason:'Reviewed published supplier contract and nights'});revision=change.costing_revision;
 change=await api('quote-versions/'+id+'/options',{expected_revision:revision,variant_id:variant,is_offered:true,cruise_level:null});revision=change.costing_revision;
 // A cruise-only setting must leave hotel review and arithmetic stable.
 let validation=await api('quote-versions/'+id+'/smart-costing/validation',undefined,'GET');assert(validation.valid,JSON.stringify(validation));
 await page.reload();await page.waitForSelector('#workspace');
 // Use the real route link again after reload.
 await openQuote();await page.locator('[data-open-quote="'+quote.id+'"]').click();await page.waitForSelector('[data-variant]');await page.locator('[data-variant]').selectOption(String(variant));
 await page.getByRole('button',{name:'Advanced view',exact:true}).click();check((await page.locator('[data-costs]').textContent()).includes('38400000.00'),'L31 actual server cost and calculation trace displayed');
 await page.screenshot({path:path.join(output,'VS2_1_BROWSER_DESKTOP.png'),fullPage:true});
 const uiAction=async(name,route,status=200)=>{const response=page.waitForResponse(r=>decodeURIComponent(r.url()).includes('quotes/'+quote.id+'/'+route)&&r.request().method()==='POST');await page.getByRole('button',{name,exact:true}).click();const r=await response;const j=await r.json();assert.equal(r.status(),status,JSON.stringify(j));return j;};
 const approved=await uiAction('Approve quote','approve');
 const sent=await uiAction('Send quote','send');check(!JSON.stringify(sent).includes('supplier_id')&&!JSON.stringify(sent).includes('margin'),'L37 sent output excludes supplier costs and profit');
 const immutable=await api('quote-versions/'+id+'/smart-costing/context',{expected_revision:revision,hotel_pax:15},'PUT',409);check(immutable.error==='IMMUTABLE_VERSION','L45 issued version blocks edits');
 await api('quotes/'+quote.id+'/confirm',{expected_revision:revision,option_id:selected.option_id},'POST',409);
 await uiAction('Accept selected variant','confirm');
 const booked=await uiAction('Open booking','create-booking');check(Number(booked.id)>0,'L46/L47 exact variant hands over to existing booking');await page.waitForFunction(()=>document.querySelector('#workspace')?.dataset.view==='booking');check(true,'L52 booking UI remains on existing Operations workspace');
 await openQuote();await page.locator('[data-open-quote="'+quote.id+'"]').click();await page.waitForSelector('[data-guests]');const revised=await uiAction('Create revision','new-version',201);check(Number(revised.version_id)!==Number(id),'L48 Create Revision creates a new existing version');
 const badCsrf=await ctx.request.post(endpoint('quote-versions/'+revised.version_id+'/smart-costing/context'),{data:{expected_revision:0,hotel_pax:16}});check(badCsrf.status()===419,'L39 missing CSRF rejected by real server');
 const guest=await browser.newContext(),gl=await guest.request.post(endpoint('auth/login'),{data:{email:'guest-editor@example.invalid',password:creds.password}});const ga=await gl.json();const gc=ga.user.csrf||ga.csrf;
 const gget=await guest.request.get(endpoint('quote-versions/'+revised.version_id+'/smart-costing/context'));check(gget.status()===200&&!JSON.stringify(await gget.json()).includes('unit_rate'),'L36 guest editor safe context');const denied=await guest.request.get(endpoint('quote-versions/'+revised.version_id+'/options'));check(denied.status()===403,'L36 supplier costing denied on server');
 const guestEdit=await guest.request.put(endpoint('quote-versions/'+revised.version_id+'/smart-costing/context'),{headers:{'X-VTA-CSRF':gc},data:{expected_revision:0,visa_pax:11}});check(guestEdit.status()===200&&!JSON.stringify(await guestEdit.json()).includes('total_vnd'),'L36 guest-only authenticated PUT exposes no costs');
 const guestCost=await guest.request.put(endpoint('quote-versions/'+revised.version_id+'/smart-costing/variants/'+variant+'/lines/'+line.id),{headers:{'X-VTA-CSRF':gc},data:{expected_revision:1,unit_amount_original:'1'}});check(guestCost.status()===403,'L36 monetary write denied');const guestBooking=await guest.request.get(endpoint('bookings/'+booked.id));const gb=JSON.stringify(await guestBooking.json());check(guestBooking.status()===200&&!/planned_cost|actual_cost|total_amount|internal_snapshot|expected_profit/.test(gb),'L37 shared booking cost/profit/finance protected');
 const profitContext=await browser.newContext();await profitContext.request.post(endpoint('auth/login'),{data:{email:'profit-denied@example.invalid',password:creds.password}});const po=await profitContext.request.get(endpoint('quote-versions/'+revised.version_id+'/options'));const pj=JSON.stringify(await po.json());check(po.status()===200&&!/profit_vnd|margin_pct|markup_pct|pricing_value/.test(pj),'L36 explicit profit DENY on options');const pb=await profitContext.request.get(endpoint('bookings/'+booked.id));check(pb.status()===200&&!/expected_profit|forecast_profit|actual_profit/.test(JSON.stringify(await pb.json())),'L37 explicit profit DENY on shared booking');
 const foreign=await browser.newContext();await foreign.request.post(endpoint('auth/login'),{data:{email:'other@example.invalid',password:creds.password}});const fg=await foreign.request.get(endpoint('quote-versions/'+id+'/smart-costing/context'));check(fg.status()===404,'L38 foreign tenant quote denied');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'VS2_1_BROWSER_MOBILE.png'),fullPage:true});check(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'L52 mobile page has no horizontal overflow');check(errors.length===0,'L52 no uncaught browser errors');
 await browser.close();fs.writeFileSync(path.join(output,'VS2_1_BROWSER_RESULTS.json'),JSON.stringify({results,errors,quote_id:quote.id,booking_id:booked.id},null,2));
})().catch(async e=>{console.error(e);if(browser)await browser.close();fs.writeFileSync(path.join(output,'VS2_1_BROWSER_RESULTS.json'),JSON.stringify({results,error:e.stack},null,2));process.exitCode=1;});
