<?php
declare(strict_types=1);
require_once __DIR__.'/../api/lib/QuoteOptions.php';
function v2check(bool $ok,string $label): void {if(!$ok)throw new RuntimeException('FAIL '.$label);echo "PASS $label\n";}
function v2reject(callable $fn,string $label): void {try{$fn();}catch(Throwable $e){echo "PASS $label: ".get_class($e)."\n";return;}throw new RuntimeException('FAIL accepted '.$label);}
$guests=['adults'=>17,'children'=>1,'infants'=>0,'foc'=>2,'total_guests'=>20,'paying_pax'=>18,'hotel_pax'=>16,'cruise_pax'=>16,'visa_pax'=>12,'meal_pax'=>15,'ticket_pax'=>13];
$fixtures=[['L01','TRANSFER_PACKAGE','CUSTOM_QTY',2,1,'14000000','28000000.00'],['L02','GUIDE_DAY','CUSTOM_QTY',2,4,'1000000','8000000.00'],['L03','HOTEL_PAX_NIGHT','HOTEL_PAX',null,3,'800000','38400000.00'],['L04','CRUISE_PAX','CRUISE_PAX',null,1,'3000000','48000000.00'],['L05','VISA_PAX','VISA_PAX',null,1,'625000','7500000.00'],['L06','MEAL_PAX_COUNT','MEAL_PAX',null,6,'200000','18000000.00'],['L07a','TICKET_PAX','TICKET_PAX',null,1,'100000','1300000.00'],['L07b','TICKET_PAX','CUSTOM_QTY',11,1,'200000','2200000.00'],['L08','SIC_PAX','CRUISE_PAX',null,1,'900000','14400000.00'],['L09','CUSTOM','CUSTOM_QTY',3,1,'0.10','0.30']];
foreach($fixtures as [$code,$formula,$source,$custom,$units,$amount,$expected]){
    $line=['formula_code'=>$formula,'quantity_source'=>$source,'custom_quantity'=>$custom,'quantity_override'=>null,'units_override'=>null];$rate=['amount'=>$amount,'currency'=>'VND','supplier_id'=>1,'source_hash'=>'stored-evidence','manual'=>false];$result=SmartCosting::calculate($line,['service_units'=>$units],$guests,$rate,'25000');v2check($result['total_vnd']===$expected,$code.' exact formula');v2check(!empty(json_decode($result['calculation_trace_json'],true)['sentence']),$code.' trace');
}
foreach(['TRANSFER_PACKAGE','GUIDE_DAY'] as $f)v2reject(fn()=>SmartCosting::calculate(['formula_code'=>$f,'quantity_source'=>'TOTAL_GUESTS','quantity_override'=>null],['service_units'=>1],$guests,['amount'=>'100','currency'=>'VND','supplier_id'=>1,'source_hash'=>'stored','manual'=>false],'25000'),'L01/L02 guest count cannot substitute resource count');
v2check(Vs2Decimal::add(Vs2Decimal::parse('10001'),Vs2Decimal::parse('10001'))===2000200,'L09 VND aggregate never rebuilt from rounded USD');
v2reject(fn()=>Vs2Decimal::mul(Vs2Decimal::LIMIT,2),'L09 checked overflow');v2reject(fn()=>Vs2Decimal::parse('1.001'),'L09 precision rejection');
v2check(count(QuoteVs2Domain::SOURCES)===8,'L10 exactly eight sources');foreach(QuoteVs2Domain::SOURCES as $source)foreach(QuoteVs2Domain::SOURCES as $changed)v2check(QuoteVs2Domain::affected(['quantity_source'=>$source,'quantity_override'=>null],[$changed])===($source===$changed),'L10 '.$source.' follows '.$changed);
v2check(!QuoteVs2Domain::affected(['quantity_source'=>'HOTEL_PAX','quantity_override'=>16],['HOTEL_PAX']),'L11 manual override excluded from arithmetic');v2check(QuoteVs2Domain::quantity(['quantity_source'=>'HOTEL_PAX','quantity_override'=>16],$guests)===16,'L11 override stable');
v2check(QuoteVs2Domain::quantity(['quantity_source'=>'VISA_PAX','quantity_override'=>null],array_replace($guests,['visa_pax'=>null]))===null,'L12 unset is not total alias');
v2check(QuoteVs2Domain::guests($guests,$guests)===$guests,'L13 FOC convention preserved');v2reject(fn()=>QuoteVs2Domain::guests(array_replace($guests,['adults'=>19]),$guests),'L13 FOC cannot overlap');v2reject(fn()=>QuoteVs2Domain::count('1.5'),'L13 integer guests');v2reject(fn()=>QuoteVs2Domain::guests($guests,['hotel_pax'=>21]),'L14 bounds');
$price=['selling_currency'=>'VND','pricing_mode'=>'MARKUP','pricing_value'=>'20','rounding_step'=>'0'];v2check(SmartCosting::pricing(10000,1,'25000',$price)['total_selling']==='120.00','L34 markup');$price['pricing_mode']='TARGET_MARGIN';v2check(SmartCosting::pricing(10000,1,'25000',$price)['total_selling']==='125.00','L34 margin');$price['pricing_mode']='MANUAL';$price['pricing_value']='129.50';v2check(SmartCosting::pricing(10000,1,'25000',$price)['total_selling']==='129.50','L34 manual');$price['pricing_mode']='MARKUP';$price['pricing_value']='20';$price['rounding_step']='7';v2check(SmartCosting::pricing(10000,1,'25000',$price)['total_selling']==='126.00','L34 upward step');
$req=['category'=>'MEAL','service_date'=>'2027-01-03','day_key'=>'day-2','scope_json'=>'{"meal_key":"lunch","dates":["2027-01-03"]}','service_units'=>1,'package_component_key'=>null];$line=['quantity_source'=>'MEAL_PAX','quantity_override'=>null];$package=['quantity_source'=>'MEAL_PAX','quantity_override'=>null];$rule=['included_category'=>'MEAL','component_key'=>'lunch','scope_rule_json'=>'{"service_date":"2027-01-03","day_key":"day-2","meal_key":"lunch","dates":["2027-01-03"]}','coverage_rule_json'=>'{"units":1}'];
v2check(Vs2Inclusions::covers($rule,$req,$line,$package,$guests),'L22 exact meal covered');v2check(!Vs2Inclusions::covers($rule,array_replace($req,['service_date'=>'2027-01-04']),$line,$package,$guests),'L22 unrelated day remains charged');$partial=$rule;$partial['coverage_rule_json']='{"quantity":10,"units":1}';v2check(!Vs2Inclusions::covers($partial,$req,$line,$package,$guests),'L24 partial coverage not prorated');
v2check(Vs2Templates::PRIVATE_ORDER===['TRANSPORT','GUIDE','HOTEL','CRUISE','VISA','MEAL','ATTRACTION']&&Vs2Templates::SIC_ORDER===['TRANSPORT','HOTEL','CRUISE','TOUR'],'L26 exact template order');
$bookingLine=['id'=>1,'line_kind'=>'SERVICE','coverage_state'=>'PRICED','requirement_id'=>1,'calculation_trace_json'=>'{"original_total":"100.00"}','original_currency'=>'USD','resolved_quantity'=>1,'resolved_units'=>1,'supplier_id'=>1];$bookingReq=[1=>['category'=>'HOTEL','service_name'=>'Reviewed service','service_date'=>'2027-01-02','metadata_json'=>'{"internal_notes":"quiet room"}','id'=>1]];
v2check(QuoteVs2Validator::bookingLines([$bookingLine],$bookingReq,'25000')[0]['total']==='100.00','L47 original USD commitment');$adjust=['line_kind'=>'ADJUSTMENT','coverage_state'=>'PRICED','adjusts_line_id'=>1,'adjustment_amount_vnd'=>'-25000'];v2check(QuoteVs2Validator::bookingLines([$bookingLine,$adjust],$bookingReq,'25000')[0]['total']==='99.00','L33 parent adjustment net');$adjust['adjustment_amount_vnd']='-1';v2reject(fn()=>QuoteVs2Validator::bookingLines([$bookingLine,$adjust],$bookingReq,'25000'),'L47 unrepresentable USD adjustment');$bookingLine['original_currency']='VND';$bookingLine['calculation_trace_json']='{"original_total":"100000001.00"}';v2reject(fn()=>QuoteVs2Validator::bookingLines([$bookingLine],$bookingReq,'25000'),'L47 booking amount bound');
v2reject(fn()=>QuoteVs2Repository::legacy(['costing_engine'=>'VS2_1']),'L42 legacy costs cannot contribute');v2reject(fn()=>QuoteVs2Repository::engine(['costing_engine'=>'UNKNOWN']),'L42 unknown engine fails closed');
$a=['start_date'=>'2027-01-02','end_date'=>'2027-01-03','schedule_json'=>'[{"day_key":"d","date":"2027-01-02","route":"Hanoi","title":"Old"}]'];$b=$a;$b['schedule_json']=str_replace('Old','New',$a['schedule_json']);v2check(QuoteVs2Domain::itineraryScope($a)===QuoteVs2Domain::itineraryScope($b),'L16 cosmetic title preserves transport scope');
echo "VS2.1 deterministic checks complete.\n";
