const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const source=fs.readFileSync(path.join(__dirname,'../visual-proposal.js'),'utf8');const settle=async()=>{for(let i=0;i<12;i++)await new Promise(r=>setImmediate(r));};
async function harness(status='DRAFT',media=true){
 const dom=new JSDOM('<main></main><aside id="modals"></aside>',{runScripts:'outside-only',url:'http://127.0.0.1:18872'}),w=dom.window,calls=[];w.eval(source);
 const day={day_key:'day-stable-key-01',date:'2027-02-10',title:'Hanoi',description:'Public description',route:'Hanoi – Halong',destination:'Hanoi',meals:'B/L',overnight_type:'HOTEL',hotel:'Reviewed hotel',guide_required:true};
 const ctx={costing_revision:10,immutable:status==='SENT',settings:{template:'VTA_STANDARD_B2B',channel:'B2B',brand_mode:'VTA',pricing_display:'NET',selected_variant_id:0,sections:['briefing','price','itinerary','hotel','contact'],accommodation:[]},days:[day,{...day,day_key:'day-stable-key-02',title:'Halong'}],links:[],requirements:[{id:1,service_name:'Guide','requirement_state':'REQUIRED'}],templates:{VTA_STANDARD_B2B:'VTA Standard B2B',VTA_B2B_WHITE_LABEL:'VTA B2B White Label',VTA_EXPLORER_B2C:'VTA Explorer B2C',VTA_PREMIUM_B2C:'VTA Premium B2C'}};
 const asset={id:1,title:'Hanoi photo',status:'DRAFT',visibility:'PERSONAL',low_resolution:true,tags:[],markets:[]};
 const api={request:async(route,opt={})=>{calls.push({route,...opt});if(route.includes('proposal')&&opt.method==='PUT'){ctx.days=structuredClone(opt.body.days);ctx.links=structuredClone(opt.body.links);ctx.settings=structuredClone(opt.body.settings);ctx.costing_revision++;return structuredClone(ctx);}if(route.endsWith('/proposal'))return structuredClone(ctx);if(route==='media-drive')return {available:false,mappings:[]};if(route.startsWith('media?'))return {items:[asset],has_more:false};if(route==='media/1')return {asset};if(route==='tour-library')return {items:[{id:1,title:'Saved program'}]};if(route==='tour-library/1')return {program:{days:[{title:'Imported day',description:'Saved program text'}]}};return {};}};
 const root=w.document.querySelector('main');const modal=(title,html)=>{const m=w.document.createElement('section');m.innerHTML='<h2>'+title+'</h2>'+html;w.document.querySelector('#modals').append(m);return m;};
 const can=p=>p==='quote.view_cost'?false:p.startsWith('media.')?media:true;
 await w.mountVisualProposal(root,{api,quoteData:{quote:{id:10,quote_ref:'QT-TEST'},version:{id:12,version_status:status}},can,modal,closeModal:()=>w.document.querySelector('#modals').replaceChildren(),toast:()=>{},onBack:()=>{},refresh:async()=>{}});await settle();assert(root.querySelector('.df-document'));assert(!calls.some(c=>c.route.startsWith('media?')));root.querySelector('[data-advanced-view]').click();root.querySelector('[data-open-media]').click();await settle();return {dom,w,root,calls};
}
(async()=>{
 let h=await harness();assert.equal(h.root.querySelectorAll('.vs22-columns>aside,.vs22-columns>section').length,3);assert(!h.root.querySelector('[name=internal_notes]'));assert(h.root.textContent.includes('Low resolution'));assert(!h.calls.some(c=>c.route.endsWith('/options')||c.route.includes('rates')||c.route.includes('suppliers')));console.log('PASS VS22 three-column builder never loads supplier costs');
 h.root.querySelector('[name=assign_role]').value='DAY_HERO';h.root.querySelector('[data-assign]').click();h.root.querySelector('[data-v22-save]').click();await settle();let save=h.calls.find(c=>c.method==='PUT');assert.equal(save.body.expected_revision,10);assert.equal(save.body.links[0].day_key,'day-stable-key-01');assert.equal(save.body.links[0].role,'DAY_HERO');console.log('PASS VS22 assignments bind stable day key with stale-write guard');
 h.root.querySelector('[data-duplicate]').click();assert.equal(h.root.querySelectorAll('[data-day]').length,3);h.root.querySelector('[data-up]').click();h.root.querySelector('[data-v22-save]').click();await settle();save=h.calls.filter(c=>c.method==='PUT').at(-1);assert.notEqual(save.body.days[0].day_key,'day-stable-key-01');assert.equal(save.body.links[0].day_key,'day-stable-key-01');console.log('PASS VS22 duplicate/reorder preserves original media identity');
 h.root.querySelector('[data-builder]').click();const m=h.w.document.querySelector('#modals section');assert.equal(m.querySelectorAll('.vs22-template').length,4);const premium=m.querySelector('[value=VTA_PREMIUM_B2C]');premium.checked=true;premium.dispatchEvent(new h.w.Event('change'));assert.equal(m.querySelector('[name=channel]').value,'B2C');m.querySelector('[data-config]').dispatchEvent(new h.w.Event('submit',{bubbles:true,cancelable:true}));h.root.querySelector('[data-v22-save]').click();await settle();save=h.calls.filter(c=>c.method==='PUT').at(-1);assert.equal(save.body.settings.template,'VTA_PREMIUM_B2C');assert.equal(save.body.links.length,2);assert.equal(new Set(save.body.links.map(l=>l.day_key)).size,2);assert(save.body.links.every(l=>l.asset_id===1));console.log('PASS VS22 switching template retains same itinerary/media');
 h.root.querySelector('[data-preview]').click();const preview=h.w.document.querySelector('iframe');assert(preview.src.includes('proposal%2Fhtml'));h.w.document.querySelector('[data-mobile]').click();assert.equal(preview.style.width,'390px');assert(h.w.document.querySelector('[href*="proposal%2Fpdf"]'));assert(h.w.document.querySelector('[href*="proposal%2Fdocx"]'));console.log('PASS VS22 snapshot preview desktop/mobile and output actions');h.dom.window.close();
 h=await harness('SENT');assert(!h.root.querySelector('[data-v22-save]'));assert(!h.root.querySelector('[data-add]'));assert(h.root.querySelector('[name=title]').disabled);console.log('PASS VS22 SENT workspace locks editor and mutators');h.dom.window.close();
 h=await harness('DRAFT',false);assert(!h.calls.some(c=>c.route.startsWith('media')));assert(h.root.textContent.includes('Media permission required'));console.log('PASS VS22 denied media permission causes no asset requests');h.dom.window.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
