<?php
declare(strict_types=1);
require_once __DIR__.'/../api/lib/Http.php';
require_once __DIR__.'/../api/lib/CoreOS.php';
require_once __DIR__.'/../api/lib/QuoteOptions.php';require_once __DIR__.'/../api/lib/QuoteReuse.php';require_once __DIR__.'/../api/lib/Auth.php';require_once __DIR__.'/../api/lib/Audit.php';require_once __DIR__.'/../api/lib/RateEngine.php';
$fixture=json_decode(file_get_contents(getenv('VS23_FIXTURE_FILE')?:sys_get_temp_dir().'/vs23-fixture.json'),true,512,JSON_THROW_ON_ERROR);if(!str_starts_with($fixture['database'],'vta_test_'))throw new RuntimeException('Disposable local fixture required');
$db=new PDO('mysql:host=127.0.0.1;port=33317;dbname='.$fixture['database'].';charset=utf8mb4','root',getenv('VTA_TEST_DB_PASSWORD'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);$user=['id'=>1,'company_id'=>1];
function check23(bool $ok,string $name):void{if(!$ok)throw new RuntimeException('FAIL '.$name);echo "PASS $name\n";}
function sql23(string $sql,array $a=[]):PDOStatement{global $db;return QuoteVs2Repository::q($db,$sql,$a);}
function version23():array{global $db,$qvid;return QuoteOptions::version($db,1,$qvid);}
function command23(callable $fn):array{global $db,$user,$qvid;return QuoteVs2::mutate($db,$user,$qvid,['expected_revision'=>(int)version23()['costing_revision']],$fn,'VS23_VARIANT_FIXTURE');}
function synthetic23(string $category,string $amount,string $formula,?int $star):int{global $db,$user;$ref='VS23-SYNTHETIC-'.bin2hex(random_bytes(4));sql23("INSERT INTO rates(company_id,rate_ref,supplier_id,category,product_name,rate_type,source_origin,status,created_by,updated_by) VALUES(1,?,1,?,?,'MANUAL_OVERRIDE','MANUAL','ACTIVE',1,1)",[$ref,$category,$ref]);$rid=(int)$db->lastInsertId();sql23("INSERT INTO rate_versions(rate_id,version_no,amount,currency,rate_basis,tax_basis,approval_status,valid_from,valid_to,created_by) VALUES(?,1,?,'VND','PER_PAX','NET','APPROVED','2026-01-01','2028-12-31',1)",[$rid,$amount]);$id=(int)$db->lastInsertId();Vs2RateTerms::save($db,$user,$id,['formula_code'=>$formula,'star_level'=>$star,'rate_eligibility_source'=>'TOTAL_GUESTS','basis_evidence'=>['evidence'=>'Explicit synthetic test rate; never a real supplier offer'],'package_scope'=>[],'inclusions'=>[],'publish'=>true]);return $id;}
$source=QuoteOptions::version($db,1,(int)$fixture['version_id']);$sourceSent=sql23('SELECT * FROM quote_sent_bundles WHERE quote_version_id=?',[$source['id']])->fetch();$clone=QuoteReuse::clone($db,$user,(int)$source['id'],(int)$source['inquiry_id'],'FULL_DRAFT');$qvid=(int)$clone['version_id'];$profile=sql23('SELECT * FROM quote_guest_profiles WHERE quote_version_id=?',[$source['id']])->fetch();QuoteSmartCosting::context($db,$user,$qvid,['expected_revision'=>(int)version23()['costing_revision']]+array_intersect_key($profile,array_flip(QuoteVs2Domain::PROFILE)));
$graph=QuoteVs2Repository::graph($db,version23());foreach($graph['requirements'] as $r)if($r['category']==='GUIDE')QuoteSmartCosting::context($db,$user,$qvid,['expected_revision'=>(int)version23()['costing_revision'],'requirements'=>[['id'=>(int)$r['id'],'service_mode'=>'PRIVATE']]]);$graph=QuoteVs2Repository::graph($db,version23());$base=array_values(array_filter($graph['variants'],fn($v)=>$v['variant_key']==='private-4-4'))[0];$reqs=array_column($graph['requirements'],null,'id');$rates=[];foreach($base['lines'] as $l)if($l['rate_version_id'])$rates[$reqs[$l['requirement_id']]['category']]=(int)$l['rate_version_id'];
$rates['TOUR']=synthetic23('TOUR','900000','SIC_PAX',null);$hotel=[3=>synthetic23('HOTEL','600000','HOTEL_PAX_NIGHT',3),4=>$rates['HOTEL'],5=>synthetic23('HOTEL','1000000','HOTEL_PAX_NIGHT',5)];$cruise=[3=>synthetic23('CRUISE','2250000','CRUISE_PAX',3),4=>$rates['CRUISE'],5=>synthetic23('CRUISE','3750000','CRUISE_PAX',5)];
$mix=command23(fn($v)=>['variant_id'=>Vs2Variants::save($db,$user,$v,['variant_key'=>'custom-4-5-vs23','hotel_level'=>'4*','cruise_level'=>5,'costing_mode'=>'PRIVATE','label'=>'Custom Mix 4/5'])]);
$ids=[];foreach(QuoteVs2Repository::graph($db,version23())['variants'] as $variant){if(!in_array($variant['variant_key'],['private-3-3','private-4-4','private-5-5','sic-3-3','sic-4-4','sic-5-5','custom-4-5-vs23'],true))continue;$vid=(int)$variant['id'];$ids[]=$vid;
 foreach($variant['lines'] as $line){$req=$reqs[$line['requirement_id']];if(!QuoteVs2Domain::applies($req,$variant,$line))continue;$category=$req['category'];$rate=$category==='HOTEL'?$hotel[(int)$variant['hotel_level']]:($category==='CRUISE'?$cruise[(int)$variant['cruise_level']]:$rates[$category]);$body=['rate_version_id'=>$rate,'quantity_override'=>null];if(in_array($category,['TRANSPORT','GUIDE'],true))$body['custom_quantity']=2;command23(fn($v)=>Vs2LineEditor::write($db,$user,$v,$vid,$body,'save',(int)$line['id']));command23(fn($v)=>Vs2LineEditor::review($db,$user,$v,$vid,(int)$line['id'],['review_reason'=>'Synthetic scenario rate and population reviewed']));}
 command23(fn($v)=>['variant_id'=>Vs2Variants::save($db,$user,$v,['variant_id'=>$vid,'is_offered'=>true])]);
}
check23(count($ids)===7,'VS23 six PRIVATE/SIC star variants plus one independent Custom Mix');
$schedule=version23()['schedule_json'];$rules=array_fill_keys(QuoteVs2Domain::PROFILE,['mode'=>'PAYING_PAX']);$config=['expected_revision'=>(int)version23()['costing_revision'],'method'=>'SAFE_PRICE','variant_ids'=>$ids,'policies'=>['B2B_AGENT'=>(int)$fixture['policy_id'],'B2C_DIRECT'=>2],'quantity_rules'=>$rules,'fx_rate'=>'25000','fx_source'=>'MANUAL'];$matrix=PriceMatrix::generate($db,$user,$qvid,$config);
check23(count($matrix['cells'])===70,'VS23 full 3/4/5 PRIVATE/SIC and Custom Mix matrix shares one itinerary');check23(version23()['schedule_json']===$schedule,'VS23 variant matrix does not duplicate or alter itinerary');
foreach($matrix['cells'] as $cell){check23($cell['status']!=='SCENARIO_REVIEW_REQUIRED','VS23 scenario review '.$cell['result']['mode'].' '.$cell['result']['label'].' '.$cell['band_key']);}
$sic=array_values(array_filter($matrix['cells'],fn($c)=>$c['result']['mode']==='SIC'))[0];$inputs=json_decode(PriceMatrix::row($db,version23())['inputs_json'],true);$sicVariant=array_values(array_filter($inputs['graph']['variants'],fn($v)=>(int)$v['id']===(int)$sic['variant_id']))[0];$calc=PaxScenario::calculate($db,$inputs['graph'],$sicVariant,4,$matrix['config'],'25000');$cats=[];foreach($calc['cost_lines'] as $line)$cats[]=$reqs[$line['requirement_id']]['category'];sort($cats);check23($cats===['CRUISE','HOTEL','TOUR','TRANSPORT'],'VS23 SIC defaults generate exactly transfer hotel cruise SIC: '.json_encode($cats));
$settings=QuoteProposal::settings(['template'=>'VTA_EXPLORER_B2C','highlights'=>'Synthetic family commercial offer']);QuoteProposal::save($db,$user,$qvid,['expected_revision'=>(int)version23()['costing_revision'],'settings'=>$settings,'days'=>QuoteProposal::days(version23()),'links'=>[]]);
check23(!PriceMatrix::report($db,version23())['valid'],'VS23 proposal channel changes require matrix revalidation');$matrix=PriceMatrix::generate($db,$user,$qvid,array_replace($config,['expected_revision'=>(int)version23()['costing_revision']]));
foreach(['validate','lock'] as $action)PriceMatrix::change($db,$user,$qvid,$action,['expected_revision'=>(int)version23()['costing_revision']]);QuoteOptions::approve($db,$user,$qvid,'Reviewed synthetic B2C star matrix');$sent=QuoteOptions::send($db,$user,$qvid)['customer_safe_snapshot'];check23($sent['commercial']['channel']==='B2C_DIRECT'&&!preg_match('/commission|net_payable|cost_total_vnd|margin_pct/',json_encode($sent)),'VS23 B2C frozen proposal hides agent and supplier commercial data');
$matrixRow=PriceMatrix::row($db,version23());$agentCell=array_values(array_filter(PriceMatrix::cells($db,$matrixRow),fn($c)=>$c['channel']==='B2B_AGENT'&&$c['min_pax']==5))[0];try{PriceMatrix::recheck($db,version23(),$agentCell,8);throw new LogicException('Wrong channel accepted');}catch(DomainException $e){check23($e->getMessage()==='CELL_NOT_IN_SENT_PROPOSAL','VS23 acceptance cannot select a different commercial channel from Sent');}
check23(sql23('SELECT * FROM quote_sent_bundles WHERE quote_version_id=?',[$source['id']])->fetch()===$sourceSent,'VS23 matrix variant testing preserves source Sent bytes');
echo "VS2.3 multi-variant and channel acceptance complete.\n";
