<?php
declare(strict_types=1);
require_once __DIR__.'/../api/lib/Http.php';require_once __DIR__.'/../api/lib/CoreOS.php';require_once __DIR__.'/../api/lib/QuoteOptions.php';require_once __DIR__.'/../api/lib/Auth.php';require_once __DIR__.'/../api/lib/RateEngine.php';
$f=json_decode(file_get_contents(getenv('VS23_FIXTURE_FILE')),true,512,JSON_THROW_ON_ERROR);if(!str_starts_with($f['database'],'vta_test_'))throw new RuntimeException('Disposable local fixture required');$db=new PDO('mysql:host=127.0.0.1;port=33317;dbname='.$f['database'].';charset=utf8mb4','root',getenv('VTA_TEST_DB_PASSWORD'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
function pass23(bool $ok,string $label):void{if(!$ok)throw new RuntimeException('FAIL '.$label);echo 'PASS '.$label.PHP_EOL;}
function denied23(callable $fn,string $code):void{try{$fn();throw new LogicException('Expected rejection '.$code);}catch(DomainException $e){pass23(str_starts_with($e->getMessage(),$code),$code);}}
$v=QuoteOptions::version($db,1,(int)$f['version_id']);$row=PriceMatrix::row($db,$v);$in=QuoteVs2Repository::decode($row['inputs_json']);$graph=$in['graph'];$variant=$graph['variants'][0];$config=$in['config'];$reqs=array_column($graph['requirements'],null,'id');
pass23(PaxScenario::bands([['min'=>5,'max'=>9,'representative'=>7]],'REPRESENTATIVE_PAX')[0]['representative']===7,'Representative pax retained inside inclusive band');
$p=CommercialPolicy::get($db,1,(int)$f['policy_id']);$full=CommercialPolicy::validate(array_replace($p,['deposit_pct'=>'100']));$r=CommercialPolicy::pricing(Vs2Decimal::parse('10000000'),8,'25000',$full);pass23($r['deposit']===$r['net_payable']&&$r['balance']==='0.00','100 percent deposit preserves net payable');
$p['policy_mode']='B2B_NET_RATE';$p['pricing_value']='100';$r=CommercialPolicy::pricing(Vs2Decimal::parse('10000000'),8,'25000',$p);pass23($r['net_per_pax']==='100.00','Manual agent net rate is fixed per paying pax');
$g=PaxScenario::guests($graph['version'],$graph['profile'],8,$config,['adults'=>6,'children'=>2,'infants'=>0,'foc'=>2,'total_guests'=>10,'paying_pax'=>8,'hotel_pax'=>10,'cruise_pax'=>9,'visa_pax'=>8,'meal_pax'=>9,'ticket_pax'=>6]);pass23($g['children']===2&&$g['foc']===2&&$g['ticket_pax']===6,'Exact family composition and service populations preserve FOC');
// The native VS21 fixture deliberately approved scoped guide inclusion terms.
$rule=QuoteVs2Repository::q($db,"SELECT i.* FROM rate_version_inclusions i JOIN rates r JOIN rate_versions rv ON rv.id=i.rate_version_id AND rv.rate_id=r.id WHERE r.company_id=1 AND i.included_category='GUIDE' ORDER BY i.id LIMIT 1")->fetch();if(!$rule)throw new RuntimeException('Approved scoped test inclusion missing');
$guide=null;$tour=null;foreach($variant['lines'] as $l){$cat=$reqs[$l['requirement_id']]['category'];if($cat==='GUIDE')$guide=$l;if($cat==='TOUR')$tour=$l;}
$hybrid=$variant;$hybrid['costing_mode']='HYBRID';foreach($graph['requirements'] as &$req)if($req['category']==='GUIDE')$req['service_mode']='BOTH';unset($req);
foreach($hybrid['lines'] as &$l){if($l['id']===$guide['id']){$l['coverage_state']='INCLUDED';$l['included_by_line_id']=$tour['id'];$l['inclusion_rule_id']=$rule['id'];$l['service_mode']='PRIVATE';}if($l['id']===$tour['id']){$l['service_mode']='SIC';$l['rate_version_id']=$rule['rate_version_id'];$l['coverage_state']='PRICED';$l['quantity_override']=null;}}unset($l);
$calc=PaxScenario::calculate($db,$graph,$hybrid,8,$config,'25000');$lines=array_column($calc['cost_lines'],null,'id');pass23(count(array_filter($lines,fn($l)=>$l['line_kind']==='SERVICE'))===8&&$lines[$guide['id']]['total_vnd']==='0.00'&&(int)$lines[$guide['id']]['resolved_quantity']===2,'HYBRID includes SIC tour and suppresses exactly scoped Guide');
$priced=$hybrid;foreach($priced['lines'] as &$l)if($l['id']===$guide['id'])$l['coverage_state']='PRICED';unset($l);denied23(fn()=>PaxScenario::calculate($db,$graph,$priced,8,$config,'25000'),'DUPLICATE_INCLUDED_COST');
$partial=$hybrid;foreach($partial['lines'] as &$l)if($l['id']===$guide['id'])$l['custom_quantity']=1;unset($l);denied23(fn()=>PaxScenario::calculate($db,$graph,$partial,8,$config,'25000'),'PARTIAL_COVERAGE_REVIEW');
$unrelated=$graph;foreach($unrelated['requirements'] as &$req)if($req['category']==='GUIDE'){$req['service_date']='2027-01-05';$req['scope_json']=json_encode(['dates'=>['2027-01-05']]);$req['service_units']=1;}unset($req);$calc=PaxScenario::calculate($db,$unrelated,$priced,8,$config,'25000');$lines=array_column($calc['cost_lines'],null,'id');pass23($lines[$guide['id']]['total_vnd']==='2000000.00','Guide outside included package dates remains chargeable');
$manual=$variant;foreach($manual['lines'] as &$l)if($reqs[$l['requirement_id']]['category']==='VISA'){$l['quantity_override']=5;$manualId=$l['id'];}unset($l);denied23(fn()=>PaxScenario::calculate($db,$in['graph'],$manual,9,$config,'25000'),'MANUAL_OVERRIDE_REVIEW_REQUIRED');$config['override_reviews'][(string)$manualId]='Reviewed fixed five visa applicants';$a=PaxScenario::calculate($db,$in['graph'],$manual,9,$config,'25000');$b=PaxScenario::calculate($db,$in['graph'],$manual,10,$config,'25000');pass23(array_column($a['cost_lines'],null,'id')[$manualId]['resolved_quantity']===5&&array_column($b['cost_lines'],null,'id')[$manualId]['resolved_quantity']===5,'Reviewed manual quantities stay stable across bands');
echo "VS2.3 scoped scenario checks complete.\n";
