<?php
declare(strict_types=1);
require __DIR__.'/vs22-native.php';
$priorIssued=$qvid;$priorSent=v2q('SELECT * FROM quote_sent_bundles WHERE quote_version_id=?',[$qvid])->fetch();
$clone23=QuoteReuse::clone($db,$user,$priorIssued,(int)v2v()['inquiry_id'],'FULL_DRAFT');$qvid=(int)$clone23['version_id'];
v2context(array_intersect_key($profile,array_flip(QuoteVs2Domain::PROFILE)));
$variant=(int)v2q("SELECT c.id FROM quote_option_variants c JOIN quote_options o ON o.id=c.quote_option_id WHERE o.quote_version_id=? AND c.variant_key='private-4-4'",[$qvid])->fetchColumn();
v2command([],function($v)use($db){SmartCosting::refresh($db,$v,[],true);Vs2Inclusions::apply($db,$v);return [];});
foreach(v2q('SELECT id FROM quote_variant_cost_lines WHERE variant_id=?',[$variant])->fetchAll() as $l)if($l['id']!=v2line($variant,'TOUR')['id'])v2review($variant,(int)$l['id']);
v2command([],fn($v)=>['id'=>Vs2Variants::save($db,$user,$v,['variant_id'=>$variant,'is_offered'=>true])]);
$policyBase=['policy_key'=>'AGENT','name'=>'Agent 15%','channel'=>'B2B_AGENT','policy_mode'=>'B2B_MARKUP','pricing_value'=>'15','minimum_margin_pct'=>'10','warning_margin_pct'=>'12','commission_pct'=>'0','deposit_pct'=>'30','rounding_step'=>'1','selling_currency'=>'USD','validity_days'=>14,'payment_terms'=>'30% deposit; balance before arrival','cancellation_policy'=>'Reviewed cancellation terms'];
$agent=CommercialPolicy::create($db,$user,$policyBase);$retail=CommercialPolicy::create($db,$user,array_replace($policyBase,['policy_key'=>'DIRECT','name'=>'Retail 25%','channel'=>'B2C_DIRECT','policy_mode'=>'B2C_MARKUP','pricing_value'=>'25']));
rejects(fn()=>PaxScenario::bands([['min'=>5,'max'=>10],['min'=>10,'max'=>15]],'SAFE_PRICE'),InvalidArgumentException::class,'VS23 inclusive overlapping bands rejected');
rejects(fn()=>PaxScenario::bands([['min'=>2,'max'=>4]],'EXACT_PAX'),InvalidArgumentException::class,'VS23 exact method rejects ranges');
rejects(fn()=>CommercialPolicy::validate(array_replace($policyBase,['channel'=>'B2C_DIRECT','policy_mode'=>'B2C_MARKUP','commission_pct'=>'10'])),InvalidArgumentException::class,'VS23 B2C commission forbidden');
rejects(fn()=>CommercialPolicy::pricing(10000000,8,'25000',array_replace($agent,['policy_mode'=>'B2B_NET_RATE','pricing_value'=>'0'])),DomainException::class,'VS23 zero selling price blocked');
$markup=CommercialPolicy::pricing(1000000000,8,'25000',array_replace($agent,['pricing_value'=>'20','rounding_step'=>'0']));$margin=CommercialPolicy::pricing(1000000000,8,'25000',array_replace($agent,['policy_mode'=>'B2B_MARGIN','pricing_value'=>'20','rounding_step'=>'0']));
check($markup['net_per_pax']==='60.00'&&$margin['net_per_pax']==='62.50','VS23 markup and target margin distinct');
$commission=CommercialPolicy::pricing(1000000000,8,'25000',array_replace($agent,['pricing_value'=>'20','rounding_step'=>'0','commission_pct'=>'10','minimum_margin_pct'=>'18']));
check($commission['net_payable']==='480.00'&&$commission['selling_per_pax']==='66.67'&&$commission['pricing_status']==='MARGIN_BELOW_POLICY','VS23 margin is on net after commission');
$rules=array_fill_keys(QuoteVs2Domain::PROFILE,['mode'=>'PAYING_PAX']);$config=['method'=>'SAFE_PRICE','bands'=>PaxScenario::DEFAULT_BANDS,'variant_ids'=>[$variant],'policies'=>['B2B_AGENT'=>(int)$agent['id'],'B2C_DIRECT'=>(int)$retail['id']],'quantity_rules'=>$rules,'fx_rate'=>'25000','fx_source'=>'MANUAL','override_reviews'=>[]];
foreach(v2q('SELECT id,quantity_override FROM quote_variant_cost_lines WHERE variant_id=?',[$variant])->fetchAll() as $l)if($l['quantity_override']!==null)$config['override_reviews'][(string)$l['id']]='Synthetic stable override reviewed';
$beforeLines=v2q('SELECT * FROM quote_variant_cost_lines WHERE variant_id=?',[$variant])->fetchAll();
$generate=fn($b)=>PriceMatrix::generate($db,$user,$qvid,['expected_revision'=>(int)v2v()['costing_revision']]+$b);
$change=fn($a,$b=[])=>PriceMatrix::change($db,$user,$qvid,$a,['expected_revision'=>(int)v2v()['costing_revision']]+$b);
$low=CommercialPolicy::create($db,$user,array_replace($policyBase,['policy_key'=>'LOW','name'=>'Below policy','minimum_margin_pct'=>'30','warning_margin_pct'=>'35']));
$lowConfig=array_replace($config,['method'=>'EXACT_PAX','bands'=>[['min'=>8,'max'=>8]],'policies'=>['B2B_AGENT'=>(int)$low['id']]]);$lowCtx=$generate($lowConfig);$lowCell=$lowCtx['cells'][0];
check($lowCell['status']==='MARGIN_BELOW_POLICY','VS23 below-policy price explicitly flagged');
rejects(fn()=>$change('validate'),DomainException::class,'VS23 minimum margin blocks validate and send');
$change('override',['cell_id'=>(int)$lowCell['id'],'context_hash'=>$lowCell['context_hash'],'reason'=>'Synthetic manager-approved commercial exception']);$change('validate');$change('lock');
check((bool)v2q('SELECT approved_by,approved_at,reason FROM commercial_overrides WHERE cell_id=?',[$lowCell['id']])->fetch(),'VS23 override records actor time reason and exact cell');
$change('unlock',['reason'=>'Switch to approved standard policies']);
$ctx=$generate($config);check(count($ctx['cells'])===10,'VS23 five default bands for two channels over one variant');
check(v2q('SELECT * FROM quote_variant_cost_lines WHERE variant_id=?',[$variant])->fetchAll()===$beforeLines,'VS23 scenario generation never changes persistent costs');
foreach($ctx['cells'] as $cell){$scenarios=$cell['result']['scenarios'];check(count($scenarios)===(int)$cell['max_pax']-(int)$cell['min_pax']+1&&!$cell['result']['failures'],'VS23 SAFE_PRICE evaluates every pax '.$cell['channel'].' '.$cell['band_key']);foreach($scenarios as $sc)check($sc['cost']['guests']['foc']===2,'VS23 FOC preserved '.$sc['pax']);}
$a=array_values(array_filter($ctx['cells'],fn($c)=>$c['channel']==='B2B_AGENT'&&$c['band_key']==='5-9'))[0];$b=array_values(array_filter($ctx['cells'],fn($c)=>$c['channel']==='B2C_DIRECT'&&$c['band_key']==='5-9'))[0];
check(array_column($a['result']['scenarios'],'cost')===array_column($b['result']['scenarios'],'cost')&&Vs2Decimal::parse($b['selling_per_pax'])>Vs2Decimal::parse($a['selling_per_pax']),'VS23 shared supplier costs with distinct selling channels');
$required=[];foreach($a['result']['scenarios'] as $sc)$required[]=Vs2Decimal::parse(CommercialPolicy::pricing(Vs2Decimal::parse($sc['cost']['cost_total_vnd']),$sc['pax'],'25000',$agent)['net_per_pax']);
check(Vs2Decimal::parse($a['net_per_pax'])===max($required),'VS23 SAFE_PRICE takes maximum required price inside band');
$selectedId=(int)$a['id'];$change('select',['cell_id'=>$selectedId,'is_selected'=>true,'is_recommended'=>true]);
rejects(fn()=>PriceMatrix::generate($db,$user,$qvid,['expected_revision'=>(int)v2v()['costing_revision']-1]+$config),DomainException::class,'VS23 stale revision generation blocked');
$oldFx=v2v()['fx_rate'];v2q('UPDATE quote_versions SET fx_rate=? WHERE id=?',['26000',$qvid]);check(!PriceMatrix::report($db,v2v())['valid'],'VS23 FX dependency change invalidates draft');v2q('UPDATE quote_versions SET fx_rate=? WHERE id=?',[$oldFx,$qvid]);
$change('validate');$ctx=$change('lock');check($ctx['matrix']['status']==='LOCKED','VS23 validated matrix locks');
rejects(fn()=>$generate($config),DomainException::class,'VS23 locked matrix cannot silently regenerate');
$public=QuoteProposal::publicQuote($db,v2v());check(isset($public['commercial'])&&!str_contains(json_encode($public),'cost_total_vnd'),'VS23 public proposal selling only');
$blocks=ProposalOutput::blocks($public);check((bool)array_filter($blocks,fn($b)=>$b['type']==='table'&&$b['headers']===['Pax','3★','4★','5★','Price basis']),'VS23 proposal renders locked star matrix');
QuoteOptions::approve($db,$user,$qvid,'Reviewed VS23 commercial matrix');$issued23=QuoteOptions::send($db,$user,$qvid);$sent23=v2q('SELECT * FROM quote_sent_bundles WHERE quote_version_id=?',[$qvid])->fetch();
check(PriceMatrix::row($db,v2v())['status']==='SENT','VS23 matrix follows existing send');
$cell=PriceMatrix::cell($db,PriceMatrix::row($db,v2v()),$selectedId);$exact=PriceMatrix::recheck($db,v2v(),$cell,8);check($exact['status']==='VALID'&&$exact['cost']['paying_pax']===8,'VS23 exact eight pax recheck');
rejects(fn()=>PriceMatrix::recheck($db,v2v(),$cell,10),DomainException::class,'VS23 acceptance outside offered band blocked');
QuoteOptions::confirm($db,$user,$qvid,(int)$a['result']['option_id'],(int)$cell['variant_id'],$sent23['content_hash'],(int)v2v()['costing_revision'],['cell_id'=>$selectedId,'paying_pax'=>8]);
$accept=v2q('SELECT * FROM quote_commercial_acceptances WHERE quote_version_id=?',[$qvid])->fetch();check((int)$accept['paying_pax']===8,'VS23 acceptance freezes exact pax');
$booking23=QuoteOptions::booking($db,$user,$qvid);$bid=(int)$booking23['id'];$book23=v2q('SELECT * FROM booking_quote_snapshots WHERE booking_id=?',[$bid])->fetch();$bookPublic=json_decode($book23['public_snapshot_json'],true);check((int)$bookPublic['paying_pax']===8,'VS23 booking snapshot exact accepted pax');
$h=SalesHandover::context($db,$user,$bid);check($h['handover']['stage']==='COMMERCIAL_CONFIRMED'&&count($h['services'])>=7,'VS23 structured handover created from immutable booking');
$transition=fn($action,$body=[])=>SalesHandover::transition($db,$user,$bid,$action,['expected_revision'=>(int)SalesHandover::context($db,$user,$bid)['handover']['revision']]+$body);
$checklist=array_fill_keys(SalesHandover::CHECKLIST,true);$checklist['flights']='NOT_PROVIDED';$transition('prepare',['checklist'=>$checklist,'sales_notes'=>'Synthetic accepted contract reviewed']);$transition('submit');
rejects(fn()=>$transition('return',['reason'=>'']),InvalidArgumentException::class,'VS23 operations return requires reason');
$transition('return',['reason'=>'Please clarify arrival flight']);check(SalesHandover::context($db,$user,$bid)['handover']['intake_status']==='NEEDS_REVIEW','VS23 return visible to Sales');
$transition('prepare',['checklist'=>$checklist]);$transition('submit');$transition('accept');check(SalesHandover::context($db,$user,$bid)['handover']['intake_status']==='READY_TO_BOOK','VS23 operations accepts without supplier booking prerequisite');
$cr=SalesHandover::changeRequest($db,$user,$bid,['description'=>'Customer requests a later pickup','affected_services'=>[(int)$h['services'][0]['id']]]);foreach(['UNDER_REVIEW','APPROVED','IMPLEMENTED'] as $status)$cr=SalesHandover::changeRequest($db,$user,$bid,['expected_revision'=>(int)$cr['revision'],'status'=>$status,'reason'=>'Fixture change status only'],(int)$cr['id']);
check($cr['status']==='IMPLEMENTED'&&v2q('SELECT * FROM booking_quote_snapshots WHERE booking_id=?',[$bid])->fetch()===$book23,'VS23 change foundation never modifies confirmed snapshot');
check(v2q('SELECT * FROM quote_sent_bundles WHERE quote_version_id=?',[$qvid])->fetch()===$sent23&&v2q('SELECT * FROM quote_sent_bundles WHERE quote_version_id=?',[$priorIssued])->fetch()===$priorSent,'VS23 historical and current Sent bytes remain identical');
$storedInputs=QuoteVs2Repository::decode(PriceMatrix::row($db,v2v())['inputs_json']);$frozenVariant=$storedInputs['graph']['variants'][0];$eight=PaxScenario::calculate($db,$storedInputs['graph'],$frozenVariant,8,$config,'25000');$nine=PaxScenario::calculate($db,$storedInputs['graph'],$frozenVariant,9,$config,'25000');$e=array_column($eight['cost_lines'],null,'id');$n=array_column($nine['cost_lines'],null,'id');
foreach($e as $id=>$line)if(in_array($line['formula_code'],['TRANSFER_PACKAGE','GUIDE_DAY'],true))check($line['total_vnd']===$n[$id]['total_vnd'],'VS23 fixed guide/vehicle package preserved '.$id);
$transfer=v2line($variant,'TRANSPORT');$capacityConfig=$config;$capacityConfig['resource_counts'][(string)$transfer['id']]=['counts'=>['20'=>1],'reason'=>'Explicit capacity test'];
rejects(fn()=>PaxScenario::calculate($db,$storedInputs['graph'],$frozenVariant,20,$capacityConfig,'25000'),DomainException::class,'VS23 capacity shortage rejected without inventing supplier rate');
rejects(fn()=>$generate($config),DomainException::class,'VS23 Sent matrix cannot regenerate');
file_put_contents($output.'/fixture23.json',QuoteVs2Repository::json(['database'=>$database,'quote_id'=>(int)v2v()['quote_id'],'version_id'=>$qvid,'variant_id'=>$variant,'cell_id'=>$selectedId,'booking_id'=>$bid,'policy_id'=>(int)$agent['id'],'low_policy_id'=>(int)$low['id'],'prior_version_id'=>$priorIssued]));
echo "VS2.3 native commercial/handover acceptance complete.\n";
