"use client";
import {use,useEffect,useState} from "react";
import {useRouter} from "next/navigation";

type Booking=any;
export default function BookingWorkspace({params}:{params:Promise<{id:string}>}){
 const {id}=use(params);const router=useRouter();const [b,setB]=useState<Booking|null>(null);const [staff,setStaff]=useState<any[]>([]);const [role,setRole]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");
 const load=async()=>{const [me,res,sr]=await Promise.all([fetch("/api/admin/auth/me"),fetch("/api/admin/bookings/"+id+"/detail"),fetch("/api/admin/staff")]);if(!me.ok){router.replace("/admin/login");return}const md=await me.json();setRole(md.user?.role||"");const d=await res.json();if(!res.ok){setError(d.error||"Unable to load booking");return}setB(d.booking);if(sr.ok)setStaff((await sr.json()).staff||[])};
 useEffect(()=>{load()},[id]);
 const patch=async(data:any)=>{setError("");setMessage("");const r=await fetch("/api/admin/bookings/"+id,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const d=await r.json();if(!r.ok){setError(d.error||"Unable to update");return}setMessage("Booking updated.");await load()};
 const addExpense=async(e:any)=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/admin/expenses",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...Object.fromEntries(f),bookingId:id})});const d=await r.json();if(!r.ok){setError(d.error||"Unable to add expense");return}e.currentTarget.reset();setMessage("Expense recorded.");await load()};
 const addPayable=async(e:any)=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/admin/payables",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...Object.fromEntries(f),bookingId:id})});const d=await r.json();if(!r.ok){setError(d.error||"Unable to add payable");return}e.currentTarget.reset();setMessage("Supplier payable recorded.");await load()};
 const paySupplier=async(pid:string,outstanding:number)=>{const raw=window.prompt("Supplier payment amount (USD)",String(outstanding));if(!raw)return;const r=await fetch("/api/admin/payables/"+pid,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({payment:Number(raw)})});const d=await r.json();if(!r.ok){setError(d.error||"Unable to record payment");return}setMessage("Supplier payment recorded.");await load()};
 const money=(n:number|null|undefined)=>"US$ "+(n||0).toLocaleString("en-US");
 if(!b)return <main className="adminPage"><div className="shell adminWrap">{error?<div className="adminError">{error}</div>:"Loading booking workspace..."}</div></main>;
 const canWriteFinance=["ADMIN","SALES","FINANCE"].includes(role); const revenue=b.estimatedTotal||0, expenses=b.expenses.reduce((n:number,x:any)=>n+x.amount,0), supplierTotal=b.supplierPayables.reduce((n:number,x:any)=>n+x.amount,0), supplierPaid=b.supplierPayables.reduce((n:number,x:any)=>n+x.paidAmount,0);
 return <main className="adminPage"><header className="adminHeader"><div className="shell"><a className="brand" href="/"><span className="brandMark">≋</span><span><b>HALONG CRUISE<br/>ADVISOR</b><small>Operations Workspace</small></span></a><nav className="adminNav"><a href="/admin">Bookings</a><a href="/admin/inventory">Inventory</a><a href="/admin/finance">Finance</a></nav></div></header>
 <div className="shell adminWrap"><div className="adminTitle"><span className="eyebrow">{b.reference}</span><h1>{b.primaryGuest} · {b.cruiseName}</h1><p>{new Date(b.departureDate).toLocaleDateString("en-US")} · {b.adults} adults · {b.children} children · {b.cabinName||"Cabin TBD"}</p></div>
 {error&&<div className="adminError">{error}</div>}{message&&<div className="adminSuccess">{message}</div>}
 <div className="adminStats"><div><span>Revenue</span><strong>{money(revenue)}</strong></div><div><span>Quoted margin</span><strong>{money(b.quotedMargin)}</strong></div><div><span>Actual/accrued profit</span><strong>{money(revenue-supplierTotal-expenses)}</strong></div><div><span>Guest due</span><strong>{money(Math.max(0,revenue-b.amountPaid+b.amountRefunded))}</strong></div><div><span>Supplier due</span><strong>{money(Math.max(0,supplierTotal-supplierPaid))}</strong></div></div>
 <div className="inventoryGrid">
 <section className="inventoryPanel"><div className="panelTitle"><h2>Guest & booking</h2><span>{b.email} · {b.phone||"No phone"} · {b.nationality||"Nationality TBD"}</span></div>
 <div className="inventoryForm"><label><span>Status</span><select value={b.status} onChange={e=>patch({status:e.target.value})}>{["NEW","CONTACTED","QUOTED","CONFIRMED","CANCELLED"].map(x=><option key={x}>{x}</option>)}</select></label>
 <label><span>Owner</span><select value={b.assignedToId||""} onChange={e=>patch({assignedToId:e.target.value||null})}><option value="">Unassigned</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name} · {s.role}</option>)}</select></label>
 <label><span>Follow-up</span><input type="date" value={b.followUpAt?b.followUpAt.slice(0,10):""} onChange={e=>patch({followUpAt:e.target.value||null})}/></label>
 <label><span>Internal notes</span><textarea defaultValue={b.internalNotes||""} onBlur={e=>patch({internalNotes:e.target.value})}/></label></div></section>
 <section className="inventoryPanel"><div className="panelTitle"><h2>Customer payments</h2><span>{b.paymentStatus} · collected {money(b.amountPaid-b.amountRefunded)}</span></div>
 <div className="inventoryItems">{b.payments.map((p:any)=><div className="inventoryItem" key={p.id}><b>{p.kind} · {money(p.amount)}</b><small>{p.status} · {p.provider} · {new Date(p.createdAt).toLocaleString("en-US")}</small></div>)}{!b.payments.length&&<p className="muted">No payment transactions yet.</p>}</div>
 <a className="darkButton" href={"/voucher/"+b.reference}>Open customer voucher</a></section>
 <section className="inventoryPanel"><div className="panelTitle"><h2>Supplier payable</h2><span>{b.cruise?.supplier?.name||"No cruise supplier assigned"}</span></div>
 {canWriteFinance&&b.cruise?.supplierId&&<form className="inventoryForm" onSubmit={addPayable}><input type="hidden" name="supplierId" value={b.cruise.supplierId}/><label><span>Amount USD</span><input name="amount" type="number" min="1" required defaultValue={b.quotedCost||""}/></label><label><span>Due date</span><input name="dueDate" type="date"/></label><label><span>Notes</span><input name="notes" placeholder="Contract / invoice reference"/></label><button className="darkButton">Add payable</button></form>}
 <div className="inventoryItems">{b.supplierPayables.map((p:any)=>{const due=Math.max(0,p.amount-p.paidAmount);return <div className="inventoryItem" key={p.id}><b>{p.supplier.name} · {money(p.amount)}</b><small>{p.status} · paid {money(p.paidAmount)} · due {money(due)}</small>{canWriteFinance&&due>0&&<button onClick={()=>paySupplier(p.id,due)}>Record payment</button>}</div>})}</div></section>
 <section className="inventoryPanel"><div className="panelTitle"><h2>Booking expenses</h2><span>Transfer, guide, commission, fees and other costs.</span></div>
 {canWriteFinance?<form className="inventoryForm" onSubmit={addExpense}><label><span>Category</span><select name="category">{["TRANSFER","GUIDE","COMMISSION","BANK_FEE","REFUND_COST","OTHER"].map(x=><option key={x}>{x}</option>)}</select></label><label><span>Amount USD</span><input name="amount" type="number" min="1" required/></label><label><span>Description</span><input name="description" placeholder="Airport transfer, bank fee..."/></label><button className="darkButton">Add expense</button></form>:<p className="muted">Your role has read-only finance access.</p>}
 <div className="inventoryItems">{b.expenses.map((x:any)=><div className="inventoryItem" key={x.id}><b>{x.category} · {money(x.amount)}</b><small>{x.description||"No description"} · {new Date(x.createdAt).toLocaleString("en-US")}</small></div>)}</div></section>
 </div></div></main>
}
