SET NAMES utf8mb4;
SET time_zone = '+07:00';

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  customer_ref VARCHAR(64) NOT NULL,
  customer_type ENUM('DIRECT','B2B_CONTACT') NOT NULL DEFAULT 'DIRECT',
  full_name VARCHAR(190) NOT NULL,
  company_name VARCHAR(190) NULL,
  country VARCHAR(120) NULL,
  market VARCHAR(120) NULL,
  whatsapp VARCHAR(64) NULL,
  email VARCHAR(190) NULL,
  preferred_language VARCHAR(80) NULL,
  source VARCHAR(80) NULL,
  notes TEXT NULL,
  sales_owner_id BIGINT UNSIGNED NULL,
  status ENUM('ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
  version_no INT UNSIGNED NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NOT NULL,
  updated_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  archived_at DATETIME NULL,
  UNIQUE KEY uq_customer_ref(company_id,customer_ref),
  KEY idx_customer_name(company_id,full_name),
  KEY idx_customer_contact(company_id,whatsapp,email),
  CONSTRAINT fk_customer_company FOREIGN KEY(company_id) REFERENCES companies(id),
  CONSTRAINT fk_customer_owner FOREIGN KEY(sales_owner_id) REFERENCES users(id),
  CONSTRAINT fk_customer_created FOREIGN KEY(created_by) REFERENCES users(id),
  CONSTRAINT fk_customer_updated FOREIGN KEY(updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agents (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  agent_ref VARCHAR(64) NOT NULL,
  company_name VARCHAR(190) NOT NULL,
  country VARCHAR(120) NULL,
  market VARCHAR(120) NULL,
  primary_contact VARCHAR(190) NULL,
  whatsapp VARCHAR(64) NULL,
  email VARCHAR(190) NULL,
  website VARCHAR(190) NULL,
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  payment_terms TEXT NULL,
  credit_terms TEXT NULL,
  default_followup_days INT UNSIGNED NOT NULL DEFAULT 2,
  preferred_hotel_level VARCHAR(32) NULL,
  branding_mode ENUM('VTA_ONLY','AGENT_VTA','WHITE_LABEL') NOT NULL DEFAULT 'VTA_ONLY',
  logo_storage_file_id VARCHAR(255) NULL,
  notes TEXT NULL,
  status ENUM('ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
  version_no INT UNSIGNED NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NOT NULL,
  updated_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  archived_at DATETIME NULL,
  UNIQUE KEY uq_agent_ref(company_id,agent_ref),
  KEY idx_agent_name(company_id,company_name),
  CONSTRAINT fk_agent_company FOREIGN KEY(company_id) REFERENCES companies(id),
  CONSTRAINT fk_agent_created FOREIGN KEY(created_by) REFERENCES users(id),
  CONSTRAINT fk_agent_updated FOREIGN KEY(updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trips (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  trip_ref VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  customer_id BIGINT UNSIGNED NULL,
  agent_id BIGINT UNSIGNED NULL,
  lead_contact_name VARCHAR(190) NULL,
  lead_whatsapp VARCHAR(64) NULL,
  lead_email VARCHAR(190) NULL,
  market VARCHAR(120) NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  adults INT UNSIGNED NOT NULL DEFAULT 0,
  children INT UNSIGNED NOT NULL DEFAULT 0,
  infants INT UNSIGNED NOT NULL DEFAULT 0,
  foc INT UNSIGNED NOT NULL DEFAULT 0,
  total_guests INT UNSIGNED NOT NULL DEFAULT 0,
  paying_pax INT UNSIGNED NOT NULL DEFAULT 0,
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  lifecycle_stage ENUM('INQUIRY','QUOTE','CONFIRMED','BOOKING','ON_TOUR','COMPLETED','LOST','CANCELLED') NOT NULL DEFAULT 'INQUIRY',
  sales_owner_id BIGINT UNSIGNED NULL,
  operations_owner_id BIGINT UNSIGNED NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  updated_by BIGINT UNSIGNED NOT NULL,
  version_no INT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_trip_ref(company_id,trip_ref),
  KEY idx_trip_dates(company_id,start_date,end_date),
  KEY idx_trip_contact(company_id,lead_whatsapp,lead_email),
  CONSTRAINT fk_trip_company FOREIGN KEY(company_id) REFERENCES companies(id),
  CONSTRAINT fk_trip_customer FOREIGN KEY(customer_id) REFERENCES customers(id),
  CONSTRAINT fk_trip_agent FOREIGN KEY(agent_id) REFERENCES agents(id),
  CONSTRAINT fk_trip_sales FOREIGN KEY(sales_owner_id) REFERENCES users(id),
  CONSTRAINT fk_trip_ops FOREIGN KEY(operations_owner_id) REFERENCES users(id),
  CONSTRAINT fk_trip_created FOREIGN KEY(created_by) REFERENCES users(id),
  CONSTRAINT fk_trip_updated FOREIGN KEY(updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inquiries (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  inquiry_ref VARCHAR(64) NOT NULL,
  trip_id BIGINT UNSIGNED NOT NULL,
  request_text MEDIUMTEXT NULL,
  destination_text VARCHAR(500) NULL,
  hotel_level VARCHAR(32) NULL,
  meals VARCHAR(255) NULL,
  transport_type VARCHAR(64) NULL,
  guide_language VARCHAR(80) NULL,
  budget_amount DECIMAL(18,2) NULL,
  budget_currency CHAR(3) NULL,
  source ENUM('WHATSAPP','EMAIL','WEBSITE','FACEBOOK','LINKEDIN','REFERRAL','EXISTING_AGENT','REPEAT_CUSTOMER','WALK_IN','OTHER') NOT NULL DEFAULT 'OTHER',
  priority ENUM('NORMAL','HIGH','URGENT') NOT NULL DEFAULT 'NORMAL',
  status ENUM('NEW','WORKING','QUOTED','SENT','FOLLOW_UP','CONFIRMED','LOST','CANCELLED') NOT NULL DEFAULT 'NEW',
  lost_reason VARCHAR(120) NULL,
  lost_note TEXT NULL,
  next_action VARCHAR(255) NULL,
  next_action_due DATETIME NULL,
  source_document_id BIGINT UNSIGNED NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  updated_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_inquiry_ref(company_id,inquiry_ref),
  KEY idx_inquiry_status(company_id,status,next_action_due),
  CONSTRAINT fk_inq_company FOREIGN KEY(company_id) REFERENCES companies(id),
  CONSTRAINT fk_inq_trip FOREIGN KEY(trip_id) REFERENCES trips(id),
  CONSTRAINT fk_inq_created FOREIGN KEY(created_by) REFERENCES users(id),
  CONSTRAINT fk_inq_updated FOREIGN KEY(updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS quotes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  quote_ref VARCHAR(64) NOT NULL,
  trip_id BIGINT UNSIGNED NOT NULL,
  inquiry_id BIGINT UNSIGNED NULL,
  current_version_no INT UNSIGNED NOT NULL DEFAULT 1,
  confirmed_version_no INT UNSIGNED NULL,
  status ENUM('DRAFT','READY','APPROVED','SENT','FOLLOW_UP','CONFIRMED','LOST','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  created_by BIGINT UNSIGNED NOT NULL,
  updated_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_quote_ref(company_id,quote_ref),
  KEY idx_quote_status(company_id,status,updated_at),
  CONSTRAINT fk_quote_company FOREIGN KEY(company_id) REFERENCES companies(id),
  CONSTRAINT fk_quote_trip FOREIGN KEY(trip_id) REFERENCES trips(id),
  CONSTRAINT fk_quote_inquiry FOREIGN KEY(inquiry_id) REFERENCES inquiries(id),
  CONSTRAINT fk_quote_created FOREIGN KEY(created_by) REFERENCES users(id),
  CONSTRAINT fk_quote_updated FOREIGN KEY(updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS quote_versions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  quote_id BIGINT UNSIGNED NOT NULL,
  version_no INT UNSIGNED NOT NULL,
  version_status ENUM('DRAFT','READY','APPROVED','SENT','CONFIRMED','SUPERSEDED') NOT NULL DEFAULT 'DRAFT',
  tour_name VARCHAR(255) NOT NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  adults INT UNSIGNED NOT NULL DEFAULT 0,
  children INT UNSIGNED NOT NULL DEFAULT 0,
  infants INT UNSIGNED NOT NULL DEFAULT 0,
  foc INT UNSIGNED NOT NULL DEFAULT 0,
  total_guests INT UNSIGNED NOT NULL DEFAULT 0,
  paying_pax INT UNSIGNED NOT NULL DEFAULT 0,
  hotel_level VARCHAR(32) NULL,
  tour_type VARCHAR(64) NULL,
  guide_language VARCHAR(80) NULL,
  meals VARCHAR(255) NULL,
  cost_currency CHAR(3) NOT NULL DEFAULT 'VND',
  selling_currency CHAR(3) NOT NULL DEFAULT 'USD',
  fx_rate DECIMAL(18,6) NOT NULL DEFAULT 25000,
  pricing_mode ENUM('MARKUP','TARGET_MARGIN','MANUAL') NOT NULL DEFAULT 'MARKUP',
  pricing_value DECIMAL(10,4) NOT NULL DEFAULT 15,
  rounding_step DECIMAL(10,2) NOT NULL DEFAULT 5,
  total_cost DECIMAL(18,2) NOT NULL DEFAULT 0,
  cost_per_paying_pax DECIMAL(18,2) NOT NULL DEFAULT 0,
  selling_per_pax DECIMAL(18,2) NOT NULL DEFAULT 0,
  total_selling DECIMAL(18,2) NOT NULL DEFAULT 0,
  profit_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  margin_pct DECIMAL(10,4) NOT NULL DEFAULT 0,
  markup_pct DECIMAL(10,4) NOT NULL DEFAULT 0,
  schedule_json JSON NULL,
  cost_json JSON NULL,
  proposal_json JSON NULL,
  included_text MEDIUMTEXT NULL,
  excluded_text MEDIUMTEXT NULL,
  terms_text MEDIUMTEXT NULL,
  approved_by BIGINT UNSIGNED NULL,
  approved_at DATETIME NULL,
  sent_by BIGINT UNSIGNED NULL,
  sent_at DATETIME NULL,
  sent_channel VARCHAR(32) NULL,
  sent_snapshot_json JSON NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_quote_version(quote_id,version_no),
  CONSTRAINT fk_qv_quote FOREIGN KEY(quote_id) REFERENCES quotes(id) ON DELETE CASCADE,
  CONSTRAINT fk_qv_approved FOREIGN KEY(approved_by) REFERENCES users(id),
  CONSTRAINT fk_qv_sent FOREIGN KEY(sent_by) REFERENCES users(id),
  CONSTRAINT fk_qv_created FOREIGN KEY(created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS quote_cost_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  quote_version_id BIGINT UNSIGNED NOT NULL,
  sort_order INT UNSIGNED NOT NULL DEFAULT 0,
  category ENUM('TRANSPORT','GUIDE','HOTEL','MEAL','ATTRACTION','TOUR','CRUISE','VISA','OTHER') NOT NULL DEFAULT 'OTHER',
  service_name VARCHAR(255) NOT NULL,
  service_date DATE NULL,
  pax DECIMAL(10,2) NOT NULL DEFAULT 1,
  qty DECIMAL(10,2) NOT NULL DEFAULT 1,
  unit_price DECIMAL(18,2) NOT NULL DEFAULT 0,
  currency CHAR(3) NOT NULL DEFAULT 'VND',
  total DECIMAL(18,2) NOT NULL DEFAULT 0,
  supplier_id BIGINT UNSIGNED NULL,
  rate_id BIGINT UNSIGNED NULL,
  rate_version_id BIGINT UNSIGNED NULL,
  source_document_id BIGINT UNSIGNED NULL,
  source_type ENUM('APPROVED_RATE','SPECIAL_QUOTE','MANUAL','LEGACY') NOT NULL DEFAULT 'MANUAL',
  manual_pax TINYINT(1) NOT NULL DEFAULT 0,
  notes VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_qci_quote(quote_version_id,sort_order),
  CONSTRAINT fk_qci_version FOREIGN KEY(quote_version_id) REFERENCES quote_versions(id) ON DELETE CASCADE,
  CONSTRAINT fk_qci_supplier FOREIGN KEY(supplier_id) REFERENCES suppliers(id),
  CONSTRAINT fk_qci_rate FOREIGN KEY(rate_id) REFERENCES rates(id),
  CONSTRAINT fk_qci_rate_version FOREIGN KEY(rate_version_id) REFERENCES rate_versions(id),
  CONSTRAINT fk_qci_doc FOREIGN KEY(source_document_id) REFERENCES documents(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO permissions(code,name) VALUES
('sales.view','View Sales workspace'),
('customer.manage','Manage customers and agents'),
('inquiry.manage','Manage inquiries'),
('quote.create','Create quotations'),
('quote.edit','Edit draft quotations'),
('quote.approve','Approve quotations'),
('quote.send','Send quotations'),
('quote.confirm','Confirm quotations'),
('quote.view_cost','View internal quote cost'),
('quote.view_profit','View quotation profit and margin');

INSERT INTO schema_migrations(version) VALUES ('004_sales_core')
ON DUPLICATE KEY UPDATE version=VALUES(version);
