SET NAMES utf8mb4;
SET time_zone = '+07:00';

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  booking_ref VARCHAR(64) NOT NULL,
  trip_id BIGINT UNSIGNED NOT NULL,
  quote_id BIGINT UNSIGNED NULL,
  confirmed_quote_version_no INT UNSIGNED NULL,
  lead_guest_name VARCHAR(190) NULL,
  lead_whatsapp VARCHAR(64) NULL,
  lead_email VARCHAR(190) NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  adults INT UNSIGNED NOT NULL DEFAULT 0,
  children INT UNSIGNED NOT NULL DEFAULT 0,
  infants INT UNSIGNED NOT NULL DEFAULT 0,
  foc INT UNSIGNED NOT NULL DEFAULT 0,
  total_guests INT UNSIGNED NOT NULL DEFAULT 0,
  paying_pax INT UNSIGNED NOT NULL DEFAULT 0,
  selling_currency CHAR(3) NOT NULL DEFAULT 'USD',
  confirmed_selling DECIMAL(18,2) NOT NULL DEFAULT 0,
  operations_status ENUM('NEW_BOOKING','ON_REQUEST','PART_CONFIRMED','ALL_CONFIRMED','READY','ON_TOUR','OPERATION_COMPLETED','COMPLETED','CANCELLED') NOT NULL DEFAULT 'NEW_BOOKING',
  customer_payment_status ENUM('UNINVOICED','UNPAID','PART_PAID','PAID','OVERPAID','REFUND_DUE') NOT NULL DEFAULT 'UNINVOICED',
  supplier_payment_status ENUM('NOT_DUE','UNPAID','PART_PAID','PAID') NOT NULL DEFAULT 'NOT_DUE',
  readiness_pct DECIMAL(5,2) NOT NULL DEFAULT 0,
  risk_level ENUM('LOW','MEDIUM','HIGH','CRITICAL') NOT NULL DEFAULT 'LOW',
  sales_owner_id BIGINT UNSIGNED NULL,
  operations_owner_id BIGINT UNSIGNED NULL,
  special_requests TEXT NULL,
  client_promises TEXT NULL,
  finance_closed_at DATETIME NULL,
  operation_completed_at DATETIME NULL,
  version_no INT UNSIGNED NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NOT NULL,
  updated_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_booking_ref(company_id,booking_ref),
  KEY idx_booking_dates(company_id,start_date,end_date,operations_status),
  KEY idx_booking_guest(company_id,lead_guest_name,lead_whatsapp),
  CONSTRAINT fk_booking_company FOREIGN KEY(company_id) REFERENCES companies(id),
  CONSTRAINT fk_booking_trip FOREIGN KEY(trip_id) REFERENCES trips(id),
  CONSTRAINT fk_booking_quote FOREIGN KEY(quote_id) REFERENCES quotes(id),
  CONSTRAINT fk_booking_sales FOREIGN KEY(sales_owner_id) REFERENCES users(id),
  CONSTRAINT fk_booking_ops FOREIGN KEY(operations_owner_id) REFERENCES users(id),
  CONSTRAINT fk_booking_created FOREIGN KEY(created_by) REFERENCES users(id),
  CONSTRAINT fk_booking_updated FOREIGN KEY(updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS guests (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  booking_id BIGINT UNSIGNED NOT NULL,
  guest_type ENUM('ADULT','CHILD','INFANT','FOC') NOT NULL DEFAULT 'ADULT',
  full_name VARCHAR(190) NOT NULL,
  gender VARCHAR(32) NULL,
  date_of_birth DATE NULL,
  nationality VARCHAR(120) NULL,
  passport_number VARCHAR(120) NULL,
  passport_expiry DATE NULL,
  passport_country VARCHAR(120) NULL,
  whatsapp VARCHAR(64) NULL,
  email VARCHAR(190) NULL,
  dietary VARCHAR(255) NULL,
  special_needs VARCHAR(500) NULL,
  room_preference VARCHAR(120) NULL,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_guest_booking(booking_id,full_name),
  CONSTRAINT fk_guest_booking FOREIGN KEY(booking_id) REFERENCES bookings(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS flights (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  booking_id BIGINT UNSIGNED NOT NULL,
  flight_type ENUM('INTERNATIONAL_ARRIVAL','INTERNATIONAL_DEPARTURE','DOMESTIC','REGIONAL','OTHER') NOT NULL DEFAULT 'OTHER',
  airline VARCHAR(120) NULL,
  flight_number VARCHAR(32) NOT NULL,
  flight_date DATE NOT NULL,
  origin_code VARCHAR(16) NULL,
  destination_code VARCHAR(16) NULL,
  departure_time TIME NULL,
  arrival_time TIME NULL,
  terminal VARCHAR(64) NULL,
  status ENUM('TENTATIVE','CONFIRMED','CHANGED','CANCELLED') NOT NULL DEFAULT 'CONFIRMED',
  notes VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_flight_booking(booking_id,flight_date),
  KEY idx_flight_number(flight_number,flight_date),
  CONSTRAINT fk_flight_booking FOREIGN KEY(booking_id) REFERENCES bookings(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS booking_services (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  booking_id BIGINT UNSIGNED NOT NULL,
  service_ref VARCHAR(64) NOT NULL,
  category ENUM('HOTEL','TRANSPORT','GUIDE','CRUISE','TOUR','ATTRACTION','MEAL','VISA','FLIGHT_SERVICE','OTHER') NOT NULL DEFAULT 'OTHER',
  service_name VARCHAR(255) NOT NULL,
  service_date DATE NULL,
  start_time TIME NULL,
  end_time TIME NULL,
  pickup_location VARCHAR(255) NULL,
  dropoff_location VARCHAR(255) NULL,
  linked_flight_id BIGINT UNSIGNED NULL,
  pax DECIMAL(10,2) NOT NULL DEFAULT 1,
  qty DECIMAL(10,2) NOT NULL DEFAULT 1,
  supplier_id BIGINT UNSIGNED NULL,
  booking_status ENUM('PLANNED','NOT_REQUESTED','REQUESTED','AVAILABLE','CONFIRMED','PART_CONFIRMED','ON_REQUEST','WAITLIST','REJECTED','CANCELLED','COMPLETED') NOT NULL DEFAULT 'PLANNED',
  planned_cost DECIMAL(18,2) NOT NULL DEFAULT 0,
  confirmed_cost DECIMAL(18,2) NULL,
  actual_cost DECIMAL(18,2) NULL,
  cost_currency CHAR(3) NOT NULL DEFAULT 'VND',
  confirmation_no VARCHAR(120) NULL,
  confirmation_source VARCHAR(64) NULL,
  driver_name VARCHAR(190) NULL,
  driver_mobile VARCHAR(64) NULL,
  vehicle_type VARCHAR(120) NULL,
  vehicle_plate VARCHAR(64) NULL,
  guide_name VARCHAR(190) NULL,
  guide_mobile VARCHAR(64) NULL,
  confirmation_deadline DATETIME NULL,
  payment_deadline DATE NULL,
  cancellation_deadline DATE NULL,
  final_names_deadline DATE NULL,
  voucher_status ENUM('NOT_REQUIRED','NOT_ISSUED','ISSUED') NOT NULL DEFAULT 'NOT_ISSUED',
  source_type ENUM('ITINERARY','QUOTE_COST','MANUAL','CHANGE') NOT NULL DEFAULT 'ITINERARY',
  source_ref VARCHAR(120) NULL,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_service_ref(booking_id,service_ref),
  KEY idx_service_booking(booking_id,service_date,booking_status),
  KEY idx_service_supplier(supplier_id,service_date),
  CONSTRAINT fk_service_booking FOREIGN KEY(booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
  CONSTRAINT fk_service_supplier FOREIGN KEY(supplier_id) REFERENCES suppliers(id),
  CONSTRAINT fk_service_flight FOREIGN KEY(linked_flight_id) REFERENCES flights(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS supplier_orders (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  order_ref VARCHAR(64) NOT NULL,
  booking_id BIGINT UNSIGNED NOT NULL,
  supplier_id BIGINT UNSIGNED NOT NULL,
  request_type ENUM('AVAILABILITY_REQUEST','BOOKING_REQUEST','AMENDMENT','CANCELLATION_REQUEST','RATE_RECONFIRMATION') NOT NULL DEFAULT 'BOOKING_REQUEST',
  status ENUM('DRAFT','REQUESTED','AVAILABLE','CONFIRMED','PART_CONFIRMED','ON_REQUEST','WAITLIST','REJECTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  current_revision INT UNSIGNED NOT NULL DEFAULT 0,
  include_agreed_rate TINYINT(1) NOT NULL DEFAULT 0,
  last_sent_at DATETIME NULL,
  followup_due_at DATETIME NULL,
  notes TEXT NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  updated_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_order_ref(company_id,order_ref),
  KEY idx_order_status(company_id,status,followup_due_at),
  CONSTRAINT fk_order_company FOREIGN KEY(company_id) REFERENCES companies(id),
  CONSTRAINT fk_order_booking FOREIGN KEY(booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
  CONSTRAINT fk_order_supplier FOREIGN KEY(supplier_id) REFERENCES suppliers(id),
  CONSTRAINT fk_order_created FOREIGN KEY(created_by) REFERENCES users(id),
  CONSTRAINT fk_order_updated FOREIGN KEY(updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS supplier_order_services (
  order_id BIGINT UNSIGNED NOT NULL,
  service_id BIGINT UNSIGNED NOT NULL,
  service_status ENUM('PLANNED','REQUESTED','AVAILABLE','CONFIRMED','REJECTED','CANCELLED') NOT NULL DEFAULT 'PLANNED',
  PRIMARY KEY(order_id,service_id),
  CONSTRAINT fk_sos_order FOREIGN KEY(order_id) REFERENCES supplier_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_sos_service FOREIGN KEY(service_id) REFERENCES booking_services(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS supplier_order_revisions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT UNSIGNED NOT NULL,
  revision_no INT UNSIGNED NOT NULL,
  revision_type ENUM('ORIGINAL','PAX_CHANGE','DATE_CHANGE','FLIGHT_CHANGE','ROOMING_CHANGE','HOTEL_CHANGE','MEAL_CHANGE','SERVICE_CHANGE','OTHER') NOT NULL DEFAULT 'ORIGINAL',
  status ENUM('DRAFT','SENT','ACKNOWLEDGED','CONFIRMED','REJECTED') NOT NULL DEFAULT 'DRAFT',
  snapshot_json JSON NOT NULL,
  reason VARCHAR(1000) NULL,
  sent_at DATETIME NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_order_revision(order_id,revision_no),
  CONSTRAINT fk_revision_order FOREIGN KEY(order_id) REFERENCES supplier_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_revision_user FOREIGN KEY(created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS supplier_confirmations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT UNSIGNED NOT NULL,
  confirmation_no VARCHAR(120) NULL,
  confirmation_source ENUM('EMAIL','WHATSAPP','PDF','PHONE','OTHER') NOT NULL DEFAULT 'OTHER',
  confirmed_by_supplier VARCHAR(190) NULL,
  confirmed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  currency CHAR(3) NULL,
  confirmed_total DECIMAL(18,2) NULL,
  cancellation_deadline DATE NULL,
  payment_deadline DATE NULL,
  final_names_deadline DATE NULL,
  notes TEXT NULL,
  recorded_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_confirmation_order FOREIGN KEY(order_id) REFERENCES supplier_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_confirmation_user FOREIGN KEY(recorded_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS entity_documents (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  document_ref VARCHAR(64) NOT NULL,
  entity_type VARCHAR(48) NOT NULL,
  entity_id BIGINT UNSIGNED NOT NULL,
  document_category VARCHAR(80) NOT NULL,
  original_filename VARCHAR(255) NOT NULL,
  mime_type VARCHAR(120) NOT NULL,
  file_size BIGINT UNSIGNED NOT NULL,
  storage_driver ENUM('GOOGLE_DRIVE','LOCAL') NOT NULL,
  storage_file_id VARCHAR(255) NULL,
  storage_path VARCHAR(500) NULL,
  notes VARCHAR(1000) NULL,
  uploaded_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_entity_document_ref(company_id,document_ref),
  KEY idx_entity_document(company_id,entity_type,entity_id,created_at),
  CONSTRAINT fk_entity_doc_company FOREIGN KEY(company_id) REFERENCES companies(id),
  CONSTRAINT fk_entity_doc_user FOREIGN KEY(uploaded_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO permissions(code,name) VALUES
('booking.view','View bookings'),
('booking.manage','Manage master bookings'),
('guest.manage','Manage guest and flight data'),
('passport.view','View passport data'),
('operations.view','View Operations workspace'),
('service.manage','Manage booking services'),
('supplier_order.create','Create supplier orders'),
('supplier_order.send','Send supplier orders'),
('supplier_order.confirm','Record supplier confirmations'),
('document.booking_upload','Upload booking documents'),
('booking.complete','Complete booking operations');

INSERT INTO schema_migrations(version) VALUES ('005_booking_operations')
ON DUPLICATE KEY UPDATE version=VALUES(version);
