-- VS2.1 additive children. Supported baseline: 001-022; no backfill.

CREATE TABLE quote_option_variants (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 quote_option_id BIGINT UNSIGNED NOT NULL,
 variant_key VARCHAR(80) NOT NULL,
 label VARCHAR(190) NOT NULL,
 costing_mode VARCHAR(16) NOT NULL,
 cruise_level TINYINT UNSIGNED NULL,
 preset_code VARCHAR(24) NOT NULL DEFAULT 'CUSTOM_MIX',
 sort_order INT UNSIGNED NOT NULL,
 is_offered BOOLEAN NOT NULL DEFAULT 0,
 pricing_mode VARCHAR(24) NOT NULL,
 pricing_value DECIMAL(10,4) NOT NULL,
 rounding_step DECIMAL(10,2) NOT NULL,
 selling_currency CHAR(3) NOT NULL DEFAULT 'USD',
 pricing_result_json JSON NULL,
 input_hash CHAR(64) NULL,
 updated_by BIGINT UNSIGNED NOT NULL,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_vs21_variant (quote_option_id,variant_key),
 FOREIGN KEY (quote_option_id) REFERENCES quote_options(id),
 FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE quote_variant_cost_lines (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 variant_id BIGINT UNSIGNED NOT NULL,
 requirement_id BIGINT UNSIGNED NOT NULL,
 line_key VARCHAR(80) NOT NULL,
 sort_order INT UNSIGNED NOT NULL,
 line_kind VARCHAR(16) NOT NULL,
 service_mode VARCHAR(16) NOT NULL DEFAULT 'BOTH',
 formula_code VARCHAR(40) NOT NULL,
 quantity_source VARCHAR(32) NOT NULL,
 quantity_override INT UNSIGNED NULL,
 custom_quantity INT UNSIGNED NULL,
 units_override INT UNSIGNED NULL,
 override_reason VARCHAR(1000) NULL,
 supplier_id BIGINT UNSIGNED NULL,
 rate_version_id BIGINT UNSIGNED NULL,
 original_currency CHAR(3) NOT NULL DEFAULT 'VND',
 unit_amount_original DECIMAL(18,2) NULL,
 coverage_state VARCHAR(24) NOT NULL DEFAULT 'UNRESOLVED',
 included_by_line_id BIGINT UNSIGNED NULL,
 inclusion_rule_id BIGINT UNSIGNED NULL,
 adjusts_line_id BIGINT UNSIGNED NULL,
 adjustment_amount_vnd DECIMAL(18,2) NULL,
 origin VARCHAR(16) NOT NULL DEFAULT 'AUTO',
 rate_status VARCHAR(24) NOT NULL DEFAULT 'RATE_NEEDED',
 manual_reason VARCHAR(1000) NULL,
 manual_contract_json JSON NULL,
 review_required BOOLEAN NOT NULL DEFAULT 1,
 reviewed_by BIGINT UNSIGNED NULL,
 reviewed_context_hash CHAR(64) NULL,
 resolved_quantity INT UNSIGNED NULL,
 resolved_units INT UNSIGNED NULL,
 unit_rate_vnd DECIMAL(18,2) NULL,
 total_vnd DECIMAL(18,2) NULL,
 calculation_trace_json JSON NULL,
 input_hash CHAR(64) NULL,
 calculated_at DATETIME NULL,
 updated_by BIGINT UNSIGNED NOT NULL,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_vs21_line (variant_id,line_key),
 KEY ix_vs21_source (variant_id,quantity_source),
 FOREIGN KEY (variant_id) REFERENCES quote_option_variants(id),
 FOREIGN KEY (requirement_id) REFERENCES quote_service_requirements(id),
 FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
 FOREIGN KEY (rate_version_id) REFERENCES rate_versions(id),
 FOREIGN KEY (included_by_line_id) REFERENCES quote_variant_cost_lines(id),
 FOREIGN KEY (adjusts_line_id) REFERENCES quote_variant_cost_lines(id),
 FOREIGN KEY (inclusion_rule_id) REFERENCES rate_version_inclusions(id),
 FOREIGN KEY (updated_by) REFERENCES users(id),
 FOREIGN KEY (reviewed_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
