-- One projection per existing version. Band definitions/configuration freeze with it.
CREATE TABLE quote_price_matrices (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 quote_version_id BIGINT UNSIGNED NOT NULL,
 status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
 method VARCHAR(24) NOT NULL DEFAULT 'SAFE_PRICE',
 generation INT UNSIGNED NOT NULL DEFAULT 1,
 config_json JSON NOT NULL,
 inputs_json JSON NOT NULL,
 dependency_hash CHAR(64) NOT NULL,
 fx_snapshot_json JSON NOT NULL,
 generated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 validated_at DATETIME NULL,
 locked_at DATETIME NULL,
 valid_until DATE NULL,
 locked_by BIGINT UNSIGNED NULL,
 updated_by BIGINT UNSIGNED NOT NULL,
 UNIQUE KEY uq_vs23_matrix_version(quote_version_id),
 UNIQUE KEY uq_vs23_matrix_parent(id,quote_version_id),
 FOREIGN KEY(quote_version_id) REFERENCES quote_versions(id),
 FOREIGN KEY(locked_by) REFERENCES users(id),
 FOREIGN KEY(updated_by) REFERENCES users(id),
 CHECK(status IN ('DRAFT','VALIDATED','LOCKED','SENT')),
 CHECK(method IN ('EXACT_PAX','REPRESENTATIVE_PAX','SAFE_PRICE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE quote_price_matrix_cells (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 matrix_id BIGINT UNSIGNED NOT NULL,
 generation INT UNSIGNED NOT NULL,
 variant_id BIGINT UNSIGNED NOT NULL,
 policy_id BIGINT UNSIGNED NOT NULL,
 band_key VARCHAR(80) NOT NULL,
 min_pax INT UNSIGNED NOT NULL,
 max_pax INT UNSIGNED NOT NULL,
 channel VARCHAR(24) NOT NULL,
 status VARCHAR(40) NOT NULL,
 is_recommended BOOLEAN NOT NULL DEFAULT 0,
 is_selected BOOLEAN NOT NULL DEFAULT 1,
 selling_per_pax DECIMAL(18,2) NULL,
 net_per_pax DECIMAL(18,2) NULL,
 selling_currency CHAR(3) NOT NULL,
 policy_snapshot_json JSON NOT NULL,
 result_json JSON NOT NULL,
 context_hash CHAR(64) NOT NULL,
 UNIQUE KEY uq_vs23_cell(matrix_id,generation,variant_id,band_key,channel),
 UNIQUE KEY uq_vs23_cell_parent(id,matrix_id),
 FOREIGN KEY(matrix_id) REFERENCES quote_price_matrices(id),
 FOREIGN KEY(variant_id) REFERENCES quote_option_variants(id),
 FOREIGN KEY(policy_id) REFERENCES commercial_policies(id),
 CHECK(min_pax>0 AND max_pax>=min_pax)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE commercial_overrides (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 matrix_id BIGINT UNSIGNED NOT NULL,
 cell_id BIGINT UNSIGNED NOT NULL,
 context_hash CHAR(64) NOT NULL,
 reason VARCHAR(1000) NOT NULL,
 approved_by BIGINT UNSIGNED NOT NULL,
 approved_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(matrix_id) REFERENCES quote_price_matrices(id),
 FOREIGN KEY(cell_id,matrix_id) REFERENCES quote_price_matrix_cells(id,matrix_id),
 FOREIGN KEY(approved_by) REFERENCES users(id),
 UNIQUE KEY uq_vs23_override_context(cell_id,context_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
