-- P5: first-party social publishing queue. Provider credentials are NEVER stored in this table.
CREATE TABLE IF NOT EXISTS marketing_publish_jobs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 company_id BIGINT UNSIGNED NOT NULL,
 content_id BIGINT UNSIGNED NOT NULL,
 account_alias VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 provider VARCHAR(32) NOT NULL DEFAULT 'FACEBOOK_PAGE',
 request_key VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 content_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 message_snapshot TEXT NOT NULL,
 scheduled_at DATETIME NOT NULL,
 status ENUM('DRAFT','APPROVED','SENDING','PUBLISHED','UNCERTAIN','BLOCKED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
 created_by BIGINT UNSIGNED NOT NULL,
 approved_by BIGINT UNSIGNED NULL,
 approved_at DATETIME NULL,
 claimed_at DATETIME NULL,
 published_at DATETIME NULL,
 provider_post_id VARCHAR(128) NULL,
 status_detail VARCHAR(200) NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_marketing_publish_tenant(company_id,id),
 UNIQUE KEY uq_marketing_publish_request(company_id,request_key),
 KEY idx_marketing_publish_due(company_id,status,scheduled_at,id),
 KEY idx_marketing_publish_history(company_id,created_at,id),
 FOREIGN KEY(company_id) REFERENCES companies(id),
 FOREIGN KEY(company_id,content_id) REFERENCES marketing_content(company_id,id),
 FOREIGN KEY(created_by) REFERENCES users(id),
 FOREIGN KEY(approved_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
