"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";

type Booking={id:string;reference:string;primaryGuest:string;cruiseName:string;departureDate:string;status:string;paymentStatus:string;amountDue:number;supplierConfirmationStatus:string;followUpAt:string|null;assignedTo?:{name:string}|null;daysUntilDeparture:number};
type Task={id:string;title:string;type:string;status:string;dueAt:string|null;owner?:{name:string}|null};
type TaskItem={booking:Booking;task:Task};
type Data={generatedAt:string;counts:Record<string,number>;queues:{overdueFollowUps:Booking[];overdueTasks:TaskItem[];supplierPending:Booking[];paymentDue:Booking[];passport:TaskItem[];transfer:TaskItem[];next1:Booking[];next3:Booking[];next7:Booking[]}};

export default function OperationsToday(){
 const router=useRouter();const [data,setData]=useState<Data|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(false);
 const load=async()=>{setLoading(true);setError("");try{const [me,res]=await Promise.all([fetch("/api/admin/auth/me"),fetch("/api/admin/operations")]);if(!me.ok){router.replace("/admin/login");return}const d=await res.json();if(!res.ok)throw new Error(d.error||"Unable to load operations queue");setData(d)}catch(e){setError(e instanceof Error?e.message:"Unable to load queue")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const booking=(b:Booking,detail?:string)=><a className="inventoryItem" href={"/admin/bookings/"+b.id} key={b.id}><b>{b.reference} · {b.primaryGuest}</b><small>{b.cruiseName} · {new Date(b.departureDate).toLocaleDateString("en-US")} · {b.assignedTo?.name||"Unassigned"}{detail?" · "+detail:""}</small></a>;
 const task=(x:TaskItem)=><a className="inventoryItem" href={"/admin/bookings/"+x.booking.id} key={x.task.id}><b>{x.task.title}</b><small>{x.booking.reference} · {x.booking.primaryGuest} · {x.task.owner?.name||"Unassigned"} · {x.task.dueAt?new Date(x.task.dueAt).toLocaleDateString("en-US"):"No due date"}</small></a>;
 return <main className="adminPage"><header className="adminHeader"><div className="shell"><a className="brand" href="/"><span className="brandMark">≋</span><span><b>HALONG CRUISE<br/>ADVISOR</b><small>Today Queue</small></span></a><nav className="adminNav"><a href="/admin">Bookings</a><a className="active" href="/admin/operations">Today</a><a href="/admin/inventory">Inventory</a><a href="/admin/finance">Finance</a></nav></div></header>
 <div className="shell adminWrap"><div className="adminTitle"><span className="eyebrow">DAILY OPERATIONS</span><h1>What needs attention today</h1><p>Prioritized exceptions, guest follow-ups and upcoming departures. Open any item to continue in the booking workspace.</p></div>
 <div className="staffBar"><span>{data?"Updated "+new Date(data.generatedAt).toLocaleString("en-US"):"Loading queue..."}</span><button onClick={load} disabled={loading}>{loading?"Refreshing...":"Refresh"}</button></div>{error&&<div className="adminError">{error}</div>}
 {data&&<><div className="adminStats"><div><span>Overdue follow-ups</span><strong>{data.counts.overdueFollowUps}</strong></div><div><span>Overdue tasks</span><strong>{data.counts.overdueTasks}</strong></div><div><span>Supplier pending</span><strong>{data.counts.supplierPending}</strong></div><div><span>Guest payment due</span><strong>{data.counts.paymentDue}</strong></div><div><span>Depart ≤ 3 days</span><strong>{data.counts.next3}</strong></div></div>
 <div className="inventoryGrid">
 <section className="inventoryPanel"><div className="panelTitle"><h2>Overdue follow-ups</h2><span>Contact guests whose follow-up date has passed.</span></div><div className="inventoryItems">{data.queues.overdueFollowUps.map(b=>booking(b,b.followUpAt?"follow-up "+new Date(b.followUpAt).toLocaleDateString("en-US"):""))}{!data.queues.overdueFollowUps.length&&<p className="muted">No overdue follow-ups.</p>}</div></section>
 <section className="inventoryPanel"><div className="panelTitle"><h2>Overdue tasks</h2><span>Operational actions past their due date.</span></div><div className="inventoryItems">{data.queues.overdueTasks.map(task)}{!data.queues.overdueTasks.length&&<p className="muted">No overdue tasks.</p>}</div></section>
 <section className="inventoryPanel"><div className="panelTitle"><h2>Supplier confirmation pending</h2><span>Confirmed guest bookings not yet confirmed by operator.</span></div><div className="inventoryItems">{data.queues.supplierPending.map(b=>booking(b,b.supplierConfirmationStatus))}{!data.queues.supplierPending.length&&<p className="muted">No supplier confirmations pending.</p>}</div></section>
 <section className="inventoryPanel"><div className="panelTitle"><h2>Guest payment due</h2><span>Confirmed bookings with outstanding guest balance.</span></div><div className="inventoryItems">{data.queues.paymentDue.map(b=>booking(b,"US$ "+b.amountDue.toLocaleString()+" due"))}{!data.queues.paymentDue.length&&<p className="muted">No confirmed guest balances due.</p>}</div></section>
 <section className="inventoryPanel"><div className="panelTitle"><h2>Passport & transfer details</h2><span>Open information collection tasks.</span></div><div className="inventoryItems">{data.queues.passport.map(task)}{data.queues.transfer.map(task)}{!data.queues.passport.length&&!data.queues.transfer.length&&<p className="muted">No passport or transfer-detail tasks open.</p>}</div></section>
 <section className="inventoryPanel"><div className="panelTitle"><h2>Upcoming departures</h2><span>1 / 3 / 7 day readiness window.</span></div><div className="adminStats"><div><span>≤ 1 day</span><strong>{data.counts.next1}</strong></div><div><span>≤ 3 days</span><strong>{data.counts.next3}</strong></div><div><span>≤ 7 days</span><strong>{data.counts.next7}</strong></div></div><div className="inventoryItems">{data.queues.next7.map(b=>booking(b,b.daysUntilDeparture+" day(s)"))}{!data.queues.next7.length&&<p className="muted">No confirmed departures in the next 7 days.</p>}</div></section>
 </div></>}
 </div></main>
}
